### ISSUE TITLE
Add Json type converters and other useful classes

### ISSUE THREAD

**Issue by NN---** [gregsdennis/json-everything#103]
**Describe the functionality that isn't covered by this suite**
System.Text.Json misses TypeConverter support, custom enum serialization out of the box and other small things.

**Describe alternatives you've considered**
There is a library [Macross Json](https://github.com/Macross-Software/core/blob/develop/ClassLibraries/Macross.Json.Extensions) which provides such small utility classes.
It would be nice to have everything in one place.

**Comment by gregsdennis** [comment]
I appreciate the suggestion, but my goal with Json.More.Net isn't to compete with other libraries or create a catch-all of miscellaneous functionality.  It's more of a "common" library for functionality I need in the other libraries in this repository.

I don't want to duplicate functionality from libraries that are actually doing a good job and are still being maintained.  Doing so would add little value to the .Net ecosystem as a whole.  This is why I deprecated and archived Manatee.Json when starting these libraries.  These are meant to supercede the old project.

That said, I do have a JSON converter for enumerations, though the functionality is somewhat limited in comparison to the features of that library.

**Comment by NN---** [comment]
Thanks for clarification.
Using this thread, is there any option to generate data classes from JSON schema ?

**Comment by gregsdennis** [comment]
I don't have generation that direction.  That gets quite complicated really quickly.

**Comment by NN---** [comment]
I suppose most cases are much simpler with one type, like string with minimum length or integer with maximum value.
If you have one type, then the work is not hard.

For multiple types case you need to use JsonElement:
Not sure if this covers all complicated schema cases, but I assume that it is possible to solve 90% of typical use cases without too much hard work.

```cs
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

class Q
{
    [JsonConstructor]
    public Q(JsonElement a)
    {
        A = a;

        switch (a.ValueKind)
        {
            case JsonValueKind.Number:
                ANumber = a.GetInt32();
                if (ANumber < 5) throw new ArgumentException(nameof(A));
                break;
            case JsonValueKind.String:
                AString = a.GetString();
                if (AString.Length < 10) throw new ArgumentException(nameof(A));
                break;
            default: throw new ArgumentException(nameof(A));
        }
    }

    public JsonElement A { get; }
    [JsonIgnore] public string? AString { get; }
    [JsonIgnore] public int? ANumber { get; }
}

class P
{

    static void Main()
    {
        try
        {
            Console.WriteLine(JsonSerializer.Deserialize<Q>("{\"A\":1}").ANumber);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }

        Console.WriteLine(JsonSerializer.Deserialize<Q>("{\"A\":11}").ANumber);
        try
        {
            Console.WriteLine(JsonSerializer.Deserialize<Q>("{\"A\":\"abc\"}").AString);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }

        Console.WriteLine(JsonSerializer.Deserialize<Q>("{\"A\":\"0123456789\"}").AString);
    }
}
```

**Comment by NN---** [comment]
Another option is to use JsonConverter.

**Comment by gregsdennis** [comment]
I'm going to close this as the topic has changed.  I'll open another issue for codegen.
