### ISSUE TITLE
How to validate scalar values ?

### ISSUE THREAD

**Issue by nabinked** [gregsdennis/json-everything#107]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.10.2
- OS: Linux
- .Net Target: Core 3.1

How do validate a scalar value using a schema ? I want to achieve what is displayed in the screenshot below.
![image](https://user-images.githubusercontent.com/7703179/117937447-5978b700-b349-11eb-86ae-8af9180fbd54.png)

I see that Validate method only takes a `JsonElement` and I am not sure how we can convert a scalar value to a JsonElement using the Parse APIs available. Any guidance would be appreciated.

**Comment by gregsdennis** [comment]
Really there's only one way to do this, but I have a shortcut.  Let's cover how it's done, then I'll show the shortcut.

`JsonDocument.Parse()` will do this for you, but you have to JSON encode the value into a string first.

```c#
var doc = JsonDocument.Parse("\"not a number\"");
var elementWithStringValue = doc.RootElement;
```

or

```c#
var doc = JsonDocument.Parse("42");
var elementWithNumberValue = doc.RootElement;
```

Json.More.Net (which is used by JsonSchema.Net) exposes several [extension methods](https://gregsdennis.github.io/json-everything/api/Json.More.JsonElementExtensions.html) for types that can be converted to JSON values.  So now all you have to do is this:

```c#
var elementWithStringValue = "not a number".AsJsonElement();
var elementWithNumberValue = 42.AsJsonElement();
```

You can read more about these conversions [in the docs](https://gregsdennis.github.io/json-everything/usage/json-more.html#data-conversions).

**Comment by gregsdennis** [comment]
There's also some fanciness you can do if you want to pass a `JsonElement` into a method that you're writing.  Read the "Making methods that require `JsonElement` easier to call" section for how to do that.

**Comment by nabinked** [comment]
Thanks @gregsdennis . This is exactly what I was after.
