### ISSUE TITLE
Validation always return true

### ISSUE THREAD

**Issue by bahaasamoudi** [gregsdennis/json-everything#108]
I Have this  model

      public class BaseData
      {
        [Required]

        [MinLength(10)]

        public string ActionSource { get; set; }

        }

and this is my code

            Json.Schema.JsonSchema schema = new JsonSchemaBuilder().FromType<BaseData>().Build();

            ValidationOptions options = new ValidationOptions();

            options.OutputFormat = OutputFormat.Basic;

            var validate = schema.Validate(JsonDocument.Parse(bodyString).RootElement, options);

the problem is validate.isvalid always returns true when ActionSource  in json or not

**Comment by gregsdennis** [comment]
What is the JSON content (`bodyString`)?

**Comment by bahaasamoudi** [comment]
this is bodyString without ActionSource
`"{\r\n    \"eventTime\": \"2021-05-19T12:41:32-05:00\"\r\n}'`
this is bodyString with ActionSource
`"{\r\n    \"eventTime\": \"2021-05-19T12:41:32-05:00\",\r\n    \"ActionSource\": \"email\"\r\n}"
`

**Comment by bahaasamoudi** [comment]
Note:
when build the schema manually everything work without any issues
` 
           Json.Schema.JsonSchema schema1 = new JsonSchemaBuilder().Properties(
               (
                   "ActionSource", new JsonSchemaBuilder()
                       .Type(SchemaValueType.String)
                       .MinLength(10)
               )
           )
           .Required("ActionSource");
`

**Comment by gregsdennis** [comment]
Please serialize the resulting schema and print it for me.

**Comment by bahaasamoudi** [comment]
Can You Please Tell me how can i serialize it ? 
I mean all object or only specific object  inside it ?

**Comment by gregsdennis** [comment]
Just with the serializer.  Schemas are already serializable.

```c#
var json = JsonSerializer.Serialize(schema);
```

Then print `json`.

**Comment by bahaasamoudi** [comment]
i found where is the problem,
i'm using [required] attribute of dotnet DataAnootations not Json.Schema.generation 
I'm sorry for that
---
can i ask you a question before close the issue ? 
in json i want to write "actionSource"  (small letter) not "Actionsource" (capital letter) without impact the required validation attribute, how can i do it ?

**Comment by gregsdennis** [comment]
That's not currently supported, but I can add support for the [`JsonPropertyName`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=net-5.0) attribute to do this.

**Comment by bahaasamoudi** [comment]
Thanks @gregsdennis

**Comment by gregsdennis** [comment]
@bahaasamoudi I was wrong.  Looks like I _do_ support the `JsonPropertyName` attribute already. See https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.Generation.Tests/SchemaGenerationTests.cs#L152

**Comment by bahaasamoudi** [comment]
Thanks @gregsdennis  it's work,
i have a question, when i have DateTime property and pass it in postman like  {"eventTime": "2021-05-19T12:41:32-05:00"}
the validation message is "Value is string but should be object"
how can i solve this problem ?

this is my class

`
 public class BaseData
    {
        [Required]    
        [JsonPropertyName("eventTime")]
        public DateTime EventTime { get; set; }
}
`

**Comment by gregsdennis** [comment]
What does the schema look like?

**Comment by bahaasamoudi** [comment]
`"{\"type\":\"object\",\"properties\":{\"eventTime\":{\"type\":\"object\",\"properties\":{}}},\"required\":[\"eventTime\"]}"`

**Comment by gregsdennis** [comment]
Looks like the system doesn't know what to do with `DateTime`.  You'll need to [provide a generator](https://gregsdennis.github.io/json-everything/usage/schema-generation.html#generators) for it.

**Comment by gregsdennis** [comment]
Please open a new issue for this. The system should handle that, but it seems I don't have a test for it, so it's not being checked.
