### ISSUE TITLE
Registration of custom IAttributeHandler ignored

### ISSUE THREAD

**Issue by wazzamatazz** [gregsdennis/json-everything#109]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.3.2
- OS: Windows 10
- .Net Target: .NET Core 3.1, .NET 5.0

**Describe the bug**
I am trying to write an `IAttributeHandler` that will use the [System.ComponentModel.DataAnnotations.DisplayAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute) to set a title and description for a schema, but the handler's `AddConstraints` method never seems to get called, despite the handler being registered via the `AttributeHandler.AddHandler<T>` method.

Based on the instructions [here](https://gregsdennis.github.io/json-everything/usage/schema-generation.html#attributes) for writing a handler for an attribute in an external assembly, I can't tell if there is something else that I am supposed to do.

**To Reproduce**
```csharp
void Main() {
    AttributeHandler.AddHandler<DisplayAttributeHandler>();

    var schema = new JsonSchemaBuilder().FromType<MyType>().Build();
   Console.WriteLine(JsonSerializer.Serialize(schema, new JsonSerializerOptions { 
        WriteIndented = true 
    }));

}

public class DisplayAttributeHandler : IAttributeHandler {

    public DisplayAttributeHandler() {
        Console.WriteLine("Constructor called");
    }

    public void AddConstraints(SchemaGeneratorContext context) {
        Console.WriteLine("AddConstraints called");
        // TODO: update the context
    }
    
}

public class MyType {

    [System.ComponentModel.DataAnnotations.Display(Name = "Test Name", Description = "Test description")]
    public string SomeProperty { get; set; }
    
}
```

When I run the above program, I get the following output (note that the `Console.WriteLine` statements in my handler are never called):

```json
{
  "type": "object",
  "properties": {
    "SomeProperty": {
      "type": "string"
    }
  }
}
```

**Expected behavior**
Handlers registered via `AttributeHandler.AddHandler<T>` should be invoked when a schema is being built.

**Additional context**
When I added a `Console.WriteLine` statement to my handler's constructor, I could see that the handler is never even instantiated.

**Comment by wazzamatazz** [comment]
Looks like there are maybe a couple of equality comparisons [here](https://github.com/gregsdennis/json-everything/blob/670a11909dc93029a15b467f2399ef3483cc0126/JsonSchema.Generation/AttributeHandler.cs#L30) and [here](https://github.com/gregsdennis/json-everything/blob/670a11909dc93029a15b467f2399ef3483cc0126/JsonSchema.Generation/AttributeHandler.cs#L42) that are using `!=` when they should use `==`?

**Comment by gregsdennis** [comment]
Nice catch. I do that sometimes.

**Comment by wazzamatazz** [comment]
We all do!
