### ISSUE TITLE
Ordering of properties in auto-generated schemas

### ISSUE THREAD

**Issue by wazzamatazz** [gregsdennis/json-everything#112]
**Environment**
- Nuget Package: JsonSchema.Net.Generation

**Can this library make doing something simpler?**
When generating a schema using the `FromType<T>` extension for `JsonSchemaBuilder`, the properties are always ordered alphabetically. It would be great to have more control over the order of properties in the resulting schema, or alternatively to add the properties in the order that they have been declared in the `T` type.

For example, if I am building a schema that could be used to automatically generate a form in a UI, I would want the schema properties to be listed in a logical order for the form entry rather than alphabetically. For example:

```csharp
public class MyOptions {
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsEnabled { get; set; }
    public string Endpoint { get; set; }
    public uint Timeout { get; set; }
}
```

Generated schema:

```json
{
  "type": "object",
  "properties": {
    "Description": {
      "type": "string"
    },
    "Endpoint": {
      "type": "string"
    },
    "IsEnabled": {
      "type": "boolean"
    },
    "Name": {
      "type": "string"
    },
    "Timeout": {
      "type": "integer"
    }
  }
}
```

At the moment, the generated schema orders the properties as `Description`, `Endpoint`, `IsEnabled`, `Name`, `Timeout`, whereas I would ideally want them in the declaration order specified in the class.

**Comment by wazzamatazz** [comment]
An example of how declaration order could be achieved by modifying `ObjectSchemaGenerator.AddConstraints`:

```csharp
bool IsPublicProperty(PropertyInfo p) {
    var accessors = p.GetAccessors();
    return accessors.All(a => a.IsPublic);
}

var membersToGenerate = context.Type.GetMembers(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).Where(m => { 
    if (m is PropertyInfo p) {
        // Only include properties that can be read from and written to.
        if (!p.CanRead || !p.CanWrite) {
            return false;
        }

        // Include properties with public getters and setters, and properties that are
        // annotated with [JsonInclude].
        return IsPublicProperty(p) || p.GetCustomAttribute<JsonIncludeAttribute>() != null;
    }

    if (m is FieldInfo f) {
        // Include public fields, and non-public fields that are annotated with [JsonInclude].
        return f.IsPublic || f.GetCustomAttribute<JsonIncludeAttribute>() != null;
    }

    return false;
});
```

The existing alphabetical ordering would just be a case of putting an `.OrderBy(m => m.Name)` at the end of the `membersToGenerate` assignment,

**Comment by gregsdennis** [comment]
That may be a possibility.  I'll probably try some of [these](https://stackoverflow.com/q/9062235/878701) solutions.  I prefer something that doesn't rely on you to add an attribute, so I'll try that first.

I may end up doing that by default and the custom `Order` attribute as a fallback.

**Comment by wazzamatazz** [comment]
Yeah relying on an attribute is problematic if e.g. you are inheriting from a type in an external library. I'm happy to submit a PR for the example implementation I posted above if that would be helpful.

**Comment by gregsdennis** [comment]
.Net doesn't guarantee the ordering of the properties and fields.  Iterating over those collections wouldn't necessarily give you what you want.

**Comment by wazzamatazz** [comment]
Yeah I understand that there's no guarantee. Something I also realised was that the member order returned by `Type.GetMembers` (and `GetProperties` etc.) means that members from the most-derived type are returned first, then members from the base class, and so on.

If you use the order of members returned by `GetMembers` instead of alphabetical, then given a class hierarchy like this:

```csharp
public class BaseOptions {
  public string Name { get; set; }
  public string Description { get; set; }
  public bool IsEnabled { get; set; }
}

public class MyOptions : BaseOptions {
  public string Endpoint { get; set; }
  public uint Timeout { get; set; }
}
```

you end up with a schema like this:

```json
{
  "type": "object",
  "properties": {
    "Endpoint": {
      "type": "string"
    },
    "Timeout": {
      "type": "integer"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "IsEnabled": {
      "type": "boolean"
    }
  }
}
```

This is obviously not ideal for scenarios when you want to generate schemas for e.g. a plugin's configuration options, but you want to have a base class that the plugin's configuration settings are derived from.

I noticed the mention of `MemberInfo.MetadataToken` in the SO post you linked to above, and I came up with an `IComparer<MemberInfo>` that allows you to order members for a given type based on its inheritance hierarchy starting from the root:

```csharp
public class MemberInfoMetadataTokenComparer : Comparer<MemberInfo> {

    private readonly int[] _typeOrder;

    private MemberInfoMetadataTokenComparer(Type type) {
        var typeStack = new Stack<Type>();

        do {
            typeStack.Push(type);
            type = type.BaseType!;
        } while (type != null);

        _typeOrder = typeStack.Select(GetMetadataToken).ToArray();
    }

    public static MemberInfoMetadataTokenComparer ForType(Type type) {
        return new MemberInfoMetadataTokenComparer(type ?? throw new ArgumentNullException(nameof(type)));
    }

    private static bool HasMetadataToken(MemberInfo? member) {
        if (member == null) {
            return false;
        }

#if NET5_0_OR_GREATER
        return member.HasMetadataToken();
#else
        try { var token = member.MetadataToken; return true; }
        catch (InvalidOperationException) { return false; }
#endif
    }

    private static int GetMetadataToken(MemberInfo? member) {
        return HasMetadataToken(member) ? member!.MetadataToken : int.MaxValue;
    }

    public override int Compare(MemberInfo? x, MemberInfo? y) {
        if (x == null && y == null) {
            return 0;
        }

        if (x == null) {
            return 1;
        }

        if (y == null) {
            return -1;
        }

        var xTypeToken = GetMetadataToken(x.DeclaringType);
        var yTypeToken = GetMetadataToken(y.DeclaringType);

        if (xTypeToken != yTypeToken) {
            var xIndex = Array.IndexOf(_typeOrder, xTypeToken);
            var yIndex = Array.IndexOf(_typeOrder, yTypeToken);

            if (xIndex < 0 && yIndex < 0) {
                return Comparer<int>.Default.Compare(xTypeToken, yTypeToken);
            }

            if (xIndex < 0) {
                return 1;
            }

            if (yIndex < 0) {
                return -1;
            }

            return Comparer<int>.Default.Compare(xIndex, yIndex);
        }

        var xToken = GetMetadataToken(x);
        var yToken = GetMetadataToken(y);

        return Comparer<int>.Default.Compare(xToken, yToken);
    }

}
```

I guess this is a rather long-winded way of saying: if there was a way or providing an `IComparer<MemberInfo>` to `ObjectSchemaGenerator` based on the `SchemaGeneratorContext.Type` passed to the `AddConstraints` method, then this would satisfy my needs, because it would allow my to order things as I needed to, and from your end, you could just order by member name if a comparer was not supplied.

**Comment by gregsdennis** [comment]
The other option is to provide a [refiner](https://gregsdennis.github.io/json-everything/usage/schema-generation.html#refiners).  You pretty much have free reign to muck with the intents.

You could detect if a schema has `properties` and reorder them at that point.
