### ISSUE TITLE
DateTime Property generation not work correctly

### ISSUE THREAD

**Issue by bahaasamoudi** [gregsdennis/json-everything#114]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.10.2
- OS: Wndows 10
- .Net Target: .NET Core 3.1, .NET 5.0

**Describe the bug**
In my class I have DateTime property , when i pass it's value as string the method JsonSchema.Validate() returns  "Value is string but should be object"

**To Reproduce**

    public class BaseData

    {

        [Required]

        [JsonPropertyName("eventTime")]

        public DateTime EventTime { get; set; }

    }

    public static async Task<HttpResponseBody<T>> GetBodyAsync<T>(this HttpRequest request)
        {
          
            var bodyString = "{\r\n    \"eventTime\": \"2021-05-19T12:41:32-05:00\"\r\n}"
            JsonSchema schema = new JsonSchemaBuilder().FromType<BaseData>().Build(); //{\"type\":\"object\",\"properties\":{\"eventTime\":{\"type\":\"object\",\"properties\":{}}},\"required\":[\"eventTime\"]}
            ValidationOptions options = new ValidationOptions();
            options.OutputFormat = OutputFormat.Detailed;

            var validation = schema.Validate(JsonDocument.Parse(bodyString).RootElement, options);
     }

**Expected behavior**
When i run the proram, validation.Message return "Value is string but should be object" and Validation.IsValid returns false, but i expect it's work with Validation.IsValid = true

**Comment by gregsdennis** [comment]
Thanks. The problem isn't validation, it's in generation of the schema.
