### ISSUE TITLE
How to iterate over ValidationResult to write all properties and their value in Dictionary

### ISSUE THREAD

**Issue by bahaasamoudi** [gregsdennis/json-everything#118]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.5.0
- OS: Wndows 10
- .Net Target: .NET Core 3.1, .NET 5.0

**My Problem**
The format of validation result not same always 

**Description**
when there is only one error the result object will be in  **message** property and **NestedResults** Property is empty:
![image](https://user-images.githubusercontent.com/31710102/119224071-6cd41100-bb05-11eb-974e-32c2f414ee82.png)
when there is Two or more errors the result object will be in **NestedResults** property and **Message** Property is empty:
![image](https://user-images.githubusercontent.com/31710102/119224164-d18f6b80-bb05-11eb-9063-2aa658c55fe1.png)
when there is Two or more **Required** errors the result object will be in **Message** property and **NestedResults** Property is empty:
![image](https://user-images.githubusercontent.com/31710102/119224194-fb489280-bb05-11eb-9036-fb030dad30ee.png)
and I think there is others ..

**My Questions is**
I Have `Dictionary<string, string> errorsResult = new Dictionary<string, string>();` and i want to iterate over errors in validation object and put the Property name in Dictionary key and error message in Dictionary  value but i can't because there is different formats in validation result 

**Output Format that i want**
![image](https://user-images.githubusercontent.com/31710102/119224726-875bb980-bb08-11eb-99c5-8e94ee518b4e.png)

**Comment by gregsdennis** [comment]
> The format of validation result not same always

The format of the output conforms to the specification (I wrote that section).

> My Questions is...

This kind of question is better suited for a site like StackOverflow, where there's a larger community of people who can help you with general programming.  Your question is, "How can I transform the standard output into this other format that I want?"

If you have a question about the library itself, or if there's a bug, I'm happy to address it.

**Comment by bahaasamoudi** [comment]
Ok, thanks @gregsdennis
