### ISSUE TITLE
JsonSchema - Add support for DateTimeOffset

### ISSUE THREAD

**Issue by JMPSequeira** [gregsdennis/json-everything#129]
Should be straight forward.

I can do the implementation for this if you'd like.

**Comment by gregsdennis** [comment]
I'd like you to work it out locally first, outside of the library, please.  The idea being that I created the library to be extensible so that if you need something that the library doesn't provide, you can just do it without having to have the library updated.

**Comment by gregsdennis** [comment]
Also, there's not a `format` for date-time-offset in JSON Schema.  I'll be curious to see the schema you come up with.

**Comment by JMPSequeira** [comment]
> I'd like you to work it out locally first, outside of the library, please. The idea being that I created the library to be extensible so that if you need something that the library doesn't provide, you can just do it without having to have the library updated.

Fair enough.

> Also, there's not a `format` for date-time-offset in JSON Schema. I'll be curious to see the schema you come up with.

IMHO `DateTimeOffset` relates to the `date-time` format more than `DateTime` as information is preserved on deserialization.

But as I said before I get your point about extensibility, and agree with it.
