### ISSUE TITLE
JsonSchema properties in camelcase

### ISSUE THREAD

**Issue by thomashinsinger** [gregsdennis/json-everything#134]
Hi, 

In my solution I use the CamelCase format for our response.
For example, this object  :

```c#
public class Client
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string OtherName { get; set; }
}
```

will be shown as 

```json
{
    "id": 123,
    "name": "name",
    "otherName": "name2"
}
```

in my api.

In addition I use your library to apply some JsonSchema, but the problem is that the properties are in PascalCase.
```json
{
  "type": "object",
  "properties": {
        "Id": {
          "type": "integer"
        },
        "Name": {
          "type": "string"
        },
		"OtherName": {
          "type": "string"
        }
  },
  "required": [
    "Id",
    "Name"
  ]
}
```

I was supposing that using 

```c#
var serializerOptions = new JsonSerializerOptions { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
```

will do the job, but it actually doesn't work as expected.

Is there a solution to have in my JsonSchema something like this : 

```json
{
  "type": "object",
  "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
		"otherName": {
          "type": "string"
        }
  },
  "required": [
    "Id",
    "Name"
  ]
}
```

**Comment by gregsdennis** [comment]
I'm not sure I understand what you're asking.  Your model and the schema are completely independent.  You can have camel-case property names in your JSON data and in the schema without any problem.

**Comment by thomashinsinger** [comment]
I want to have the Camel-Case format for the property names of the JsonSchema. 

In my case, the property names of my JsonSchema are in Pascal-Case even if I use the 'JsonNamingPolicy.CamelCase' of the 'JsonSerializerOptions ' which would normally changes this automatically.

**Comment by gregsdennis** [comment]
As I mentioned, you can do that just by naming them that way _in the schema_.  The model that you deserialize into has nothing to do with the schema or validating the JSON data.  Can you show me the code that you're trying?

**Comment by thomashinsinger** [comment]
For creating my JsonSchema i'm using this

`SchemaGeneratorConfiguration schemaGeneratorConfiguration = new SchemaGeneratorConfiguration()
{
	Generators = new List<ISchemaGenerator>()
	{
		{ new BooleanNullableSchemaGenerator() },
		{ new DateTimeNullableSchemaGenerator() },
		{ new DateTimeSchemaGenerator() },
		{ new IntegerNullableSchemaGenerator() },
		{ new NumberNullableSchemaGenerator() }
	}
};
JsonSchemaBuilder jsonSchema = new JsonSchemaBuilder().FromType<TDto>(schemaGeneratorConfiguration);`

Which TDto is a generic parameter. I do other stuff after that, but I don't think it willchange anything.

And after for the serialization of the JsonSchema i'm using this

`public JsonSchemaJsonResult(JsonSchema jsonSchema)
{
    string jsonSchemaString = JsonSerializer.Serialize(jsonSchema, new JsonSerializerOptions()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    });
}`

I assume that because i'm using the 'generic' FromType for creating the JsonSchema it keep the property names in Pascal-Case, but also was assuming that JsonSerializerOptions will resolve that without any problems

**Comment by gregsdennis** [comment]
OH!   You're trying to _generate_ a schema.  (This is why I have issue templates that ask for what library is being used.)

A few things here:

1. You don't need all of those generators.  Those data types are handled already by the generators that are already in the library, and they're included by default.
2. Serialization has nothing to do with generating a schema.  Secondarily to this, the reason the keys under `properties` are not affected by the `PropertyNamingPolicy` is because they are string keys of a `Dictionary<string, JsonSchema>`; they're not properties.

Now to your solution.

You want to _generate_ the schema with camel-case properties.  It looks like I need to add an option for that.

**Comment by gregsdennis** [comment]
In the meantime, you can decorate your model with the `JsonPropertyName` attribute and specify the property names in camel-case yourself.  A benefit of this is that the serializer will also pick up on this attribute.

**Comment by thomashinsinger** [comment]
Ohhh, that's explain why the serialization with the option PropertyNamingPolicy didn't work.

Sorry, for the misunderstanding, i'm not that good in english, and didn't say a single time that my JsonSchema was generated :s

I use this generators because I have some specific type that I didn't find in your library. For example I didn't find the generator for the type _bool?_ that's why I have this generator : 

```c#
internal class BooleanNullableSchemaGenerator : ISchemaGenerator
{
	public bool Handles(Type type)
	{
		return type == typeof(bool?);
	}

	public void AddConstraints(SchemaGeneratorContext context)
	{
		context.Intents.Add(new TypesIntent(SchemaValueType.Boolean, SchemaValueType.Null));
	}
}
```

Do you think that this is a good enhancement to add to your library an option on the generation to choose the format of the properties ?

**Comment by gregsdennis** [comment]
The library comes with the most commonly-used types already supported.  Please read the [documentation(https://gregsdennis.github.io/json-everything/usage/schema-generation.html).  Nullability is also supported.  You won't need to use those.

**Comment by thomashinsinger** [comment]
Uhh, very nice upgrades, I was using an old version of the library that's why I didn't have those, with an upgrade of the package I can now delete those, thanks

**Comment by thomashinsinger** [comment]
Your branch work perfectly fine on my side ! 

Nice job !
