### ISSUE TITLE
Add opt-in support for System.ComponentModel.DataAnnotations

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#143]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.7.1
- .Net Target: `netstandard2.0` will need a [nuget pkg](https://www.nuget.org/packages/System.ComponentModel.Annotations/); built into `net5.0`

**Can this library make doing something simpler?**
The attributes defined by this library are good, but @DanielHabenicht suggested it would be nice to have support for the attributes that are already used for data annotation and validation.

**Additional context**
Conversely, a comment on [StackOverflow](https://stackoverflow.com/a/68322628/878701) indicated that this kind of cross support could interfere with functions, and that they'd like to keep these separate.

As such, it would be a good idea to support these attributes under a configuration value.

**Comment by gregsdennis** [comment]
In starting to build this one based on conversation in #141, I found that there might be some conflicts for users who try to use the attributes from both this library and from `System.ComponentModel.DataAnnotations` (in the case presented in the "additional context" section).

For example, this library defines `[Required]`, but so does `DataAnnotations`.  Using both would mean having to use the namespaces (or renaming them via `using` inclusion statements.  While not a show-stopper, it isn't the best experience.

Secondarily, trying to control serialization separately from schema generation would mean that the user has to double-up on the attributes.

Given these shortcomings, maybe the configuration needs to enable each attribute separately.

**Comment by rosenqui-cysiv** [comment]
For anyone else looking for `System.ComponentModel..DataAnnotations` support, I did a quick & dirty attribute handler to adapt some of the System.ComponentModel attributes. This just handles a couple of them, but one could easily add more.

```
internal sealed class SystemAttributeHandler : IAttributeHandler {
    void IAttributeHandler.AddConstraints(SchemaGeneratorContext context) {
        var dnAttr = context.Attributes.FirstOrDefault(x => x.GetType() == typeof(System.ComponentModel.DisplayNameAttribute));
        if (dnAttr is System.ComponentModel.DisplayNameAttribute dn)
            context.Intents.Insert(0, new Json.Schema.Generation.Intents.TitleIntent(dn.DisplayName));

        var descAttr = context.Attributes.FirstOrDefault(x => x.GetType() == typeof(System.ComponentModel.DescriptionAttribute));
        if (descAttr is System.ComponentModel.DescriptionAttribute da)
            context.Intents.Insert(0, new Json.Schema.Generation.Intents.DescriptionIntent(da.Description));
    }
}
```

**Comment by moscarelli** [comment]
How can I make this work on the Schema generator? 
I try [MaxLength()] and [ Maximum()] but both don't show up in the schema.

**Comment by rosenqui-cysiv** [comment]
You'd have to modify the above code to look for an attribute of type `System.ComponentModel.DataAnnotations.MaxLengthAttribute` and then add the necessary `MaxLengthIntent` similar to what the code does for Title and Description.

**Comment by gregsdennis** [comment]
I've recently discovered that while the `System.ComponentModel.DataAnnotations` namespace isn't respected by `JsonSerializer`, it _is_ handled by ASP.Net.  That misalignment seems weird to me, but it exists nonetheless.

I am reconsidering this one.

**Comment by cdavernas** [comment]
First of all, the library is pure gold! Thanks for sharing your awesome work.

Would really love, though, to have DataAnnotations supported, this would greatly reduce overhead on the DTOs I use.

 Furthermore, considering excluding properties based on JsonIgnore would be a charm: more often than not, I use it in librairies to avoid shadow members to be considered, and would prefer avoiding direct dependency on your lib for those.

**Comment by gregsdennis** [comment]
@cdavernas does [this comment](https://github.com/gregsdennis/json-everything/issues/143#issuecomment-1098418010) help at all?

**Comment by cdavernas** [comment]
Yes, I believe that will do! Just wanted to know if you had other plans. 
Many thanks!

**Comment by gregsdennis** [comment]
In the immediate term, no.  Still open for future development, though.  (I might do it as an extension package, though.)

**Comment by gregsdennis** [comment]
@cdavernas @rosenqui-cysiv @moscarelli ☝️ I'm publishing a separate library for DataAnnotations support.  It's a separate library because these attributes can't do everything that I want them to, which is why I created my own set.  However, this should get you a jump start.

**Comment by Welchen** [comment]
@gregsdennis  did that separate library get created or is that work still need to be done?

**Comment by gregsdennis** [comment]
Yes, it's a separate package. Please see the PR above for the changes, the readme for a link to the package, and the docs for details.

**Comment by tdhintz** [comment]
I'm not spotting a concise example of generating a compile time class for validation and deserialization from data annotations on a target class.  Can you be specific?  Is there a sample project demonstrating that?

**Comment by gregsdennis** [comment]
You'll want to follow the general [schema generation](https://docs.json-everything.net/schema/schemagen/schema-generation/) process.  Also the data annotations support is listed [here](https://docs.json-everything.net/schema/schemagen/data-annotations/).

**Comment by tdhintz** [comment]
Neither of those documentation pages explain the simple creation of a generated C# class that performs validation and deserialization.  Maybe that's what they explain but it isn't obvious.  I guess there was a GenerateCode() method that could create a class and that has been deprecated in favore of Corvus?

**Comment by gregsdennis** [comment]
I think there's a confusion here. This issue is about _schema_ generation, not code (C#) generation. The docs I linked explain that functionality.

The code generation library has been deprecated entirely, but there are other docs pages that describe its functionality.  Start here: https://docs.json-everything.net/schema/codegen/schema-codegen/
