### ISSUE TITLE
Json Patch model binding weirdness

### ISSUE THREAD

**Issue by Jetski5822** [gregsdennis/json-everything#146]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 1.0.5
- OS: Windows
- .Net Target: core 3.1

**How can I help you today?**
I have some patch JSON:

```
[
   {
      ""value"":true,
      ""OperationType"":""Replace"",
      ""path"":""/IsManualEditIndicator"",
      ""op"":""replace""
   },
   {
      ""value"":""2021-04-02T00:34:11Z"",
      ""OperationType"":""Replace"",
      ""path"":""/ClockingDateTime"",
      ""op"":""replace""
   }
]
```

When I call and MVC endpoint like so; it works.

```
        public async Task<IActionResult> Patch(
            int id,
            [FromHeader(Name = "traceId")] string traceId)
        {
            var json = "";

            using (StreamReader reader
                      = new StreamReader(Request.Body, Encoding.UTF8, true, 1024, true))
            {
                json = await reader.ReadToEndAsync();
            }

            var patch = JsonSerializer.Deserialize<Json.Patch.JsonPatch>(json);
```

Patch is populated, world is good.
If I change it over to this;

```
        public async Task<IActionResult> Patch(
            int id,
            [FromHeader(Name = "traceId")] string traceId,
            [FromBody] JsonPatch clockingPatch)
        {
```

I get the following;

```
{
   "type":"https://tools.ietf.org/html/rfc7231#section-6.5.1",
   "title":"One or more validation errors occurred.",
   "status":400,
   "traceId":"00-d4ceda59a9448c4bbfa0826d24ab93e2-03d71d05696cb54f-00",
   "errors":{
      "Operations[0].From.Segments":[
         "The Segments field is required."
      ],
      "Operations[1].From.Segments":[
         "The Segments field is required."
      ]
   }
}
```

Any thoughts on how I can fix this? as im a little confused :D

**Comment by gregsdennis** [comment]
Interesting scenario you've found.  From the [docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0#input-formatters) I'd expect that the ASP.Net would just do the same deserialization that you're doing in the manual one.

Would you work up a minimal solution that replicates this, please?  I want to make sure that what I debug is the same as what you're seeing.

Thanks for the report.

**Comment by gregsdennis** [comment]
The MS docs for [how to do JSON Patch](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0) suggest using Newtonsoft _and_ System.Text.Json 🤦

**Comment by Jetski5822** [comment]
Here you go https://github.com/Jetski5822/JsonPatchBug146

Something weird for you, it works under IISExpress... but NOT Kestrel.

If you clone, build, and then flip it to be Kestrel 
![image](https://user-images.githubusercontent.com/619530/126787392-4709a1d8-17b0-4cb5-85bd-a0ce416a635a.png)

using Postman do... PATCH to http://localhost:5000/patchme

```
[
   {
      "value":true,
      "OperationType":"Replace",
      "path":"/IsManualEditIndicator",
      "op":"replace"
   },
   {
      "value":"2021-04-02T00:34:11Z",
      "OperationType":"Replace",
      "path":"/ClockingDateTime",
      "op":"replace"
   }
]
```

![image](https://user-images.githubusercontent.com/619530/126787470-e0914a97-8263-43a6-8a95-4f6baba3e710.png)

So weird.!!!

**Comment by Jetski5822** [comment]
Hmm, In here https://github.com/gregsdennis/json-everything/blob/master/JsonPatch/PatchOperation.cs#L20

Shouldnt Op and Path be the only non nullable objects? with Value and From being nullable objects? based on here http://json.schemastore.org/json-patch

**Comment by gregsdennis** [comment]
Having those non-null resolved some processing issues I had while enabling nullable reference types in the lib.  I do have it nullable in a DTO in the converter defined in the same file, toward the bottom.

**Comment by gregsdennis** [comment]
Well, it's definitely deserializing the patch properly.

![image](https://user-images.githubusercontent.com/2676804/126851811-c07d3855-62ae-4868-885b-d7f85cb7de30.png)

Something's happening between the deserialization and entering the controller.  Maybe ASP.Net is doing some validation, though I'm not sure what would be instructing it to do so.

**Comment by gregsdennis** [comment]
Okay.  Found what might be causing it and a [workaround](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#non-nullable-reference-types-and-required-attribute) for you.

Update *Startup.cs*:

```c#
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages()
        .AddMvcOptions(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true);
}
```

**Comment by gregsdennis** [comment]
Looked at this a bit today.  I'm still not sure where that error message is being generated, so I don't know how to fix it other than the above.

**Comment by Jetski5822** [comment]
Nice one Greg, I'll give it a go -  I'll also pull your code to my sln and see if I can get it to work.

It's weird that it works fine in IIS express though :/

**Comment by gregsdennis** [comment]
The validation engine is saying that `JsonPointer.Segments` is not nullable and so requires a value.  But because your patches don't declare a `from` value, it gets a default pointer, and `.Segments` is null for that.  If I make that property nullable, the problem goes away.  But that doesn't feel right because it should always have a value.  (I supply a static `Empty` pointer to be used instead of `default`).

Interestingly, I'm using `default` to fill the `from` value in the `PatchOperationConverter`.  If I use `JsonPointer.Empty` instead, the problem also goes away.  I think this is the fix.

**Comment by gregsdennis** [comment]
Okay.  Try v1.0.6.

**Comment by Jetski5822** [comment]
It works!!! Nice one - thanks for the fast turn around.
