### ISSUE TITLE
Easier sub-schema navigation

### ISSUE THREAD

**Issue by shadow-cs** [gregsdennis/json-everything#15]
It would be helpful if we can traverse sub-schemas more easily. Currently specific types which hold sub-schemas have to be traversed manually since they share o common ancestor/interface.

A `switch` over all keywords (which have sub-schemas) is currently necessary, see [here](https://gist.github.com/shadow-cs/24576043ac49421910ae7cdbabf3e8b3#file-jsonschemaloader-cs-L94).

Original discussion: #8.

**Comment by gregsdennis** [comment]
I agree with the motivation for this, but I'm struggling to find an elegant solution.

For reference:

> I started trying to add a subschemas property to the IRefResolvable interface, but I found that the main problem is that the keywords expose subschemas differently. Some have a single subschema (contains), while others have multiple (anyOf). For the ones with multiple, the subschema is a direct descendant in an array (anyOf), while for others, the schema is nested under keys ($defs, properties), both of which differently affect how references would be resolved.
> 
> This means that the "better" solution is actually to create three different interfaces (single schema, multiple indexed subschemas, multiple keyed subschemas) rather than adding onto IRefResolvable, but I'm not sure that really helps navigating the schema structure.

**Comment by gregsdennis** [comment]
@shadow-cs I'd like to discuss some things about your gist that caught my eye, but such a conversation doesn't suit GitHub well.  Do you mind joining my [Slack workspace](https://join.slack.com/t/manateeopensource/shared_invite/zt-4klcm69x-_MA8Z2ZSZ4JNu_d3lQOVPg) and DM-ing me?

**Comment by gregsdennis** [comment]
Offline, @shadow-cs and I discussed and we agree that the best approach would be to add three new interfaces to describe the different types of schema-carrying keywords.

- single child schema
- list of schemas
- string-keyed dictionary of schemas

Keywords will implement these keywords as appropriate.  This also provides a mechanism for custom keywords to be included in the kind of navigation that's desired.

**Comment by gregsdennis** [comment]
Do you have any issue with these interfaces being implemented explicitly?  This means that you'd have to cast to the interface to see the properties.  It means that I don't have to rename properties, which would be a breaking change.

**Comment by shadow-cs** [comment]
Works like a charm, no problems with explicit casting.
