### ISSUE TITLE
Access JsonLogic internal properties

### ISSUE THREAD

**Issue by apm101** [gregsdennis/json-everything#154]
**Environment**
- Nuget Package: JsonLogic 
- Nuget Version: 1.3.1

**How can I help you today?**
Can internal properties be made public? I would like to post process rules after deserialization. Is there a cleaner alternative to do this?

Ex. Access rules list in AndRule

**Comment by gregsdennis** [comment]
Can you give an example of what you'd like to do?

**Comment by apm101** [comment]
I would like to validate that the selected values in select are 'valid' before processing the rule. (product id from a product list). 

Atm I'm validating the values during deserialization (iffy)

**Comment by apm101** [comment]
Seems like a big change. Its fine, I'll fork for my requirements. 

I appreciate the library. 👍

**Comment by gregsdennis** [comment]
Um... okay.  I haven't really had the opportunity to look into this yet, and I'm still not completely certain what you're looking for.

**Comment by gregsdennis** [comment]
So to answer your question, I've built these libraries with a preference for immutability.  Being able to modify the rules would go against that philosophy.

I'd like to explore your need a bit more to see if there's a way that I could accommodate it.

**Comment by apm101** [comment]
My use case is probably niche. Don't worry about it.
