### ISSUE TITLE
JsonSchema.Equals

### ISSUE THREAD

**Issue by bard83** [gregsdennis/json-everything#16]
Currently seems not possible, from a JsonSchema instance, to compare a JsonSchema with an other one. Are you going to support this?

**Comment by gregsdennis** [comment]
I think this will depend on what you mean by equality.

If you're looking for "the two schemas serializer to the same JSON," I can probably accommodate that.

If you're looking for "these schemas might serialize to different JSON, but they are functionally equivalent," I don't think that's doable in this library.  It would involve a lot of theory and code to identify refactorings, much like a mathematical symbolic processor.  Probably best as a library unto itself.

**Comment by gregsdennis** [comment]
What it's going to take to implement this:

- `JsonSchema` will need equality
  - all keywords + `OtherData`, or
  - boolean value
- all keyword implementations will need equality

Probably would be best for everything to implement `IEquatable<T>`.

This isn't difficult; it'll just take some time.

**Comment by bard83** [comment]
> If you're looking for "the two schemas serialize to the same JSON," I can probably accommodate that.

Yes, this is what I meant.
