### ISSUE TITLE
Typo in the validation error message for minProperties 

### ISSUE THREAD

**Issue by pbajrak** [gregsdennis/json-everything#165]
**Environment**
- Nuget Package: 1.11.2
- Nuget Version: 5.11.0
- OS: Windows 10
- .Net Target: .NET 5.0

**Describe the bug**
The `minProperties `has wrong validation error.

**To Reproduce**

```cs
var schema = @"{
                ""type"": ""object"",
                ""minProperties"": 1
                }";

var json = JsonDocument.Parse(@"{}").RootElement;

var jsonSchema = JsonSchema.FromText(schema);

var validationResult = jsonSchema.Validate(json, new ValidationOptions
    {
        OutputFormat = OutputFormat.Basic
    });
Console.WriteLine(JsonSerializer.Serialize(validationResult));
```

**Expected behavior**
Output is
`{"valid":false,"keywordLocation":"#/minProperties","instanceLocation":"#","error":"Value has more than 1 properties"}`
but should be
`{"valid":false,"keywordLocation":"#/minProperties","instanceLocation":"#","error":"Value has less than 1 properties"}`

**Additional context**
The same behaviour can be observerd [https://json-everything.net/json-schema](https://json-everything.net/json-schema)

**Comment by gregsdennis** [comment]
Thanks for finding this. That's likely a copy/paste error.  I'll put out an update soon.

**Comment by gregsdennis** [comment]
That should hit nuget and be available on the website soon.  (I should put the package versions on the website!)

**Comment by pbajrak** [comment]
Great. Thanks for quick fix
