### ISSUE TITLE
Generate Json Data from Json Schema 

### ISSUE THREAD

**Issue by SirAvatar** [gregsdennis/json-everything#173]
Firstly, fantastic library, extremely useful.

I have read your documentation, and samples.
I have found examples of Json Data to Json Schema but not the other way around. 

Is this possible?

**Comment by SirAvatar** [comment]
Awesome, Great news.
I didn’t think it would be too difficult as there are many json schema to POCO generators.

Thanks again for your insight and quick response. 
Really appreciate it.

**Comment by gregsdennis** [comment]
I haven't forgotten about this.  Just haven't had much time to work on it.

**Comment by gregsdennis** [comment]
I've made some good progress on this over the past few days.  Had to reorganize my approach.

**Comment by gregsdennis** [comment]
Due to difficulties in finding a good Regex-based string generation library, I'm not going to be able to support any of the Regex-supported keywords:

- `pattern`
- `patternProperties`
- `propertyNames` (not explicitly Regex, but usually used with it)

**Comment by gregsdennis** [comment]
@SirAvatar what are your requirements here?  I may be able to publish a prerelease version that suits your needs.

I have something that works for very basic schemas.  The following is not yet supported:

- the above Regex items
- reference keywords (e.g. `$ref`, `dynamicRef`, etc)
- annotation / metadata keywords (e.g. `title`, `description`)
- `content*` keywords
- `dependencies` / `dependent*` keywords

I'd still like to add `const` and `enum` support before I release something.  I also have an idea how `if`/`then`/`else` could work.

Lastly, you may find that it can't generate data when you can find something that fits.  This can happen when some combination of the schema and the system's randomizer get tied in a knot.  It works most of the time (I don't have metrics), but it's not 100%.

**Comment by gregsdennis** [comment]
JsonSchema.Net.DataGeneration should be available soon.  Please see the [docs](https://gregsdennis.github.io/json-everything/usage/schema-datagen.html).
