### ISSUE TITLE
Extraneous JsonSchema.Net NuGet Dependencies?

### ISSUE THREAD

**Issue by ArcanoxDragon** [gregsdennis/json-everything#174]
Currently, JsonSchema.Net.Generation has a direct dependency on the "Humanizer" metapackage, which pulls in all of their localization resources as "compile" dependencies if I add "JsonSchema.Net.Generation" to a project. This means I get a ton more `.dll`s in my output folder than without the Generation package. It looks like the only place Humanizer is used is when changing the casing of property names during schema generation; is there a chance the dependency could be changed to `Humanizer.Core`? I don't think their culture-specific localization packages are necessary for case changes on property names, but I'm not 100% sure on that. 

In addition, `JsonSchema.Net` itself has a strong dependency on `JetBrains.Annotations`, which caused my existing NuGet package references for that package to be updated in my entire solution, and all of the `bindingRedirects` (for every entry-level project) to need to be changed. I'm working in a .NET Framework solution with a ton of "entry" projects, so this is a bit undesirable. JetBrains suggests [in a blog post](https://blog.jetbrains.com/dotnet/2018/05/03/what-are-jetbrains-annotations/) that the annotations be included as source instead of as a `JetBrains.Annotations` dependency reference for libraries intended for consumption by others. They have additional documentation on that [here](
https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html#embedding-declarations-of-code-annotations-in-your-source-code)

**Comment by gregsdennis** [comment]
Thanks for the question.

I'll see what I can do about Humanizer, but the Jetbrains one needs to stay.

That blog post you reference is pretty old now, and they don't recommend copying the code in anymore.  In fact, in their options, you can see that they explicitly recommend the nuget package now.

![image](https://user-images.githubusercontent.com/2676804/139941626-960fd379-ee53-4dc8-8056-2b4671691361.png)

**Comment by ArcanoxDragon** [comment]
Interesting; I've never noticed that blurb in the ReSharper settings now. Our code base has a lot of legacy Framework projects in it and, for historical reasons, all NuGet packages for `packages.config`-based projects are under version control, so I try and avoid needing to update things like `JetBrains.Annotations` when I can avoid it, but it looks like I may not be able to avoid it this time.

Hopefully the Humanizer dependency can indeed be lightened though; that will help a lot.

**Comment by gregsdennis** [comment]
It looks like referencing Humanizer.Core is probably the preferred method for another package.  From their docs:

> Here are the options:
> 
> - **All languages**: use the main Humanizer package. This pulls in Humanizer.Core and all language packages.
> - **English**: use the Humanizer.Core package. Only the English language resources will be available
> - **Specific languages**: Use the language specific packages you'd like. For example for French, use Humanizer.Core.fr. You can include multiple languages by installing however many language packages you want.
> 
> The detailed explanation for how this works is in the comments [here](https://github.com/Humanizr/Humanizer/issues/59#issuecomment-152546079).

This way, if an application _needs_ those other translations (e.g. for non-English capitalizations) they can install the packages they need at the application level.
