### ISSUE TITLE
exclusiveMinimum should be a boolean not a number

### ISSUE THREAD

**Issue by khalidabuhakmeh** [gregsdennis/json-everything#180]
**Environment**
- Nuget Package: [e.g. JsonSchema.Net]
- Nuget Version: 1.11.5
- OS: macOS
- .Net Target: .NET 6

**Describe the bug**

The JSON Schema (http://json-schema.org/draft-04/schema#) draft says that `exclusiveMinimum` and `exclusiveMaximum` should be `booleans`, whereas JSONSchema.NET assumes they will be numbers.

```json
    "exclusiveMaximum": {
      "type": "boolean",
      "default": false
    },
```

<img width="360" alt="Screenshot 2021-11-11 at 16 22 43" src="https://user-images.githubusercontent.com/228256/141370946-5402ea89-3ec8-4131-89a4-1956da1e7de2.png">

**To Reproduce**

Try loading the following schema using `JsonSchema.FromFile`

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "name": {
      "description": "Name of the product",
      "type": "string"
    },
    "price": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": ["id", "name", "price"]
}
```

**Expected behavior**

Don't throw an exception, because the schema definition is correct :)

**Comment by darrelmiller** [comment]
This was fixed a while ago.  exclusiveMinimum should be a number https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.5

**Comment by khalidabuhakmeh** [comment]
Thanks @darrelmiller for educating me. I'll update my code.

**Comment by gregsdennis** [comment]
@khalidabuhakmeh to be clear, in draft 4 `exclusiveMinimum` and `exclusiveMaximum` were booleans as you mentioned (you even linked the draft 4 spec).  These keywords were updated to numeric values in draft 6 in order to reduce the number of keywords needed to specify this requirement.

I had supported draft 4 in Manatee.Json, but when I made this library (which is intended as a replacement), I made a conscious decision to no longer support draft 4.  This simplified a number of things including not having to support these keywords as booleans.

**Comment by khalidabuhakmeh** [comment]
@gregsdennis any chance you could add validation to make sure a loaded schema is supported by JsonSchema.NET?

The original error wasn't clear the draft was the issue.

**Comment by gregsdennis** [comment]
That error is already supported but turned off in favor of performance.  If you [enable meta-schema validation](https://gregsdennis.github.io/json-everything/usage/schema-validation.html#options), it will return an error staying that it doesn't recognize draft 4.
