### ISSUE TITLE
Add array navigation support to JsonPointer

### ISSUE THREAD

**Issue by Arithmomaniac** [gregsdennis/json-everything#184]
The existing `JsonPointer.Create<T>` implementation has code for "usual" `IReadOnlyList`s:

https://github.com/gregsdennis/json-everything/blob/62d55e8b3c6537cf9dce99d81ccb336e2f88f3c5/JsonPointer/JsonPointer.cs#L249-L256

However, arrays are a special case and need different treatment; I think it would look something like this:

```csharp
if (
    body is BinaryExpression binaryExpression and { NodeType: ExpressionType.ArrayIndex }
    && binaryExpression.Right is ConstantExpression arrayIndexConstantExpression
)
{
    // Array index
    segments.Insert(0, PointerSegment.Create(arrayIndexConstantExpression.Value.ToString())); 
    body = binaryExpression.Left;
}
```

**Comment by gregsdennis** [comment]
Yep that seems to work just fine.  R# helped me restructure the expression, so the code's a bit different.

Expressions like this aren't something I've used a lot.  I'm having trouble figuring out how I want to format it 😂.
