### ISSUE TITLE
Expose classes in Json.Schema.Generation.Generators publicly

### ISSUE THREAD

**Issue by dazerdude** [gregsdennis/json-everything#188]
**Can this library make doing something simpler?**
I'd like to be able to extend the behaviors of the generators in Json.Schema.Generation.Generators, but they are not exposed.

**Describe alternatives you've considered**
In my project, I've pulled the ones I need from the registry via reflection, but this would be a lot easier if they just weren't internal. Exposing the SchemaGeneratorContext would be similarly helpful so I can flexibly run AddConstraint code without concern.

**Comment by dazerdude** [comment]
It's also very annoying to use the PropertiesIntent from outside of the binary as SchemaGeneratorContexts are required to use it, even though PropertiesIntent only uses the intent list from the Context.

**Comment by gregsdennis** [comment]
What are you looking to extend?  These were not designed to be extended but replaced.  If you want to configure different behavior the design intent was for you to create a new one and register it.

I actually want to overhaul how the generation works (but I'm lacking the time recently).  There are a few other shortcomings of the current design, and it could be done better.

**Comment by dazerdude** [comment]
Alright, if you're looking to rewrite, I'll just fork and take what I need. This issue was largely what I saw as an easy band aid to help me work around other issues in the api.

I would note, that because of the global ordering in the GeneratorRegistry, it's not really possible to replace the default ones either. In particular if I wanted my own version of ObjectSchemaGenerator to sit at the bottom of the stack, I don't see how I would do this without a lot of reflection.

My specific issue is that I have a couple simple objects that I'd like to be able to take as objects, or regex strings, or numbers. To generate the underlying object schema, I'd like to just call the ObjectSchemaGenerator directly since calling FromType/ContextCache naively will route through my schema generator again, and modifying a copied config is a bit of a pain.

To do this tho, I need to a) be able to create a new context to capture the intents, and b) access the ObjectSchemaGenerator directly to call AddConstraints. I would prefer to run the library code for generating the object schema so that I have all the relevant features and get bug fixes when the library updates. But if you think you'll overhaul it anyway, this becomes a moot point.
