### ISSUE TITLE
Support for i18n and custom error messages

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#190]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.11.6
- OS: Linux
- .Net Target: 5.x

**How can I help you today?**
Does this library support other languages for the error messages or provide a way to provide custom error messages when certain validation fails?

**Comment by gregsdennis** [comment]
I don't directly support this currently, no.  I'm open to suggestions on how to implement it in an extensible way.

In Manatee.Json, I had static properties on each keyword that output a message.  These also supported replacement tokens for values to be inserted.  For example, `maximum` supported `{maximumValue}` and `{actualValue}` tokens that would be replaced with the actual values.

This doesn't support multiple languages at runtime though.  I'd have to do a culture-keyed dictionary approach, I think.

**Comment by gregsdennis** [comment]
I did some research on this by exploring how packages like Humanizer do it.  The coding itself looks fairly straightforward, but the packaging part seems rather rather complex.  I'm still looking into it.

If you have suggestions, I'm open to them.

**Comment by ItsVeryWindy** [comment]
I'm still thinking it through at this stage. I know it would probably involve using `ResourceManager` and `CultureInfo`.

I've looked at a few other approaches to do with formatting, like how structured logging currently works in asp.net core and if something similar could be done here, as it would be nice to avoid lookups in situations where the messages aren't going to be read.

At the moment I've sort of worked around the issue by introducing another keyword that overrides the message with one it keeps in a dictionary.
