### ISSUE TITLE
Infinite loop for meta schema

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#191]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.11.6
- OS: Linux
- .Net Target: 5.x

**Describe the bug**
I was trying to validate a schema that used a meta schema but it got stuck in an infinite loop.

**To Reproduce**
I was following the example for defined here https://gregsdennis.github.io/json-everything/usage/schema-vocabs.html

**Expected behavior**
Json to validate

**Additional context**
It seems to be getting stuck here in this while loop https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/ValidationOptions.cs#L128

I suspect this is due to the fact it refers to itself and there is no schema reference that refers back to what json schema version is being used. Changing the schema referenced by the meta schema to one of the ones defined in the while loop avoids the issue.

**Comment by gregsdennis** [comment]
Thanks for the report. This is quite confusing since all of the tests pass, and they're using the meta-schemas.

Can you post a test or some other example that replicates this behavior?

**Comment by ItsVeryWindy** [comment]
Sure, I've put this together https://github.com/ItsVeryWindy/json-everything-loop

**Comment by gregsdennis** [comment]
Two things:

1. Yes, the library should handle this properly and not end in an infinite loop.
2. Custom meta-schemas should use one of the drafts (or a meta-schema that eventually points to one of the drafts) as its `$schema` value.  Custom meta-schemas should not be self-referential.  (See https://github.com/json-schema-org/json-schema-spec/issues/1153#issuecomment-982853157 for a discussion on this.)
