### ISSUE TITLE
handling of unknown formats

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#193]
**Describe the bug**
https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.2.3

As per the spec, an implementation must not fail to collect unknown formats as annotations.

There is also the bit in there about format assertion vocabulary, is that the same as specifying `RequireFormatValidation`?

Currently it seems that there is no way to force a failure when encountering an unknown format.

**To Reproduce**
Define a schema with an unknown format. When validating it will return an annotation but the value will be null.

**Expected behavior**
The annotation value should contain the name of the unknown format.

If `RequireFormatValidation` is set to true, additionally I might expect the validation to fail which it currently does not.

**Comment by gregsdennis** [comment]
> There is also the bit in there about format assertion vocabulary, is that the same as specifying `RequireFormatValidation`?

Yeah, this is the in-library setting that's suggested in [section 7.2.1](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.2.1):

> Implementations MAY still treat "format" as an assertion in addition to an annotation and attempt to validate the value's conformance to the specified semantics. The implementation MUST provide options to enable and disable such evaluation and MUST be disabled by default.

---

I'll need to write a test for failing assertion for unknown formats.

Particularly out of [Section 7.2.3](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.2.3):

> When the Format-Assertion vocabulary is specified, implementations MUST fail upon encountering unknown formats.

This might make a good addition to the [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) as well.

---

I'll get some tests worked up.  Thanks for the report.

**Comment by gregsdennis** [comment]
You may also be interested in reading through the [discussion](https://github.com/json-schema-org/json-schema-spec/issues/1020) around updating this for the latest spec.  The "Review" section of [my comment](https://github.com/json-schema-org/json-schema-spec/issues/1020#issuecomment-730750514) is probably a good place to start.

**Comment by gregsdennis** [comment]
Tracking on branch `issue193-custom-format-behaviors`
