### ISSUE TITLE
Json Schema allocates a lot

### ISSUE THREAD

**Issue by dazerdude** [gregsdennis/json-everything#197]
**Environment**
- Nuget Package: JsonSchema.Net
- OS: Windows
- .Net Target: 6

**Describe the bug**
Json Schema allocates a _lot_ when validating reasonably complex json files. For my specific case it appears to allocate ~12 GB.

**To Reproduce**
My json files aren't too complex, but they are somewhat deep. They top out around 24 levels deep. I do have a fair bit of oneOf/anyOfs and an object that contain a list of itself.

**Expected behavior**
Processing a json file shouldn't really take that much ram. Especially when I have optimizations enabled.

**Additional context**
The perf analyzer basically says they're all Validation Contexts and associated structures. I ripped these out of my fork, and just use the one context everywhere. It works great for me, and gets the job done in a constant ~50MB, but I disabled some features/keywords that I wasn't using to get it done. Additional substate is pushed into this master context (and pulled out when the keyword exits).
https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/ValidationContext.cs#L146

Some potentially low hanging fruit that could help:
NavigatedReferences creates a HashSet when traveling down a level but staying with the same instance? Navigating to the same reference for the same object (even from a different keywords) seems unnecessary? I don't know all the details here, but in my case these collections were growing quite large and pinning it to the json element instead of the nested context worked great. I have tons of references but only in document.
https://github.com/gregsdennis/json-everything/blob/24f2557ce2ec3a146b6047f55b1f486bd024c0f8/JsonSchema/ValidationContext.cs#L167

The Clone call can also allocate some, although it presumably only clones the relevant parts of the document, every sublevel clones it's parent even if the sublevel doesn't reference a different part of the document. Passing JsonElements by reference (instead of embedding them in the context) helped. Cloning once at top level so the reference the document isn't lost (or just taking the JsonDocument in the api, potentially just two entry points).
https://github.com/gregsdennis/json-everything/blob/24f2557ce2ec3a146b6047f55b1f486bd024c0f8/JsonSchema/ValidationContext.cs#L159

I removed the subschema location pointer entirely since I didn't really care. InstanceLocation is quite useful for debugging, but I decomposed it into a Stack of strings held by the master context, for my current document location, and then dynamically resolved that when I needed it (for final error points and the like). The stack is popped on the way up. This saves a fair bit of space and allocation time. Perhaps a list of PointerSegments but even that strikes me as a bit unnecessary as it greedily copies the string.

In the same vein, you have a lot of format strings of the form $"{i}" or $"{name}". I could be wrong, and these could be optimized away, but I believe these are translated to calls to string.Format . Making them relatively much slower than just calling ToString on the object (or just passing it in if it's a string like JsonProperty.Name). I don't think they were contributing too much to the memory issue though as I believe the runtime won't allocate a new string if the output string already exists (but I'm not totally sure).
https://github.com/gregsdennis/json-everything/blob/24f2557ce2ec3a146b6047f55b1f486bd024c0f8/JsonSchema/PatternPropertiesKeyword.cs#L87
https://github.com/gregsdennis/json-everything/blob/24f2557ce2ec3a146b6047f55b1f486bd024c0f8/JsonSchema/ContainsKeyword.cs#L63

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'm definitely interested in improvements to this.  It was a problem in Manatee.Json as well.  I'll have a look at your fork to see if what you've done could be adapted to the other keywords.

**Comment by gregsdennis** [comment]
@dazerdude I had a look at your fork, but I don't see these changes.  Have you committed them on any branch?

**Comment by dazerdude** [comment]
Yeah, sorry. I forked it into my primary project because I never expected to submit them back.

I'll copy them to my fork of json-everything and upload them.

**Comment by dazerdude** [comment]
A couple minor things other changes that are here.

I have very large enums, so I replaced the List with a set in EnumKeyword. This helped my perf, but may be slower than a list for lots of different small enums. I didn't do much of an analysis here. It was an obvious win for me.
https://github.com/dazerdude/json-everything/blob/master/JsonSchema/EnumKeyword.cs#L39

GetCustomAttributes is a great function, but pretty slow since it's reflected. I removed references to FilterKeywords as a result for a speed increase. Particularly the call here in ValidateSubschema (which get's called a lot for deep json files). Consider lazily caching by type or a similar optimization.
https://github.com/dazerdude/json-everything/blob/master/JsonSchema/JsonSchema.cs#L215

**Comment by gregsdennis** [comment]
Thanks for putting this together. Sometimes it takes another pair of eyes to see things.

I'll have a look at what you've done. It sounds like I can make some good improvements based on this.

**Comment by gregsdennis** [comment]
I've updated the implementation to use a collection of stacks rather than create a bunch of context objects.  Also, the results are built during validation rather than converted from the contexts at the end.

This required quite a bit of rework around keyword implementation.

Do to all the changes, this will defiinitely be a 2.0 thing.  I have a few other issues I'd like to pull in so long as I'm making breaking changes, so it could be a bit before I publish.

In the meantime, could you please have a look at branch `reduce-context-allocations`?  I'd like to see how the modifications handle your scenario.  The only change that I've included from your suggestions so far is using a single context.

---

Re: `NavigatedReferences`

This tracks what subschemas have been used to validate what location.  Its only purpose is detection of circular references.  There are actually tests against this in the test suite.

Re: Element cloning

I've encountered problems where the parent document is disposed before I'm done with it.  Therefore I clone it.  I can't predict when this happens, so I just take the safe route.

**Comment by dazerdude** [comment]
Some quick work. I'll be sure to take a look this weekend. I'd definitely save this for a major release.

Briefly, both cloning & NavigatedReferences are clearly useful features. After I naively removed NavigatedReferences I had to hack it back in to save myself from recursive cycles. I do not like the solution in my fork very much. It works, but it's unclean. I think you're (source -> dest) set looks a lot better. I hesitate to make statements about correctness on NavigatedReferences because it's clearly used by several different reference keywords and I don't understand all the things references can do, as I only use references within the same document.

Cloning the document at top level, which it looks like you in the branch, instead of every level should save you from an eager garbage collector. I don't have evidence for this, but I'd expect the child JsonElements to reference the cloned root JsonElement. You know you're root element won't be cleaned up until you complete validation because you've tied it to your root context (although I'd believe it existing in the stack to be enough). Tbh, it strikes me as a bit interesting on their end that the garbage collect can even clean up the underlying datasource, but it probably proved a nice optimization or something.

**Comment by gregsdennis** [comment]
Hey @dazerdude I'd really like to get this out, but I want to know what the performance difference is for you.  Could you test this at your earliest convenience, please?

**Comment by dazerdude** [comment]
Oh, I'm sorry man. This absolutely fell off my radar over the holidays. I'll schedule some time tomorrow night to generate some perf numbers.

**Comment by gregsdennis** [comment]
No worries. Thanks.

**Comment by dazerdude** [comment]
Memory looks great! It's relatively stable with regular garbage collections. It certainly doesn't grow forever anymore.

In my cpu profiles, it looks like ValidationContext.From & JsonSchema.ValidateSubschema are very much the hotest functions. 

ValidationContext.From: Probably hard to improve too much, but I still suspect Cloning here is unnecessary if you clone the root and keep a reference to it (or take the JsonDocument directly). I'd bet money that Clone() is duplicating the entire document to reference at every level. There's a lot of time spent in the coreclr under this ValidationContext.From which I think is your calls to Clone().

JsonSchemaValidateSubschema: A ton of cpu is being burned on the loop iteration. It appears to be due to KeywordExtensions.Priority() calling Type.GetCustomAttribute() in there. I'd lazily cache the Priorities for each type in a static Dictionary<Type, int> so that you don't need to do the reflection call every. This will be much faster and seems like an easy safe win for a fair bit of perf. Reflection is pretty useful but can be slow especially on hot paths.

I also see some heat on EnumKeyword. I have very large enums that I use constantly though. Using a HashSet here would help with my specific case, but I can swap it out locally (or submit back a fix since it's clearly related to my use case). 

Anyway, the primary issue is much improved. Thanks for the ping, and sorry again it took me so long to get back to you.

**Comment by gregsdennis** [comment]
Thanks for checking that, and for the suggestions.  I'll pull in the changes I have, then look at the others.

**Comment by gregsdennis** [comment]
I've added the caching for keyword priority, but I don't think can use a hash set for enum values.

Enum values can be any JSON value.  But the implementations of `.GetHashCode()` doesn't work right for `JsonElement`, so I had to ~make~ borrow [`.GetEquivalenceHashCode()`](https://github.com/gregsdennis/json-everything/blob/master/Json.More/JsonElementExtensions.cs#L70-L126), which is no less computationally intensive than `.IsEquivalentTo()` (same file, line 21).

See also: 

- https://github.com/gregsdennis/json-everything/issues/76
- https://github.com/dotnet/runtime/issues/33388

**Comment by dazerdude** [comment]
Oh, mine version seems to work okay. I just passed in JsonElementEqualityComparer.Instance as the equality comparer in the HashSet constructor. That looks like it calls .GetEquivalenceHashCode() to generate the hashes. I may be missing a latent bug (my enum is _just_ strings), but I don't really see why a set wouldn't work?

It'll certainly be faster if it's not buggy. The computation of .GetEquivalenceHashCode() might be exactly the same as .IsEquivalentTo() but HashSet.Contains() only needs to compute the one hash code.

This is my enum keyword (edited for brevity)
```
public class EnumKeyword : IJsonSchemaKeyword, IEquatable<EnumKeyword>
{
        internal const string Name = "enum";
        private readonly HashSet<JsonElement> _Values;
        public IReadOnlyCollection<JsonElement> Values => _Values;
        public EnumKeyword(params JsonElement[] values)
        {
	        if (values == null) throw new ArgumentNullException(nameof(values));
	        _Values = new HashSet<JsonElement>(values, JsonElementEqualityComparer.Instance);
        }
        
        public EnumKeyword(IEnumerable<JsonElement> values)
        {
	        if (values == null) throw new ArgumentNullException(nameof(values));
	        _Values = new HashSet<JsonElement>(values, JsonElementEqualityComparer.Instance);
        }
        
        public void Validate(ValidationContext context)
        {
	        context.EnterKeyword(Name);
	        context.IsValid = Values.Contains(target);
	        context.ExitKeyword(Name, result.IsValid);
        }
}
```

**Comment by gregsdennis** [comment]
🤔 That equality comparer uses those methods I mentioned, but you're right about only having to compute the hash code once.  I wasn't thinking about the hash set caching the codes; I was thinking it would iterate through them each time.  Brain fart.
