### ISSUE TITLE
Schema Generation 2.0

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#198]
This single issue is to consolidate other issues raised against this library.

- #117
  - Base class requirements could be extracted into their own definition.
  - Sealed classes should protect against new properties.
- #143
  - Make use of (or otherwise support the use of) .Net's data annotations.
- #149
  - Allow certain attributes on types so that they can be applied to the top-level schema.
  - Possibly support read-only and write-only properties (although not supported by `System.Text.Json` serialization).

**Comment by ugumba** [comment]
Suggestion: Add logic in ObjectSchemaGenerator to match System.Text.Json's logic for automagically combining read-only properties with constructor initialization.  Also consider supporting [JsonConstructor].

**Comment by ugumba** [comment]
Recommendation: Get rid of statics, like SchemaGenerationContextCache.  Alternatively, allow a consumer the option to provide a custom cache instance e.g. in SchemaGeneratorConfiguration.

**Comment by ArcanoxDragon** [comment]
> Recommendation: Get rid of statics, like SchemaGenerationContextCache. Alternatively, allow a consumer the option to provide a custom cache instance e.g. in SchemaGeneratorConfiguration.

I second this, as right now it seems the library is not entirely thread-safe. For example, if one thread starts generating a schema (which clears the cache), and then another thread starts generating an infinitesimally small amount of time later, it would clear the cache again while the first thread is possibly still populating/utilizing it.

**Comment by gregsdennis** [comment]
> Suggestion: Add logic in ObjectSchemaGenerator to match System.Text.Json's logic for automagically combining read-only properties with constructor initialization. Also consider supporting [JsonConstructor].

I'm generating schemas, not the model.  The constructor itself is irrelevant in this process.  However, one of the things I _am_ looking at is implicit `readOnly` and `writeOnly` for properties without getters or setters, respectively.

> Recommendation: Get rid of statics, like SchemaGenerationContextCache. Alternatively, allow a consumer the option to provide a custom cache instance e.g. in SchemaGeneratorConfiguration.  (and the second)

This is supposed to be a tool that gives you a starting point schema that you can build upon manually.  It's not something that's expected to run in a production environment.  I say so in the docs very explicitly and loudly.  I'm not expecting it to run in a multithreaded environment.

**Comment by ArcanoxDragon** [comment]
> This is supposed to be a tool that gives you a starting point schema that you can build upon manually. It's not something that's expected to run in a production environment. I say so in the docs very explicitly and loudly. I'm not expecting it to run in a multithreaded environment.

Do you have any plans (in the near or distant future) to expand the library so that it is "suitable" for production use? There isn't much out there to choose from in the way of JSON Schema generation libraries, unfortunately, the main one being `Newtonsoft.Json.Schema` which requires a paid license.

Your library seems to be producing equivalent schemas as far as I can tell, but it is not inherently thread-safe (not without external locks, at least).

**Comment by gregsdennis** [comment]
So there are several facets to this, and I had a fairly in-depth conversation with the other JSON Schema spec contributors when I was initially putting this library together that has sadly since been lost to the free Slack black hole of time.

### 1. Capability

We (the JSON Schema group) see schemas that are quite complex; things that require humans understanding what's going on.  We don't believe that a generated schema can model desired behavior as accurately as one manually written by a human.  Simple schemas can be generated eaily, but we agree that they should be reviewed by a developer before being used in production.  The developer may find optimizations or other changes that suit their specific needs that a generator can't address.

Additionally, there are schema keywords that are quite useful but simply cannot be expressed properly from .Net.

- `patternProperties`
- `$dynamicRef`/`$dynamicAnchor`
- `if`/`then`/`else`
- `not`

### 2. Compatability

Because JSON Schema is a constraints system, trying to represent a type system, like what .Net uses, is very difficult.  So difficult in fact that we haven't determined a "suggested" way to do it.

There's a lot more information about this [here](https://github.com/json-schema-org/json-schema-spec/issues/348#issuecomment-322940347), explained better than I can.

### 3. Practicailty

Because you're generating schemas from .Net types, it's very likely that the set of types you want covered by schemas is unchanging.  This means that you know the types that need schemas at build time.  It's therefore better to generate schemas _before_ run time and then store them than to generate them _at_ run time (even with a caching mechanism).  If you're doing this, then it makes sense to have a developer verify that the schema that's generated is actually what you want and perhaps make further edits to optimize/tweak them and taylor them to your needs.

Creating them before run time means that you likely have tooling that looks at an assembly and generates schemas for the appropriate types.  Speed and parallelism isn't commonly a concern in such tooling, and so it's not a priority of mine.

The only exception to this is if you're creating .Net types at run time (e.g. IL generation), and I'm not convinced that generating a schema for such types is a good idea.

---

All of that said, of course I want to make this work as best as I can while being easy to use.  But I firmly believe that generating schemas for your types at runtime is a bad idea.  As such, I cannot include features that encourage developers to write applications that do so.

**Comment by ArcanoxDragon** [comment]
My use case for generating schemas at runtime may be a bit different than the typical use case. I have a browser (TypeScript) application that acts as a visual editor for a wide variety of models, determined by what the C# back-end gives it. The easiest way to communicate the structure and constraints on the model is by generating a JSON Schema of a model's C# class, passing that to the browser along with the JSON representation of the model's current state, and the browser app then understands exactly how to represent the model for editing.

In this use case, generating a schema ahead of time and having a human modify it afterwards would add an impractical amount of maintenance effort; that's where the runtime generation comes into play.

**Comment by gregsdennis** [comment]
> determined by what the C# back-end gives it

This is the part that I'm talking about.  A C# back-end is going to be precompiled.  You're not generating types at runtime.  The schema space is finite and predetermined.

I don't feel comfortable saying that any version of this library (or any schema generation library) will be safe for use in production.  It is offered as a design-time tool.  It may be sufficient for some simple models, but there are complexities in building schemas that cannot be accounted for in generation like this.

My suggestion is to generate schemas, review them, and then store them for retrieval at run time.  If they happen to not need any manual changes, that's great.  However I cannot guarantee that.

**Comment by nielsvanvelzen** [comment]
This issue was closed with the release of 2.0.0 but I don't think #143 is actually solved. Using `System.ComponentModel.DataAnnotations` doesn't seem to affect the generated schemas.

**Comment by gregsdennis** [comment]
Based on the experience mentioned in https://github.com/gregsdennis/json-everything/issues/143#issuecomment-877759620, I've opted to not include built-in support for the annotations in `DataAnnotations`.  Trying to fit both in, even with a configuration, is confusing, and having my own set of attributes allows:

- my own customization of the attributes to align with JSON Schema, and
- separation of concerns: schema generation vs serialization.

I'm sorry, but this isn't something I'm going to be adding.

**Comment by nielsvanvelzen** [comment]
Understandable, thanks for the explanation!
