### ISSUE TITLE
Validate Patch with Schema

### ISSUE THREAD

**Issue by Chaosflo** [gregsdennis/json-everything#199]
**Describe the functionality that isn't covered by this suite**
I don't know if that's already considered but what would be nice is to combine JsonSchema.Net with JsonPatch.Net.

I want to validate the patch elements with a schema.

**Describe alternatives you've considered**
What could be done is to traverse the schema with a json path and validate the part of the schema with the patch.
I think this could be done easily!

**Additional context**
When I have overseen the feature please let me know!

Thanks for reading
Greetings from austria

**Comment by gregsdennis** [comment]
Thanks for the idea.  I'm having trouble following that you mean, though.  Can you explain with an example?

**Comment by Chaosflo** [comment]
For sure! 

In my application I send patches for updating around.

Because the store has no validation mechanism, I must do it at the api.

Means I get let's say this Patch 

`[
  { "op": "replace", "path": "/baz", "value": "boo" },
  { "op": "add", "path": "/hello", "value": ["world"] },
  { "op": "remove", "path": "/foo" }
]`

Then I want to go through every item and validate them.

So watch the first operation.
The property 'baz' can only handle numeric values.
So what I want is that this get's an issue. 

Then the second 
Is the array with name 'hello' capable of adding another string element? 
If it is an string array and, let's say for further complexity, is unique in the array this get's valid.

Then the third
When I remove the value of 'foo', is it valid to do so? 
Is it required, ...

And so on 

I hope it's clear what I have meant here

**Comment by gregsdennis** [comment]
That's an interesting problem.  I think, though, that it might be easier (and perhaps more efficient) to just validate the data after applying the patch.

```c#
var patch = JsonSerializer.Deserialize<JsonPatch>(patchText);
var data = JsonDocument.Parse(jsonText).RootElement;
var schemaForData = JsonSerializer.Deserialize<JsonSchema>(schemaText);

var patchResults = patch.Apply(data);
var newData = patchResults.Result;

var schemaResults = schemaForData.Validate(newData);

if (!schemaResults.IsValid)
    throw new Exception("Patch resulted in invalid data");

return newData;
```

This seems a better approach than trying to validate after each operation.

In general, the changes a patch would apply can't be validated without the data.  For example, if a patch says to add an item to an array, but the schema says there's a maximum number of items for that array, we can't know if the result is valid unless we have the data that we're starting with.

**Comment by Chaosflo** [comment]
Sadly that would be extremly inperformant.

I will get megabytes of data in my store.
When I need to download everytime the whole megabyte, apply the patch and then validate would make the patch irrelevant.

So that's why I had the idea of validating the patch and not the whole document which has at min mega bytes of date =/

**Comment by gregsdennis** [comment]
> download everytime the whole megabyte...

What are you downloading every time?

**Comment by Chaosflo** [comment]
The data from the store.

When I do it like you proposed I need to download the whole data from the store.
Apply the patch to the whole data.
Then after the patch I need to check if the data is valid.
And then I need to send the whole data to the store again to be updated =/ 

My plan is to avoid that because of performance reason.

Means I get the patch.
Then I validate only the patch with the json schema
The last step to send only the patch to the store

**Comment by gregsdennis** [comment]
I think your proposal is an interesting idea, but, as I mentioned before, it's not a generally solvable problem.

If I were to have a go at it, I'd do it in another library rather than include it in one I have defined already.  I encourage you to try to implement it yourself.  If you come up with something, I'd be interested to hear how it works.

Thanks.
