### ISSUE TITLE
JSONata

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#20]
[JSONata](http://docs.jsonata.org/overview.html) ("j-sonata") is a query language for JSON data.

**Comment by JMPSequeira** [comment]
Hey, are you actually thinking of bringing this to .NET? Do you have any timeframe as to it's development?

**Comment by gregsdennis** [comment]
I have it here as a placeholder until it gains some interest.

There's a lot of work involved to support JSONata since it's a syntax outside of JSON.  I have to build my own parser and everything; I can't rely on System.Text.Json.
