### ISSUE TITLE
Json.Schema.Generation: schema from "legacy" immutable classes (before C# record)

### ISSUE THREAD

**Issue by ugumba** [gregsdennis/json-everything#202]
Legacy immutable classes typically have getter-only properties, which are only settable by the constructor.

System.Text.Json automatically detects and supports these properties - it can also be enforced by [JsonConstructor].
Getter-only properties are, however, filtered out and ignored by ObjectSchemaGenerator.
It's a bit jarring when Json.Schema.Generation is missing semantics from System.Text.Json.

A couple of workarounds for when the code is available, in order of personal preference:

* Port to C# record (the init-only getter seems to get past the filter in ObjectSchemaGenerator)
* Use readonly field instead of getter-only property

When types come from 3rd party assemblies, however, these workarounds are not available.

**Comment by gregsdennis** [comment]
I mentioned the reasoning behind the current support of only read/write properties [here](https://github.com/gregsdennis/json-everything/issues/149#issuecomment-892492510).

It seems this may have changed recently with .net 6.

Also, I'm working on a [2.0](https://github.com/gregsdennis/json-everything/issues/198).  I welcome your suggestions there.

**Comment by ugumba** [comment]
Thanks!
Just to note that this is not new with .NET 6 - System.Text.Json has handled readonly properties, matching them up with constructor parameters at least since .NET 5.  I know, it's a somewhat annoying bit of magic for J.S.Generation to consider mirroring.

**Comment by gregsdennis** [comment]
Version 2 is out.  It now supports single-accessor properties and readonly fields by adding the appropriate keywords to the schema.  This behavior can be overridden by the attributes.
