### ISSUE TITLE
JSON validation regression in JsonSchema.Net v1.12.0

### ISSUE THREAD

**Issue by coderpatros** [gregsdennis/json-everything#203]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: v1.12.0
- OS: Windows Server 2022, Ubuntu 20.04 and Mac OS 11
- .Net Target: .NET 6

**Describe the bug**
Dependabot bumped this dependency version in one of my projects and a bunch of tests failed. I've checked it out locally and it appears there was a regression introduced between v1.11.6 and v1.12.0. But I can't tell what might be causing that by looking at the changes.

**To Reproduce**
I have tried to create a fairly minimal reproduction here https://github.com/coderpatros/jsonschema.net-validation-repro

That has the version set as v1.11.6 so you can confirm it was working as expected first.

**Expected behavior**
I expect the example in the repro to validate as valid JSON.

**Comment by gregsdennis** [comment]
Thank for reporting this and coming up with the repro solution. I'll check it out.

**Comment by gregsdennis** [comment]
It looks like you have a few issues in your schema.  In several places, you specify `format: string`.  This is not a known format.  Fixing this was actually one of the [specific changes of 1.12.0](https://gregsdennis.github.io/json-everything/release-notes/json-schema.html), but it seems that fix may have been a little overzealous.

From [draft 7, section 7.1](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-7.1):

> A format attribute can generally only validate a given set of instance types.  If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.

So, yeah, it looks like validation should succeed here.  I'll propose a test be added to [the test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) as it looks like this may not be covered.

**Comment by coderpatros** [comment]
:man_facepalming: thanks for picking that up. I assumed it was correct because we've used it across a bunch of different JSON validators. Guess they all are forgiving of invalid formats.

Thanks heaps @gregsdennis

**Comment by gregsdennis** [comment]
I just checked the test suite.  It doesn't appear to contain an "unknown format" test.  I'll set up a PR to add one, then I can update the library.

**Comment by gregsdennis** [comment]
[@itsverywindy](https://github.com/ItsVeryWindy), you may be interested in this one.  It looks like unknown formats should pass validation, per the spec.  In #193, you said

> Currently it seems that there is no way to force a failure when encountering an unknown format.

In order to address this, I'm going to add option `bool OnlyKnownFormats` to support your desired behavior.

**Comment by coderpatros** [comment]
Thanks heaps for looking into this for me. And the awesome library.
