### ISSUE TITLE
Incorrect XML-doc summaries on some intent constructors

### ISSUE THREAD

**Issue by cosborne83** [gregsdennis/json-everything#206]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.8.3
- OS: Windows
- .Net Target: .NET 6

**Describe the bug**

1.  The XML-doc summary for Json.Schema.Generation.Intents.DescriptionIntent constructor incorrectly states that it "Creates a new **MinimumIntent** instance."

See: https://github.com/gregsdennis/json-everything/blob/5b257ecb789d0f434269713182fe35282c921e89/JsonSchema.Generation/Intents/DescriptionIntent.cs#L14

2. The XML-doc summaries for Json.Schema.Generation.Intents.EnumIntent constructors appear to have been copied from the "Apply" method.

See: https://github.com/gregsdennis/json-everything/blob/5b257ecb789d0f434269713182fe35282c921e89/JsonSchema.Generation/Intents/EnumIntent.cs#L19
and: https://github.com/gregsdennis/json-everything/blob/5b257ecb789d0f434269713182fe35282c921e89/JsonSchema.Generation/Intents/EnumIntent.cs#L28

**To Reproduce**
Comments visible in IntelliSense when writing code to construct a new DescriptionIntent or EnumIntent.

**Expected behavior**
The summary should indicate that the constructor creates a new DescriptionIntent or EnumIntent instance per summaries on other Intent constructors.

**Comment by gregsdennis** [comment]
Thanks for reporting these.  I'm working on a 2.0 of this library, and I'll try to review these comments before publish.
