### ISSUE TITLE
vocabularies not being applied correctly when using different schemas

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#207]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.0.0

**Describe the bug**
Essentially, if one schema that uses a vocabulary and then references another schema that uses a different vocabulary, when the second schema is read it overwrites the vocabulary being used and then that vocabulary is applied regardless of the schema being validated.

**To Reproduce**
1. Create a schema that references a schema using a vocabulary (ie.2020)
2. Have that schema reference another schema that uses a different vocabulary (ie. 2019)
3. After that reference any keyword in the first schema that is particular to just that vocab (eg. $dynamicRef which is only available in 2020)

**Expected behavior**
Behave the same way as before.

**Additional context**
This appears to be a regression from 1.x. and it's to do with these parts here. The SchemaKeyword sets what vocab to filter by, but there is nothing responsible for clearing that up when that schema is finished validating. So in the example above the 2019 schema will set the vocabulary and that carries on after when executing the rest of the 2020 schema.

https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/SchemaKeyword.cs#L56
https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/ValidationContext.cs#L171
https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/JsonSchema.cs#L211

Also note here that the keyword filtering happens before the first keyword is processed, so in the example above the 2020 schema dictates what vocab is filtered for the root of the 2019 schema.

**Comment by gregsdennis** [comment]
I believe there are a few tests in the suite that cover this, but they may be optional, so I'm going to add some explicit ones.

This may be a result of reducing down to a single, reused context object.

**Comment by gregsdennis** [comment]
I've created this test:

```c#
JsonSchema schema = new JsonSchemaBuilder()
	.Schema(MetaSchemas.Draft202012Id)
	.Type(SchemaValueType.Array)
	.Items(new JsonSchemaBuilder().Ref("#/$defs/draft7schema"))
	.Defs(
		("draft7schema", new JsonSchemaBuilder()
			.Schema(MetaSchemas.Draft7Id)
			.Type(SchemaValueType.Array)
			.PrefixItems(new JsonSchemaBuilder().Type(SchemaValueType.Number))
			.Items(new JsonSchemaBuilder().Type(SchemaValueType.String))
		)
	);

var instance = JsonDocument.Parse("[[\"string\"]]");

var result = schema.Validate(instance.RootElement, new ValidationOptions() {OutputFormat = OutputFormat.Detailed});

Console.WriteLine(JsonSerializer.Serialize(result, new JsonSerializerOptions {WriteIndented = true}));
Assert.True(result.IsValid);
```

which validates 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "$ref": "#/$defs/draft7schema"
  },
  "$defs": {
    "draft7schema": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "prefixItems": [
        {
          "type": "number"
        }
      ],
      "items": {
        "type": "string"
      }
    }
  }
}
```

against `[["string"]]`.

The idea is that `prefixItems` should be ignored since it's a draft 2020-12 keyword in a draft 7 schema.

Not only does it pass, the logs show that it appropriately ignores `prefixItems`.

```
Registering subschemas.
Beginning validation.
  Processing $schema...
  $schema complete: valid
  Processing $id...
  $id complete: valid
  Processing $defs...
  $defs complete: valid
  Processing type...
  type complete: valid
  Processing items...
    Validating item at index 0.
      Processing $ref...
        Processing $schema...
        $schema complete: valid
        Processing $id...
        $id complete: valid
        Processing type...
        type complete: valid
        Processing items...
          Validating item at index 0.
            Processing type...
            type complete: valid
          Item at index 0 valid.
        items complete: valid
      $ref complete: valid
    Item at index 0 valid.
  items complete: valid
Transforming output.
Validation complete: valid
```

**Comment by gregsdennis** [comment]
I just noticed you have some special sequencing in your scenario.  Can you write a test or adjust my test to replicate?

**Comment by ItsVeryWindy** [comment]
So I've tweaked your test a bit, one thing I did notice that I didn't before is that you filter things twice, the first time by draft and then by vocabulary, so in order to trigger it you need to use a keyword that's valid for the schema you're using, but not in the vocabulary of the one you're coming from.

```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "array",
    "items": {
        "$ref": "#/$defs/draft2020schema"
    },
    "$defs": {
        "draft2020schema": {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "type": "array",
            "prefixItems": [
                {
                    "type": "number"
                }
            ],
            "items": {
                "type": "string"
            }
        }
    }
}
```

**Comment by gregsdennis** [comment]
Okay, Yeah, that replicated it.  Thanks.

The instance I was using was `[ [ 1, "string" ] ]`, which should validate, but fails on the `1`, thinking it should be a string.  The log for this validation is:

```
Registering subschemas.
Beginning validation.
  Processing $schema...
  $schema complete: valid
  Processing $id...
  $id complete: valid
  Processing $defs...
  $defs complete: valid
  Processing type...
  type complete: valid
  Processing items...
    Validating item at index 0.
      Processing $ref...
        Processing $schema...
        $schema complete: valid
        Processing $id...
        $id complete: valid
        Processing type...
        type complete: valid
        Processing items...
          Validating item at index 0.
            Processing type...
            type complete: invalid
          Item at index 0 invalid.
          Validating item at index 1.
            Processing type...
            type complete: valid
          Item at index 1 valid.
        items complete: invalid
      $ref complete: invalid
    Item at index 0 invalid.
  items complete: invalid
Transforming output.
Validation complete: invalid
```

**Comment by gregsdennis** [comment]
v2.0.1 should be available shortly.  If you don't mind, please also verify that #208 is fix as well.

**Comment by gregsdennis** [comment]
One of my collaborators in JSON Schema pointed out that `$schema` should only be applied if it's adjacent to an `$id` that declares a new base URI.

Additionally, `$schema` should only be allowed at non-root locations in 2020-12.

**Comment by ItsVeryWindy** [comment]
So, I can verify that this issue seems to be fixed, nice one 👍 . But #208 does not appear to be as I'm still getting issues with references in the subschema not resolving.  At least for my purposes I can currently work around the issue by referencing it instead of embedding it.
