### ISSUE TITLE
Using json-everything to validation Json?

### ISSUE THREAD

**Issue by clintcarter1999** [gregsdennis/json-everything#215]
I am trying to find an example of validating json body with a json schema loaded from file using JsonSchema.Net in C#.
I am not sure who to ask other than I see your name, gregsdennis on the Nugget Package.
Any chance you could point me in the right direction?

**Comment by gregsdennis** [comment]
Hello.  Yes, this is the correct place.  Have you seen the [documentation](https://gregsdennis.github.io/json-everything/usage/schema-building.html)?
