### ISSUE TITLE
JsonLogic can't compare strings with dots in them.

### ISSUE THREAD

**Issue by CJHunter91** [gregsdennis/json-everything#219]
**Environment**
- .Net Target: core .Net6

**How can I help you today?**
I'm trying to use JsonLogic that uses a json path to find a data schema.

 Is there is a way of evaluating the json logic and just comparing the variable as a string against the data rather than a path?
If I evaluate the following, it will always evaluate to 3 because its trying to find the value within a nested object.
The reason it is keyed to a json path is that that's the identifier for the field data.
`      
var ruleObj = JsonSerializer.Deserialize<Rule>("{\"if\":[" +
    "{\"==\": [{\"var\": \"$.properties.deoxynivalenolRisk\"}, 10] }," +
    "2," +
    "3" +
    "]}"
    );
var result = ruleObj.Apply(JsonDocument.Parse("{\"$.properties.deoxynivalenolRisk\": 10}").RootElement);

Console.WriteLine(JsonSerializer.Deserialize<int>(result.GetRawText()));
Console.Read();
`

**Additional context**

**Comment by gregsdennis** [comment]
That's an interesting one.  Have you tried it at https://jsonlogic.com/play.html to see what the original implementation does?

**Comment by gregsdennis** [comment]
I've tested this on the JSON Logic site I linked above, and it's giving the same result: `3`.

I understand what you're asking for, but I prefer to remain in compliance with the original implementation.  You may want to open a bug on [their site](https://github.com/jwadhams/json-logic/issues) to have the rules around this scenario changed.
