### ISSUE TITLE
resolving references inside an item fails

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#220]
**Environment**
Online

**Describe the bug**
This following fails when it tries to resolve the reference, not sure if it's also an issue elsewhere with other keywords.

**To Reproduce**
Schema
```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://json-schema.org/draft/2019-09/schema",
    "$ref": "#/$defs/test/items/properties/test",
    "$defs": {
      "test": {
      	"items": {
          "properties": {
            "test": {
              "type": "string"
            }
          }
        }
      }
    }
}
```
Data
```
{}
```

**Expected behavior**
Error that the data isn't a string.

**Additional context**
I suspect this issue seems to be around how the `ItemsKeyword` implements `ResolvePointerSegment` as it assumes it's either going to be passed null or a number, but in this case it is passed "properties".

Potentially the fix is as simple as passing downstream when a single schema is involved. I have flipped some of the logic here as "0/1/2/3" may also be a reference to a property.

```csharp
IRefResolvable? IRefResolvable.ResolvePointerSegment(string? value)
{
	if (SingleSchema == null)
	{
		if (!int.TryParse(value, out var index)) return null;
		if (index < 0 || ArraySchemas!.Count <= index) return null;

		return ArraySchemas[index];
	}

	if (value == null) return SingleSchema;

	IRefResolvable resolvable = SingleSchema;

	return resolvable.ResolvePointerSegment(value);
}
```

**Comment by gregsdennis** [comment]
I'm sure I replied to this, and I'm fairly sure I fixed this, but I'll check again tonight.

Sorry for the delay.

**Comment by gregsdennis** [comment]
The first thing that jumped out at me is that your `$id` is the same as the `$schema`, which will definitely confuse the validator.  It's not the problem, but you probably want to use a URI that's not a meta-schema URI for `$id`.

**Comment by gregsdennis** [comment]
You are correct in isolating where the issue is, but your solution is recursive, which is something I tried to avoid for this process.  The flow is controlled in `JsonSchema`.  The idea was that this would return `SingleSchema` which would then be handled in the next loop iteration.

This problem is actually more widespread than just `items`.  It's in all of the keywords that support a single schema, like `additionalProperties` and `if`, etc.
