### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by moscarelli** [gregsdennis/json-everything#222]
Hi. 
I just need clarification over the license.
Does this package require any kind of commercial license if used to build on a commercial application? 
I see the license page and see the commercial license is free just want to be sure because I saw some other packages that say commercial license-free but internally they use NewtonSoft which requires licensing for commercial use. 

Thanks for the attention.

**Comment by gregsdennis** [comment]
The license is MIT - free to use.

If you still want to contribute financially, you can using the "sponsor" button down at the top of the GitHub page.
