### ISSUE TITLE
Full Examples

### ISSUE THREAD

**Issue by moscarelli** [gregsdennis/json-everything#223]
Hi, I'm looking for full documentation (examples) on how to generate a schema save it as a text and then use this to validate a JSON text.

From the documentation, I found on the web I came to the generation of text being executed by 
```
 var schemaBuilder = new JsonSchemaBuilder();
            var schma = schemaBuilder.FromType<Test1>().Build();
            var text = JsonSerializer.Serialize(schma);
```
Not sure if this is the correct way.

Also considering the validation and grab the errors  I can't find a way to grab a JSON text object and use the schema generated to validate it grab the possible errors. 

Thanks very much.

**Comment by gregsdennis** [comment]
Your code is fine to generate the schema.

```c#
var schemaBuilder = new JsonSchemaBuilder();

// here is where the schema is actually generated.  This object is what you'll use to
// validate incoming JSON data.
var schma = schemaBuilder.FromType<Test1>().Build();

// this just gets the schema as JSON text.  It's not really necessary unless you want
// to store the schema somewhere (e.g. a file or DB)
var text = JsonSerializer.Serialize(schma);
```

To perform validations, you just need to parse the JSON instance and pass it to the `Validate()` method.

```c#
var instance = JsonDocument.Parse(jsonText).RootElement;

var results = schma.Validate(instance);
```

---

I hesitate to put a full example in the docs because I don't believe any generation like this can be good enough to use directly in production.  I think it's good to use as a tool which produces an artifact and for humans to review, and edit if necessary, the artifact before production use.  I state this in the documentation:

> Ideally, this functionality should be used to create a starting point in authoring a schema. The schemas output by this library should be reviewed by actual people prior to being put into a production system.

The [examples I have](https://gregsdennis.github.io/json-everything/examples/index.html) currently cover more advanced scenarios since most of the common usage is covered inline in the [Usage](https://gregsdennis.github.io/json-everything/usage/json-more.html) sections.  The section on validation can be found [here](https://gregsdennis.github.io/json-everything/usage/schema-validation.html).

**Comment by moscarelli** [comment]
I found this discussion and agreed 100%, mostly because it is also the exact way I architected my project structure, since generating the schemas at run time would be time-consuming and considering the objects are always the same (project entities) there was no reason to make that happen every time I need validation, having the schemas files stored separately seems to be the right call and it was 😄 . I have a separated tool (a desktop app) and my project has a post-build event set to call the app so the schemas are generated once 👍 
I will make some more tests and let you know the results. 
Thanks very much

**Comment by moscarelli** [comment]
So I might be doing something wrong 
I use this code 

`var schemaBuilder = new JsonSchemaBuilder();

            // Here is where the schema is actually generated.  This object is what you'll use to
            // validate incoming JSON data.
            var schma = schemaBuilder.FromType<Test1>().Build();

            // This just gets the schema as JSON text.  It's not really necessary unless you want
            // to store the schema somewhere (e.g. a file or DB)
            var text = JsonSerializer.Serialize(schma);

            //To perform validations, you just need to parse the JSON instance and pass it to the Validate() method.

            var jsonText = JsonSerializer.Serialize(new Test1 {ID = null });

            var instance = JsonDocument.Parse(jsonText).RootElement;

            
            var results = schma.Validate(instance);`

`    public  class Test1
    {
        
        [Required]
        public int? ID { get; set; } 
        
        [Nullable(false)]
        public string Name { get; set; } 
        
        public int test { get; set; }

        [UniqueItems(true)]
        [Minimum(1)]
        public List<string> Lines { get; set; } 
    }`

It generates this schema 

`{"type":"object","properties":{"ID":{"type":"integer"},"Name":{"type":"string"},"test":{"type":"integer"},"Lines":{"type":"array","items":{"type":"string"},"uniqueItems":true}},"required":["ID"]}`

I tested with this instance 
`{"ID":null,"Name":null,"test":0,"Lines":null}`


But the results variable show no errors 
![image](https://user-images.githubusercontent.com/39997204/155255546-3c074bac-6d7f-43e3-89e9-7f724dfe2794.png)


not sure what I'm doing wrong on the code just to confirm both are ok I  posted then in the  web page to test the schema and the instance and got the validation I was expecting 

Value is null but should be integer
Instance location: #/ID
Schema location: #/properties/ID/type
Value is null but should be string
Instance location: #/Name
Schema location: #/properties/Name/type
Value is null but should be array
Instance location: #/Lines
Schema location: #/properties/Lines/type


What I'm doing wrong?

**Comment by gregsdennis** [comment]
I see that you're serializing the model to get the instance. Are you sure that the null values are present in the model?  The serializer usually omits properties with default values, so you may be getting just `{}`.  Since you're not requiring any properties, that'll pass validation.

**Comment by moscarelli** [comment]
Hi, yes they are, this is the serialized instante {"ID":null,"Name":null,"test":0,"Lines":null}

**Comment by moscarelli** [comment]
Well found out the issue.  I search on the issues list and found an example of validation, we need to pass a format to get their results, I add  (new ValidationOptions { OutputFormat = OutputFormat.Basic }) solved my issue.

![image](https://user-images.githubusercontent.com/39997204/155332095-79ec2efa-56f8-423a-bd43-c1bf94c1c748.png)

Thank you. 😄

**Comment by gregsdennis** [comment]
I'm glad you found the issue.

Please let me know if I can make the documentation clearer.

**Comment by moscarelli** [comment]
Things that might help are:

Think the current documentation might be overwhelming for most people 😄  (me included) . A few lines on how to have it on a daily basis scenario will help very much.

Also, 
Let more clear that the property annotation came from Json.Schema.Generation namespace. One can think this will be a regular Data Annotation or even a JsonProperty kind of annotation. It removes the ambiguity.

Highlight the necessity of the Formater on the Validation method, is in the IntelliSense but one could thing is optional and the verbose messages are the default with they aren't.

Display a simple application example in the docs will explain a lot on how to deal with the object with basics for generating and validating the JSON.  I understand the concerns but this kind of basic example is probably the majority of functionality that makes other developers go search for this kind of package. 

Thanks very much.

**Comment by gregsdennis** [comment]
Since I've redone the website, I need to find a place for examples.  I think it might just be having an examples folder in the repo.

**Comment by gregsdennis** [comment]
I've added an area for some examples to the website.  Please let me know if you'd like me to include any specific examples that are missing (or create a PR yourself if you like.)
