### ISSUE TITLE
Using JSONPath instead of JSONPointer for resolving $data references

### ISSUE THREAD

**Issue by manuschillerdev** [gregsdennis/json-everything#224]
**Environment**
--

**How can I help you today?**
Currently, the known implementations for the $data keyword (json-everything, ajv) use JSONPointer for resolving references provided for `$data` attributes.

I am thinking if it would make more sense to use JSONPath instead for being able to query values instead of providing a strict reference to it. Think of having an array of objects, and you want to validate that at least one of its objects matches `.selected = true`:

```
$.myArray[?(@.selected == true)]
```

I think this would not be possible with JSONPointer today, right?

**Comment by gregsdennis** [comment]
This is a common question.  Thanks for asking.

***NOTE** ajv uses `$data`, but I've stayed away from using keywords starting with `$` as JSON Schema will likely  reserve them soon.*

I used JSON Pointer for multiple reason, but mostly because it can only indicate a single value whereas JSON Path has the potential of returning multiple values.

Other reasons include:

- JSON Schema already uses JSON Pointer, not JSON Path (also for the reason above)
- JSON Pointers are common in URIs which can be used to reference external data; JSON Path cannot be used in a URI.

**Comment by manuschillerdev** [comment]
> I used JSON Pointer for multiple reason, but mostly because it can only indicate a single value whereas JSON Path has the potential of returning multiple values.

I see, thanks! What if we dissallowed multiple values being returned from a resolved JSONPath and throwed an Error in this case? "JSONPaths may only return a single value"

We could still leverage the power of queries while maintaining common resolver logic, right?

**Comment by gregsdennis** [comment]
You still have the problem of embedding them in URIs for external references.

JSON Pointer was _made_ specifically to identify a single location.  It's the right tool for the job.

Yes, it's my vocabulary, and I can do what I want with it, but I'm not ready to introduce a new syntax that JSON Schema isn't already using.

---

That said, you may be interested in [this discussion](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/155) over in the JSON Path spec repo (which I'm also a part of).

**Comment by manuschillerdev** [comment]
> That said, you may be interested in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/155 over in the JSON Path spec repo (which I'm also a part of).

Thanks for the context !

> Yes, it's my vocabulary, and I can do what I want with it, but I'm not ready to introduce a new syntax that JSON Schema isn't already using.

No problem at all, I think I didn't make it clear enough, that this was asked only out of curiosity and was not intended to be a feature request at all! 

Thanks again for all your great work in the JSON space and for your hard work on the library!
