### ISSUE TITLE
Clarification on ValidationResults

### ISSUE THREAD

**Issue by ohmineer** [gregsdennis/json-everything#226]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.0.2
- OS: Windows
- .Net Target: .NET 6.0

**How can I help you today?**
I am trying to validate a Json file against a schema but I can't seem to understand the results. 
Validator is using `OutputFormat.Basic` and I get `IsValid = true` property so I expected then NestedResults count to be 0.
 On the contrary, this is what I am observing: 

![NestedResults](https://user-images.githubusercontent.com/8396492/155525767-c84668dd-d13d-4bea-9a17-433ce9cf2c27.png)

I am confused about the fact that each `NestedResult` are also valid but the `Message` property looks like an error.
Currently, my code returns `ValidationResults` to subsequent stages and the count of `NestedResults` was my error flag. 
This does not seem to be the right strategy. 

Using the same files, the [online tool](https://json-everything.net/json-schema) deems the JSON demo file is valid and returns a combination of annotations and results but not messages.

Should I ignore the messages and/or `NestedResults` when `IsValid` is true? 

Thanks in advance for your support,

**Additional context**
This is the JSON Schema I am using for validation:
````json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$ref": "#/definitions/TestSequence",
  "definitions": {
    "TestSequence": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "tests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Test"
          }
        }
      },
      "required": [
        "tests"
      ],
      "title": "TestSequence"
    },
    "Test": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "id": {
          "type": "number"
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Result"
          }
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "results"
      ],
      "title": "Test"
    },
    "Result": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "result": {
          "default": ""
        },
        "lowerLimit": {
          "default": ""
        },
        "upperLimit": {
          "default": ""
        }
      },
      "title": "Result",
      "required": [
        "result"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "result": {
                "type": "number"
              }
            }
          },
          "then": {
            "properties": {
              "lowerLimit": {
                "type": "number"
              },
              "upperLimit": {
                "type": "number"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "result": {
                "type": "string"
              }
            }
          },
          "then": {
            "properties": {
              "lowerLimit": {
                "type": "string"
              },
              "upperLimit": {
                "type": "string"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "result": {
                "type": "boolean"
              }
            }
          },
          "then": {
            "properties": {
              "lowerLimit": {
                "type": "boolean"
              },
              "upperLimit": {
                "type": "boolean"
              }
            }
          }
        }
      ]
    }
  }
}
````

And this is the JSON file I am using:
````json
{
  "tests": [
    {
      "id": 60011,
      "results": [
        {
          "result": 6,
          "lowerLimit": 5
        },
        {
          "result": 3,
          "lowerLimit": 5
        }
      ]
    }
  ]
}
````

**Comment by gregsdennis** [comment]
Thanks for reporting this!

🤔 I'm not sure what's going on here.  I've tested on https://json-everything.net/json-schema, and the schema's reporting as valid.  This is expected though as it matches your result.  However, the error message isn't serialized for nodes that show successful validations, so the site's not going to highlight the issue.

I'll replicate this in a unit test later so I can debug through it.

**Comment by gregsdennis** [comment]
Okay, it looks like this is an issue in how I collapse the results.  When I process the validation, I build the entire tree of results.  Then, right before I return from validation, I collapse the result nodes based on the desired output format.

I'll dig in a bit more and see why this is maintaining an error message.

Again, it _is_ serializing correctly, though, so you see no error message there.

**Comment by gregsdennis** [comment]
An update will be published soon.  Those nested items shouldn't have been included.

I had logic that kept any nodes that had a message, whether or not they failed validation.  I've fixed this inclusion logic, so that won't be a problem anymore.

For this, you should only expect a root node declaring validation success.

**Comment by ohmineer** [comment]
Thanks for the clarification and the quick solution!

**Comment by gregsdennis** [comment]
I just noticed something on this while doing some refactoring.  For draft 7, anything adjacent to a `$ref` should be ignored.  Since you have a `$ref` at the root, the `definitions` are ignored, so the `$ref` shouldn't be able to resolve.  This is actually left as implementation-defined by the spec, but it makes sense to me to adhere to this rule.

As a result, future versions (v4+) will not process this schema as expected.  You'll need to update to a later draft (recommended) or wrap the `$ref` in an `allOf`:

```json
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [ 
	  { "$ref": "#/definitions/TestSequence" }
  ],
  "definitions": {
    ...
  }
}
```
