### ISSUE TITLE
Schema format

### ISSUE THREAD

**Issue by moscarelli** [gregsdennis/json-everything#229]
Hi. 
There is a way to generate the schemas with some format? 
Currently, all the schemas are generated inline (no newlines)  I looked on the SchemaGeneratorConfiguration class but did not find anything clear about how to make the schemas look better. 

Thanks,

**Comment by gregsdennis** [comment]
I'm not sure what you mean.  Schemas are generated as actual `JsonSchema` instances.  There's no formatting involved.

You would format them when you serialize, at which point you can use `new JsonSerializerOptions { WriteIntented = true }`.

**Comment by MichaelJachan** [comment]
merci :) (y)
