### ISSUE TITLE
Unable to Read Property Names Starting with Commercial 'at' Sign (@)

### ISSUE THREAD

**Issue by DanielBoulerice** [gregsdennis/json-everything#234]
**Environment**
- Nuget Package: JsonPath.Net
- Nuget Version: 0.1.14
- OS: Windows
- .Net Target: .Net 5

We want to implement a configurable JSON decider to "decide" if an input JSON can be processed normally.  We read a system that gives us JSON-encoded objects.  So far, all is fine.  To implement the decider, I use JsonPath.Net, but selectors will fail because the  JSONs we get contains names starting with '@' characters, e.g.:

**This is a typical JSON:**
```
JSON:
{
  "id": "bsd_REQQA-317426",
  "name1": "val1",
  "name2": "val2",
  "note": [
    {
      "@type": "SomeNoteType",
      "id": "91112cf4-7cbf-41c7-a4dd-9241b247f821",
      "date": "2022-01-04T20:54:17.36888923Z",
      "text": "OT Overview ID:000000000012821\nFacility Name:Test Case 96",
      "@baseType": "Note",
      "noteType": "Internal"
    },
    {
      "@type": "AnotherNote",
      "id": "5384acca-4497-4b37-aa98-f857f1b82637",
      "date": "2021-09-12T12:25:30Z",
      "text": "Add some Internal Note reading stuff.",
      "author": "RPA System",
      "@baseType": "Note",
      "noteType": "Internal",
      "summary": "Some guy testing."
    }
  ]
}

```
And when I write a JSONPath query to get a @Type, it fails.  See the last case below.  All the others work but for case 4, which is identical to case 3, but for the queried name.
```
--------------
  Criterion: $.id
    bsd_REQQA-317426
--------------
  Criterion: $.note[?(.id=="91112cf4-7cbf-41c7-a4dd-9241b247f821")].text
    OT Overview ID:000000000012821
Facility Name:Test Case 96
--------------
  Criterion: $.note[*].text
    OT Overview ID:000000000012821
Facility Name:Test Case 96
    Add some Internal Note reading stuff.
--------------
  Criterion: $.note[*].@type
    PathParseException: Could not identify selector
```
It clearly comes from the JsonPath.Parse on line 97, where "@" is given a specific "LocalRootNode" meaning.

Considering that [RFC 7158](https://datatracker.ietf.org/doc/html/rfc7158) is very loose on the the subject of names (search Section 4 for "An object whose names are all unique is interoperable in the sense that all software implementations receiving that object will agree on the name-value mappings."), we can say that a name starting with "@" is still a valid JSON name because "@Type" is different than "@Wipe" in a C# dictionary.  So the parser seems to have placed the "@" character at too high a priority in the parsing precedence.

**Suggestion**
I would recommend allowing an escape character (backslash?) to allow entering any following character outside parsing logic.

**Comment by gregsdennis** [comment]
Thanks, and this is a good question.

While `@type` is a completely valid _JSON_ property name, it's not going to work with the `.` operator because that only allows `[0-9a-zA-Z_]` chars to follow.  This is intended to represent valid property names in most languages, e.g. C# and JS.

What you need to do for the'this property is use the bracket syntax for property names:

```
$.note[*]['@type']
```

This syntax is for valid JSON property names that do not fit the other format.  This syntax will also be used for so-called "normalized" paths.

**Comment by DanielBoulerice** [comment]
Thanks for that!
