### ISSUE TITLE
Parameterless constructor for use with Web API?

### ISSUE THREAD

**Issue by Nettsentrisk** [gregsdennis/json-everything#239]
I was wondering whether it is or could be possible to do something like:

`public ActionResult Patch([FromBody] JsonPatch patch) `

Doing this works:
`public ActionResult Patch([FromBody] List<PatchOperation> operations) `

Although the former would make this simpler to generate a JsonPatch for use in the method.

**Comment by gregsdennis** [comment]
Thanks for the question.  The `JsonPatch` type already has a JSON converter defined in the library: `PatchJsonConverter`.  This should be invoked during deserialization.

Silly question: are you using System.Text.Json's serializer?

**Comment by Nettsentrisk** [comment]
Not on purpose in any case. So you're saying the following should work without an error about a parameterless constructor?

`public ActionResult Patch([FromBody] JsonPatch patch)`

This is in a project running .NET Framework 4.8.

(Should be noted that I'm a frontender doing some backend-type work here so I'm a bit on thin ice.) 😄

**Comment by gregsdennis** [comment]
It should work if you're using .Net's serializer. If you're using Newtonsoft, then it won't.  In fact, I'm not sure whether this library would work with Newtonsoft at all.

**Comment by gregsdennis** [comment]
Revised: I'm confident it won't work with Newtonsoft.  It uses the System.Text.Json data model underneath.
