### ISSUE TITLE
[Changelog] add page to show release notes

### ISSUE THREAD

**Issue by TilmannBach** [gregsdennis/json-everything#241]
since your new website i am missing the nice release notes overview, which was formerly on: 
https://json-everything.net/release-notes/json-schema.html

where can i get the changelog of `JsonSchema.Net` now?

The link on nuget.org: https://www.nuget.org/packages/JsonSchema.Net (tab Release Notes) also directs to a 404 page

**Comment by gregsdennis** [comment]
Sorry... I'm still working on how to get those in.  It's nice to know someone's looking at them.

In the meantime, you're welcome to look at the [markdown files](https://github.com/gregsdennis/json-everything/tree/master/json-everything.net/wwwroot/md/release-notes).  I _am_ still keeping them up-to-date.

**Comment by gregsdennis** [comment]
Ugh... I updated [these](https://github.com/gregsdennis/json-everything/blob/master/docs_source/release-notes/json-schema.md), not the ones I put in the site.

**Comment by gregsdennis** [comment]
I've added a notice to the site and pinnned this issue for now.

**Comment by TilmannBach** [comment]
thanks for the great work! the link to the markdown files helped me for now :)

**Comment by gregsdennis** [comment]
I've added the release notes to the site now.  They're just kinda in there.  It may change locations in the page.  I make no claims about skill as a UX designer.
