### ISSUE TITLE
anyOf not providing correct results for instance/schema location

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#245]
**Describe the bug**
I noticed something unusual with the results I was getting back whilst using anyOf as the instance and schema locations didn't match what I was expecting. This one seems pretty straightforward, as in this instance anyOf is pushing the schema location as the instance location. I've included a link to the line with the issue as well as what it probably should be for reference.

https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/AnyOfKeyword.cs#L63
https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/AllOfKeyword.cs#L63

**Comment by gregsdennis** [comment]
Thanks @ItsVeryWindy.  I'm your experience, is this only affecting output, or is there something wrong with validation outcomes?

**Comment by ItsVeryWindy** [comment]
As far as I can see it's only affecting output, however there aren't many places where I am using anyOf at the moment. I'm only picking up some of these issues because I've got test code that relies on being able to evaluate the instance and schema locations.

**Comment by gregsdennis** [comment]
Sounds good. I'll see if I can push out an update tonight.  Thanks.
