### ISSUE TITLE
Support for .NET 6 System.Text.Json.Nodes

### ISSUE THREAD

**Issue by janruo** [gregsdennis/json-everything#251]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.3.0
- OS: Win10
- .Net Target: .NET 6

**Can this library make doing something simpler?**
It would be convenient if the library supported the new [System.Text.Json.Nodes namespace classes](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.nodes?view=net-6.0) added in .NET 6.

**Examples:** 
Validating a JsonNode/JsonObject/JsonArray directly:

```cs
var schema = JsonSchema.FromText("{ ... }");
var json = new JsonObject
{
    ["foo"] = true,
    ["bar"] = 123
};

// Suggestion: Add support for this:
schema.Validate(json); 

// Currently we have to do an extra serialization step:
schema.Validate(json.ToJsonString());
```

Dynamically building a schema with a JsonObject:
```cs
var node = new JsonObject
{
    ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
    ["type"] = "object",
    ["properties"] = new JsonObject
    {
        // ...
    },
    ["additionalProperties"] = false
};

// Suggestion: Add a new method to create a schema from a JsonNode, something like:
var schema = JsonSchema.FromNode(node);

// Currently we have to do an extra serialization step:
var schema = JsonSchema.FromText(node.ToJsonString());
```

**Comment by gregsdennis** [comment]
Thanks. I've been contemplating this one, and I'm not sure that nodes are the right model here.  Nodes are read/write, whereas elements are read only.  I can't see a real case for needing to have a writeable instance model; the instance doesn't change during validation.

> `schema.Validate(json.ToJsonString())`

This wouldn't work. You're passing a string, but an element is expected.

Lastly, this library is too complex to support both nodes and elements, like I have in JsonPointer.Net.

I'll continue to contemplate, but without a significant use case, I don't think this will be done.

**Comment by janruo** [comment]
> This wouldn't work. You're passing a string, but an element is expected.

There is an [extension method](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/JsonSchemaExtensions.cs#L29-L33) that accepts a string.

> You can already dynamically build a schema with `JsonSchemaBuilder`. This is actually better than using nodes because it's strongly typed, which prevents you from adding bad data.

Thanks for the tip. The typing is really nice, but I like the readability of the JsonObject's collection/object initializer because it mirrors the actual JSON structure.

> Lastly, this library is too complex to support both nodes and elements, like I have in JsonPointer.Net.

Understandable. It's not a big issue since we can just use the string methods, even though it's not the most optimal solution because of the additional serialization/deserialization step.

**Comment by gregsdennis** [comment]
> There is an extension method that accepts a string

Oh yeah. I forget that's there.  There were so many users of Manatee.Json that tried to do that and it would fall because of the implicit cast from string to `JsonValue`.  You'd probably run into that with nodes as well...

> I like the readability of the JsonObject's collection/object initializer because it mirrors the actual JSON structure.

The builder is specially designed to mimic the JSON structure as well.  See the [code](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.Tests/GithubTests.cs#L660).  With the tuple syntax, the similarity is obvious.  It's not exactly the same syntax, but the structure is there.

**Comment by janruo** [comment]
> The builder is specially designed to mimic the JSON structure as well. See the [code](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.Tests/GithubTests.cs#L660). With the tuple syntax, the similarity is obvious. It's not exactly the same syntax, but the structure is there.

You're right, it does look pretty good when structured like that. I'll try it out 👍

**Comment by gregsdennis** [comment]
Another hindrance to supporting JsonNode is [this issue](https://github.com/dotnet/runtime/issues/66948) in which I bring up an issue with JSON null vs .Net null in the node model.  I feel I need this supported in some manner to fully support these libraries.

**Comment by gregsdennis** [comment]
I've opened an [API augmentation proposal](https://github.com/dotnet/runtime/issues/68128) that would make this a bit easier.

**Comment by s-summers** [comment]
Is there consideration to bringing `JsonNode` support to `JsonPath.Net` like you have done for `JsonPointer.Net` or will you be depending on those API changes to go through first?

**Comment by gregsdennis** [comment]
Unfortunately I don't think my API proposal is going to go through, which makes things a bit harder, but probably not impossible.

I had supported nodes in JSON Pointer because it's a requirement for supporting them in JSON Patch, where using nodes actually makes sense.

Nodes are the writable model for JSON; elements are read-only.  JSON Path, being a query system, is inherently read-only.

**Comment by gregsdennis** [comment]
@s-summers why do you have both `JsonObject` and `JsonElement`?  Why do you need `JsonObject`?

> then modify and/or check values via JSON Path

JSON Path isn't going to help you modify values.  As I mentioned, it's a query syste, so it's read-only.

**Comment by gregsdennis** [comment]
So you're already working with nodes and needing to pass elements is an extra step for you... 🤔

Microsoft has really backed us into a corner here.  They've now defined two domain models, and people like me now need to support both.  And sadly, the only real way to do it right now is to duplicate code.

I'll see if I can find a way to abstract the model and work only with that, but don't hold your breath.  I _really_ don't want to duplicate code.

**Comment by gregsdennis** [comment]
I've opened [another issue](https://github.com/dotnet/runtime/issues/70427) that will help lead me toward a solution here.

**Comment by gregsdennis** [comment]
I've decided to try to move _everything_ to nodes (see above PR).  Looks like it works pretty well.  All the tests pass anyway.

I did have to open #281 for JsonPath.Net as it needs more work than just updating the model.

In my research I found that converting a `JsonElement` to a `JsonNode` was pretty simple, which meant that if I just had code that supported nodes, I wouldn't _also_ need code that supported elements.  This discovery was the main catalyst for making this update.

The change major-increments all of the libraries except for Json.More.Net, which is a minor update.

I just need to do some local testing around https://json-everything.net to ensure it still works with these changes, and I should be good to merge.

**Comment by gregsdennis** [comment]
@janruo it looks like that extension method that takes a string is trumped by the implicit cast from `string` to `JsonNode`.

```c#
[Test]
public void StringDataIsParsedBeforeValidation()
{
	var schema = new JsonSchemaBuilder()
		.Type(SchemaValueType.Array)
		.Items(new JsonSchemaBuilder().Type(SchemaValueType.Integer))
		.Build();

	// this calls JsonSchema.Validate(JsonNode?, ValidationOptions)
	// not JsonSchemaExtensions.Validate(string, ValidationOptions)
	var results = schema.Validate("[1,2,3]");

	results.AssertValid();
}
```

I'll need to remove this method.  This will be another breaking change.
