### ISSUE TITLE
Rules with array.length throw an exception

### ISSUE THREAD

**Issue by janruo** [gregsdennis/json-everything#252]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 1.4.0
- OS: Win10
- .Net Target: 6

**Describe the bug**
Applying a rule that tries to compare `array.length` throws `Json.Logic.JsonLogicException: 'Cannot compare Null and Number.'`

**To Reproduce**
```cs
using Json.Logic;
using System.Text.Json;

var rule = JsonSerializer.Deserialize<Rule>(@"{
    "">="": [
        { ""var"": ""things.length"" },
        1
    ]
}");

var data = JsonDocument.Parse(@"{
    ""things"": [1, 2, 3]
}").RootElement;

var result = rule.Apply(data);
```

**Expected behavior**
The rule should run and return a correct value.

![screenshot](https://user-images.githubusercontent.com/49906573/162196817-e6640bbe-cb2e-4ad1-b288-fe31076e95ce.png)

**Comment by gregsdennis** [comment]
I think this is because I'm using JSON Pointer to perform the evaluations.

I do a conversion from `things.length` to `/things/length`, then just evaluate the pointer.  Since there's not a `length` property in the JSON, the evaluation returns null.

(I really don't like coding special cases like this.)

**Comment by janruo** [comment]
Hmm, it seems like the original library can access any "hidden" JS property of the object, even things like:

Rule
```json
{ "var": "things.__proto__.constructor.name" }
```

Data
```json
{ "things": [1, 2, 3] }
```

Result
```json
"Array"
```

Not sure if that is even intended behavior 🤔
