### ISSUE TITLE
ISchemaRefiner using AnyOfIntent with RequiredIntents causes unexpected missing output.

### ISSUE THREAD

**Issue by TYoung86** [gregsdennis/json-everything#253]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.8.3
- OS: Windows 11 x64
- .Net Target: .NET 6

**Describe the bug**
Using an `ISchemaRefiner` implementation to add a required intent for anyOf (or oneOf?) required fields gives unexpected results.

**To Reproduce**
For a type with with 2 ID properties that are mutually exclusive,
```csharp
      context.Intents.Add(new AnyOfIntent(new ISchemaKeywordIntent[] {
        new RequiredIntent(new() { idPropName1 }),
        new RequiredIntent(new() { idPropName2 })
      }));
```
Only the first appears to have generated output.

**Expected behavior**
```json
  "anyOf": [
    {
      "required": [
        "IdProperty1"
      ]
    },
    {
      "required": [
        "IdProperty2"
      ]
    }
  ],
```

**Actual behavior**
```json
  "anyOf": [
    {
      "required": [
        "IdProperty1"
      ]
    }
  ],
```

**Additional context**
Reversing the order of `ISchemaKeywordIntent` passed to `AnyOfIntent`, such that `idPropName2` is first, changes the output to only emit `IdProperty2`.

**Comment by TYoung86** [comment]
Turns out to just be confusing syntax, here is the correct syntax for the above's intention;
```csharp
        context.Intents.Add(new AnyOfIntent(new ISchemaKeywordIntent[] {
          new RequiredIntent(new() { idPropName1 })
        }, new ISchemaKeywordIntent[] {
          new RequiredIntent(new() { idPropName2 })
        }));
```

**Comment by gregsdennis** [comment]
Hm..  Yeah, sorry.  That API doesn't make much sense to me either.  Not sure what I was going for there.

I'm going to reopen this to remind me to fix it when I (finally) get around to doing a 2.0 of this lib.

Thanks for the report.

**Comment by TYoung86** [comment]
I think the syntax makes sense even though it is confusing. Each array is a separate context of keywords.

One alternative syntax would be to implement a collection interface and use an initializer, and while more convenient to interpret, it's usage would not be any more obvious to implement. (e.g. `new AnyOfIntent { new ISchemaKeywordIntent[] { ... }, new ISchemaKeywordIntent[] { ... } }`) The only difference is the clarity of being an collection initializer more obviously implies a multiple, but the fact that it's not a constructor is unintuitive.

I don't know if can be a better pattern for this other than creating a custom type as the parameter type that then provides a more obvious initialization pattern either with implicit operator magic, params or initializer lists. (e.g. `new AnyOfIntent(new(keyword1, keyword2, keyword3), new(keyword4, keyword5, keyword6))`)

It is probably fine the way it is.

**Comment by gregsdennis** [comment]
Thanks for the feedback!  The way I see it, the fact that you are questioning it, which led me to questioning it, means that _something_ could be better.
