### ISSUE TITLE
MaxLenght  Annotation

### ISSUE THREAD

**Issue by moscarelli** [gregsdennis/json-everything#256]
I have a class with annotation 
[Required]
and  [MaxLenth(100)

The Schema is generated ok for the required property but it ignores the MaxLenthtotally.
I even try Maximum and Minimum but the schema doesn't add this as items to be validated. 

Is there any configuration to be done in the schema generation to allow these annotations being picked up on the schema ?

**Comment by gregsdennis** [comment]
Are you saying that these annotations are on the class?

If that's the case, class-level annotations aren't really supported well, and is something that I'm planning on addressing in JsonSchema.Net.Generation v2 (when I can get to it).

**Comment by moscarelli** [comment]
Thanks, I was looking over some other comments but if it is not fully supported I would need to wait.

**Comment by moscarelli** [comment]
@gregsdennis  I actually was doing something wrong on my side. I placed the annotation on the correct classes and the schema shows up the validation and the validation is working as expected. Sorry.
