### ISSUE TITLE
Provide custom EvaluationContext for JsonPath

### ISSUE THREAD

**Issue by darrelmiller** [gregsdennis/json-everything#257]
We are trying to implement a prototype of the OpenAPI Overlays draft specification and need to use JsonPath to reference elements of the OpenAPIDocument DOM as if it were a JSON document.

If there were an overload to this https://github.com/gregsdennis/json-everything/blob/2dbe5cf14591a4dcfcf3aeeeb2699097e411c5e7/JsonPath/JsonPath.cs#L245 that allowed us to provide our own custom EvaluationContext that would give us a starting point.  Or is there a better extensibility point to evaluate JsonPath on something other than a JSON document?

**Comment by gregsdennis** [comment]
Hey Darrel, the context object is an internal implementation detail.  It's not intended to be exposed.

However, I'm happy to hear more about your requirement and discuss options.
