### ISSUE TITLE
Would like more context in ValidationResult about which properties it relates to

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [gregsdennis/json-everything#258]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.3.0

**Can this library make doing something simpler?**
`ValidationResult` does not have any information about which properties it relates to.  This makes it very difficult to work out
which parts of a json object do not conform to the schema.  For example, w would like to supply missing property values
if the schema defines a default value.

**Describe alternatives you've considered**
Current workaround is to parse `ValidationResult.Message` to work out which properties it relates to.  Obviously, this is far from
ideal and very brittle.

**Sample code**
```csharp
using System.Text.Json;
using Json.Schema;

const string SchemaContent = @"
{
  ""description"": ""A person"",
  ""type"": ""object"",
  ""properties"": {
    ""first_name"": {
      ""type"": ""string""
    },
    ""last_name"": {
      ""type"": ""string""
    }
  },
  ""required"": [""last_name""]
}
";

var item = new { first_name = "Joe" };
var json = JsonSerializer.Serialize(item);
var doc = JsonDocument.Parse(json);
var schema = JsonSchema.FromText(SchemaContent);
var options = new ValidationOptions { OutputFormat = OutputFormat.Verbose };
var results = schema.Validate(doc.RootElement, options);

foreach (var result in results?.NestedResults)
{
  // ENHANCEMENT    Would like more context in ValidationResult about which properties it relates to
  Console.WriteLine(result?.Message);
}

```

Output:
```bash
C:/dev/XCM/JsonSchemaNet_ValidationResult/bin/Debug/net6.0/JsonSchemaNet_ValidationResult.exe 



Required properties ["last_name"] were not present
```

**Comment by gregsdennis** [comment]
Hey @TrevorDArcyEvans, thanks for the suggestion.

The output format is actually defined by the [specification](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.12).  I don't want to deviate from that.

The specification also says that many keywords are to output annotations, but `required` doesn't have an annotation output.  Even if it did, annotations are omitted from the output of a failed schema validation, so if `required` fails, the schema that contains it fails, and any annotations are removed.

(The "verbose" format would still have any annotations that were produced, though.)

---

Now, all of that pertains to the _serialized_ form of the output.  While it's still in its data model (`ValidationResults`), I can add stuff.  I just shouldn't serialize the additional data.

I'm currently working on a few of the other libs at the moment, but I could get to this afterward.

**Comment by gregsdennis** [comment]
Starting to look at this.

What kind of additional information would you be looking for, from an API perspective?  For example, `properties` could yield a `List<string>` to describe what properties were missing, but other keywords would provide a different data type.

**Comment by gregsdennis** [comment]
@TrevorDArcyEvans you may be interested in a [new thread](https://github.com/orgs/json-schema-org/discussions/63#discussioncomment-2847309) on a discussion around updating the output format.

**Comment by gregsdennis** [comment]
@TrevorDArcyEvans, [I've proposed another idea](https://github.com/orgs/json-schema-org/discussions/63#discussioncomment-2960665) on the output format changes discussion.  This reorganizes the nodes so that they represent subschemas instead of keywords.  The keywords are then exposed in `annotations` or `errors` (depending on the outcome) as a keyword-keyed object with the values being the error message or annotation value.

I think this gets you what you're looking for.  Can you have a look, please?
