### ISSUE TITLE
Json logic custom operator arguments

### ISSUE THREAD

**Issue by cezaryluksza** [gregsdennis/json-everything#260]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 1.40
- OS: Windows 10
- .Net Target: .NET 6

**How can I help you today?**
Hi,

I'm trying to add some more complex custom rule and I'm struggling with accessing operator arguments.
My rule inherits from abstract Rule, but implementing Apply method gives me access only to JsonElement data.
I saw your built-in ruleset implementation and you access to operator arguments with constructor.
However, the documentation says to use a parameterless constructor for custom rules.
Is there any easy way to get into operator arguments?

**Comment by cezaryluksza** [comment]
Successfully added a custom rule, but isn't the documentation misleading?
Shouldn't it say something like: `If your rule has no arguments it must have a parameterless constructor.`?

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll have a look into what the requirements actually are.

**Comment by gregsdennis** [comment]
Yeah, i think that might be older documentation.  It looks like I do have it set up to handle arguments.

I can update that.  It looks like that's in the XML docs as well as the markdown on json-everything.net.  I can update the site easily enough, but would have to do a new release to fix the XML docs, so that may take longer.

**Comment by gregsdennis** [comment]
I think the more appropriate text for the docs would be: 

> The arguments for your rule must correspond to the parameters of the constructor.

I've made that update.  Thanks for raising this.
