### ISSUE TITLE
Using "var" as the second argument inside "some" will result incorrect outcome

### ISSUE THREAD

**Issue by wangh-trimble** [gregsdennis/json-everything#263]
**Environment**
- Nuget Package: JsonLogic.Net, 1.1.11
- Nuget Version: 6.1.0
- OS: WSL
- .Net Target: net6.0

**Describe the bug**
Looks like if you using "var" for a second argument inside of "some" it's returning wrong result. For instance from the attached screenshots from the nice Jsonlogic playground:
![image](https://user-images.githubusercontent.com/96781582/168244332-6a639643-242b-4b85-8058-8f64ca415f65.png)
![image](https://user-images.githubusercontent.com/96781582/168244515-56d7873e-2238-49ed-a287-8b34e8dd7bb7.png)

**To Reproduce**
(please refer to the screenshots, I've been using the latest library and the playground should be doing the same)

**Expected behavior**
The first "in" operator case should return "True", as 1 shall be found in [1] during the iteration; then the "greater than" case shall return "False".

**Additional context**
Is it anything like I am using it wrong?

**Comment by gregsdennis** [comment]
Thanks for reporting, @wangh-trimble.  For ease of access (and copy/paste) can you list those JSON values in code blocks in the issue, please?

I think (but I'm not sure) this may be related to a similar `var` issue discussed in #183, specifically [this comment](https://github.com/gregsdennis/json-everything/issues/183#issuecomment-997345446).

**Comment by wangh-trimble** [comment]
Thank you @gregsdennis for the quick reply! Sure, here is the one piece JSON test code, the same if you just use ">" operator:
Rule:
```
{
    "some" : [
        { "var":"x"},
        {
            "in": [ {"var":""}, {"var":"y"} ] 
        } 
    ]
}
```
Data:
```
{
    "x": [-1, 0, 1],
    "y": [2, 3, 1]
}
```

I will also take a look at the comment you pointed out.

**Comment by wangh-trimble** [comment]
![image (49)](https://user-images.githubusercontent.com/96781582/168266332-9df8af8c-c400-4a7d-9afa-10d0607b5a4c.png)

Also here is a local debug screenshot with the given test JSON data mentioned upstairs :)

**Comment by gregsdennis** [comment]
Is `{"var":""}` correct? This would definitely return null, which may be your problem.

**Comment by AIZ-THerring** [comment]
> Is `{"var":""}` correct? This would definitely return null, which may be your problem.

That doesn't seem right to me.  An empty string and a null are two different things.

**Comment by wangh-trimble** [comment]
@gregsdennis Any updates? Or anything unclear about this question?

We are evaluating whether this library can be used in our production, so, sorry for making it sound a bit pushing.

**Comment by wangh-trimble** [comment]
Digged a bit deeper, if you write a test case in https://github.com/gregsdennis/json-everything/blob/master/JsonLogic.Tests/SomeTests.cs

```
[Test]
    public void SomeInTest()
    {
        var rule = new SomeRule(new VariableRule("x"),
            new InRule(new VariableRule(""), new VariableRule("y")));

        var data = JsonDocument.Parse("{ \"x\": [-1, 0, 1], \"y\": [2, 3, 1] }").RootElement;
        JsonAssert.IsTrue(rule.Apply(data));
    }
```

and run, then you will get error:
```
Json.Logic.Tests.SomeTests.SomeInRule:
    Outcome: Failed
    Error Message:
    Json.Logic.JsonLogicException : Cannot apply in to Number and Null.
```

which is caused from this line: https://github.com/gregsdennis/json-everything/blob/1c9e3f903e09fc65968f151879fe7eb0d2e0566c/JsonLogic/Rules/SomeRule.cs#L27


As you can see, it is replacing the original data with iteration item, which is causing the `_source (VariableRule)` work incorrectly in `InRule`. For a quick fix we tried, if you change it into:
```
return inputData.Select(value => 
            {
                if (_rule is InRule)
                {
                    return _rule.Apply(value, data);
                }

                return _rule.Apply(value);
            })
```

And add an overload method like this to https://github.com/gregsdennis/json-everything/blob/master/JsonLogic/Rule.cs
```
    public virtual JsonElement Apply(JsonElement item, JsonElement data)
    {
        throw new NotImplementedException();
    }
```

Then the implementation in https://github.com/gregsdennis/json-everything/blob/master/JsonLogic/Rules/InRule.cs
```
public override JsonElement Apply(JsonElement item, JsonElement data)
    {
        var test = _test.Apply(item);
        var source = _source.Apply(data);

        if (source.ValueKind == JsonValueKind.String)
        {
            var stringTest = test.Stringify();
            var stringSource = source.GetString();

            if (stringTest == null || stringSource == null)
                throw new JsonLogicException($"Cannot check string for {test.ValueKind}.");

            return (!string.IsNullOrEmpty(stringTest) && stringSource.Contains(stringTest)).AsJsonElement();
        }

        if (source.ValueKind == JsonValueKind.Array)
        {
            var items = source.EnumerateArray();
            return items.Any(i => i.IsEquivalentTo(test)).AsJsonElement();
        }

        throw new JsonLogicException($"Cannot apply `in` to {test.ValueKind} and {source.ValueKind}.");
    }
```

**Comment by gregsdennis** [comment]
Nope, that's not it.  Pointers are handled right.

If I added this

```c#
public virtual JsonElement Apply(JsonElement item, JsonElement data)
```

I'd have to implement it in everything.  I'm not sure that's necessary.

I'm trying to wrap my head around what this logic is doing.

```json
{"some":[
  {"var":"x"},
  {"in":[
    {"var":""},
    {"var":"y"}
  ]}
]}

{"x":[-1, 0, 1],"y":[2, 3, 1]}
```

The `some` looks like it's taking `[-1, 0, 1]` and running each element through the `in`.

What is the `{"var": ""}` doing?  Seems to me like it would get the entire data (which is actually what the docs say).  Is the JS implementation using the value passed from `some` as the data for the first argument?  Is that documented anywhere?

OH!  It _is_!

> It can be useful to use `{"var":""}` to get the entire array element within the test.

Ew!  How is it supposed to distinguish between that and

```json
{"in":[
  {"var":"x"},
  {"var":"y"}
]}

{"x":-1,"y":[2, 3, 1]}
```

Their playground manages this.  What?!  I'm so confused.  I need some time to play with this.

**Comment by gregsdennis** [comment]
It looks like `all`, `none`, and `some` are the only ones that support _passing_ that special context data, but literally _any_ operator can be nested inside of it.

My question is how does the nested rule know which data (passed data or external data) to use?  Does this only work for an empty string in the `var`?  What if I actually _want_ the full external data instead of the passed data?

**Comment by gregsdennis** [comment]
Re-reading the "spec" requirements on https://jsonlogic.com/operations.html#all-none-and-some, it looks like the interpretation in the opening comment isn't quite right.  This library needs to mimic the original library, and for these cases, it doesn't.  I'll need to revert this.
