### ISSUE TITLE
How to apply .AdditionalProperties(false) recursively

### ISSUE THREAD

**Issue by MichaelJachan** [gregsdennis/json-everything#264]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 2.0.1
- OS: Win10
- .Net Target: Core 6.0

Dear Mr. Dennis!
I would like to add **"additionalProperties": false** to each level of a JSON Schema. So far, I only managed to apply it on the top-level of the generated Schema:

```
    public string Generate(Type t)
    {
        SchemaGeneratorConfiguration config = new();
        config.Nullability = Nullability.AllowForNullableValueTypes;
        config.PropertyOrder = PropertyOrder.AsDeclared;
        JsonSchemaBuilder builder = new JsonSchemaBuilder().FromType(t, config);

        builder.AdditionalProperties(false);// TODO shall be applied recursively

        JsonSchema jsonSchema = builder.Build();
        string schema = JsonSerializer.Serialize(jsonSchema);
        return schema;
    }

```
How to set it recursively?

Many thanks, 

Michael :)

**Comment by MichaelJachan** [comment]
Update: I found your class 
`public class AdditionalPropertiesIntent. `

It has a constructor 
`public AdditionalPropertiesIntent(SchemaGenerationContextBase context)`

But i'd expect 
`public AdditionalPropertiesIntent(bool value)`

**Comment by gregsdennis** [comment]
There's not a built-in way to do this, but I could add an option to control this fairly easily.  Options would be:

- Never
- Sealed object types
- All object types

I might also create an attribute for this.

In the meantime, you have a couple options:

- Create and handle the attribute
- Create a refiner to add the intent

Instructions for both are [in the docs](https://json-everything.net/json-schema).

---

The `additionalProperties` keyword actually takes a schema, of which `false` is a valid schema that just always fails (and `true` always succeeds).  Thus, for generation purposes, having a generation context in the constructor is correct.

You can see this in the fluent builder extension method as well:

https://github.com/gregsdennis/json-everything/blob/1c9e3f903e09fc65968f151879fe7eb0d2e0566c/JsonSchema/JsonSchemaBuilderExtensions.cs#L34

That said, I don't currently have a way of representing a `false` context.  I'll need to set that up.

**Comment by MichaelJachan** [comment]
Hi! I would apprechiate a solution like [ Never Sealed All]. In the meantime i have constructed my own:

```
internal class NoAdditionalPropertiesRefiner : ISchemaRefiner
{
    public bool ShouldRun(SchemaGenerationContextBase context) => context.Type.IsClass && context.Type != typeof(Version) && context.Type != typeof(string);

    public void Run(SchemaGenerationContextBase context) => context.Intents.Add(new NoAdditionalPropertiesIntent());
}

internal class NoAdditionalPropertiesIntent : ISchemaKeywordIntent
{
    public void Apply(JsonSchemaBuilder builder) => builder.AdditionalProperties(false);
}

```

**Comment by gregsdennis** [comment]
Nice.  Glad you found a workaround.

**Comment by gregsdennis** [comment]
I decided not to go with the config option for now.  Instead I added attributes.  Have a look at the PR if you're interested.  There are a few tests that show how they're used.
