### ISSUE TITLE
Problem with anyOf Keyword

### ISSUE THREAD

**Issue by MichaelJachan** [gregsdennis/json-everything#269]
Dear Mr. Dennis, i've got another issue. My schema defines a property, which must be any of:

multiple of 2, OR
multiple of 5. 

The value 15 fulfills 1 of these 2 conditions, thus "anyOf" shall be fulfilled.

But is validates to false. 

Many thanks again, Michael :)

```
{
  "type": "object",
  "properties": {
    "anyOfIntegerProperty": {
      "description": "An integer property",
      "type": "integer",
      "anyOf": [
        {
          "multipleOf": 2,
          "multipleOf": 5
        }
      ]
    }
  }
}

```

```
{
  "anyOfIntegerProperty": 15
}
```

**Comment by gregsdennis** [comment]
You have both `multipleOf` keywords in the same subschema.  You need to split them into two subschemas.

```json
{
  "type": "object",
  "properties": {
    "anyOfIntegerProperty": {
      "description": "An integer property",
      "type": "integer",
      "anyOf": [
        {
          "multipleOf": 2
        },
        {
          "multipleOf": 5
        }
      ]
    }
  }
}
```

The editor on json-everything.net provides this error.

![image](https://user-images.githubusercontent.com/2676804/169498638-e9fa097d-d859-4372-89e4-112070cdfeb0.png)

**Comment by MichaelJachan** [comment]
I understand. Thx again :)
