### ISSUE TITLE
Exclusion of all errors in Detailed/Basic validation result formats

### ISSUE THREAD

**Issue by eraffel-MDSol** [gregsdennis/json-everything#27]
I'd expect the Detailed/Basic formatted results to not include validation errors if those errors wouldn't cause the entire document to be invalid (e.g. inside an AnyOf or an If/Then), as functions in Manatee.JsonSchema

**Comment by gregsdennis** [comment]
I'll have to consult the spec too see what it says, if anything (this case might not be considered).  My preference is default to spec behavior, but I can add an option to configure it.

**Comment by gregsdennis** [comment]
Relevant section is http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4.3

**Comment by gregsdennis** [comment]
Yeah, it seems that output was an oversight in general.  I thought I had the reduction algorithms set up right, but they were not... a lot not.

**Comment by eraffel-MDSol** [comment]
```c#
using System.Text.Json;
using Json.Schema;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema =
                @"{
                  ""title"": ""A test schema"",
                  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
                  ""type"": ""object"",
                  ""properties"": {
                    ""ShouldBeNull"": {
                      ""type"": ""null""
                    },
                    ""NullOrString"": {
                      ""anyOf"": [
                        {
                          ""type"": ""null""
                        },
                        {
                          ""type"": ""string""
                        }
                      ]
                    }
                  }
                }
                ";

            var invalidJson =
                @"{""ShouldBeNull"": ""ABC"", ""NullOrString"": null}";

            var schemaObj = JsonSchema.FromText(schema);
            var doc = JsonDocument.Parse(invalidJson);
            var val = schemaObj.Validate(doc.RootElement, new ValidationOptions {OutputFormat = OutputFormat.Basic});
            var json = JsonSerializer.Serialize(val);
        }
    }
}

```

There's the test code I am using. and here's the Json I'm getting back.

```
{
   "valid":false,
   "keywordLocation":"#",
   "instanceLocation":"#",
   "errors":[
      {
         "valid":true,
         "keywordLocation":"#/title",
         "instanceLocation":"#"
      },
      {
         "valid":true,
         "keywordLocation":"#/type",
         "instanceLocation":"#"
      },
      {
         "valid":false,
         "keywordLocation":"#/properties/ShouldBeNull/type",
         "instanceLocation":"#/ShouldBeNull",
         "error":"Value is string but should be null"
      },
      {
         "valid":false,
         "keywordLocation":"#/properties/NullOrString/anyOf/1/type",
         "instanceLocation":"#/NullOrString",
         "error":"Value is null but should be string"
      }
   ]
}
```

Of the 4 errors there, the only one I'd expect to see is the third one, since the first two aren't errors at all and the fourth one didn't contribute to the overall failure of the validation.

**Comment by gregsdennis** [comment]
https://github.com/json-schema-org/json-schema-spec/issues/973 is an issue that I opened when I was writing the output for this library.  The point of that issue is that there's a lot of stuff that was overlooked, for various reasons.

I think what I have right now is per the spec, but the spec isn't really clear on some of the nuances, like which nodes to keep for basic and detailed formats.  For instance, you're asking for nodes that don't match the local validation result to be removed (e.g. the failing subnodes of a passing `anyOf`).

Please have a review and join in the discussion if you have some ideas.

**Comment by eraffel-MDSol** [comment]
I'm not sure I have anything to contribute to the spec discussion. I just know for our purposes, we're only interested in the errors that cause the document to fail validation.

**Comment by eraffel-MDSol** [comment]
Also, if you add `"additionalProperties": false,` to the schema, it generates a bunch of extra errors that I don't understand why they're there.

**Comment by gregsdennis** [comment]
Okay... I've figured out what's going on here.  The `allOf` is an applicator keyword, and based on the algorithm for 10.4.3, specifically:

> All applicator keywords ("*Of", "$ref", "if"/"then"/"else", etc.) require a node.

I'm just holding on to all of them for applicators, I think.  I'll make some more adjustments.
