### ISSUE TITLE
Restrict what can be patched on an object using JsonPatch

### ISSUE THREAD

**Issue by nicholas-brooks** [gregsdennis/json-everything#271]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 1.1.2
- OS: Windows
- .Net Target: net6

**How can I help you today?**

I'm busy adding Patch support using json+patch to a net6 minimal api project.  This library seems to work well so far, so thanks for writing this!

However I'm also looking to see how I can restrict what properties on an Object are allowed to be patched.  Or if there is a way to extend what JsonPatch.Net is already doing by, for example checking for an attribute on a property.

e.g.
```
class ObjectToPatch
{
    [DoNotPatch]
    public int Id { get; set; }
    public string Name { get; set; }
}
```

Of course happy to hear any other way of trying to achieve the same result.

**Comment by gregsdennis** [comment]
I don't think that JSON Patch has a restriction the way you're asking.  There's the `test` operation, but that just verifies that a path/value exists.  It's mainly for checking that arrays have X items before inserting at index X+1.

Have you seen this working elsewhere?  It'd be nice to have an example to follow, or better yet, a specification.

**Comment by nicholas-brooks** [comment]
Thanks for the quick response Greg!

The only example I've seen is in this library, https://github.com/Starcounter-Jack/JSON-Patch (javascript).  It accepts a validator delegate that is called when applying the patch.  You can validate whether a particular patch operation is 'valid' according to your own rules (e.g. 'replace','add','remove' not allowed for '/Id').

I don't believe there is any spec for such a feature.  It was more of a JsonPatch.Net library question as to whether it could do such a thing, or whether there was a way of extending it to do such a task.

**Comment by gregsdennis** [comment]
I don't currently have such a feature, no. It's set up for strict adherence to the spec right now.

I'll have a look at that implementation and see if I can incorporate it.

**Comment by nicholas-brooks** [comment]
Thanks Greg.

Two other libraries I found (dotnet):

* https://github.com/TwentyFourMinutes/JsonPatch.Restrict
* https://github.com/Labradoratory/JsonPatch.Patchable

**Comment by gregsdennis** [comment]
I think there's an inherent difference between those libraries and this one.  This library operates on `JsonElement`, not objects, like those others.  (I _do_ have extensions that operate on objects, but they just serialize, apply the patch, and deserialize.)

I think the best option for you is to identify the pointers to the values that should be readonly (you can use the [lambda expression overload](https://github.com/gregsdennis/json-everything/blob/master/JsonPointer/JsonPointer.cs#L236) to do this easily), and then check the incoming patch against those pointers.

In the example above, you want to prevent people from writing to `/Id` (or `/id` depending on how you're serializing), so you just need to check the patch to see if there are any `replace` or `copy` operations with that pointer.

This should be fairly easy to implement.

**Comment by gregsdennis** [comment]
I just had a thought:  you could use JSON Schema to validate the patch before applying it.

For example, this schema validates a patch _and_ that none of the operations modify `/Id`.

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "allOf": [
    { "$ref": "http://json.schemastore.org/json-patch" }
  ],
  "items":{
    "not": {
      "anyOf": [
        {
          "properties": {
            "op": { "const": "add" },
            "path": { "const": "/Id" } 
          }
        },
        {
          "properties": {
            "op": { "const": "copy" },
            "path": { "const": "/Id" } 
          }
        },
        {
          "properties": {
            "op": { "const": "move" },
            "path": { "const": "/Id" } 
          }
        },
        {
          "properties": {
            "op": { "const": "remove" },
            "path": { "const": "/Id" } 
          }
        },
        {
          "properties": {
            "op": { "const": "replace" },
            "path": { "const": "/Id" } 
          }
        }
      ]
    }
  }
}
```

**Comment by nicholas-brooks** [comment]
Hi Greg.  My apologies about not responding sooner.

Thanks for the feedback and suggestions.  In the end what I did was:

- Get all settable properties for the object to patch.
- For each `PatchOperation`:
  - check that the operation matches a settable property.  If not, it's a validation failure.
  - check that the operation is not for properties that are a [Key] or [Ignore] or (some custom attributes we have).  If so, it's a validation failure.

The only thing we don't handle yet is nested properties (e.g. Order.DeliverTo.ContactName), but that isn't needed atm.
