### ISSUE TITLE
Generated json-schema contains both '$ref' and 'type' & 'format' when a custom attribute is used

### ISSUE THREAD

**Issue by decevy** [gregsdennis/json-everything#272]
**Environment**
- Nuget Package: JsonSchema.Net, JsonSchema.Net.Generation
- Nuget Version: 2.4.0, 2.1.0
- OS: Windows 10
- .Net Target: 6.0.201

**Describe the bug**
Generated json-schema contains both '$ref' and 'type' & 'format' when a custom attribute is used.

**To Reproduce**
Create simple attribute class:
```
[AttributeUsage(AttributeTargets.Property)]  
public class UnfortunateAttribute : Attribute  
{  
}
``` 
Create class to be generated:
```
public class ObjectA
{
    public Guid Property1 { get; set; }
    [Unfortunate]
    public Guid Property2 { get; set; }
}
```
Generate:
```
JsonSchemaBuilder builder= new();
JsonSchema schema= builder.FromType(typeof(ObjectA));
JsonSerializerOptions serializerOptions = new() { WriteIndented = true };
string rawSchema = JsonSerializer.Serialize(schema, serializerOptions);
```
Output:
```
{
  "type": "object",
  "properties": {
    "Property1": {
      "$ref": "#/$defs/Guid"
    },
    "Property2": {
      "type": "string",
      "format": "uuid",
      "$ref": "#/$defs/Guid"
    }
  },
  "$defs": {
    "Guid": {
      "type": "string",
      "format": "uuid"
    }
  }
}
```

**Expected behavior**
I'd expect the Property2 to look like below, because properties `"type": "string"` and `"format": "uuid"` are already defined inside _#/$defs/Guid_.
```
...
    "Property2": {
      "$ref": "#/$defs/Guid"
    }
...
```

**Additional context**

**Comment by gregsdennis** [comment]
Interesting scenario.  Looks like the system is interpreting the `[Unfortunate]` attribute as a separate definition.

Thanks for the report.  I'll add this as a test to work out an update.

**Comment by gregsdennis** [comment]
I don't have that as an option, no, but I can add it.

**Comment by decevy** [comment]
> I don't have that as an option, no, but I can add it.

That would be great! :)

**Comment by gregsdennis** [comment]
It's in v 2.2.0, just released.

I didn't put it in initially because I figured terse schemas were better.
