### ISSUE TITLE
Mutate JsonNode using JsonPointer

### ISSUE THREAD

**Issue by yufeih** [gregsdennis/json-everything#276]
**Environment**
- Nuget Package:  JsonPointer.Net
- Nuget Version: 2.0.0

**Can this library make doing something simpler?**
Allow `JsonPointer` to mutate a `JsonNode`.

Today the `JsonPointer.TryEvaulate` method can retrieve the value of a `JsonNode`, but usually `JsonNode` is used for mutation. Something like a `bool JsonPointer.TrySetValue(JsonNode root, JsonNode value)` method would allow direct mutation of `JsonNode` using `JsonPointer`.

Same requirement was brought up here: https://github.com/gregsdennis/json-everything/issues/251#issuecomment-1143649899

**Describe alternatives you've considered**
In `Json.NET`, the same functionality can be achieved using `JObject.SelectToken` followed by a `JToken.Replace`.

**Comment by gregsdennis** [comment]
Thanks for the suggestion.  This seems pretty in line with the [JSON Patch `replace` operation](https://jsonpatch.com/#replace).

```c#
var patch = PatchOperation.Replace(pointer, value);
var result = patch.Apply(root);

var newJson = result.Result;
```

The only catch is that I haven't updated JsonPatch to support nodes yet.

**Comment by gregsdennis** [comment]
> The only catch is that I haven't updated JsonPatch to support nodes yet.

Now I have 😄

**Comment by yufeih** [comment]
Thanks!
