### ISSUE TITLE
Custom attributes on class properties are oddly shuffled over MemberGenerationContext's

### ISSUE THREAD

**Issue by decevy** [gregsdennis/json-everything#277]
**Environment**
- Nuget Package: JsonSchema.Net, JsonSchema.Net.Generation
- Nuget Version: 2.4.0, 2.2.1
- OS: Windows 10
- .Net Target: 6.0.201

**Describe the bug**
Custom attributes on class properties are oddly shuffled over MemberGenerationContext's

**To Reproduce**
Add class with different attributes on the properties.
```
public class Person
{
	[MyAttribute1]
	public string FirstName { get; set; }
	[MyAttribute2]
	public string LastName { get; set; }
}

[AttributeUsage(AttributeTargets.Property)]
public class MyAttribute1 : Attribute { }

[AttributeUsage(AttributeTargets.Property)]
public class MyAttribute2 : Attribute { }
```
Create a refiner that looks for the TypeGenerationContext and prints the attributes within the PropertiesIntent:
```
public class PersonRefiner : ISchemaRefiner
{
	public void Run(SchemaGenerationContextBase context)
	{
		var properties = context.Intents.OfType<PropertiesIntent>().Single();
		var firstNameContext = (MemberGenerationContext)properties.Properties["FirstName"];
		var lastNameContext = (MemberGenerationContext)properties.Properties["LastName"];

		Console.WriteLine($"FirstName attributes: {string.Join(", ", firstNameContext.Attributes)}");
		Console.WriteLine($"LastName attributes: {string.Join(", ", lastNameContext.Attributes)}");
	}

	public bool ShouldRun(SchemaGenerationContextBase context)
	{
		return context.Type == typeof(Person);
	}
}
```
Generate:
```
JsonSchemaBuilder jsonSchemaBuilder = new();
SchemaGeneratorConfiguration generatorConfiguration = new();
generatorConfiguration.Refiners.Add(new PersonRefiner());
jsonSchemaBuilder.FromType(typeof(Person), generatorConfiguration).Build();
```
Output:
```
FirstName attributes: MyAttribute1
LastName attributes: MyAttribute1
```

**Expected behavior**
I'd expect the output to look like:
```
FirstName attributes: MyAttribute1
LastName attributes: MyAttribute2
```

**Additional context**
Also, when I play with SchemaGeneratorConfiguration.PropertyOrder it seems to shuffle the attributes around in other ways. Possibly this is related to this issue?

**Comment by gregsdennis** [comment]
Thanks for the report and replication steps.  I'll dig in and see what's going on.

**Comment by gregsdennis** [comment]
Okay, I've figured out what's going on here.  The system identifies unique subschemas by two things: the type and, in the case of members, any _handled_ attributes.  Since your `MyAttribute1` and `MyAttribute2` don't have associated handlers, they are ignored.

The proper way to get the system to do something with these attributes is to have them [implement `IAttributeHandler`](https://json-everything.net/json-schema#attributes).

Note that this only happens because the properties are of the same type.  If you change one to `int` (or anything other than `string`), it works fine.
