### ISSUE TITLE
Invalid IL code in Json.Schema.JsonSchema:ValidateSubschema 

### ISSUE THREAD

**Issue by appfibre** [gregsdennis/json-everything#279]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.4
- OS: MacOS
- .Net Target: Xamarin.Mac v2.0

**Describe the bug**
Getting the following exception when trying to validate any schema:
_Invalid IL code in Json.Schema.JsonSchema:ValidateSubschema (Json.Schema.ValidationContext): IL_019a: stloc.s   15_
This looks like a problem with the Mono Runtime not able to accept 'this' as an in parameter on the method Push in ValidationContext.cs

**To Reproduce**
When running **using Xamarin.Mac**:
    JsonSchema schema = JsonSchema.FromText("{}");
    schema.Validate("{}");

**Expected behavior**
Should not raise any exception

**Additional context**
I've looked at the source code, and found that the following line (around 228) fails in the method ValidateSubSchema in JsonSchema.cs:
context.Push(subschemaLocation: context.SchemaLocation.Combine(keyword.Keyword()), subschema: **_this_**);

Options I found to resolve the issue:
1. Change "this" to (JsonSchema)this
2. make "this" a variable before calling context.Push and pass the variable instead
3. Inside ValidationContext.cs Push method (line 147) remove the "in" keyword for the subschema parameter

**Comment by gregsdennis** [comment]
Thanks for the report, but this sounds more like a Xamarin bug than anything with my library.

Have you been able to test the solutions you propose?  Seems like 1 and 2 would be optimized out.  I'm hesitant to include code to appease Xamarin, especially when the library has been proven to otherwise work on Mac.

**Comment by appfibre** [comment]
Thanks.

I have tested all three options and they resolve the issue for me but haven't run your unit tests...  Also, specifying the first two arguments in the Push call as null works.  Agree it is Xamarin/compiler bug.
