### ISSUE TITLE
JsonPath.Net needs rewrite

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#281]
This rewrite will accomplish two goals:

1. **Realign the implementation with the spec.**  The spec is nearing completion, and I've wanted this implementation to act as something of a reference for it (at least for now).  There are a few things that need to be removed.
    - `.length` was not included in the spec due to its conflict with the dot-member syntax.  The team feel we need a proper extension mechanism to support this functionality, but we will not be defining that in the first iteration.
    - Math operations will not be included in filter expressions due to their complexity.  For now, only equality/comparison operators are supported.
2. **Support `JsonNode`.**  The other libraries have all been updated.  While that effort was mostly a straightforward substitution with some edits for API differences, it quickly became apparent that this library needed more work, so it was postponed.

**Comment by warappa** [comment]
Hi @gregsdennis,
I saw you created the branch `path/rewrite-for-nodes` to use `JsonNode` instead of `JsonElement`, but it hasn't been worked on since 27th of June (which I think is due to your interim announcement and your current focus on JsonSchema).

I would be interested in the state of this branch, if there were any road-blocks, and what needs to be done to complete the `JsonNode` conversion. Maybe I could help finishing this part of this issue. 🙂

**Comment by gregsdennis** [comment]
I'm actually working on it now! 😆 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/2676804/208531738-4095be63-3381-4283-b0a6-0c09aa081e2e.png">

A large part of this update is also re-aligning it with the spec, which makes some changes from traditional JSON Path.

**Comment by gregsdennis** [comment]
The new branch is [path/update](https://github.com/gregsdennis/json-everything/tree/path/update).

**Comment by glen-nicol** [comment]
Hi there, I'm considering moving to System.Text.Json to reduce my allocation load during lots of JSON parsing. This library seems very useful given the lack of support for JsonPath in the official library. But I would like to target the readonly API using ```JsonElement```. Do you still plan to bring the old functionality back to support ```JsonElement```? 

I see there are some conversions from ```JsonElement``` to ```JsonObject``` and friends that I can use as a workaround but I do worry that will just add some of the allocations back in that I am trying to avoid.

**Comment by gregsdennis** [comment]
Everything is based on the nodes API now.  I have no plans to move back to elements.

**Comment by glen-nicol** [comment]
Got it, would you welcome a PR if I got the gumption?

**Comment by gregsdennis** [comment]
If both can be supported, I might be up for it, but there's a lot of internal workings that rely on nodes.  I'm not interested in having a lot of duplicated code.
