### ISSUE TITLE
JsonPatch.Net Unable to Create patch that clears array

### ISSUE THREAD

**Issue by leachdaniel** [gregsdennis/json-everything#283]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 2.0.0
- OS: Windows
- .Net Target: Core 3.1

**Describe the bug**
CreatePatch generates instructions for array operations that cannot successfully apply.

**To Reproduce**
Add this to the unit test `JsonPatch.Tests/PatchExtensionTests.cs`
```csharp
	[Test]
	public void CreatePatch_ClearArray()
	{
		var model = new
		{
			Example = "asdf",
			Values = new object [] {new {Value1 = 22, Value2 = 333}, new {Value1 = 33}}
		};
		var model2 = new
		{
			Example = "asdf",
			Values = new object[] { }
		};

		var patch = model.CreatePatch(model2);

		var final = patch.Apply(model);

		Assert.AreEqual(0, final.Values.Length);
	}
```
Error: Target path `/Values/1` could not be reached. Operation: 1

**Expected behavior**
The final array should be clear.

**Additional context**
When modifying the document

**Comment by gregsdennis** [comment]
Thanks for the report.  Please be aware that the logic behind patch creation isn't extensive.  I think at best, you'd get a patch that manually removes each of the items.

Do you know if this was an issue in a previous version (1.x)?

**Comment by leachdaniel** [comment]
Yes the issue is not new. I do have a potential fix isolated to PatchForArray. When the target is shorter than the original it will work backwards but also an optimization to replace when 0 elements.

```csharp
            private static void PatchForArray(JsonArray original, JsonArray target, List<PatchOperation> patch, JsonPointer path)
	    {
		    if (target.Count >= original.Count)
		    {
			    for (int i = 0; i < target.Count; i++)
			    {
				    var ui = (uint)i;
				    if (i >= original.Count)
				    {
					    patch.Add(PatchOperation.Add(path.Combine(ui), target[i]));
					    continue;
				    }

				    PatchForArrayIndex(i, ui);
			    }
		    }
		    else if (target.Count == 0)
		    {
			    patch.Add(PatchOperation.Replace(path, target));
		    }
		    else
		    {
			    int i = original.Count;
			    while (--i >= 0)
			    {
				    var ui = (uint)i;
				    if (i >= target.Count)
				    {
					    patch.Add(PatchOperation.Remove(path.Combine(ui)));
					    continue;
				    }
				    PatchForArrayIndex(i, ui);
			    }
		    }

		    void PatchForArrayIndex(int i, uint ui)
		    {
			    var origValue = original[i];
			    var modValue = target[i];

			    CreatePatch(patch, origValue, modValue, path.Combine(ui));
		    }
	    }
```

**Comment by leachdaniel** [comment]
@gregsdennis I'd be happy to make a PR for this. Note that It would require re-ordering one of the other test expectations. Let me know if it would be worth doing. I would also add some more unit tests to make sure other related cases work such as removing multiple elements from an array.

**Comment by leachdaniel** [comment]
@gregsdennis I'd be happy to make a PR for this. Note that It would require re-ordering one of the other test expectations. Let me know if it would be worth doing. I would also add some more unit tests to make sure other related cases work such as removing multiple elements from an array.

**Comment by gregsdennis** [comment]
Yeah, go ahead. Thanks.
