### ISSUE TITLE
An exception is thrown if the "var" operator returns null from some operators

### ISSUE THREAD

**Issue by jevvo-trimble** [gregsdennis/json-everything#286]
**Environment**
- Nuget Package: JsonLogic 2.0.0
- Nuget Version: 6.1.0
- OS: WSL
- .Net Target: net6.0

**Describe the bug**
An exception is thrown if the "var" operator returns null from some operators. 
![image](https://user-images.githubusercontent.com/107613400/174029942-e6e18626-9eac-4698-90ec-399fd7309012.png)

**To Reproduce**
```
[Test]
public void ExceptionThrownIfVarNull ()
{
  var rule = System.Text.Json.JsonSerializer.Deserialize<Rule>("{ \"in\" : [ {\"var\": \"item\"}, {\"var\": \"list\"} ] }");
  var result = rule.Apply();
}
```

**Expected behavior**
rule.Apply() should return false if "var" operator returns null.
if data was not been provided.
![image](https://user-images.githubusercontent.com/107613400/174030964-3ead54b7-d39f-4e2f-87f9-9e52ebd731a9.png)
if var property could not be found.
![image](https://user-images.githubusercontent.com/107613400/174031401-e15aa333-d1b7-46c6-98dc-f239ecd34a95.png)
for JsonLogic "play  ground"
```json
{"in": [{"var": "item"}, {"var": "list"}]}
```

**Additional context**
This behavior could be found only in some methods. I only know about "in" and "<" but I think it could be some more.
For method like "===" is working as expected
![image](https://user-images.githubusercontent.com/107613400/174032739-848eb438-e406-4267-a183-965f1fb74de2.png)
```c#
[Test]
public void JustExample ()
{
	var rule = System.Text.Json.JsonSerializer.Deserialize<Rule>("{ \"===\" : [ {\"var\": \"item\"}, {\"var\": \"list\"} ] }");
	var result = rule.Apply();
}
```
Not sure if null === null is correct. Thought.

For "in" operator it should be a simple fix:
```c#
public override JsonNode? Apply(JsonNode? data, JsonNode? contextData = null)
{
	var test = _test.Apply(data, contextData);
	var source = _source.Apply(data, contextData);

	if (source is JsonValue value && value.TryGetValue(out string? stringSource))
	{
		var stringTest = test.Stringify();

		if (stringTest == null || stringSource == null)
			throw new JsonLogicException($"Cannot check string for {test.JsonType()}.");

		return !string.IsNullOrEmpty(stringTest) && stringSource.Contains(stringTest);
	}

	// suggestion
	if (source == null)
		return false;

	if (source is JsonArray arr)
		return arr.Any(i => i.IsEquivalentTo(test));

	throw new JsonLogicException($"Cannot apply `in` to {test.JsonType()} and {source.JsonType()}.");
}
```

Not sure about other rules.

Please could you apply a solution to both JsonLogic 2.0.0 and 3.00

**Comment by gregsdennis** [comment]
Thanks for reporting.  I've been able to replicate on json-everything.net.  I'll have a look and try to get an update out soon.

Unfortunately, I don't support retroactive updates.  My build process runs automatically on `master` branch.

**Comment by gregsdennis** [comment]
> rule.Apply() should return false if "var" operator returns null.

I don't think this is exactly the case.

![image](https://user-images.githubusercontent.com/2676804/174037893-c7060985-3b44-4829-9914-264ef5c4c9c6.png)

It seems to be a variance on [how `in` behaves](https://jsonlogic.com/operations.html#in).

> If the second argument is an array, tests that the first argument is a member of the array

This doesn't say what the operator should do if the second argument is _not_ an array.  It appears that https://jsonlogic.com returns a false for this case whereas I decided to throw an exception because of the type mismatch.

**Comment by gregsdennis** [comment]
There are some other weird things that their playground does.

```json
{"+":[0,[4,2,false]]}
```

This returns 4.  It looks like it decomposes `[4,2,false]` and just takes the first item before adding the values.

```json
{"+":[0,["string",2,false]]}
```
and 

```json
{"+":[0,"string"]}
```

both return `null`, which supports that theory.

**Comment by jevvo-trimble** [comment]
Thank you for a quick response.

```
var rule = System.Text.Json.JsonSerializer.Deserialize<Rule>("{\"var\": \"item\"}");
var result = rule.Apply();
result  == null -> true 
```
IMO Is correct behavior. If you do not provide any data or data that could not be found, it will return null.

So `{ \"in\" : [ {\"var\": \"item\"}, {\"var\": \"list\"} ] }`  with no data provided it's same as `{"in": [null, null]}`
![image](https://user-images.githubusercontent.com/107613400/174045342-ce27d636-e1c0-46ef-bc50-bfe6c151b780.png)

To me, throwing an exception laments the usage of the rule to only strict, specific data. As example {"in": [{"var": "item"}, {"var": "list"}]} Data should always item and list in the correct formats.

But what about the cases when you don't have control over data? (It's coming via API).  Or cases when different rules could be used in different resources.

IMO If the exception approach is used, it would be could throw different types of exceptions. One for incorrect rule format. The second is for incorrect data.
Currently  `{ \"in123\" : [ {\"var\": \"item\"}, {\"var\": \"list\"} ] }` and `{"in": [null, null]}` will thorw JsonLogicException.
In my case, if data is missing I want to catch it and return false.  If the rule is incorrect I want to throw an exception.

**Comment by jevvo-trimble** [comment]
Will do.
What sort of actions are you planning to do?
Are you keeping exceptions?

**Comment by gregsdennis** [comment]
My preference is to match the original implementation if I can.

**Comment by gregsdennis** [comment]
I'm pushing a fix for just the `in` operation.  See v3.0.1.  I'll look at the others in the next few weeks.

**Comment by jevvo-trimble** [comment]
Sorry, I did not have time to check them all.
![image](https://user-images.githubusercontent.com/107613400/174555441-7511753b-f839-4ca1-b3b0-2a0de4aa064d.png)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\jevvo\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\jevvo\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Name | Rule | json-everything.net | JsonLogic playgrand
-- | -- | -- | --
Tested  (throws exeption). Not  working correct
AddRule | { "+": [ null, 1]} | Cannot add null | null
DivideRule | { "/": [ 1, null]} | Cannot divide types null and number. | null
  | { "/": [ null, 1]} | Cannot divide types null and number. | 0
MaxRule | { "max": [ 1, null, 2]} | Cannot find max with null. | 2
  | { "max": [ null, null]} | Cannot find max with null. | 0
MinRule | { "min": [ 1, null, 2]} | Cannot find min with null. | 0
  | { "min": [ null, null]} | Cannot find min with null. | 0
ModRule | { "%": [ 1, null]} | Cannot divide types number and null. | null
  | { "%": [ null, 1]} | Cannot divide types number and null. | 0
MultiplyRule | { "*": [ null, 1]} | Cannot multiply null. | null
  | { "*": [ *, null]} | Cannot multiply null. | null
SubstrRule | { "substr": [ null, 1,2]} | Start value must be an integer | "ul"
  | { "substr": [ "hello", null]} | Cannot substring a null | "hello"
  | { "substr": [ "hello", 1, null]} | Count value must be an integer | ""
SubtractRule | { "-": [ 1, null]} | Cannot subtract null | 1
  | { "-": [ null, 1]} | Cannot subtract null | -1
Not tested (throws   exeption)
AllRule |   |   |  
InRule |   |   |  
LessThanEqualRule |   |  
LessThanRule |   |   |  
MissingSomeRule |   |  
MoreThanEqualRule |   |  
MoreThanRule |   |   |  
NoneRule |   |   |  
ReduceRule |   |   |  
SomeRule |   |   |  
Not tested (throws   exeption). Should not needed any changes
IfRule ? |   |   |  
Tested (throws exeption). Working correct
CatRule | { "cat": [ null, "hello"]} | "hello" | "hello"
  | { "cat": [ "hello", null]} | "hello" | "hello"



</body>

</html>

**Comment by gregsdennis** [comment]
Wow!  Thanks!  Just having this actually helps a lot.

**Comment by gstrit** [comment]
Hello.

As far as I can see, there is the same issue with ''some'' and ''all'' operators.

**Comment by gregsdennis** [comment]
Name | Rule | json-everything.net | JsonLogic playgrand
-- | -- | -- | --
MaxRule | { "max": [ 1, null, 2]} | Cannot find max with null. | 2
MinRule | { "min": [ 1, null, 2]} | Cannot find min with null. | 0

These seem inconsistent.  Why would `max` actually give the max, but `min` gives 0?  Does it _cast_ the null to 0, maybe?  That seems _really_ weird.

This concept needs better specification.
