### ISSUE TITLE
Exception MissingMethodException when serializing JsonPatch in JsonPatch.Net 2.0.0

### ISSUE THREAD

**Issue by knoxi** [gregsdennis/json-everything#288]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 2.0.0
- OS: Windows
- .Net Target: .net 6.0

**Describe the bug**
After upgrading to the new release of `JsonPatch.Net 2.0.0` I get an error when I try to serialize a `JsonPatch` object.

```
System.MissingMethodException: 'Method not found: 'System.Text.Json.Nodes.JsonNode Json.More.JsonElementExtensions.AsNode(System.Text.Json.JsonElement)'.'
```

The issue is that the package `Json.More.Net` is referenced by the package `JsonPointer.Net` with an older version V1.5 instead the current V1.6.

Adding an explicit reference to the package `Json.More.Net` V1.6.0 solves the issue.

**To Reproduce**
* Create a new test project, add a reference to the package `JsonPatch.Net 2.0.0` only 
* try to serialize the json string to a `JsonPatch` object in a test.

```
var patchExpected = JsonSerializer.Deserialize<JsonPatch>(
    "[{\"op\":\"replace\",\"path\":\"/1/test\",\"value\":\"test32132\"},{\"op\":\"remove\",\"path\":\"/2/test\"},{\"op\":\"add\",\"path\":\"/2/test1\",\"value\":\"test321\"},{\"op\":\"replace\",\"path\":\"/3/test/2\",\"value\":3},{\"op\":\"add\",\"path\":\"/4\",\"value\":{\"test\":[1,2,3]}}]"
    );
```

**Expected behavior**
* Serialization should not throw an exception
* no explicit reference to `Json.More.Net`

**Additional context**

**Comment by gregsdennis** [comment]
New packages incoming
