### ISSUE TITLE
SchemaValidationMiddleware

### ISSUE THREAD

**Issue by ivan-codes-foss** [gregsdennis/json-everything#293]
I came across a stackoverflow answer which has a link to SchemaValidationMiddleware which used to be used in json-everything.net. The link has since expired. Is this available anywhere?

**Comment by gregsdennis** [comment]
Hey there.  Yeah, that middleware was part of the old json-everything.net back end. I've since moved to a WASM site.

I'll see if I can find the last commit for you to browse.  I'll update the SO link as well.

**Comment by ivan-codes-foss** [comment]
That's brilliant, thank you!
