### ISSUE TITLE
Problem with JSON Schema Validation with update to Version 3.0.0

### ISSUE THREAD

**Issue by MichaelJachan** [gregsdennis/json-everything#295]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 3.0.0 and 3.0.1
- OS: Win10
- .Net Target: net6.0

Dear Mr. Dennis! 

I enjoy working with your validator very much:) But today i tried to update from Version 2.x.x to 3.x.x, and a simple validation case stopped to yield a positive validation result:

The Schema

```
{
  "type": "object",
  "properties": {
    "booleanProperty": {
      "type": "boolean"
    }
  },
  "additionalProperties": false
}
```

The JSON

`{ "booleanProperty": false }`

The error message (after using your package V 3.x.x; NOTE: NO ERROR when using V 2.x.x)

**Value is "string" but should be "object"**

FURTHER INFO: I can not reproduce this fail which your online tool [https://json-everything.net/json-schema](https://json-everything.net/json-schema). With which version of the validator is it running? 2.x.x or 3.x.x? 

Best, Michael :)

**Comment by gregsdennis** [comment]
Thanks for the report.

You can see the versions that the suite is running in the top right of the page.

**Comment by MichaelJachan** [comment]
OK, so we have a problem: 

Your website runs on 3.0.1, but doesnt show the error. 

My .NET Code also uses 3.0.1, and has the issue (after update from 2.x.x9

:(

**Comment by MichaelJachan** [comment]
I actually only loaded the Nuget Package JsonSchema.Net.Generation in my CSPROJ:

```
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net.Generation" Version="3.0.1" />
  </ItemGroup>

```

When i add the Nuget JsonSchema.Net, the bug remains:

```
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="3.1.2" />
    <PackageReference Include="JsonSchema.Net.Generation" Version="3.0.1" />
  </ItemGroup>

```
When i remove the Package JsonSchema.Net.Generation, the bug remains:

```
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="3.1.2" />
  </ItemGroup>

```

**Comment by MichaelJachan** [comment]
Here is a minimal C# Code, which generates the Bug:


```
JsonSchema jsonSchema = JsonSchema.FromText(
@"{ 
  ""type"": ""object"",
  ""properties"": { ""booleanProperty"": { ""type"": ""boolean"" } }
}");

ValidationOptions options = new() { OutputFormat = OutputFormat.Verbose };

ValidationResults validationResults = jsonSchema.Validate(@"{ ""booleanProperty"": false }", options);

```

validationResults  has 2 NestedResults:
NestedResults[0].IsValid **FALSE**
NestedResults[0].Message **Value is "string" but should be "object"**

NestedResults[1].IsValid **TRUE**

**Comment by gregsdennis** [comment]
Okay.... so this is mentioned in the release notes.

The overload to take a JSON string and automatically parse it has been removed because `JsonNode` defines an implicit cast from `string`.

From the notes:

> Removed `JsonSchemaExtensions(this JsonSchema, string, ValidationOptions)` since the implicit cast from `JsonNode` was taking precendence
>
> ***IMPORTANT** Removal of this extension will only manifest at runtime. Code that called this extension method will still compile, but the validations will most likely fail.*

You'll need to separately parse that into a `JsonNode`.

**Comment by MichaelJachan** [comment]
Thank you again :)
