### ISSUE TITLE
 Operator return type 

### ISSUE THREAD

**Issue by jevvo-trimble** [gregsdennis/json-everything#302]
**Environment**
- Nuget Package: JsonLogic 3.0.1
- Nuget Version: 6.1.0
- OS: WSL
- .Net Target: Net6.0

**How can I help you today?**
Hello, is there any way to validate if the operator returns a boolean as result?

**Additional context**
I need to find a way to check if JsonLogic expression is valid for the custom cases. In my case, only boolean expressions are allowed. Rules classes are internal, so I could not use them to check the type after Deserialization. It would be good if rule class has a return type property or some validator that consumes some custom rules.
Currently, the only way to validate if an expression is correct is to convert it?

**Comment by gregsdennis** [comment]
Hey, thanks for the question.

Rules currently output a `JsonNode?`, which _may_ contain a boolean, but may also be almost anything else..  There's not a really good way to test that you get a boolean out other than

```c#
var isBool = node.TryGetValue(out bool value);
```

Note that there could be an issue in that if the underlying value is a `JsonElement` this will still return false, even if the element's underlying value is a boolean.

This is really more of a .Net question than anything with my library, though.

Let me know if that doesn't answer your question.

---

As a _really_ alternative workaround (perhaps a bit convoluted), you can define a JSON Schema that verifies the value is a boolean:

```json
{ "type": "boolean" }
```

```c#
var schema = new JsonSchemaBuilder().Type(SchemaValueType.Boolean).Build();

var logicResult = myLogic.Apply(data);
var validationResult = schema.Validate(logicResult);
var isBool = validationResult.IsValid;
```

**Comment by jevvo-trimble** [comment]
Thank you for a quick reply. 

In both cases, you are applying the rule. But I don't think that is the correct way of doing it in my case. I'm creating rules via API. So I want to check if the rule is valid without executing it (I don't have data at that point in time). I was hoping you could do something like that: 

`var rule = JsonSerializer.Deserialize<Rule>(json);
if (rule.ReturnType == bool)`

or 

`var rule = JsonSerializer.Deserialize<Rule>(json);
var ruleType = rule.GetType()
if(ruleType  in  AddRule)
{
    return false;
}
... `

**Comment by gregsdennis** [comment]
Oh, no, there's not really a way to know what's going to come out of a rule without running it, especially if it depends on input data.

**Comment by gregsdennis** [comment]
Maybe you can check if the root rule is one of the comparisons (`==`, `<=`, etc), but beyond something like that, I don't think it's possible in a general way to know what the return type will be.

**Comment by gregsdennis** [comment]
> Do you think is possible to add a virtual property to Rule called something like "return type"?

The thing is that this isn't avaialble _generally_.  It doesn't make sense for a lot of the rules.

We actually don't know what `IfRule` will return because it depends on what's in the "true" and "false" case parameters.

> Is there a reason why rules are internal?

I anticipated that there wouldn't be a need to access them.  They are completely defined, and there's no reason to extend them.  The only extension point in JSON Logic is creating new rules, which you can do.

I _could_ seal and expose them.

**Comment by jevvo-trimble** [comment]
Now I should be able to do what I need!

**Comment by gregsdennis** [comment]
I'm going to reopen this as I haven't need the PR yet.  I'm still trying to decide how to go about dealing with deserialization with internal constructors.

**Comment by jevvo-trimble** [comment]
Sorry. I did not check if PR is done.
