### ISSUE TITLE
Functional difference between 2.4.0 and 3.2.0 on JsonSchema.Validate - can we get an obsolete tag?

### ISSUE THREAD

**Issue by JimInWA** [gregsdennis/json-everything#306]
**Environment**
- Nuget Package: JsonSchema.Net 
- Nuget Version:  2.4.0 compared to 3.2
- OS: Windows
- .Net Target: .Net 6 (Azure Functions)

**Describe the bug**
In 2.4.0, there were 3 extension methods for JsonSchema.Validate:
- One that has a JsonElement as the first parameter
- One that has a JsonDocument as the first parameter
- One that has a string as the first parameter

Our code was using the last extension method.

While 3.2.0 still has 3 extension methods for JsonSchema.Validate, we see that in the release notes on https://json-everything.net/json-schema for JsonSchema.Net that under the breaking changes for 3.0 that the one that accepted a string has been dropped:
- One that has a JsonNode? as the first parameter
- One that has a JsonDocument as the first parameter
- One that has JsonElement as the first parameter

When we updated our NuGet package to use 3.2.0, our code compiled without any changes however all of our validations started failing with the following error: '#/type' 'Value is "string" but should be "object"'.  Several of our tests failed with this message.

It turns out that there was an implicit cast from our string to JsonNode? - which we missed initially as the code compiled but we noticed when trying to figure out what happened (ReSharper for the win).  We also see that this is documented on the release notes page "IMPORTANT Removal of this extension will only manifest at runtime. Code that called this extension method will still compile, but the validations will most likely fail."

However, it would be really nice if we could have that extension method back and have an obsolete tag added to that method.  This way, users of the library would get a warning during the compilation phase instead of at run time.

**To Reproduce**

Using 2.4.0, set up the following test:

string errorSchemaAsString = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema#\",\"type\":\"object\",\"properties\":{\"Status\":{\"description\":\"Status object\",\"type\":\"object\",\"properties\":{\"Success\":{\"enum\":[false]},\"errors\":{\"description\":\"errors array\",\"type\":\"array\",\"maxItems\":1}},\"required\":[\"Success\",\"errors\"],\"$comment\":\"note the case sensitivity - errors (starts with lowercase e)\"}},\"required\":[\"Status\"]}";

string contentAsString = "{\"Status\": { \"Success\":false, \"errors\": [{ \"Message\" : \"This is an error message" }] } }";

JsonSchema jsonSchema = JsonSchema.FromText(errorSchemaAsString);

ValidationResults validationResults = jsonSchema.Validate(jsonToValidate, new ValidationOptions
{
    RequireFormatValidation = true,
    ValidateAs = Draft.Draft202012,
    OutputFormat = OutputFormat.Basic
});

Now, repeat the same test in 3.2.0 - see the differences.

**Expected behavior**
Expectation of the above code is that jsonSchema.Validate should not give an error in either 2.4.0 or 3.2.0.  Or the that the 3.2.0 codebase should tell us that we shouldn't use the string anymore to avoid the implicit cast.

**Additional context**
Please add back the extension method that took a string into the 3.x codebase and add a deprecation / obsolete tag to that extension method?  That way, people that are using the old extension method will get a compilation error and will know that they need to

**Comment by gregsdennis** [comment]
I'm sorry, I had to remove this due to a conflict with the implicit cast from `string` to `JsonNode?`.  The resulting call becomes ambiguous and doesn't compile.

Your solution will be to add a single line of code before validation to parse the string into a node.

```c#
var node = JsonNode.Parse(text);
```

**Comment by gregsdennis** [comment]
I explicitly mentioned this in the release notes for v3.0.0.

**Comment by JimInWA** [comment]
Thank you for the very quick reply - really appreciate it.

I saw it in the release notes which I checked before I went to do the upgrade, but I still missed the implication until our tests failed.

Since the code won't compile if both Extension methods are there, I understand that the obsolete tag won't be able to be added.

Thanks again.
