### ISSUE TITLE
Is there a way to make sure your schema is well-formed according to the format defined by json-schema.org?

### ISSUE THREAD

**Issue by JimInWA** [gregsdennis/json-everything#307]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 3.2
- OS: Windows
- .Net Target: .Net 6 (Azure Functions)

**How can I help you today?**
I wanted to find out if there is any functionality in JsonSchema.Net that would help with the following issue.  We have looked through the documentation and haven't found anything explicit, but we definitely could have missed something.

Our team is new to using JSON schema validation.  Unfortunately we made a very newbie mistake in our schema files where we did not realize that for our array that we couldn't list the "properties" directly under the "type": "array" section - instead you need to have the “properties” listed underneath an “items”.  If you don’t have the nesting correct, the validations are ignored.

We have manually fixed the issue in our 4 schema validation files but we are worried that we have potentially missed other things too.

Is there anything in JsonSchema.Net that we could use to check to make sure our schema is well-formed according to the format defined by json-schema.org?

I see that there was a comment to create a Schema linter back in December 2020, but I don't see any follow-up.  Not sure if my request would fit under that area, but something like that would be helpful too.

**Additional context**

**Comment by gregsdennis** [comment]
The `JsonSchema` type won't deserialize properly if the data doesn't match the expected model.  I look at that as a benefit of being in a strongly-typed language.

If you want to validate the JSON representation of the schema _before_ deserializing it, [meta-schemas](https://json-everything.net/json-schema#meta-schemas) do exactly that.  They're also hardcoded in the `MetaSchemas` static type.

**Comment by JimInWA** [comment]
Note: I have tried to follow the meta-schemas documentation but I am not seeing a path forward yet.  I am going to provide this comment on the deserialization piece and then I will go back to trying to figure out the meta-schemas approach.

I don't understand your comment about the JsonSchema type won't deserialize properly.

Here is a sample schema file that is well-formed JSON but it is not correctly nested according to the Schema Validation rules as the "type": "array" does not have the required "items" (and then the "properties" should be under the "items")

{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "type": "object",
  "properties": {
    "Data": {
      "type": "object",
      "properties": {
        "myProperty": {
          "type": "string"
        },
        "myArray": {
          "type": "array",
          "properties": {
            "arrayProperty1": {
              "type": "string"
            }
          },
          "required": [
            "arrayProperty"
          ]
        }
      },
      "required": [
        "myProperty",
        "myArray"
      ]
    }
  },
  "required": [
    "Data"
  ]
}

We read the Schema contents from a file using File.ReadAllText storing that in a string variable.

Then we do JObject.Parse on that string variable to validate that it is well-formed JSON.  

Then we do JsonSchema.FromText using that string variable.

Then we can use the following code snippet to convert the JsonSchema variable back to JSON and compare it - the items in the JsonSchema exactly match the value we imported - **
including the fact that the "items" is missing**.

```
JsonDocument jsonSchemaAsJsonDocument = jsonSchema.ToJsonDocument();
string jsonSchemaBackFromJsonDocument;

using (var stream = new MemoryStream())
{
    Utf8JsonWriter writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true });
    jsonSchemaAsJsonDocument.WriteTo(writer);
    writer.Flush();
    jsonSchemaBackFromJsonDocument = Encoding.UTF8.GetString(stream.ToArray());
}
```

**Comment by gregsdennis** [comment]
> as the "type": "array" does not have the required "items"

I see what you're saying.  `properties` only pertains to object values and when a schema specifies that the type must be an array, something is probably wrong.

There's a lot of conversation going on in the [specification repos](https://github.com/json-schema-org) around linting that you might be interested in.  The idea is to design an analyzer that can detect these sorts of mistakes.  I'm not sure which issues (if any) have been created to discuss this, but we've had a lot of discussion in the JSON Schema Slack workspace, and it's definitely in the queue of things to look at.

I have held off on implementing anything like this here because I want to make sure it's in line with whatever we decide over there.

---

For what it's worth, `JsonSchema` is completely serializable.  `JsonSchema.FromText()` is just a shortcut for

```c#
var schema JsonSerializer.Deserialize<JsonSchema>(text);
```

You can see the code [here](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/JsonSchema.cs#L80).

To get the string representation of the schema object, just serialize it again.

```c#
var schemaText = JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true });
```

(You may also want to set `Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping` as the serializer is _very_ aggressive when it comes to escaping characters.)

**Comment by JimInWA** [comment]
> I have held off on implementing anything like this here because I want to make sure it's in line with whatever we decide over there.

Completely makes sense - I wouldn't want to have design something and then have to refactor it if it isn't in line with the decided patterns.  I will try to take a look at the [specification repos](https://github.com/json-schema-org) later today or next week.

> To get the string representation of the schema object, just serialize it again.

Yeah, that is a lot simpler compared to what I was doing :)
