### ISSUE TITLE
Announcement about JSON Path

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#309]
I've been having some issues with how the IETF is [managing the JSON Path project](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/228#issuecomment-1197254339).  This is the most recent of many cases where the IETF is exercising control over the direction of JSON Path and not listening outsiders.  I have seen additional cases where this sort of behavior was applied toward others as well.  I refuse to be part of an effort that does not strive for inclusion of probably the most important sector, i.e. implementors, but instead aims to retain sole control over the development of a specification intended to standardize a syntax that is already an integral part of many existing platforms and has been for over 15 years.

**_As such, I am seriously considering scrapping JsonPath.Net and pulling it from Nuget (well, marking it deprecated)._**

Instead I would like to offer JMES Path, which I believe to be a more robust mechanism for querying JSON data anyway.  I _might_ even offer compatability with colloquial JSON Path (what's currently defined by @goessner's original blog post) within the same library, but I wouldn't be claiming any adherence to whatever abomination IETF decides goes into the official spec.

What are the community's thoughts?

**Comment by gregsdennis** [comment]
Doing some research, it looks like @danielaparker has implemented a nice System.Text.Json solution for JMES Path.  I'm not sure of its compliance level, thought.  Regardless, it should be listed on [jmespath.org/implementations](https://jmespath.org/libraries.html) because the one that's there uses Newtonsoft, and it doesn't look like System.Text.Json will be supported for a while (if ever, see https://github.com/jdevillard/JmesPath.Net issue 49).

**Comment by gregsdennis** [comment]
After some discussions with others in the standards arena, I've decided that I'm going to continue with JSON Path.  Let's see where this goes.

**Comment by elibarel10** [comment]
Hi Greg, what are the weak points of using JPath? we are debating it's value in one of our systems, and we really want to move  from newtonsoft to system.text.json, with json-everything, that still uses JPath :) 
do we have safe and strong alternatives for querying a json with strong performance?
