### ISSUE TITLE
Support [JsonExtensionData] for json schema generation

### ISSUE THREAD

**Issue by ivarne** [gregsdennis/json-everything#312]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 3.0.2
- OS: windows
- .Net Target: 6.0

**Can this library make doing something simpler?**
In `System.Text.Json`, the attribute `[JsonExtensionData]` is used to store and access additional properties on an object. It seems to me like schema generation, could use this attribute to hide the property in the schema and ensure that `AdditionalProperties` is set to true for the object.

**Describe alternatives you've considered**
What I'm proposing could be accomplished by adding two custom attributes, but they seem redundant.
```diff
+ [AdditionalProperties(true)]
  public class MyClass
  {
      public int Id { get; set; }
  
+     [JsonExclude]
      [JsonExtentionData]
      public IDictionary<string, JsonElement> ExtraProperties { get; set; }
  }
```

**Comment by gregsdennis** [comment]
(I think you mean to have `additionalProperties` rather than `additionalItems`.)

Firstly, thank you for the suggestion.

Before we get to it, I'd like to clarify that `additionalProperties: true` in JSON Schema is implicit.  JSON Schema will not fail an instance on the basis that extra properties are present unless `additionalProperties: false` is explicitly in the schema.  This means that

```json
{
  "type": "object",
  "properties": {
    "Id": { "type": "integer" },
  },
  "additionalProperties": true
}
```

is the same as 

```json
{
  "type": "object",
  "properties": {
    "Id": { "type": "integer" },
  }
}
```

`additionalProperties: true` doesn't add any value to this schema.  In fact, this schema doesn't even require `Id` because `required` isn't explicitly included.  An empty object `{}` and `{ "foo": false }` would both satisfy this schema.

`[JsonExtentionData]` is just a serialization consideration because .Net is a strongly typed framework and doesn't have anywhere else to put extra data.

I question whether this is really needed.

---

Regarding your suggestion, is it easier to understand what the generated schema will be with this

```c#
[AdditionalProperties(true)]
public class MyClass
{
    public int Id { get; set; }

    [JsonExclude]
    public IDictionary<string, JsonElement> ExtraProperties { get; set; }
}
```

or this

```c#
public class MyClass
{
    public int Id { get; set; }

    [JsonExtentionData]
    public IDictionary<string, JsonElement> ExtraProperties { get; set; }
}
```

I would argue that the first is more intuitive.  It's very explicit that `additionalProperties: true` will be added to the schema (although it's not necessary).  It's intentional, which means that future readers of your code should be able to better understand what the code is _supposed_ to do.

**Comment by ivarne** [comment]
Sorry for the typo (I edited my post).

Regarding `[Required]` and the default value for `additionalProperties`, that's something I think should be possible to change/configure with `ISchemaRefiner`.

#264 inspired me to create a `ISchemaRefiner` to change the default `additionalProperties` from `true` to `false`, and with this implementation the `AdditionalPropertiesIntent(true)` is actually very usefull, because I can apply `false` when it is not explicitly true.

```C#
public class AdditionalPropertiesFalseRefiner : ISchemaRefiner
{
    public bool ShouldRun(SchemaGenerationContextBase context) =>
        context.Intents.OfType<TypeIntent>().All(i=>i.Type == Json.Schema.SchemaValueType.Object) &&
        !context.Intents.OfType<AdditionalPropertiesIntent>().Any();

    public void Run(SchemaGenerationContextBase context)
    {
        context.Intents.Add(new AdditionalPropertiesIntent(SchemaGenerationContextBase.False));
    }
}
```
I'm also thinking about a refiner that add required for all non-nullable properties as well, but I have not yet tried.

----------------------

I'm hoping to avoid the need to annotate the classes, as it is used in lots of projects and I don't want to spread a dependency on `Json.Schema.Generation` everywhere. I have a separate C# console app that handles generation and writes the result to disk and check into git. The schema is to be used with VSCode to get completion and validation when editing (configuration)files that will be Deserialized using `System.Text.Json`, and possibly for typescript definitions in the frontend.

Currently we're writing JsonSchema manually, but most devs seem to find it challenging to learn a new tool. I was hoping there was a way to just write once and review the result. For me the question is not what annotations makes it easier to read, but how we are likely to generate a useful schema more automatic than a bullet point that you need to manually update a schema file somewhere.

**Comment by gregsdennis** [comment]
> I'm also thinking about a refiner that add required for all non-nullable properties as well, but I have not yet tried.

There is already some provision for this.  Please see the docs: https://json-everything.net/json-schema#nullability

> it is used in lots of projects and I don't want to spread a dependency on Json.Schema.Generation everywhere.

This is the reason for DTOs.  Separate your concerns.  Create an interface that defines all the properties you need, then have multiple implementations: 1 for the domain, 1 for API comms, 1 for database (if you need it), and 1 for schema generation.  The interface keeps all of the models in sync, but each model has a distinct purpose.

**Comment by ivarne** [comment]
> There is already some provision for this. Please see the docs: https://json-everything.net/json-schema#nullability

Yes, but there isn't a way to say that all fields should be required in the schema, unless explicitly marked as nullable (that I have found). I think that should be an option.

> This is the reason for DTOs. Separate your concerns. Create an interface that defines all the properties you need, then have multiple implementations: 1 for the domain, 1 for API comms, 1 for database (if you need it), and 1 for schema generation. The interface keeps all of the models in sync, but each model has a distinct purpose.

If I am going to have a complete copy of the classes that make up my datamodel for schema generation. How is that better than the current situation of manually maintaining the json schema?

**Comment by gregsdennis** [comment]
> there isn't a way to say that all fields should be required in the schema

This is also true about JSON Schema, which this library is modelled after.  I think you'll be interested in [this proposal](https://github.com/json-schema-org/json-schema-spec/pull/1144) for the next draft, which will do what you want.  I'll probably add it in when the next draft releases, but I don't know when that will be (we're working on it).

**Comment by gregsdennis** [comment]
> How is that better than the current situation of manually maintaining the json schema?

Even with the copies, you still get the advantage of the compiler, especially if you use an interface to keep them synced.
