### ISSUE TITLE
Numberify doesn't work in all cultures

### ISSUE THREAD

**Issue by warappa** [gregsdennis/json-everything#318]
**Environment**
- Commit: f18e645179fb8b068a9c3183c73ffbc1782a709a (from 2022-08-12)
- Nuget Package: -
- Nuget Version: -
- OS: Windows
- .Net Target: All

**Describe the bug**
When converting a string to a number with `Numberify()`, floating point numbers are only parsed correctly if the current culture has a english-like number format. For eg. `de-AT` this isn't the case, so the input string `3.14` just returns ~the integer value `3`~ `null`,  as `,` is the decimal separator.

**To Reproduce**
```csharp
CultureInfo.CurrentCulture = new CultureInfo("de-AT");
var number = JsonValue.Create("3.14").Numberify();
```

**Expected behavior**
It should return correct floating point numbers regardless of current culture.

**Comment by gregsdennis** [comment]
Thanks for the report. I should be able to get to this soon.

**Comment by warappa** [comment]
I have a small PR ready in a minute if you want.
