### ISSUE TITLE
Json.Logic.LogicComponentConverter.Write not implemented - any other way to serialize rules to JSON string?

### ISSUE THREAD

**Issue by crankedapps** [gregsdennis/json-everything#328]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 3.1.2

**How can I help you today?**
I am looking a way I can convert Rule objects into serialized JSON.  I noticed there is documentation on json-everything.net referring to `LogicComponentConverter` class' `Write` method to handle this serialization however it throws a `NotImplementedException`.

- Is there any plans for this to be implemented soon?
- Do you recommend any libraries or other methods that could handle generating JSON string from the Rule objects?
- I only need to utilize a few rules and have limited time - would you accept a PR of partial implementation of this function?

Thank you for your time.

**Comment by gregsdennis** [comment]
I guess I never considered that people would want to go back from the model to JSON.  I just thought it would be imported and operated on.

I can add this support, no problem.

**Comment by crankedapps** [comment]
> I guess I never considered that people would want to go back from the model to JSON. I just thought it would be imported and operated on.
> 
> I can add this support, no problem.

That is great news, thank you!  Any idea of timeline of when we can expect this to be done?

**Comment by gregsdennis** [comment]
It shouldn't be more than a week.
