### ISSUE TITLE
Generating a schema for a class inheriting from Dictionary produces incorrect results

### ISSUE THREAD

**Issue by trocadilho** [gregsdennis/json-everything#335]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 3.0.3
- OS: Windows 11
- .Net Target: 6.0

**Describe the bug**
When generating a schema for a class that inherits from a Dictionary:

1. An incorrect type "array" is assigned.
2. Any properties in the class itself disappear from the schema.

**To Reproduce**
Have the following class:
```csharp
public class MyClass : Dictionary<string, int>
{
    public string SomeProperty { get; set; }
}
```

Use JsonSchema.Net.Generation to generate a schema:
```csharp
var schema = new JsonSchemaBuilder().FromType<MyClass>().Build();
```

The result schema is:

```json
{
   "type":"array",
   "items":{
      "type":"object",
      "properties":{
         "Key":{
            "type":"string",
            "readOnly":true
         },
         "Value":{
            "type":"integer",
            "readOnly":true
         }
      }
   }
}
```

**Expected behavior**
The following schema was expected:
```json
{
   "type":"object",
   "properties":{
      "SomeProperty":{
         "type":"string"
      }
   },
   "additionalProperties":{
      "type":"integer"
   }
}
```

**Additional context**

- `ArraySchemaGenerator.Handles` is returning true for this case. It would be expected that it returned false.
- Also, it would be expected that `StringDictionarySchemaGenerator.Handles` (or `EnumDictionarySchemaGenerator.Handles`, if the base class was a Enum keyed Dictionary) would return true, but it's returning false.
- To account for the missing property, I suppose `StringDictionarySchemaGenerator.AddConstraints and EnumDictionarySchemaGenerator.AddConstraints` would have to add the `PropertiesIntent`.

**Comment by trocadilho** [comment]
I just noticed this commentary on the global `GeneratorRegistry`: 
```csharp
// the dictionary ones are enumerable, so they need to come before the array one
			new StringDictionarySchemaGenerator(),
			new EnumDictionarySchemaGenerator(),
			new ArraySchemaGenerator(),
```

So apparently the real problem is really that the Dictionary generators returning false.

**Comment by gregsdennis** [comment]
I suggest creating your own generator for this.  As you pointed out, the available generators don't handle custom properties on dictionaries well.

This is something I'll consider for future versions, though.  I've been busy with supporting the next version of JSON Schema lately (both in this suite and the spec itself).
