### ISSUE TITLE
Handling of `null` values in uniqueKeys

### ISSUE THREAD

**Issue by zregvart** [gregsdennis/json-everything#342]
**Environment**
Trying to implement `uniqueKeys` in a separate project.

**How can I help you today?**
I'm not clear on the handling of `null` or non-existing values with the `uniqueKeys`. Reading https://json-everything.net/json-schema#the-uniquekeys-keyword it is not clear to me:
 - equality of `null` values
 - equality of the placeholder values for a non-existing locations

Given this schema:

**Schema:**
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "a": {
        "type": "string"
      },
      "b": {
        "type": "string"
      }
    }
  },
  "uniqueKeys": [
    "/b"
  ]
}
```

And considering this data:

**Data:**
```json
[
  {"a": "A", "b": null},
  {"a": "X", "b": "B"},
  {"a": "A", "b": null},
]
```

The resulting collection after evaluating the JSON paths could to be:

```jsonc
[
  {"b": null},
  {"b": "B"}
  {"b": null}
]
```

Are the two `{"b": null}` considered equal?

Concerning the placeholder for non-existant values, if the `uniqueKeys` constraint was defined as `"uniqueKeys": ["/a","/c"]` the resulting collection after evaluating the JSON paths could be:

```jsonc
[
  {"a": "A", "c": <placeholder>}, // or perhaps {"a": "A"}?
  {"a": "A", "c": <placeholder>},
]
```

Are the two `{"a": "A", "c": <placeholder>}` considered equal?

And finally, if the `uniqueKeys` constraint was defined as `"uniqueKeys": ["/c"]` the resulting collection after evaluating the JSON paths could be:

```jsonc
[
  {"c": <placeholder>}, // or perhaps {}?
  {"c": <placeholder>},
]
```

Are the two `{"c": <placeholder>}` considered equal?

Thank you for your time :)

**Comment by gregsdennis** [comment]
The placeholder is mentioned specifically because a naive implementation of this would just use `null` to represent a missing value.  However JSON `null` is a valid value distinct from a key missing.  To that end, missing keys need to be represented in another way.

In my implementation, which you can play with [here](https://json-everything.net/json-schema), the placeholder _does_ count as a value (just that it's hidden), so your

```jsonc
[
  {"a": "A", "c": <placeholder>}, // or perhaps {"a": "A"}?
  {"a": "A", "c": <placeholder>},
]
```

would not be considered unique, and validation would fail.

**Comment by zregvart** [comment]
To summarize: all placeholder values are considered to be equal with one another and all `null` values are considered to be equal with one another. Thanks, that clears things up!
