### ISSUE TITLE
Follow reference mechanism

### ISSUE THREAD

**Issue by mirkoSekulic** [gregsdennis/json-everything#343]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 3.2.1
- OS: any
- .Net Target: .net6

**Can this library make doing something simpler?**

There is not an easy way to follow reference other than implementing extension with simmilar implementation as internal "FindSubschema" method.
More so, decription of IRefResolvable contains: <br/>
> Defines functionality required to resolve `$ref` and `$recursiveRef` keywords

but it doesn't provide the mechanism to resolve `$ref` keyword.

**Describe alternatives you've considered**

Changing access modifier of FindSubschema method to public, or better to create extension or public method with following definition:
```c#
public JsonSchema ResolveReference(JsonPointer path);
```

**Comment by gregsdennis** [comment]
May I ask, why do you need to resolve a reference into a schema?  The system handles resolving references by itself.  (Also note that the [next version](https://github.com/gregsdennis/json-everything/pull/326) will do this quite differently, and it's actually internalized more.)

**Comment by mirkoSekulic** [comment]
I'm working on a conversion from xsd schema to json schema and vice versa.
We need to reproduce exactly the same xsd when doing round trip conversion. Some complex xsd schemas producing complex json schema with lot of references.  In some cases, when converting back to xsd we need to follow references to determine what was the original xsd structure.
Also I'm working on generating c# classes based on the input json schema. Ability to follow references comes handy here.
Could be that this feature is project specific, but to me it looks like it's not a bad idea to have this extension as part of the library it self.

**Comment by gregsdennis** [comment]
That sounds like a neat project.  I'd like to mention it to the JSON Schema team, actually.  Also, what's the project (if it's public)?  I wouldn't mind giving it a mention on this project's readme.

There's already some code in [OpenAPI.Net](https://github.com/microsoft/OpenAPI.NET) to do C# generation.  Maybe use that directly or as a reference.  They (soon to include me) are working on updating for Open API 3.1, which will likely use JsonSchema.Net for their validation engine.

As for your immediate need, I suggest that you serialize the schema to a `JsonNode` (or deserialize to `JsonNode` before going to `JsonSchema`) then just apply the pointer to that using the `JsonPointer` class.  I think the serializer is fast enough that the performance impact would be negligible.

**Comment by mirkoSekulic** [comment]
@gregsdennis  It's an opensource project called Altinn used by public sector in Norway.
More you can find on the documentation [here](https://docs.altinn.studio/).
You're might most interested in datamodeling part were we've used your library. It's in this [repo](https://github.com/Altinn/altinn-studio). You can explore more [here](https://github.com/Altinn/altinn-studio/tree/master/src/studio/src/designer).
Feel free to reference it in readme if you want. 
cc @RonnyB71

**Comment by gregsdennis** [comment]
@mirkoSekulic I've recently pushed v4.0-beta which actually removes `IRefResolvable` as it handles all of the registration stuff internally now (see full release notes on https://json-everything.net/json-schema.

I'm open to helping you get what you need, though.  There is a `FindSubschema()` method that I have as internal.  I was debating making it public, though.

**Comment by gregsdennis** [comment]
@mirkoSekulic can you please take a look at ☝️ (bundling) and see if that will solve your need?

**Comment by gregsdennis** [comment]
Also, regarding `FindSubschema()`, since it's now defined by `IBaseDocument`, that's now exposed.  You just need to pass an evaluation options object (the registry is needed).  I think I'm going to close this.

**Comment by mirkoSekulic** [comment]
@gregsdennis Sorry, I didn't had time to follow up on the previous comment.
But yes, this can be closed. Exposing FindSubschema is something that we needed.
