### ISSUE TITLE
JsonPath and regex

### ISSUE THREAD

**Issue by bard83** [gregsdennis/json-everything#350]
**Environment**
- Package: JsonPath

**How can I help you today?**
Does JsonPath support regex? 
Is there a way to filter simply saying the X properties should exist and not be empty without check the values programmatically?

**Additional context**
`$.[?(@.a)]` won't be enough, the property ("a") with empty string value will be listed in the result. Maybe this regex might help `$.[?(@.a =~ ^\w+$)]` but seems that it's not supported .
```json
[
  { "a": "value" },
  { "a": "" }
]
```

Thanks in advanced

**Comment by gregsdennis** [comment]
The spec team is still working out regex support.  It will be supported, but isn't just yet.

I've been meaning to update the library as the spec updates, but I've been busy working on Schema lately.

As it stands, support for regex will be provided via two functions: `match()` and `search()`.  You can read more in the path spec repo. There's a link on the readme for this repo.

**Comment by bard83** [comment]
Thanks for answering.

I guess that then I've to solved my problem differently.  I'll address my original question in a different topic.
