### ISSUE TITLE
Unable to access nuget package JsonSchema.Net  release notes

### ISSUE THREAD

**Issue by Bertk** [gregsdennis/json-everything#361]
**Environment**
- Nuget Package:  JsonSchema.Net
- Nuget Version: 3.3.2
- OS: Windows 11
- .Net Target: n.a.

**How can I help you today?**
The nuget package has URL for release note but I cannot access it.

https://json-everything.net/release-notes/json-schema.html

<img width="503" alt="image" src="https://user-images.githubusercontent.com/2315215/208289399-b43345c3-2c2b-4b95-b273-57f3548671f5.png">

**Additional context**
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2315215/208289423-bead9e71-3fef-439b-bd79-46a06d6cf26d.png">

**Comment by gregsdennis** [comment]
Hmm... looks like I need to update that.  I thought it would redirect, but it doesn't seem to.

You can view the release notes on https://json-everything.com/json-schema.  Look in the sidebar on the left for the release notes.  I'm sorry, I don't have those set up for a direct link yet.

**Comment by Bertk** [comment]
Thanks. The markdown source URL works for me.

**Comment by gregsdennis** [comment]
I've updated all of the packages (see commit [9a7bd8d](https://github.com/gregsdennis/json-everything/commit/9a7bd8df91ce4e4f0268fac7ee1f23d43badb73c)) to include references to both the markdown file here and the appropriate page on https://json-everything.net.
