### ISSUE TITLE
json schema handling string/nulls

### ISSUE THREAD

**Issue by petrce** [gregsdennis/json-everything#363]
Hi please is there any way how to allow nulls for properties that have 
`type: "string"`
defined in the schema?
unfortunately, the typescript framework I use for validation on client doesn't allow `type: ["string","null"]` in schema

right now I am getting this error: "Value is "null" but should be "string"" when I call JsonSchema.Validate

**Comment by gregsdennis** [comment]
`type: ["string","null"]` is the correct way to do this.

What typescript implementation are you using?  If they don't support this, you should file a bug over there.
