### ISSUE TITLE
Operators '<' and '<=' throws errors in case 3 parameters were passed

### ISSUE THREAD

**Issue by alexkharuk** [gregsdennis/json-everything#373]
Hello! 

**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 3.3.0
- OS: macOS
- .Net Target: net6.0

**Describe the bug**
Operators '<' and '<=' throws errors in case 3 parameters were passed and one of them or all have type String, like "1". But parameters are working fine in case 2 parameters were passed

**To Reproduce**
{"<" : [1, 2]} - passed
{"<" : ["1", 2]} - passed
{"<" : [1, 2, 3]} - passed
{"<" : ["1", 2, 3]} - throw an error "Lower bound must be a number"

i checked your code and found that:

in case 2 parameters you are trying to convert strings to numbers:
`var numberA = a.Numberify();`

but in case 3 parameters you are not:
`var low = (A.Apply(data, contextData) as JsonValue)?.GetNumber();`

**Comment by gregsdennis** [comment]
Thanks for finding this.  I'm happy to accept a PR to fix.

**Comment by alexkharuk** [comment]
Hello. PR was created: https://github.com/gregsdennis/json-everything/pull/375
