### ISSUE TITLE
Discrepancy between js and .net version in comparison operators

### ISSUE THREAD

**Issue by alexkharuk** [gregsdennis/json-everything#377]
Hello! not sure is this is a bug, if not please feel free to update this issue.

**Environment**
Nuget Package: JsonLogic
Nuget Version: 3.3.1
OS: macOS
.Net Target: net6.0

**Describe the bug**
There are some discrepancy between js and .net version in comparison operators.

**To Reproduce**
i made some testing with https://jsonlogic.com/ and found that JS library allows such code.
comparison of the strings:
`{"<" : ["abs", "123"]}`, result: true
`{">" : ["abs", "123"]}`, result: false
and some silly comparison that always have result: false. i am not good with JS, but probably this is because in following samples it is comparing NaN with number:
`{">" : ["abs", 123]}` result: false
`{"<" : ["abs", 123]}` result: false

But .Net lib in this cases trows errors.

What you think about add ability to compare strings in to .net version to remove discrepancy?

**Comment by gregsdennis** [comment]
Trying to align their original implementation and this one is a continued headache.  Their test suite is very basic, and they don't specify a lot of the behaviors.

Alignment is the goal.

**Comment by gregsdennis** [comment]
I really wish they had an actual test suite or a spec.

**Comment by gregsdennis** [comment]
Found an interesting one:

```jsonc
{"cat" : ["abc", {}]}
// returns "abc[object Object]"
```

I don't think that's something I want to replicate.  I think I'm okay throwing an error for this.

**Comment by gregsdennis** [comment]
This works, apparently:

```json
{"+": 3}
```

Which means that none of my serializers are right because they all expect arrays.  Also, `+` expects at least two values.

**Comment by gregsdennis** [comment]
@alexkharuk I think I got it all.  Please download and play with it.  If you notice anything out of place, please let me know.

**Comment by gregsdennis** [comment]
Looks like they're converting the empty string to 0.

The `<` operator seems to go through this process:

- check if all are strings; if so, compare (e.g. `{"<": ["15", "4"]}` returns true)
- attempt to convert to numbers; if successful, compare (e.g. `{"<": ["15", 4]}` returns false)
- convert to strings and compare
