### ISSUE TITLE
Add extra detail to JsonLogicExceptions where appropriate?

### ISSUE THREAD

**Issue by dcook-net** [gregsdennis/json-everything#379]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 3.3.1

**Can this library make doing something simpler?**
Came across [this](https://github.com/gregsdennis/json-everything/blob/91c340ea89396519f80a9b606f52ff6298654cf6/JsonLogic/Rules/LessThanRule.cs#L74) exception today in LessThanEqualRule, and ended up spending a bit of time trying to work out which of the many comparisions where actually causing this. 

I was thinking that this could have been sped up if the exception included the values numberA & numberb, as this would have helped zero in on the culprit faster:
`
private string AsString(decimal? number) => number.HasValue ? number.ToString() : "null"; 

if (numberA == null || numberB == null)
       throw new JsonLogicException($"Cannot compare {a.JsonType()}:{AsString(numberA)} and {b.JsonType()}:{AsString(numberB)}.");
`
I realise that at least one of them will be null, but one may not.

If you are happy with that, we can raise a PR to make this change.

Regards,
Dave

**Comment by dcook-net** [comment]
I realised the error of my ways!

**Comment by gregsdennis** [comment]
I think this is in conflict with #377, which, if implemented, _should_ remove all of those exceptions.  I'm not sure.  There's a lot of research that needs to go into that one to find out the behavior of the the JS implementation.

**Comment by dcook-net** [comment]
ah, ok...and the nulls wouldn't have a negative impact on the attempt to compare.
👍🏻
