### ISSUE TITLE
JsonNode to YAML

### ISSUE THREAD

**Issue by yufeih** [gregsdennis/json-everything#381]
**Describe the functionality that isn't covered by this suite**

The `Yaml2JsonNode` package can convert YAML to JsonNode, consider support the other direction to convert JsonNode to YAML. This enables generating YAML files from JsonNode.

**Describe alternatives you've considered**

**Additional context**

**Comment by gregsdennis** [comment]
Yeah, I initially just created this because people write JSON Schemas in YAML (e.g. for OpenAPI).  For completeness, I knew I should come back and implement the other direction.

If you want to have a crack at it, please feed free.  Try to mirror the API I already have, please.

**Comment by yufeih** [comment]
Thank you!
