### ISSUE TITLE
JsonPath $[n] returns no matches for Json that is only an array

### ISSUE THREAD

**Issue by thutch** [gregsdennis/json-everything#382]
**Environment**
- Nuget Package: JsonPath.Net
- Nuget Version: 0.3.3
- OS: Windows 10 
- .Net Target: .Net 6

**Describe the bug**
JsonPath returns no matches when evaluating a JsonArray that is the root.
E.g. $[0]

**To Reproduce**
```
var jsonArray = "[ \"a\", \"b\", \"c\", \"d\"]";
var jsonPath = JsonPath.Parse("$[0]");
var pathResult = jsonPath.Evaluate(jsonArray);
```
pathResult will have zero matches. 

**Expected behavior**
pathResult should have at least one match, "a". 

**Additional context**
None at this time.

**Comment by gregsdennis** [comment]
Your seat is being implicitly cast to a `JsonNode` as a string value, not an array.  You need to parse the JSON value first.

```c#
var jsonText = "[ \"a\", \"b\", \"c\", \"d\"]";
var jsonArray = JsonNode.Parse(jsonText);
var jsonPath = JsonPath.Parse("$[0]");
var pathResult = jsonPath.Evaluate(jsonArray);
```

**Comment by thutch** [comment]
Ah, thank you.
