### ISSUE TITLE
JsonLogic - unexpected behaviour from `var` operator

### ISSUE THREAD

**Issue by Sykander** [gregsdennis/json-everything#383]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 3.3.1
- OS: MacOS
- .Net Target: net6.0

**Describe the bug**

Within a `none` rule, I am using `var` to retrieve a specific property on that object and check it against a specific value. However when that value is missing I expect `var` to return null as `var` should be pointing to the data context within the current element being evaluated within the array. But what actually happens is internally `var` calls a special secondary data called `contextData` (the root data object) and returns the value from there if it exists.

**To Reproduce**

Rule
```json
{
	"none": [
		{
			"var": "additionalDrivers"
		},
		{
			"===": [
				{
					"var": "relationshipToProposer.dataCode"
				},
				"J"
			]
		}
	]
}
```
Data
```json
{
	"hasAdditionalDrivers": true,
	"additionalDrivers": [
		{}
	],
	"relationshipToProposer": {
		"dataCode": "J",
		"displayText": null
	}
}
```

Expected
```json
true
```

Actual Result
```json
false
```
**Expected behavior**

Within a `none` operator, `var` should only be able to retrieve data from within the currently evaluated item of the array supplied to `none`.

**Additional context**

The docs do not mention anything like this sort of behaviour [json-logic docs](https://jsonlogic.com/operations.html#all-none-and-some), and the same rule and data produces the expected output in other versions of JsonLogic tool, which leads me to believe this is a bug.

**Comment by gregsdennis** [comment]
Yeah, that looks to be right.  I'll add a test and fix.  Thanks.

**Comment by gregsdennis** [comment]
It looks like there is some odd behavior here that (as always with this project) isn't specified completely.  #263 is related.  I'm having trouble getting both of these to work.

**Comment by Sykander** [comment]
Hey, thanks for the quick reply,

I think resolution described in #263 is the bug I am talking about. 😅 

**Example**

Rule:
```json
{
    "some" : [
        { "var":"x"},
        {
            "in": [ {"var":""}, {"var":"y"} ] 
        } 
    ]
}
```
Data:
```json
{
    "x": [-1, 0, 1],
    "y": [2, 3, 1]
}
```

I would expect this to return `false` and when checking against the other json-logic libraries they agree
<img width="749" alt="Screenshot 2023-02-21 at 11 24 11" src="https://user-images.githubusercontent.com/26931543/220332249-708a7475-412a-43aa-aa82-66b3f862e133.png">.

However, it looks like the issue you linked is suggesting the exact opposite behaviour to what happens in the other json-logic libraries. I don't think it's possible to support both this issue and #263.

**Comment by gregsdennis** [comment]
Yeah, I definitely want alignment with the original.  I'll have to re-read that issue to find out why I thought it should be the other way.
