### ISSUE TITLE
GenerateData() throws System.InvalidOperationException: 'The node already has a parent.' when default value is set

### ISSUE THREAD

**Issue by leonardo-gooten** [gregsdennis/json-everything#384]
**Environment**
- Nuget Package: JsonSchema.Net.DataGeneration
- Nuget Version: 1.0.2
- OS: windwos 10 64 bit
- .Net Target: .Net 6

**How can I help you today?**
GenerateData() is throwing System.InvalidOperationException: 'The node already has a parent.' when I add a "default" keyword.
I was trying to see if the library would generate json from schema using the default values.

The default value is set only once on TestDataExamples.cs line 16. Removing it, the exception is not thrown.

**Additional context**
Attached my code. You can press run on VS2022. It's a simple code. It first validates some json against a schema, then tries to generate data from that schema.

[json-schema-demo - Copy.zip](https://github.com/gregsdennis/json-everything/files/10784808/json-schema-demo.-.Copy.zip)

**Comment by gregsdennis** [comment]
No, `default` isn't supported since it's not a validation keyword.  The data generation only considers keywords that can affect validation.

Thanks for reporting the exception.  I'll have a look soon.

**Comment by gregsdennis** [comment]
Looks like the `enum` generation is just taking the value from the schema without making a copy.  I can fix this up.  Will have a patch out soon.
