### ISSUE TITLE
"additionalProperties" being validated as a property 

### ISSUE THREAD

**Issue by nabinked** [gregsdennis/json-everything#39]
**Describe the bug**
The `additionalProperties` keyword is being treated as a property.

**To Reproduce**
```csharp
using System;
using System.Text.Json;
using Json.Schema;

var schema = @"{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""additionalProperties"": false
}";

var data = @"{
  ""prop1"":""val""
}";

var jsonSchema = JsonSchema.FromText(schema);
var validationResult = jsonSchema.Validate(JsonDocument.Parse(data).RootElement, new ValidationOptions { OutputFormat = OutputFormat.Basic });
Console.WriteLine(JsonSerializer.Serialize(validationResult));

//outputs
{
    "valid": false,
    "keywordLocation": "#/additionalProperties/$false",
    "instanceLocation": "#/prop1",
    "error": "All values fail against the false schema"
}

```

**Expected behaviour**
The error should indicate that additional properties is present.
![image](https://user-images.githubusercontent.com/7703179/99497150-9c288a80-29c9-11eb-859c-a6962d481e44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- .NET 5 (SDK 5.0.100)
 - Nuget Version [e.g. 22]
![image](https://user-images.githubusercontent.com/7703179/99497515-25d85800-29ca-11eb-8738-5e786ccebd37.png)

**Comment by gregsdennis** [comment]
The schema *is* indicating that.  Perhaps the confusion is that the error is technically coming from the `false` subschema of the `additionalProperties`.  Regardless, the instance fails for the same reason.

**Comment by nabinked** [comment]
Yes, basically the error message is a bit misleading. Please feel free to update the issue to reflect the actual issue here.

**Comment by gregsdennis** [comment]
The error message this library gives is more accurate.  It's the subschema of the `additionalProperties` that's generating the error, not the keyword itself.  Additionally Newtonsoft hasn't updated their output formatting to 2019-09 yet; it just gives an error message.

**Comment by nabinked** [comment]
Also I am not sure if this is expected but should the 2nd error be present in the errors list ?
**schema**
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "additionalProperties": false,
  "properties": {
    "firstName": {
      "const":"foo"
    }
  }
}
```
**data**
```json
{
  "firstName": "bar"
}
```
**outputs**
```json
{
  "valid": false,
  "keywordLocation": "#",
  "instanceLocation": "#",
  "errors": [
    {
      "valid": false,
      "keywordLocation": "#/properties/firstName/const",
      "instanceLocation": "#/firstName",
      "error": "Expected value to match given value"
    },
    {
      "valid": false,
      "keywordLocation": "#/additionalProperties/$false",
      "instanceLocation": "#/firstName",
      "error": "All values fail against the false schema"
    }
  ]
}
```

**Comment by gregsdennis** [comment]
Yes, this property is implemented per the specification:

From [9.3.2.3](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.3)

> Validation with "additionalProperties" applies only to the child values of instance names that do not appear in the annotation results of either "properties" or "patternProperties".

So what's the annotation result of `properties`?  From [9.3.2.1](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.1):

> The annotation result of this keyword is the set of instance property names matched by this keyword.

This means that only properties from `properties` that _pass validation_ produce annotations, and that `additionalProperties` applies to the rest.

In your case, `firstName` didn't pass `#/properties/firstName/const`, so there is no annotation from it.  Then `#/additionalProperties/$false` must look at it since there's no annotation.  This also produces an error.

Honestly, I don't see the point of defining it this way.  I, like you, think that the `additionalProperties` error is superfluous.  But this is what the spec defines, so this is how it's implemented.

**Comment by nabinked** [comment]
Thanks @gregsdennis for taking the time to explain in detail. I think this, as a consumer of this lib, may be confusing to a lot of developers unless they are aware that this is how the spec defines it. Would be worth mentioning it in the docs somewhere to avoid people raising similar issues in future.

**Comment by gregsdennis** [comment]
Yeah, I can probably do something in the docs.
