### ISSUE TITLE
Moving on from .Net Standard

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/json-everything#390]
From testing, it appears that updating to System.Text.Json v7 will require that I drop support for .Net Core 3.1.

I don't expect this will be a problem for most of my users as .Net Core 3.1 is [end-of-life](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) anyway, but I feel it deserves notification and a major version bump in the libraries.

This will come... eventually.

**Comment by m-gallesio** [comment]
Hello.
I just tried using this library in a .NET 7 project, and it pulled in System.Text.Json 7.0.0 with no apparent issues.
Unless there are specific reasons I don't think a forced upgrade is strictly required.

**Comment by gregsdennis** [comment]
Some further discussions in #532 revealed that it might be time to move on from .Net Standard.  I need feedback from users.

This would probably apply to the entire suite.

**Comment by gregsdennis** [comment]
I now have a branch with everything working for net6.0.

Might try to multi-target with net8.0 later, but very happy this is working for now.

**Comment by gregsdennis** [comment]
This .Net 7 Regex stuff would be nice to have.

https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#stringsyntaxattribute-regex
