### ISSUE TITLE
JsonPointer.Net 3.0.0 breaks JsonSchema.Net 3.3.2

### ISSUE THREAD

**Issue by quentez** [gregsdennis/json-everything#396]
**Environment**
- Nuget Package: 3.3.2
- OS: macOS Ventura
- .Net Target: 7.0.200

**Describe the bug**
When using JsonPointer.Net 3.0.0 together in the same project with JsonSchema.Net 3.3.2, calling `Validate()` on a `JsonSchema` object results in the following error:

```
System.MissingFieldException: Field not found: 'Json.Pointer.JsonPointer.UrlEmpty'.
```

**Expected behavior**
No error when calling `Validate()` on a `JsonSchema` object.
Downgrading to JsonPointer.Net 2.2.1 fixes the problem.

Is it now recommended to use the JsonSchema 4.0.0 beta?
I'm happy to help provide more information if needed!

**Comment by gregsdennis** [comment]
> Downgrading to JsonPointer.Net 2.2.1 fixes the problem.

This is the compatible version for the JsonSchema.Net 3.x versions.

> Is it now recommended to use the JsonSchema 4.0.0 beta?

It's available for experimentation, but I probably won't be pushing a non-prerelease version until we get the next version of the spec out.  There are significant changes coming in the spec.

That said, the validation is solid and usable in production.  Just don't expect the full version to be 100% API-compatible; things may change still.

**Comment by quentez** [comment]
> This is the compatible version for the JsonSchema.Net 3.x versions.

Oh I see. I think I was confused because I only upgraded JsonPatch.Net from `2.0.4` to `2.0.5` and didn't realize this pulled an incompatible dependency along the way.

Thank you for the quick reply!
