### ISSUE TITLE
If Replace operation is performed on JSON that doesn't have specified fields, these fields are added to JSON

### ISSUE THREAD

**Issue by anarujnii** [gregsdennis/json-everything#397]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 2.0.5
- OS: Windows 11 Pro
- .Net Target: .NET 5, 6, 7

**Describe the bug**
If `Replace` operation is performed on JSON that doesn't have specified fields, these fields are added to JSON

**To Reproduce**
<details><summary>Code to reproduce the problem</summary>
<p>

```
using System;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Json.Patch;
using Json.Pointer;

const string mask = "*****";
var maskJson = JsonValue.Create(mask);

var pathsToPatch = new[] { "/first_name", "/last_name" };

var patchOperations = pathsToPatch.Select(path => PatchOperation.Replace(JsonPointer.Parse(path), maskJson));
var patchConfig = new JsonPatch(patchOperations);

const string singleObjectJson =
    "{\"id\":\"640729d45434f90313d25c78\",\"guid\":\"f2e2767c-03e0-4862-addc-7d46c55efb33\",\"city\":\"Boston\"}";

var singleObject = JsonNode.Parse(singleObjectJson);
var patchedSingleObject = patchConfig.Apply(singleObject).Result;
Console.WriteLine(JsonSerializer.Serialize(patchedSingleObject));
// ^ outputs {"id":"640729d45434f90313d25c78","guid":"f2e2767c-03e0-4862-addc-7d46c55efb33","city":"Boston","first_name":"*****","last_name":"*****"}
```

</p>
</details>

**Expected behavior**
Nothing changes in JSON
Considering that [https://jsonpatch.com/](https://jsonpatch.com/) says that `Replace` equals to `Remove` and `Add`, I assume `Remove` result should be checked before adding the new fields

**Comment by gregsdennis** [comment]
That's a reasonable check. Have you tested on any other online playgrounds?

**Comment by anarujnii** [comment]
So I've just checked that and found out that the [RFC6902](https://www.rfc-editor.org/rfc/rfc6902#section-4) notation explicitly says that `The target location MUST exist for the operation to be successful.`
I've also tried it out using online tools and JS libraries.
[https://jsonpatch.me/](https://jsonpatch.me/) silently returns unmodified JSON.
Both [jsonpatch.js](http://jsonpatchjs.com/) and [jsonpatch-js](http://bruth.github.io/jsonpatch-js/) throw an error about missing value.
