### ISSUE TITLE
Creating Compound Schema Document (bundle/bundling)

### ISSUE THREAD

**Issue by amis92** [gregsdennis/json-everything#401]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 3.3.2

**How can I help you today?**

I want to create Compound Schema Documents from a set of schemas stored in separate files. 
I think this is currently not possible using the JsonSchema.Net package, and I'd like it to be :D If it is, please advise how.

The bundling is described on [json-schema.org](https://json-schema.org/understanding-json-schema/structuring.html#bundling).

**Additional context**

I've browsed the issues and I suspect that having #343 implemented would allow me to implement a crude bundler myself, and also generate the C# code myself a bit easier as I'm doing a lot of customizations.

However, a direct Bundler/Compound Schema Document builder provided by this project would be much more helpful.

**Comment by gregsdennis** [comment]
Specific to this library (as opposed to JSON Schema), what feature would you like to see in terms of bundling?  This library already supports the reference keywords.  Can you propose an API?

Note that creating a bundle will still require loading and registering all of the relevant documents.

**Comment by amis92** [comment]
Yes - loading and registering documents is obviously on my side. However it's not easy to get the list of all referenced schema IDs.

Although the schema supports reference keywords, there's not a simple way to actually browse/visit the node tree and find/filter all the references. So ideally I'd like to be able to retrieve a list of referenced IDs of schemas I need to import. Then I'd loop through a list, and for each distinct ID I'd import and recursively process these references (and then bundle the set into $defs). Currently the issue is that most/all of the logic is only triggered on Evaluation (validation), which I'm completely oblivious to - e.g. base-uri tracking is a thing I need to do manually currently.

For a specific API, it could be as simple as `public IEnumerable<Uri> GetAllReferencedSchemaIds()` which would return all distinct resolved/absolute IDs. Or a `public IEnumerable<IRefKeyword> GetAllRefKeywords()` if I could somehow resolve it's Uri to an absolute Uri easily. Or a visitor implementation over all keywords, that visits all of their child schemas automatically (walker-visitor), because it's currently hard to implement such a visitor without going deep into implementation.

**Comment by gregsdennis** [comment]
If all you really want is the IDs, I suggest a different approach: JSON Path.

With the schema serialized in `JsonNode` form, you can query it really easily to get the `$ref` values:

```c#
var path = JsonPath.Parse("$..['$ref']");
var data = schema.SerializeToNode();

var ids = path.Evaluate(data);
```

However, this won't analyze dynamic refs, which (in general) need an instance for the schema to evaluate, or get the absolute URIs.

---

I think an explicit bundling function might be in order here.  Something that:

- analyzes the schema
- resolves all of the `$ref`s
- returns a copy of the root schema with the `$ref` targets in the `$defs` (the bundle)

Something like

```
JsonSchema Bundle(EvaluationOptions? options = null) { ... }
```

**Comment by gregsdennis** [comment]
Would something like this work for you?

```jsonc
// root
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-everything/foo",
  "type": "object",
  "properties": {
    "bar": {
      "$ref": "bar"
    }
  }
}

// external
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-everything/bar",
  "type": "string"
}

// result
{
  "$id": "https://json-everything/foo(bundled)",
  "$defs": {
    "26f6f0d167": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://json-everything/foo",
      "type": "object",
      "properties": {
        "bar": {
          "$ref": "bar"
        }
      }
    },
    "c6e748adb1": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://json-everything/bar",
      "type": "string"
    }
  },
  "$ref": "https://json-everything/foo"
}
```

**Comment by amis92** [comment]
It does look promising!

I think I'd start with a simpler method to actually return just those referenced schemas, and allow the clients to bundle themselves however they deem appropriate, then maybe another method with a more opinionated way of generating an actual bundle document as you have here. I'll try to review today or tomorrow. However I'd like to thank you right now for such a quick response and action, you're great!
