### ISSUE TITLE
Discrepancy between js and .net version in missing operator

### ISSUE THREAD

**Issue by alexkharuk** [gregsdennis/json-everything#404]
Hello mr. @gregsdennis. I found one more discrepancy, please take a look.

**Environment**
Nuget Package: JsonLogic
Nuget Version: 4.0.1
OS: macOS
.Net Target: net6.0

**Describe the bug**
Discrepancy between js and .net version in `missing` operator

**To Reproduce**
rule: `{"if":[{"missing": "var1" },["missing"],["not missing"]]}`
data: `{"var1": ""}`

JS result: `["missing"]`
.Net result: `["not missing"]`

**Comment by gregsdennis** [comment]
I have had it with the stupid, undocumented, inconsistent behaviors from their dumb library.

It says right in [_their_ documentation](https://jsonlogic.com/truthy.html) that the truthiness of the empty string is false.

**Comment by gregsdennis** [comment]
I think something's wrong with your logic:

- `missing` takes an array
- your data is inconsequential

---

Oh!  Okay...  here's the replication:

Logic: `{"missing": "var1" }`

Data: `{"var1": ""}` returns `["var1"]`
Data: `{"var1": "a"}` returns `[]`

`missing` isn't checking the data for the presence of the property.  It's evaluating the truthiness of the value at that property.

I hate this stupid library.

**Comment by alexkharuk** [comment]
yes. my bad. but even after correction i have the same result:

rule: `{"if":[{"missing": ["var1"] },["missing"],["not missing"]]}`
data:` {"var1": ""}`
JS result:` ["missing"]`
Net result: `["not missing"]`

**Comment by gregsdennis** [comment]
Oh. No, I want saying your example was wrong. I just isolated the example more precisely.

**Comment by alexkharuk** [comment]
Thanks for quick fix, @gregsdennis!

**Comment by alexkharuk** [comment]
@gregsdennis hello. looks like i found issue with this fix in .NET

rule `{ "missing": "a" }`
data: `{ "a": true }`
output: `[]`

data: `{ "a": false }`
output: `["a"]`

**Comment by gregsdennis** [comment]
WHY IS EMPTY STRING SPECIAL CASED?!  I hate this stupid library.  It was such a good idea, but so much of it makes no sense.

**Comment by gregsdennis** [comment]
Alright, let's try this again.

**Comment by alexkharuk** [comment]
@gregsdennis hello. now it looks and works in the same way. Thanks for your help and quick fixes!
