### ISSUE TITLE
JsonSchema.Net.DataGeneration Version 1.0.3 seems to require a beta version of  JsonSchema.Net

### ISSUE THREAD

**Issue by ltlombardi** [gregsdennis/json-everything#405]
**Environment**
- Nuget Package: JsonSchema.Net.DataGeneration
- Nuget Version: 1.0.3 
- OS: W10
- .Net Target: .Net 7.0

**Describe the bug**
Version 1.0.3 seems to require a beta version of  JsonSchema.Net as the bellow picture shows.
I imagine this should not be happening

![image](https://user-images.githubusercontent.com/898124/225487945-e1a4c150-d53e-4e9a-9a81-a9282930ffaf.png)

**Comment by gregsdennis** [comment]
You're probably right.  It's going to take a bit for me to fix that because they're all in the same solution.  I'll have to branch off where JsonSchema.Net v3.3.2 was last and reapply those commits.  Then I have to publish manually.

I don't really have a better way to do this.

**Comment by gregsdennis** [comment]
v1.0.4 has been published.  It should be available for download soon.
