### ISSUE TITLE
JsonPointer referring to an array throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by mbj2011** [gregsdennis/json-everything#408]
**Environment**
- Nuget Package: JsonPointer.Net
- Nuget Version: 3.0.0

**Describe the bug**
When referring to an array (*not* an element inside of an array) in a piece of JSON using forward slash, JsonPointer.Evaluate and JsonPointer.TryEvaluate both throw an IndexOutOfRangeException.

**To Reproduce**

The error occours regardless of the number of elements in the array or the position of the array inside the JSON.

Here are two minimal examples that will throw IndexOutOfRangeExceptions:

```c#
var pointer = JsonPointer.Parse("/");
var data = JsonNode.Parse("[]");

pointer.TryEvaluate(data, out var array);
```

And

```c#
var pointer = JsonPointer.Parse("/");
var data = JsonDocument.Parse("[]").RootElement;

var array = pointer.Evaluate(data);
```

The two separate errors occurs because of the following two checks:
```c#
if (segmentValue[0] == '0') return null;
```

I'm not entirely sure what the purpose of this check is. I'm guessing it's because /007 is not a valid way to refer to an element at index 7.

**Expected behavior**
In both of the pieces of code above, I would expect to have access to an empty array.

**Comment by gregsdennis** [comment]
Thanks for reporting this.

The pointer `/` actually resolves to an empty-string key within an object.  So for an array, it should just return no results.

I'll have a look to determine what's going on.
