### ISSUE TITLE
`schema.Bundle()` fails with NullReferenceException for ItemsKeyword

### ISSUE THREAD

**Issue by amis92** [gregsdennis/json-everything#417]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.0.0
- OS: Linux
- .Net Target: .NET 7.0

**Describe the bug**

`JsonSchemaExtensions.Bundle(EvaluationOptions)` throws `NullReferenceException` given a schema containing `ItemsKeyword`.

**To Reproduce**

```csharp
#r "nuget: JsonSchema.Net, 4.0.0"
using Json.Schema;
// items: true
var singleItemSchema = new JsonSchemaBuilder()
    .Items(JsonSchema.True)
    .Build();
singleItemSchema.Bundle(); // throws
// items: [true, true]
var multiItemSchema = new JsonSchemaBuilder()
    .Items(new[]{JsonSchema.True, JsonSchema.True})
    .Build();
multiItemSchema.Bundle(); // throws
```

<details>
<summary>stacktrace</summary>

for `singleItemSchema`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
at Json.Schema.JsonSchemaExtensions.Bundle(JsonSchema jsonSchema, EvaluationOptions options)
```

for `multiItemSchema`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
at Json.Schema.JsonSchemaExtensions.Bundle(JsonSchema jsonSchema, EvaluationOptions options)
```

</details>

**Expected behavior**

Method returns bundled schema without exception.

**Additional context**

It seems (at least for the single-item case) this code is the problem:

https://github.com/gregsdennis/json-everything/blob/44d5fe8f83882d061b336cedc792bcc60563fd3e/JsonSchema/JsonSchemaExtensions.cs#L122-L125

On line 123, `ItemsKeyword` is `ISchemaCollector`, but when initialized with a single non-array value, it will return a null for `ISchemaCollector.Schemas`.

For multi-item case, I am not sure.

**Comment by amis92** [comment]
In terms of a personal opinion, I feel that all these interfaces are problematic - there's no common abstraction, and although they behave differently - in the end, there's a need to just iterate through subschemas.

So, I'd propose a new interface `ISubschemaContainer` that just provides an `IEnumerable<JsonSchema> Schemas` (impromptu names), and all schema-containing keywords (implementing any of the current container/collector interfaces) should implement it - it could be done via default interface methods (these interfaces could provide default implementation for `ISubschemaContainer` which they'd inherit, but I guess it's not viable due to the current set of targeted runtimes). And I think that the `JsonSchema` could also use having a public `GetSubschemas(bool recursive)` method to simplify cases when you need to enumerate nested schemas - that'd considerably improve experience for manual schema analysis/traversing.

**Comment by gregsdennis** [comment]
Those separate interfaces were the solution in #15, so I can just remove them.  Unfortunately I've lost the conversation to the Slack abyss.  For now, those interfaces will remain.

I'll dig into what's causing the failure, though.
