### ISSUE TITLE
Override JsonSchema.toString()

### ISSUE THREAD

**Issue by martinp999** [gregsdennis/json-everything#42]
Firstly, thank you for such an awesome library and excellent documentation.

I installed it yesterday and am experimenting with adding a reference to a schema using the fluent approach (it would also be good to include a more fully fleshed out example on https://gregsdennis.github.io/json-everything/usage/schema/references.html that uses the fluent approach).

I _think_ I have it right but it would be really good to see the generated schema as JSON.  Could you override JsonSchema.toString() so that it outputs something that JsonSchema.FromText(content) could load?

**Comment by gregsdennis** [comment]
Thank you for the compliment.  I'm glad that the library is working well for you.

Converting a `JsonSchema` to a string isn't something that really fits in a `.ToString()` method.  It requires serialization:

```c#
var condensed = JsonSerializer.Serialize(schema);
var indented = JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true };
```

Typically you want `.ToString()` to remain fairly simple and quick.

---

In regard to adding references with the fluent syntax, the best way is to just call the `.Ref()` extension method with a string reference:

```c#
var internalRefSchema = new JsonSchemaBuilder()
    .Defs(("myObj", new JsonSchemaBuilder().Type(SchemaValueType.Object)))
    .Ref("#/$defs/myObj")
    .Build();
var externalRefSchema = new JsonSchemaBuilder()
    .Ref("https://myserver.org/schema/myschema.json")
    .Build();
```

I haven't figured out a way to do a definition and a reference in such a way that it's compile-time checked. You're just going to need to be sure that your strings are right.

**Comment by martinp999** [comment]
Many thanks for that.  Both of your suggestions worked for me.
