### ISSUE TITLE
Encountered circular reference for allOf construction

### ISSUE THREAD

**Issue by jpmikkers** [gregsdennis/json-everything#435]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.0.5
- OS: Windows11
- .Net Target: net7

**Describe the bug**
I built a schema for an array where the items have a type that's derived from another type. When I evaluate the schema on a correct json file, JsonSchema.Net says there is a circular reference. See below for the schema.

**To Reproduce**

schema:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "array",
  "items": { "$ref": "#/$defs/DerivedType" },

  "$defs": {

    "BaseType": {
      "type": "object",
      "properties": {
        "field1": { "type": "string" }
      }
    },

    "DerivedType": {
      "allOf": [
        { "$ref": "#/$defs/BaseType" },
        { "properties": { "field2": { "type": "string" } } }
      ]
    }
  }
}
```

test json:

```json
[
  {
    "field1": "foo",
    "field2": "bar"
  }
]
```

**Expected behavior**
There is no circular reference as far as I can tell.

**Additional context**
Oddly enough, it seems json-everything.net/json-schema/ playground validates correctly. Here's the stacktrace I get from C#:

```
 Message: 
Test method Tests.UnitTests.TestBugJson threw exception: 
Json.Schema.JsonSchemaException: Encountered circular reference at schema location `file:///C:/redacted/bugschema2.json` and instance location `/0`

  Stack Trace: 
RefKeyword.Evaluate(EvaluationContext context)
EvaluationContext.Evaluate()
AllOfKeyword.Evaluate(EvaluationContext context)
EvaluationContext.Evaluate()
RefKeyword.Evaluate(EvaluationContext context)
EvaluationContext.Evaluate()
ItemsKeyword.Evaluate(EvaluationContext context)
EvaluationContext.Evaluate()
JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
JsonSchemaExtensions.Evaluate(JsonSchema jsonSchema, JsonElement jsonElement, EvaluationOptions options)
UnitTests.TestBugJson() line 165
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by gregsdennis** [comment]
Thanks for reporting.  The playground is running .net 6.  I wonder if that's part of the cause.

**Comment by gregsdennis** [comment]
Please see the PR ☝️.  I haven't been able to replicate this locally.  Doesn't seem that .net 7 is the issue, either.

**Comment by gregsdennis** [comment]
Yep... Reading from a file produces the error.  How odd.

**Comment by jpmikkers** [comment]
Yup my test was reading from file. Fwiw, the target being an array is not a factor, it also throws if you change that to an object containing a derivedtype field
