### ISSUE TITLE
It would good idea to include the available Enum options in the error message.

### ISSUE THREAD

**Issue by akshay-zz** [gregsdennis/json-everything#441]
The following error message tells that provided values are not from the list of options.
`Expected value to match one of the values specified by the enum`

It would be great if we can add the available option in the error message.
`Expected value to match one of the values specified by the enum. Available options ["option A","option B","option C"]`.

Changes going to be very simple as I can see in the `Resources.resx`. 

```
 <data name="Error_Enum" xml:space="preserve">
    <value>Expected value to match one of the values specified by the enum</value>
  </data>
```
to 
```
 <data name="Error_Enum" xml:space="preserve">
    <value>Expected value to match one of the values specified by the enum. Available options [[values]] </value>
  </data>
```

**Comment by akshay-zz** [comment]
What is your suggestion on this @gregsdennis?

**Comment by gregsdennis** [comment]
I intentionally didn't include the enum values in the error message by default. The `enum` keyword supports all JSON values, including objects in arrays, so in general it doesn't make sense to include them in the error message.

However you can register a custom error message fairly easily.  As you pointed out I do supply the values, so if you include the token in your custom error message it should be rendered as an array.

Here are the docs for custom error messages: https://json-everything.net/json-schema#schema-errors

**Comment by gregsdennis** [comment]
Also for reference:

https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/EnumKeyword.cs#L138-L145

**Comment by akshay-zz** [comment]
Oh great to hear that. Will try to customize the error message. Thanks for your quick feedback.

**Comment by akshay-zz** [comment]
`ErrorMessages.Enum = "Expected value to match one of the values specified by the enum. Available options [[values]]";` 
Yep, this worked as expected. Thanks.
