### ISSUE TITLE
Add an attribute to explicite expected schema type of a property

### ISSUE THREAD

**Issue by L3Z4** [gregsdennis/json-everything#444]
**Environment**
- Nuget Package:  JsonSchema.Net.Generation
- Nuget Version: 3.1.0 
- OS: Windows
- .Net Target: Core 3.x

**Can this library make doing something simpler?**
I'd like to be able to explicite the type of a given property thanks to an attribute for schema generation
```csharp
public Foo
{
   [PropertyType(SchemaValueType.Array, SchemaValueType.String)] // Stuff like that
   public object Bar { get; set; }
}
```

So the generated schema will looks like
```json
{
  "type": "object",
  "properties": {
    "Foo": {
      "type": ["array", "string"],
      "items": {}
    }
  }
}
```

I volunteer to propose a solution

**Comment by gregsdennis** [comment]
Thanks for submitting your suggestion.

You've removed part of the issue template that's designed to tell me what library this is for.  Can you edit your comment to add that back in, please?  I assume this is for schema generation from the content.

**Comment by gregsdennis** [comment]
I understand that there may be legitimate reasons to do this, but the architect in me is screaming that you're modelling something wrong.  I'm trying to silence him 😆.

Realistically, the `type` keyword is generally added automatically by the generation system.  It feels awkward to have two places that can add it.  Also this seems very specific to properties of type `System.Object` where there's not enough information to generate anything else.

Let me think about this for a while.  There might be another solution that's less tied to this use case.

For now, you can [create that attribute](https://json-everything.net/json-schema#schema-schemagen-attributes) in your own code.

**Comment by gregsdennis** [comment]
After thinking about this for a bit, I don't think I'll be adding this one to the library.  I think this is a rather special case, and since the library supports multiple avenues of customization, I'll leave this to you to add for your own use.
