### ISSUE TITLE
library not supporting format date

### ISSUE THREAD

**Issue by vikash-2** [gregsdennis/json-everything#445]
**Describe the bug**
i have a json schema and instance 
```
{
    "properties": {
        "recordingMethod": {
            "type": "string",
            "format": "date"
        }
    }
}

{
    "recordingMethod": "5"
}
```

**Expected behavior**
It should show error message 
**String '5' does not validate against format 'date'.** but it is getting validated True

**Comment by gregsdennis** [comment]
Could you post the code you're using to run the validation, please?  I suspect it's not validating `format`, which is an annotation by default.

Please see the [documentation](https://json-everything.net/json-schema#schema-format) for validating formats.

**Comment by gregsdennis** [comment]
Which options have you chosen when validating?  Please see the options [documentation](https://json-everything.net/json-schema#evaluation).

**Comment by vikash-2** [comment]
I have checked with all option but It validated true but it should fail.
you can too try in playground with below schema and instance.
Schema
```
{
    "properties": {
        "recordingMethod": {
            "type": "string",
            "format": "date"
        }
    }
}
```
Instance
```
{
    "recordingMethod": "5"
}
```

**Comment by gregsdennis** [comment]
I tried in in the playground when you first reported it.  There is no bug here.

Without format validation:
![image](https://user-images.githubusercontent.com/2676804/237034652-b11e8e17-b942-4bdb-b807-a24a006b52b0.png)


With format validation:
![image](https://user-images.githubusercontent.com/2676804/237034792-3fa31d81-03c1-44b4-b8b5-e8835882a899.png)

**Comment by vikash-2** [comment]
thank you , now it is working as expected.
