### ISSUE TITLE
Update/Remove schemas from SchemaRegistry & Generating default values.

### ISSUE THREAD

**Issue by matt-oplo** [gregsdennis/json-everything#449]
**Environment**
- Nuget Package: JsonSchema.Net, JsonSchema.Net.DataGeneration
- Nuget Version: 4.1.1, 1.1.0
- OS: Linux
- .Net Target: net 7.0 -->

**Can this library make doing something simpler?**
[JsonSchema.Net]
The SchemaRegistry allows us to Register schemas, but there is no way to remove or update schemas once they are registered. The current code simply ignores the request if the schema is already registered. 
- I would like to be able to call an Update method with the same parameters as Register to replace the existing registered schema. 
- I would like to be able to call a Remove/Delete method to remove a registered schema.

[JsonSchema.Net.DataGeneration]
I would like an option to generate data on a schema using the default value of underlying types. Eg. using the `default` value expression.

**Describe alternatives you've considered**
Forking the repo and maintaining my own version.

**Additional context**
I think these would be good additions to an already excellent library.

**Comment by gregsdennis** [comment]
> there is no way to remove or update schemas once they are registered

What is your purpose in unregistering them?

The system is already designed to allow for temporary registration through the local registry provided by `EvaluationOptions.SchemaRegistry`.  Any registrations here

- are only available to the evaluations that use this options object
- will be released from memory when the options object goes out of scope

Is there some other reason you need to unregister schemas?

> generate data on a schema using the default value of underlying types ... using the `default` value expression

I'm not quite sure I understand.  It sounds like you're talking about the C# `default` keyword, but data generation doesn't interact with C# types at all.  Are you talking about the JSON Schema `default` keyword, as in

```json
{
  "properties": {
    "foo": {
      "type": "string",
      "default": "bar"
    }
  }
}
```

**Comment by gregsdennis** [comment]
In the future, I'd appreciate these being reported separately.  Thank you.

**Comment by matt-oplo** [comment]
I'm using JSON Schema to 

> > there is no way to remove or update schemas once they are registered
> 
> What is your purpose in unregistering them?
> 
> The system is already designed to allow for temporary registration through the local registry provided by `EvaluationOptions.SchemaRegistry`. Any registrations here
> 
> * are only available to the evaluations that use this options object
> * will be released from memory when the options object goes out of scope
> 
> Is there some other reason you need to unregister schemas?

I have an API Gateway that can dynamically register routes, and I use JSON Schema to validate input. I'm loading and caching the schemas in the SchemaRegistry.Global repository. I'd like to be able to manage that cache so that when routes are removed, I can remove the associated schema without having to tear the whole thing down and reload them, thus negating the benefits of caching. Loading and parsing the schema on every request in a transient SchemaRegistry also negates the benefits. It would also be useful to inspect the SchemaRegistry to see if a schema is registered using a `containsKey`-like method.

If I've misunderstood the proper way to use the SchemaRegistry, I'd be happy to be corrected.

**Comment by matt-oplo** [comment]
> 
> > generate data on a schema using the default value of underlying types ... using the `default` value expression
> 
> I'm not quite sure I understand. It sounds like you're talking about the C# `default` keyword, but data generation doesn't interact with C# types at all. Are you talking about the JSON Schema `default` keyword, as in
> 

I was referring to the C# `default` keyword. This is the function I've written to do what I wanted, but I'm not sure how useful this would be to anyone else:

```
    private JsonNode? GetDefaultValue(SchemaValueType? schemaValueType)
    {
        return schemaValueType switch
        {
            SchemaValueType.Array => new JsonArray(),
            SchemaValueType.Boolean => JsonValue.Create(default(bool)),
            SchemaValueType.Integer => JsonValue.Create(default(int)),
            SchemaValueType.Number => JsonValue.Create(default(int)),
            SchemaValueType.Object => new JsonObject(),
            SchemaValueType.String => JsonValue.Create(string.Empty),
            _ => null
        };
    }
```

> In the future, I'd appreciate these being reported separately. Thank you.

Yes. My apologies.

**Comment by gregsdennis** [comment]
Thanks for both.  I think these can be added pretty easily.

I'm traveling right now. So, please give me a little time.

**Comment by gregsdennis** [comment]
> I'd like to be able to manage that cache so that when routes are removed, I can remove the associated schema without having to tear the whole thing down and reload them, thus negating the benefits of caching.

Are you dynamically adding and removing routes while the system is running?

**Comment by gregsdennis** [comment]
Regarding the defaults, it sounds to me like you want _minimal_ generation.  That is, generate the minimum data to get the schema to pass.

This is slightly different that "default" generation.  With default generation, in the C# sense, the default for a `List<int>` would be `null`, but that wouldn't satisfy a schema like `{ "type": "array", "items": { "type": "integer" } }` because `null` isn't an array.

Minimal generation, however, would give you an empty array.  If you were to add a `minItems: 5`, then you'd get an array containing five `0`s.

I think I can do the minimal generation, but I don't think the `default` generation would work well.

**Comment by gregsdennis** [comment]
@matt-oplo any would you mind having a look at the comments above, please?

**Comment by gregsdennis** [comment]
@matt-oplo closing for now.  If you'd like to revist this, please see my comments above.
