### ISSUE TITLE
An easy way to print evaluation errors?

### ISSUE THREAD

**Issue by ahi-el** [gregsdennis/json-everything#453]
Hi,

I'm using this library in my code to validate incoming jsons, and I'd like to return a fitting error message in case the evaluation failed
Is there an easy way to print the errors, and if not - I don't mind opening a PR. Any suggestions on where to start?

Thanks!

**Comment by gregsdennis** [comment]
Have you had a look at the [documentation](https://docs.json-everything.net/schema/basics/#schema-results)?  It explains the output and where you will find any error messages.

**Comment by gregsdennis** [comment]
@ahi-el did the documentation answer your question?
