### ISSUE TITLE
Localization for Sweden

### ISSUE THREAD

**Issue by pawel-wachalski** [gregsdennis/json-everything#457]
**How can I help you today?**
Hi, we need validation errors localized for sweden, the same way it is done for es culture. If I were to provide translation would you be able to add support for it?

 I saw similar issue over here:
https://github.com/gregsdennis/json-everything/issues/298

**Comment by gregsdennis** [comment]
Sure!  Just create a new resource file with the translations, and I'll handle the rest.

**Comment by pawel-wachalski** [comment]
Thanks! Took some time, but I have just added a [PR ](https://github.com/gregsdennis/json-everything/pull/470/files#diff-389d821d9f3da0352bf7fadc9b371e888fb8c8945173306e5f05959c5cc3536a) with resources for Sweden and Norway
