### ISSUE TITLE
Look for specific fields in schema and then lookup the corresponding values in json data

### ISSUE THREAD

**Issue by JohnnyPoon** [gregsdennis/json-everything#461]
**Describe the functionality that isn't covered by this suite**
Having a schema and the corresponding json, I want to lookup for any fields down in the object hierarchy with specific properties. In my case, I want to lookup for fields of type string with format password. The result of the lookup/query will return a list of paths. From the paths, I can apply to the corresponding json, so that I can read the value of those paths and replace the existing values with new values. In my use case, I am about to retrieve all passwords, encrypt them, store the passwords in some vault, and replace the password with masked ones.

**Comment by gregsdennis** [comment]
Hello.  Can you give some examples of what you're trying to do?

**Comment by JohnnyPoon** [comment]
My app allows administrators to define their own Json Schema. Below are two example schemas:
Example Schema 1
`{
  "title": "Data source 1",
  "type": "object",
  "required": [
    "token",
    "hostname"
  ],
  "properties": {
    "token": {
      "title": "Personal Access Token",
      "type": "string",
      "format": "password",
      "minLength": 4,
      "default": ""
    },
    "hostname": {
      "title": "Server Hostname",
      "type": "string",
      "minLength": 4,
      "default": ""
    }
  }
}`

Example Schema 2
`{
  "title": "Data source 2",
  "type": "object",
  "required": [
    "connectionstring"
  ],
  "properties": {
    "connectionstring": {
      "title": "Connection String",
      "type": "string",
      "format": "password",
      "minLength": 4,
      "default": ""
    }
  }
}`

Based on the above schemas, the App will present a form and allow user to enter the corresponding values. Example values:
`{"token":"some secret token","hostname":"some https path"}`
and
`{"connectionString": "user:password@hostname:port/database_name"}`

Now I hope the App can retrieve the value of "token" and "connectionString" as they are of type string and with the format password in their corresponding schema. After retrieving, the App will encrypt it and store back the masked values to the json data.

**Comment by gregsdennis** [comment]
So the validation already gives you the query bit.

```json
{
  "valid": true,
  "evaluationPath": "",
  "schemaLocation": "https://json-everything.net/cffa3e7cc4",
  "instanceLocation": "",
  "annotations": {
    "title": "Data source 1",
    "properties": [
      "token",
      "hostname"
    ]
  },
  "details": [
    {
      "valid": true,
      "evaluationPath": "/properties/token",
      "schemaLocation": "https://json-everything.net/cffa3e7cc4#/properties/token",
      "instanceLocation": "/token",
      "annotations": {
        "title": "Personal Access Token",
        "format": "password",
        "default": ""
      }
    },
    {
      "valid": true,
      "evaluationPath": "/properties/hostname",
      "schemaLocation": "https://json-everything.net/cffa3e7cc4#/properties/hostname",
      "instanceLocation": "/hostname",
      "annotations": {
        "title": "Server Hostname",
        "default": ""
      }
    }
  ]
}
```

You can extract the specific ones with the following JSON Path

```jsonpath
$..[?@.annotations.format=='password'].instanceLocation
```

This gives the result:

[
  {
    "Value": "/token",
    "Location": "$['details'][0]['instanceLocation']"
  }
]

That at least gives you the locations.

To replace the values, you'll need something like JSON Patch as neither JSON Schema nor JSON Path can mutate data.

However JSON Patch requires JSON Pointers (`/details/0/instanceLocation`), not JSON Paths (`$['details'][0]['instanceLocation']`), so you'll need to perform a [conversion](https://docs.json-everything.net/api/JsonPath.Net/JsonPathExtensions/#asjsonpointerthis-jsonpath-path).

```c#
var pointer = path.AsJsonPointer()`;
```

Now this can be included in a JSON Patch to mutate the data.

(This process could be made quite a bit simpler if JSON Patch used JSON Path to match operations, but [that proposal](https://github.com/json-patch/json-patch2/issues/23) isn't going anywhere.)
