### ISSUE TITLE
embedded schema's doesn't resolve local $ref with the correct baseuri

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#468]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.1.1
- OS: Windows
- .Net Target: .NET 7

Local JSON references within embedded schemas seems to be resolved using the default baseuri and a random segment. 

I modified [this test](https://github.com/gregsdennis/json-everything/blob/b5243c6c06f6ecedfd995e96677341c404ca1660/JsonSchema.Tests/BaseDocumentTests.cs#L11) to visualize what I mean:
```
[Fact]
public void SchemasEmbeddedInJsonCanBeReferenced_Valid()
{
    var json = JsonNode.Parse("""
    {
        "prop1": "foo",
        "prop2": [
            "bar",                
            {
                "type": "integer"
            }            
        ],
        "prop3":
        {
            "$ref": "#/prop2/1"
        }
    }
    """);

    var options = new EvaluationOptions
    {
        OutputFormat = OutputFormat.List
    };

    var jsonBaseDoc = new JsonNodeBaseDocument(json, new Uri("http://localhost:1234/doc"));
    options.SchemaRegistry.Register(jsonBaseDoc);

    JsonSchema subjectSchema = new JsonSchemaBuilder()
        .Ref("http://localhost:1234/doc#/prop3");

    JsonNode instance = 42;

    var result = subjectSchema.Evaluate(instance, options);

    result.IsValid.Should().BeTrue();
}    
```

Note `prop3` having a local `$ref`, `#/prop2/1`, to a schema in `prop2`.

This will fail with `Json.Schema.JsonSchemaException: Cannot resolve base schema from `https://json-everything.net/392a16a19e#/prop2/1`

I would expect this to be resolved to `http://localhost:1234/doc#/prop2/1`.

The schema gets found and registered as a sub schema of "http://localhost:1234/doc", but it seems it get's registered with the wrong baseuri. I fixed it by setting the root schema's baseuri in `JsonNodeBaseDocument` right before [this line](https://github.com/gregsdennis/json-everything/blob/b5243c6c06f6ecedfd995e96677341c404ca1660/JsonSchema/JsonNodeBaseDocument.cs#LL55C37-L55C37), like this:
```
public JsonSchema? FindSubschema(JsonPointer pointer, EvaluationOptions options)
{
    if (_foundSubschemas.TryGetValue(pointer, out var schema)) return schema;

    if (!pointer.TryEvaluate(_node, out var location)) return null;

    schema = location.Deserialize<JsonSchema>();
    if (schema != null)
        schema.BaseUri = BaseUri;
    _foundSubschemas[pointer] = schema;

    return schema;
}
```

I don't know if that change has other consequences though.

**Comment by Fresa** [comment]
After some more experimentation it doesn't seem local $ref in embedded json schemas work either.

**Example 1**
Reference a schema as a local json reference outside the schema
```
{
    "prop1": "foo",
    "prop2": [
        "bar",                
        {
            "type": "integer"
        }            
    ],
    "prop3":
    {
        "type": "object",
        "properties":
        {
            "data":
            {
                "$ref": "#/prop2"
            }
        }
    }
}
```
Using this payload:
```
{
  "data": 42
}
```
`Json.Schema.JsonSchemaException: Cannot resolve base schema from `https://json-everything.net/64d665e9da#/prop3`

**Example 2**
Reference a sub schema in a json schema
```
{            
    "prop3":
    {
        "type": "object",
        "properties":
        {
            "data":
            {
                "$ref": "#/definitions/prop2"
            }
        },
        "definitions":
        {
            "prop2":
            {
                "type": "integer"
            }
        }
    }
}
```
Using this payload:
```
{
  "data": 42
}
```
`Json.Schema.JsonSchemaException: Cannot resolve base schema from `https://json-everything.net/945cb54a8f#/definitions/prop2``

I used the same code as described above just exchanged the embedded schema json objects and evaluation payloads.

**Comment by Fresa** [comment]
You're right, I made a typo, the reference should have been `"#/prop2/1"`, which throws `Json.Schema.JsonSchemaException: Cannot resolve base schema from `https://json-everything.net/ebdb2bc71b#/prop2/1`. I'll update the second example.

**Comment by gregsdennis** [comment]
I think your two examples are the same now.

**Comment by Fresa** [comment]
It's slightly different. I've updated the first example to show the document as a plain formatted json string to make it easier to compare the two examples. 

In the first example `prop3` is a reference to a simple scalar schema hence the scalar payload 42. 

In the second example `prop3` is a schema that has a property `data` that refers to the simple scalar schema, hence the object payload:
```
{
  "data": 42
}
```

I just ran the two examples again, with the baseuri properly set in the `JsonNodeBaseDocument`, and the first example pass, the second one fails with the mentioned error of not being able to solve the reference `#/prop2/1`.

**Comment by gregsdennis** [comment]
So, instead of just setting the base URI for the schema, the `JsonNodeBaseDocument` has to initialize the schema.  This is an internal method on `JsonSchema`, and it basically goes through the entire schema and sets base URIs and other things everywhere.  (`Initialize()` also needs a registry to run.)

I think I have everything working now.
