### ISSUE TITLE
Yaml2JsonNode fails json->yaml->json roundtrip

### ISSUE THREAD

**Issue by amis92** [gregsdennis/json-everything#476]
**Environment**
- Nuget Package: Yaml2JsonNode
- Nuget Version: 1.2.0
- OS: Linux
- .Net Target: .NET 7

**Describe the bug**

When converting JSON string it's always converted to Any-style of Yaml Scalar.

Converting a JSON with a number within a string prevents roundtripping to yaml and again JSON, because a string (that looks like a number) in original JSON becomes an actual JSON number scalar when converting back from YAML.

Additionally, when creating repro, I've discovered that `json.ToYamlNode` doesn't handle `null` values within JSON.

**To Reproduce**

See fiddle: https://dotnetfiddle.net/FfxJlu

```c#
using System;
using System.Linq;
using System.Text.Json.Nodes;
using Yaml2JsonNode;
					
var jsonText = """
  {"foo":123,"foz":"123","bar":1.23,"baz": "1.23"}
  """;
var json = JsonNode.Parse(jsonText);
var yaml = json.ToYamlNode();
var yamlText = YamlSerializer.Serialize(yaml: yaml);

var jsonRoundtripped = YamlSerializer.Parse(yamlText).Single().ToJsonNode();
var jsonRoundText = jsonRoundtripped.ToJsonString();

Console.WriteLine("# jsonText:");
Console.WriteLine(jsonText);
Console.WriteLine();
Console.WriteLine("# yamlText:");
Console.WriteLine(yamlText);
Console.WriteLine("# jsonRoundText:");
Console.WriteLine(jsonRoundText);
```

Diff what is and what I'd want:

```diff
# jsonText:
{"foo":123,"foz":"123","bar":1.23,"baz": "1.23"}

# yamlText:
foo: 123
- foz: 123
+ foz: '123'
bar: 1.23
- baz: 1.23
+ baz: '1.23'

# jsonRoundText:
- {"foo":123,"foz":123,"bar":1.23,"baz":1.23}
+ {"foo":123,"foz":"123","bar":1.23,"baz":"1.23"}
```

**Expected behavior**

A json converted into YAML and back to JSON keeps the scalar types. That'd mean that the YAML scalar nodes are created as single- or double-quoted string-scalars for decimal- or bool- parsable strings.

**Additional context**

Generally, the conversion from YAML to JSON handles type differentiation quite well, but opposite direction isn't as thorough.

**Comment by amis92** [comment]
And also thank you for that package in general. I've found it very useful!

**Comment by gregsdennis** [comment]
Thanks for the reproduction.  That helps a lot.  In the future, could you also add the output you get vs the output you expect, please?

I'll get to work on this.

**Comment by amis92** [comment]
Added output vs expected!

**Comment by gregsdennis** [comment]
I see what you mean.  Numbers are interpreted as strings from the YAML back to JSON.

This is actually a consequence of YAML and hwo YamlDotNet handles parsing more than anything with this library.  With YAML in general it's not always possible/efficient to tell if a value is intended to be a string or a number.

I'll see if I can do anything about it.  Ultimately, I'm limited to how that project is parsing the YAML.

**Comment by gregsdennis** [comment]
I think this is probably the best match to what you're wanting.

https://github.com/aaubry/YamlDotNet/issues/315

You might try the workaround.  You can configure the serializer as part of the `.Serialize()` method:

```
var text = YamlSerialize.Serialize(yaml,
    builder => builder.WithEventEmitter(nextEmitter => new QuoteSurroundingEventEmitter(nextEmitter)));
```

I'm not sure this is something that I'm ready to put in this lib, though.

**Comment by amis92** [comment]
Couldn't setting YamlScalar.Style to Quoted work when mapping from JSON ode to YamlNode?

**Comment by gregsdennis** [comment]
Yep.  That worked!  I didn't even know that was a thing I could set.  Nice call.

I'll have an update out soon.
