### ISSUE TITLE
ToJsonNode handles decimal number separator potentially incorrect

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#478]
**Environment**
- Nuget Package: Yaml2JsonNode
- Nuget Version: 1.1.1
- OS: Windows 11
- .Net Target: .NET 7

Since plain YamlScalarNode is non-typed, it's value is represented as a string, [decimal.TryParse](https://github.com/gregsdennis/json-everything/blob/114428ee05a7ea6e7a5e9f3362d599ff7b6ab12e/Yaml2JsonNode/YamlConverter.cs#L107) will use the current culture's number format info when parsing which might use an incorrect separator. 

Maybe use `NumberFormatInfo.InvariantInfo` or a json specific format provider for decimals/numbers?

**Comment by gregsdennis** [comment]
Yep. Thanks. I'll have a look.

**Comment by gregsdennis** [comment]
Look out for v1.2.2.  Thanks for the report.
