### ISSUE TITLE
Support for in-built serialization attributes

### ISSUE THREAD

**Issue by sbiaudet** [gregsdennis/json-everything#48]
I've an object with this schema.

```
 public class Person
    {
        [JsonPropertyName("_id")]
        public string Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public int Age { get; set; }

    }
```

Schema generation extension generate a schema with a id property and not an _id property.

**Comment by gregsdennis** [comment]
Your post sounds like a bug report, but `JsonPropertyName` isn't an attribute defined by this library.

Are you asking for it to be added?

**Comment by sbiaudet** [comment]
I don’t known really ;)

JsonPropertyName is a standard attribute now in dotnet and I thinking that the generation of name is aligned with standard json serialisation but you right it’s not a bug but a new demand or feature.

Do you think we can use jsonpropertyname or do you wan’t to create a new schemapropertyname ?

Sébastien BIAUDET

**Comment by gregsdennis** [comment]
I'll have to do some research to determine where those attributes are defined (e.g. which frameworks, etc).

Thanks for the suggestion.

**Comment by gregsdennis** [comment]
Attributes defined in `System.Text.Json`:

- [.Net Core 3.0+](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization?view=netcore-3.0)
  - [JsonConverterAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverterattribute?view=netcore-3.0) - Identifies the converter class for a type.  Not useful for schema generation. ❌
  - [JsonExtensionDataAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonextensiondataattribute?view=netcore-3.0) - Identifies a property to be used for junk data from the JSON instance.  Not useful for schema generation. ❌
  - [JsonIgnoreAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=netcore-3.0) - Does not serialize the property.  Useful for schema generation. ✔️
  - [JsonPropertyNameAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=netcore-3.0) Specifies a JSON key for the property if different than the .Net property.  Useful for schema generation. ✔️
- [.Net 5](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization?view=net-5.0) (all of above, plus...)
  - [JsonConstructorAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconstructorattribute?view=net-5.0)  Identifies a constructor to be used by the serializer.  Not useful for schema generation. ❌
  - [JsonIncludeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-5.0) Allows serialization of non-public members.  Useful for schema generation. ✔️
  - [JsonNumberHandlingAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonnumberhandlingattribute?view=net-5.0) Specifies optional behaviors for number handling (e.g. storage in a string, etc).  Useful for schema generation. ✔️

**Comment by gregsdennis** [comment]
@sbiaudet, Schema.Net.Generation v1.1.0 should be available soon, supporting `JsonPropertyName` and `JsonIgnore`.

**Comment by gregsdennis** [comment]
@sbiaudet v1.2.0 should be available soon to support the remaining .net 5 attributes.  I've mirrored the attribute classes in the .net standard version so they're always available.  Enjoy!

**Comment by sbiaudet** [comment]
@gregsdennis great job !!!
