### ISSUE TITLE
Understanding How IDictionary<string,object> Schemas Are to Be Generated

### ISSUE THREAD

**Issue by aolszowka** [gregsdennis/json-everything#484]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.3.0

### What's your question?

Consider the following toy DTO's:

**SimpleDTO.cs**:
```csharp
namespace DTOTests
{
    public class SimpleDTO
    {
        public string StringProperty { get;set; }
        public int IntProperty { get;set; }
    }
}
```

**SimpleIDictionaryDTO.cs**
```csharp
namespace DTOTests
{
    public class SimpleIDictionaryDTO
    {
        public IDictionary<string, SimpleDTO> Value { get; set; }
    }
}
```

In a library called `DTOTests.dll`

And a Generator Library that does something akin to this:

```csharp
Assembly targetAssembly = Assembly.LoadFrom(filePath);

foreach (Type type in targetAssembly.ExportedTypes)
{
  string fileName =  $"{type.FullName}.json";
  JsonSchemaBuilder jsb = new JsonSchemaBuilder();
  SchemaGeneratorConfiguration configuration = new SchemaGeneratorConfiguration();
  jsb = jsb.FromType(type);
  var schema = jsb.Build();
  var json = JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true });
  File.WriteAllText(fileName, json);
}
```

Out of the box this will generate a "Schema" like so:

```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        }
      }
    }
  }
}
```

Next consider a badly formatted JSON File according to the C# DTO definition above ("b" is missing the two required properties):

```json
{
    "Value": {
        "a": {
            "StringProperty": "a",
            "IntProperty": 1
        },
        "b": {}
    }
}
```

If you utilize the Playground (https://json-everything.net/json-schema) this validates as valid, which in my opinion should not be valid:

![image](https://github.com/gregsdennis/json-everything/assets/2592881/292ae0a0-7aa3-4485-9e45-0de6bcfd3f96)

I feel like I am missing something, am I misusing this functionality?

I would have expected something similar to this hand rolled schema:

```json
{
    "type": "object",
    "properties": {
        "Value": {
            "$ref": "#/$defs/SimpleDTO"
        }
    },
    "required": [
        "Value"
    ],
    "$defs": {
        "IDictionaryStringSimpleDTO": {
            "type": "object",
            "patternProperties": {
                "^.": {
                    "$ref": "#/$defs/SimpleDTO"
                }
            }
        },
        "SimpleDTO": {
            "type": "object",
            "properties": {
                "StringProperty": {
                    "type": "string"
                },
                "IntProperty": {
                    "type": "integer"
                }
            },
            "required": [
                "StringProperty",
                "IntProperty"
            ]
        }
    }
}
```

Using this schema with the above test set in the playground properly detects the bad JSON according to the schema:
![image](https://github.com/gregsdennis/json-everything/assets/2592881/76753f20-1861-4ee3-a7d5-884edfb2738b)

### Is there any other information you'd like to share regarding this bug?

Is there additional steps that must be taken to get the auto generated schema to work?

Alternatively, is there any way to try and manipulate the generator to get something closer to the hand rolled version? I am more than happy to contribute and document the changes required, if pointed in the right direction.

The actual use case is far more complex than the above toy program (It is an `IDictionary<string, IDictionary<string, IDictionary<string, IDictionary<string, MyDTO>>>>>` - yes, it's that bad!) attempting to hand roll these schemas are very intensive timewise and error prone. If I can improve the Schema Generator, I think that is the better path forward.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey, thanks for the question.

>  ("b" is missing the two required properties)

It doesn't look like you've indicated that the properties are required.  Try applying the `[Required]` attribute (from my library, not  from System.Components.DataAnnotations):

```c#
namespace DTOTests
{
    public class SimpleDTO
    {
        [Required]
        public string StringProperty { get;set; }
        [Required]
        public int IntProperty { get;set; }
    }
}
```

This change produces the following schema:

```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "required": [
          "StringProperty",
          "IntProperty"
        ]
      }
    }
  }
}
```

And when you validate your instance with the missing data, you get the expected evaluation result:

```json
{
  "valid": false,
  "details": [
    {
      "valid": false,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/24a263f7e9#",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/properties/Value",
      "schemaLocation": "https://json-everything.net/24a263f7e9#/properties/Value",
      "instanceLocation": "/Value"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Value/additionalProperties",
      "schemaLocation": "https://json-everything.net/24a263f7e9#/properties/Value/additionalProperties",
      "instanceLocation": "/Value/a",
      "annotations": {
        "properties": [
          "StringProperty",
          "IntProperty"
        ]
      }
    },
    {
      "valid": false,
      "evaluationPath": "/properties/Value/additionalProperties",
      "schemaLocation": "https://json-everything.net/24a263f7e9#/properties/Value/additionalProperties",
      "instanceLocation": "/Value/b",
      "errors": {
        "required": "Required properties [\"StringProperty\",\"IntProperty\"] were not present"
      }
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Value/additionalProperties/properties/StringProperty",
      "schemaLocation": "https://json-everything.net/24a263f7e9#/properties/Value/additionalProperties/properties/StringProperty",
      "instanceLocation": "/Value/a/StringProperty"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Value/additionalProperties/properties/IntProperty",
      "schemaLocation": "https://json-everything.net/24a263f7e9#/properties/Value/additionalProperties/properties/IntProperty",
      "instanceLocation": "/Value/a/IntProperty"
    }
  ]
}
```

**Comment by gregsdennis** [comment]
Also please have a look at the [schema generation docs](https://docs.json-everything.net/schema/schema-generation/).  They give a lot of information on how to use the library, including various ways to customize its output.

**Comment by aolszowka** [comment]
@gregsdennis Thank you so much for your quick response. As you mentioned decorating the classes fixes the case linked above.

However the underlying issue for us, is still present, I think I needed a more complex case.

I apologize for the length of this, but I'm trying to build up to the scenario without disclosing any internal test data.

Let's repeat the class definitions from above with your suggested changes:

**SimpleDTO.cs**:
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    public class SimpleDTO
    {
        [Required]
        public string StringProperty { get;set; }
        [Required]
        public int IntProperty { get;set; }
    }
}
```

**SimpleIDictionaryDTO.cs**
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    public class SimpleIDictionaryDTO
    {
        [Required]
        public IDictionary<string, SimpleDTO> Value { get; set; }
    }
}
```

This generates the following schema:

**SchemaFromJsonEverything-SimpleIDictionaryDTO.schema**
```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "required": [
          "StringProperty",
          "IntProperty"
        ]
      }
    }
  },
  "required": [
    "Value"
  ]
}
```

Let's test with the following JSON object:

**HappyPath-SimpleIDictionaryDTO.json**
```json
{
    "Value": {
        "a": {
            "StringProperty": "a",
            "IntProperty": 1
        },
        "b": {
          "StringProperty": "b",
          "IntProperty": 2
        }
    }
}
```

So Far so good!

Let's test with a "bad" JSON Object:

**BadJSONWithMissingProperty-SimpleIDictionaryDTO.json**
```json
{
    "Value": {
        "a": {
            "StringProperty": "a",
            "IntProperty": 1
        },
        "b": {
          "StringProperty": "b"
        }
    }
}
```

Nice this validates as bad!

Let's try another "bad" JSON:

**BadJSON-WithAdditionalProperty-SimpleIDictionaryDTO.json**
```json
{
    "Value": {
        "a": {
            "StringProperty": "a",
            "IntProperty": 1
        },
        "b": {
          "StringProperty": "b",
          "IntProperty": 2,
          "BadProperty": 1
        }
    }
}
```

Bummer this still validates, but this is probably because we do not have `"additionalProperties": false` on the inner object. Looking at the documentation (thank you for that its pretty good!) I cannot see a way to decorate this within the object, in any case we can manually add it for now.

**Question 1** Can I decorate the code to get this property (additionalProperties) added automatically?

So now our JSON Schema looks like this:

**SchemaFromJSONEverything-SimpleIDictionaryDTO-WithAdditionalPropertiesFalseOnInnerObject.schema**
```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "additionalProperties": false,
        "required": [
          "StringProperty",
          "IntProperty"
        ]
      }
    }
  },
  "required": [
    "Value"
  ]
}
```

This now causes the `BadJSON-WithAdditionalProperty-SimpleIDictionaryDTO.json` to fail, awesome.

Let's try one more bad JSON:

**BadJSON-AdditionalProperitesOnSimpleIDictionaryDTO.json**
```json
{
    "Value": {
        "a": {
            "StringProperty": "a",
            "IntProperty": 1
        }
    },
    "Value2": {
        "a": {},
        "b": {
            "StringProperty": "a",
            "IntProperty": 1,
            "OtherProperty": 1
        },
        "c": {
            "AlternateProperty": "a"
        }
    }
}
```

This validates as true; but this is just another case of missing `"additionalProperties": false` on the IDictionary Level:

**SchemaFromJSONEverything-SimpleIDictionaryDTO-WithAdditionalPropertiesFalseOnAllDTOs.schema**
```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "additionalProperties": false,
        "required": [
          "StringProperty",
          "IntProperty"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "Value"
  ]
}
```

Sweet this validates as false now!

Ok Lets try something else; a little more complicated and closer to my  use case. Consider this DTO:

**NestedIDictionaryDTO.cs**
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    public class NestedIDictionaryDTO
    {
        [Required]
        public IDictionary<string, IDictionary<string, SimpleDTO>> NestedIDictionary { get; set; }
    }
}
```

This Generates the following Schema:

**SchemaFromJSONEverything-NestedIDictionaryDTO.schema**
```json
{
  "type": "object",
  "properties": {
    "NestedIDictionary": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "StringProperty": {
              "type": "string"
            },
            "IntProperty": {
              "type": "integer"
            }
          },
          "required": [
            "StringProperty",
            "IntProperty"
          ]
        }
      }
    }
  },
  "required": [
    "NestedIDictionary"
  ]
}
```

I already know that I want to add `"additionalProperties": false` to the schema based on above testing, however due to the nesting I am unable to add it at all levels; but I have added it to the ones I can:

**SchemaFromJSONEverything-NestedIDictionaryDTO-ManualAdditionalPropertiesFalse.schema**
```json
{
  "type": "object",
  "properties": {
    "NestedIDictionary": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "StringProperty": {
              "type": "string"
            },
            "IntProperty": {
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "required": [
            "StringProperty",
            "IntProperty"
          ]
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "NestedIDictionary"
  ]
}
```

Now Lets test this bad JSON:

**BadJSON-FailureToGenerateInnerInnerDictionaryObject.json**
```json
{
    "NestedIDictionary": {
        "Value": {
            "a": {
                "StringProperty": "a",
                "IntProperty": 1
            },
            "b": {
                "StringProperty": "b",
                "IntProperty": 2
            }
        },
        "Value2": {
            "a": {
                "StringProperty": "a",
                "IntProperty": 1
            },
            "b": {}
        }
    }
}
```

This works (validate as false)

However consider this bad JSON:

**BadJSON-FailureToGenerateInnerDictionaryObject.json**
```json
{
    "NestedIDictionary": {
        "Value": {
            "a": {
                "StringProperty": "a",
                "IntProperty": 1
            },
            "b": {
                "StringProperty": "b",
                "IntProperty": 2
            }
        },
        "Value2": {}
    }
}
```

This fails (validates as true, but should be false in my opinion)

I believe this is what is attempted to be described to me in the [`Nullability` section](https://docs.json-everything.net/schema/schema-generation/#schema-schemagen-nullability) of the documentation but I don't know enough yet to understand it.

I am reading the official documentation for (object)[https://json-schema.org/understanding-json-schema/reference/object.html] perhaps something with [`minProperties`](https://json-schema.org/understanding-json-schema/reference/object.html#size)?

Applying this to the schema like so seems to work as expected:

**SchemaFromJSONEverything-NestedIDictionaryDTO-ManualAdditionalPropertiesFalse-ManualMinProperties.schema**
```json
{
  "type": "object",
  "properties": {
    "NestedIDictionary": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "object",
        "minProperties": 1,
        "additionalProperties": {
          "type": "object",
          "properties": {
            "StringProperty": {
              "type": "string"
            },
            "IntProperty": {
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "required": [
            "StringProperty",
            "IntProperty"
          ]
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "NestedIDictionary"
  ]
}
```

Bingo seems to work in the use cases I've provided above and some corner cases I have attempted to test.

**Question 2** Is there a way to decorate this to generate the `minProperties` value on this Dictionary at all levels?

I recongize that the recommendation from the team is not to attempt real-time schema generation, but there are enough footguns in here I am hoping to give a few more hints within the POCOs to cover some common cases.

I appreciate your help!

**Comment by gregsdennis** [comment]
What you're looking for it the `[AdditionalProperties]` attribute, which (for your case) would go on the type itself.

```c#
[AdditionalProperties(false)]
public class SimpleIDictionaryDTO
{
    [Required]
    public IDictionary<string, SimpleDTO> Value { get; set; }
}

[AdditionalProperties(false)]
public class SimpleDTO
{
    [Required]
    public string StringProperty { get;set; }
    [Required]
    public int IntProperty { get;set; }
}
```

which generates

```jsonc
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {  // this one is describing the TValue of your dictionary
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "required": [
          "StringProperty",
          "IntProperty"
        ],
        "additionalProperties": false // this one is from the attribute on SimpleDTO
      }
    }
  },
  "required": [
    "Value"
  ],
  "additionalProperties": false // this one is from the attribute on SimpleIDictionaryDTO
}
```

I don't have a `minProperties` attribute, but you can create one simply enough: https://docs.json-everything.net/schema/schema-generation/#schema-schemagen-attributes

**Comment by aolszowka** [comment]
Thank you again for the quick response; I have implemented as you suggested, but we still encounter an error in some of the more complex scenarios.

Consider the following types:

**MinPropertiesAttribute.cs**
```csharp
using Json.Schema.Generation;
using Json.Schema.Generation.Intents;

namespace DTOTests
{
    [AttributeUsage(AttributeTargets.Property)]
    public class MinPropertiesAttribute : Attribute, IAttributeHandler<MinPropertiesAttribute>
    {
        public uint Value { get; }

        public MinPropertiesAttribute(uint value)
        {
            Value = value;
        }

        public void AddConstraints(SchemaGenerationContextBase context, Attribute attribute)
        {
            context.Intents.Add(new MinPropertiesIntent(Value));
        }
    }
}
```

**SimpleDTO.cs**
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    [AdditionalProperties(false)]
    public class SimpleDTO
    {
        [Required]
        public string StringProperty { get;set; }
        [Required]
        public int IntProperty { get;set; }
    }
}
```

**SimpleIDictionaryDTO.cs**
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    [AdditionalProperties(false)]
    public class SimpleIDictionaryDTO
    {
        [Required]
        [MinProperties(1)]
        public IDictionary<string, SimpleDTO> Value { get; set; }
    }
}
```

This produces the following Schema:

**DTOTests.SimpleIDictionaryDTO.schema**
```json
{
  "type": "object",
  "properties": {
    "Value": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/simpleDTO"
      },
      "minProperties": 1
    }
  },
  "required": [
    "Value"
  ],
  "additionalProperties": false,
  "$defs": {
    "simpleDTO": {
      "type": "object",
      "properties": {
        "StringProperty": {
          "type": "string"
        },
        "IntProperty": {
          "type": "integer"
        }
      },
      "required": [
        "StringProperty",
        "IntProperty"
      ],
      "additionalProperties": false
    }
  }
}
```

Consider the following invalid JSON Object:

**Missing single required IDictionary Value**
```json
{
    "Value": {}
}
```

This properly flags that this is missing at least one IDictionary Value and the Schema is good.

However lets try something a little more complicated:

**NestedIDictionaryDTO.cs**
```csharp
using Json.Schema.Generation;

namespace DTOTests
{
    [AdditionalProperties(false)]
    public class NestedIDictionaryDTO
    {
        [Required]
        [MinProperties(1)]
        public IDictionary<string, IDictionary<string, SimpleDTO>> NestedIDictionary { get; set; }
    }
}
```

This generates the following schema:

**DTOTests.NestedIDictionaryDTO.schema**
```json
{
  "type": "object",
  "properties": {
    "NestedIDictionary": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/iDictionaryOfStringAndSimpleDTO"
      },
      "minProperties": 1
    }
  },
  "required": [
    "NestedIDictionary"
  ],
  "additionalProperties": false,
  "$defs": {
    "iDictionaryOfStringAndSimpleDTO": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "required": [
          "StringProperty",
          "IntProperty"
        ],
        "additionalProperties": false
      }
    }
  }
}
```

Now consider the following invalid JSON object:
**Missing Inner SimpleDTO Object**
```json
{
    "NestedIDictionary": {
        "Value": {}
    }
}
```

This comes back as valid.

This simple fix of adding `"minProperties": 1` at the `iDictionaryOfStringAndSimpleDTO` resolves the issue, however I do not know how to apply this property to what I would call an anonymous type, is this possible in the library?

**DTOTests.NestedIDictionaryDTO-ManualMinPropertiesAtiDictioanryOfStringAndSimpleDTO.schema**
```json
{
  "type": "object",
  "properties": {
    "NestedIDictionary": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/iDictionaryOfStringAndSimpleDTO"
      },
      "minProperties": 1
    }
  },
  "required": [
    "NestedIDictionary"
  ],
  "additionalProperties": false,
  "$defs": {
    "iDictionaryOfStringAndSimpleDTO": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "object",
        "properties": {
          "StringProperty": {
            "type": "string"
          },
          "IntProperty": {
            "type": "integer"
          }
        },
        "required": [
          "StringProperty",
          "IntProperty"
        ],
        "additionalProperties": false
      }
    }
  }
}
```

Here are some other test cases that propertly validate as false with the above as well:

**Test1.json**
```json
{
    "NestedIDictionary": {
        "Value": {
          "invalid": "a"
        }
    }
}
```

**Test2.json**
```json
{
    "NestedIDictionary": {
        "Value": {
          "invalid": {
            "invalid": "a"
          }
        }
    }
}
```

Thank you again for your help and patience.

**Comment by gregsdennis** [comment]
> `IDictionary<string, IDictionary<string, SimpleDTO>>`

Yeah, I'm not adding support for something like this.  This kind of thing is one of the reasons why this kind of tool should not ever be considered production ready.  Tools like this cannot cater to every scenario.  This library strives to cover most cases, while also providing you multiple ways to customize to your needs.

> This simple fix of adding "minProperties": 1 at the iDictionaryOfStringAndSimpleDTO resolves the issue

This is your solution.  Use the tool to generate as much as you can, and finish the schema manually.  This is a dev tool, not for production.

**Comment by aolszowka** [comment]
Thank you so much for the assistance, and I appreciate the work! We'll close this as resolved.

Thank you again!
