### ISSUE TITLE
ToJsonNode() does not preserve YAML null values

### ISSUE THREAD

**Issue by nickcampau** [gregsdennis/json-everything#485]
### Nuget Package

Yaml2JsonNode

### Package Version

1.2.2

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug

YAML `null` values are not preserved when converting to `JsonNode`. They are converted as a string literal instead.

### Please add test code or steps to reproduce the behavior

Here is a test code exhibiting the issue.
https://dotnetfiddle.net/DDdvhP

### What did you expect?

`null` values from YAML documents are preserved when converting to `JsonNode`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the report.  I'll set up a test to see if I can reproduce this.

**Comment by gregsdennis** [comment]
It looks like YamlDotNet either isn't handling these right or is just trying to present all of the information from the text.  Regardless, it's not presenting `null` for any of these; it's giving me a string.  (They have a several [open issues](https://github.com/aaubry/YamlDotNet/issues?q=is%3Aissue+is%3Aopen+null) regarding nulls, this issue being among them.)

For (my) reference: https://yaml.org/type/null.html

I'll have to add some hack code to work around this.
