### ISSUE TITLE
Custom Error Message when payload violates schema rule like minimum or maximum

### ISSUE THREAD

**Issue by dcook-net** [gregsdennis/json-everything#487]
### Nuget Package

JsonSchema.Net

### Package Version

Whichever is currently in use on the https://json-everything.net/json-schema/ - assume 4.1.6

### What's your question?

I'm trying to create a custom error message to return when a value is out of bounds for a min or max rule:

Schema:
`
{
    "type": "object",
    "properties": {
        "value": {
            "type": "integer",
            "maximum": 999999,
            "errorMessage": "[[received]] is more than the max allowed: [[limit]]"
            }
    }
}
` 

Payload:
`
{
    "value" : 1000000
}
`
But instead of the expected '1000000 is more than the max allowed: 999999' I get 
'1000000 is greater than or equal to 999999'

Is this a bug, are my expectations wrong, or am I doing something wrong here?
I suspect my expectations are wrong, because this message appears to come from this resource file: https://github.com/gregsdennis/json-everything/blob/6b0e7087d951175eb2d19166cbfdc651bffc6b46/JsonSchema/Localization/Resources.resx#L163

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Have you looked at the documentation for customizing error messages?  https://docs.json-everything.net/schema/basics/#schema-errors

`errorMessage` isn't a keyword. It's ignored.
