### ISSUE TITLE
Cannot set double.MaxValue nor decimal.MaxValue to MaximumAttribute

### ISSUE THREAD

**Issue by mikolajpiecuch** [gregsdennis/json-everything#488]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.3.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug

Cannot set double.MaxValue nor (double)decimal.MaxValue to MaximumAttribute. It is caused probably because of that issue in CLR: https://github.com/dotnet/runtime/issues/68042

### Please add test code or steps to reproduce the behavior

Add [Maximum(double.MaxValue)] or [Maximum((double)decimal.MaxValue)] to property

### What did you expect?

Be able to set constraint decimal.MaxValue to property

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Yep, I think you've found the issue.  As it's a .Net issue and not anything with this library, it doesn't seem there's anything I can do to fix the conversion.

The [`[Maximum]` attribute](https://docs.json-everything.net/api/JsonSchema.Net.Generation/MaximumAttribute/) constructor takes a double for authoring convenience (so that you can do `[Maximum(15)]` instead of having to do `[Maximum(15m)]`.  What I can do is add a constructor that takes a `decimal`.  This will avoid the conversions you mention above.

**Comment by mikolajpiecuch** [comment]
Hi @gregsdennis attributes cannot take `decimal` as a parameter or have decimal properties. It's another limit in CLR. I was there trying to change this :) There are two options:
- add default ctor which will be set decimal.MaxValue (it can be misleading)
- add ctor with bool parameter which will be set decimal.MaxValue (what about passing false here?)

I could prepare solution but don't know which solution is better. Do you have any other suggestion?

**Comment by gregsdennis** [comment]
> attributes cannot take `decimal` as a parameter

Ah, yes.  I remember that now.

I don't particularly care for either of those solutions.  I agree that the default constructor is misleading, but `maximum` doesn't take a boolean value in JSON Schema, so that's also somewhat misleading.  Let me think about it for a bit.

**Comment by gregsdennis** [comment]
So the solution I think I've landed on is automatically clamping the value to the `decimal` range along with some documentation.

**Comment by michaelgwelch** [comment]
@gregsdennis thanks for the feedback. I'll have a take at implementing our own. For us the main use case is dynamically generating JSON schemas from live data.
