### ISSUE TITLE
Consolidate Evaluation Results with json-schema output schema

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#489]
### Nuget Package

JsonSchema.Net

### Package Version

4.1.5

### Can this library make doing something simpler?

`EvaluationResults` does not align with json-schema.org output schema. 
I see you've been part of defining it, good stuff! 👌

Wouldn't it be great if this implementation was aligned with that specification? Or is this to be considered as work in progress?

For the latest work in progress schema version it differs at `details` -> `nested` and the conditional `allOf` part:
https://github.com/json-schema-org/json-schema-spec/blob/fb89a3bf6f5aa066253d30b353abcbbe478b7a3c/output/schema.json

For draft 2020-12 it differs a bit more:
http://json-schema.org/draft/2020-12/output/schema 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Fresa** [comment]
Cool, I missed that converter! 

`draft-next` says there can be an optional property called [`nested`](https://github.com/json-schema-org/json-schema-spec/blob/fb89a3bf6f5aa066253d30b353abcbbe478b7a3c/output/schema.json#L27C2-L29), this one does not seem to be included in `EvaluationResultsJsonConverter` but it produces a property called [`details`](https://github.com/gregsdennis/json-everything/blob/9a74b2cb701599369e17b8e5c5af03336aec1727/JsonSchema/EvaluationResults.cs#L373-L377) which looks suspiciously similar.

**Comment by gregsdennis** [comment]
Yeah, we determined that `details` was a better name, but probably got distracted by leaving IETF and didn't update the document.

There are likely a few more changes coming once we get back to actual spec authorship.  For now, it is what it is.
