### ISSUE TITLE
JsonPath.TryParse throws exception if the source string is empty

### ISSUE THREAD

**Issue by ben-wckdrzr** [gregsdennis/json-everything#495]
### Nuget Package

JsonPath.Net

### Package Version

0.6.3

### Operating System

Mac

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug

If you call JsonPath.TryParse() with an empty string as the first parameter, a `System.IndexOutOfRangeException` is thrown with the message `Index was outside the bounds of the array.`

### Please add test code or steps to reproduce the behavior

Simply run the following:
```
JsonPath.TryParse("", out JsonPath? jsonPath);
```

### What did you expect?

Function should return false and leave the out path property null

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.  It looks like this may have been handled in previous versions, but I remove it when adjusting where whitespaces could be expected.

I'll have a fix out soon.

**Comment by ben-wckdrzr** [comment]
Thanks for fixing so quickly - all working well 👍
