### ISSUE TITLE
Bring back the option to exclude EvaluationResults

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#500]
### Nuget Package

JsonSchema.Net

### Package Version

5.1.0

### Can this library make doing something simpler?

Pre 5.0.0 one could use the `EvaluationResults.Ignore()` to exclude evaluation results, for example any result that is valid. The `Exclude` property is still there and it is used by the `EvaluationResultsJsonConverter`, but nothing sets that property any more.

Maybe make the setter public?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Have you read the updated [documentation](https://docs.json-everything.net/schema/vocabs/#schema-vocabs-custom-keywords-1)?

> For `maximum`, evaluation means we check if the value is a number. If not, we indicate that the keyword doesn’t apply by calling `.MarkAsSkipped()`. (This tells _JsonSchema.Net_ that that any nested results don’t need to be added.) If the instance is a number, and it doesn’t meet the requirement, then we fail the keyword with an error.

**Comment by gregsdennis** [comment]
I'll have to look at that `Exclude` property, but the strategy now is just to not have the results object added in the first place.

**Comment by Fresa** [comment]
Here's an example of what I mean:
<img width="411" alt="image" src="https://github.com/gregsdennis/json-everything/assets/1190300/c185bd00-efc0-4846-8328-8a2342a4ebd6">

I previously filtered out those evaluation results. I can of course write my own json convert that does that, but it was neat that it was supported out of the box.

**Comment by gregsdennis** [comment]
How would you filter them out?  What's the reason for doing so?  Maybe there's another solution here.

Related: I've been working on revamping the output for JSON Schema, and this library is a test bed for that work.  This seems like another filtering option candidate.

- [annotation filtering](https://github.com/orgs/json-schema-org/discussions/236)
- [output unit pruning](https://github.com/json-schema-org/json-schema-spec/issues/1319)
- [first run at writing spec language for ☝️](https://github.com/json-schema-org/json-schema-spec/pull/1385/files#diff-9e470d7f858bf7e6a5770b153fb395f3f20e7fb289a05c5b0420c6c2f77306b8R570-R605)

**Comment by gregsdennis** [comment]
`EvaluationResults.Ignore()` was meant to be used inside of a custom keyword.  In previous versions, I used it in keywords like `$defs` that don't do anything, but that model has changed with v5, and the method isn't needed for that purpose anymore.

I didn't expect anyone to use it to hide specific nodes post-evaluation.

**Comment by Fresa** [comment]
I simply filtered out any evaluation result that `IsValid` leaving me with only invalid results (using the hierarchy format) to be able to focus on the problems. I haven't experienced any valid result to be of interest in that case. Reading the [discussion you had about output pruning](https://github.com/json-schema-org/json-schema-spec/issues/1319) this might be a naive approach in certain situations, however I usually consult the schema if the output is not clear enough about what my options are to fix the problems presented to me.

**Comment by gregsdennis** [comment]
I can think of a couple solutions to this, one of which you can do now.  However, there are some side effects of just looking for error messages that I think you should be aware of.

Just searching for error messages could return messages that don't impact the outcome.  Like if you have a successful validation, but there's an `anyOf` subschema that failed, that subschema will produce errors.  You actually want to ignore these, but that's hard to tell if you don't have the valid nodes as well.

### Option 1 - JSON Path

There are several options here depending on what you want.

- `$..errors.*` will just get the error messages themselves.
- `$..errors` will return all of the error dictionaries, which will also give you the keywords that produced those errors.
- `$..[?@.errors]` will return all of the nodes which have errors.

The last one actually might be best since you'll also probably want the instance location.

This is likely your best short-term bet.

### Option 2 - New filter feature

We discuss the filtering that you want and I build it (or you do and submit a PR).

### Option 3 - Custom filter feature

This I just now thought of, and it would enable a user to devise their own filtering mechanism.  This will take some thought to build a usable API.

**Comment by Fresa** [comment]
I'm excluding evaluation results by looking at the `IsValid` property. I assume any result is not valid either if it explicitly has produced errors or if any of it's child results (`Details`) is not valid, is that not true?

Here's an example of what I do:
```
public static class EvaluationResultsExtensions
{
    private static void ExcludeValidResults(this IEnumerable<EvaluationResults> results)
    {
        foreach (var result in results)
        {
            result.ExcludeValidResults();
        }
    }

    public static void ExcludeValidResults(this EvaluationResults results)
    {
        if (results.IsValid)
        {
            // Exclude
            results.Ignore();
            return;
        }
        results.Details.ExcludeValidResults();
    }
}
```

Would of course be more appropriate if this could be configured within the json converter instead of this hack :)

**Comment by gregsdennis** [comment]
> I assume any result is not valid either if it explicitly has produced errors or if any of it's child results (`Details`) is not valid, is that not true?

That's not true.

Consider this schema:

```json
{
  "anyOf": [
    { "type": "string" },
    { "type": "number" },
    { "type": "boolean" }
  ]
}
```

The instance `"a string"` will only validate on the first subschema, but the others will have errors and `valid` will be false.  Yet the overall validation passes:

```json
{
  "valid": true,
  "evaluationPath": "",
  "schemaLocation": "https://json-everything.net/193ef3a33a#",
  "instanceLocation": "",
  "details": [
    {
      "valid": true,
      "evaluationPath": "/anyOf/0",
      "schemaLocation": "https://json-everything.net/193ef3a33a#/anyOf/0",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/1",
      "schemaLocation": "https://json-everything.net/193ef3a33a#/anyOf/1",
      "instanceLocation": "",
      "errors": {
        "type": "Value is \"string\" but should be \"number\""
      }
    },
    {
      "valid": false,
      "evaluationPath": "/anyOf/2",
      "schemaLocation": "https://json-everything.net/193ef3a33a#/anyOf/2",
      "instanceLocation": "",
      "errors": {
        "type": "Value is \"string\" but should be \"boolean\""
      }
    }
  ]
}
```

Conversely for this schema:

```json
{
  "not": { "type": "string" }
}
```

the instance `"a string"` fails overall, but without any errors.

```json
{
  "valid": false,
  "evaluationPath": "",
  "schemaLocation": "https://json-everything.net/74ad7420d3#",
  "instanceLocation": "",
  "details": [
    {
      "valid": true,
      "evaluationPath": "/not",
      "schemaLocation": "https://json-everything.net/74ad7420d3#/not",
      "instanceLocation": ""
    }
  ]
}
```

(I'm sure another case could be contrived, but this is the only one I can think of.)

**Comment by Fresa** [comment]
`anyOf` works fine with the mentioned approach, but you are right about `not`. `oneOf` might also produce a similar result (the instance matches multiple sub-schemas).

Maybe each keyword could identify a minimal set of relevant evaluation information? I think you are on to something in the thread about pruning, it sounds like what I'm looking for. Is that something that's available today, or have you just experimented?

**Comment by gregsdennis** [comment]
Pruning nodes isn't something I've figured out how to do in a nice way yet.  (That's what that discussion is for.)  You can see in the discussion that there's a lot to consider.  I don't particularly like the idea of each keyword specifying what needs to go into the output.  The output is meant to be generic.
