### ISSUE TITLE
Template enum received and spec values in the error message

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#501]
### Nuget Package

JsonSchema.Net

### Package Version

5.1.0

### Can this library make doing something simpler?

The `EnumKeyword` [error message](https://github.com/gregsdennis/json-everything/blob/67b39f6d0ed3ff4d55bcc61f2d7da2b486324b8e/JsonSchema/Localization/Resources.resx#L138-L140) does not template the failed instance value nor the defined values in the schema, but the `EnumKeyword` [Evaluator propagates them](https://github.com/gregsdennis/json-everything/blob/67b39f6d0ed3ff4d55bcc61f2d7da2b486324b8e/JsonSchema/EnumKeyword.cs#L97) to the template. 

Adding those template parameters to the error message would make the error message more useful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Later in the [code](https://github.com/gregsdennis/json-everything/blob/67b39f6d0ed3ff4d55bcc61f2d7da2b486324b8e/JsonSchema/EnumKeyword.cs#L133-L135).  This renders in the IDE and the [API docs](https://docs.json-everything.net/api/JsonSchema.Net/ErrorMessages/#getenumcultureinfo-culture).

```c#
/// The default messages are static and do not use these tokens as enum values
/// may be any JSON type and could be quite large.  They are provided to support
/// custom messages.
```

**Comment by Fresa** [comment]
Aha it's possible to override the templates via `ErrorMessages`, sweet!
