### ISSUE TITLE
JsonSchema.FindSubschema returns null for existing path

### ISSUE THREAD

**Issue by Splamy** [gregsdennis/json-everything#506]
### Nuget Package

JsonSchema.Net

### Package Version

5.1.3

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug

When accessing `additionalProperties` via `JsonPointer` to `((IBaseDocument)JsonSchema).FindSubschema` the call will return null.

### Please add test code or steps to reproduce the behavior

```csharp
[Test]
public void IssueXXX()
{
	IBaseDocument schema = JsonSchema.FromText("""
	{
		"type": "object",
		"additionalProperties": {
			"title": "DictTemplate",
			"type": "object",
			"properties": {
				"Enabled": {
					"type": "boolean"
				}
			}
		}
	}
	""");

	var pointer = Pointer.JsonPointer.Parse("/additionalProperties");
	var subSchema = schema.FindSubschema(pointer, EvaluationOptions.Default);

	Assert.IsNotNull(subSchema);
}
```

### What did you expect?

Since the JsonSchema is unambiguous in this case I would expect the method to return the subschema here.

### Is there any other information you'd like to share regarding this bug?

The fault is at this line:
https://github.com/gregsdennis/json-everything/blob/a4aae65dd856736f42dcd0b0cf3c3bc36dfcb86b/JsonSchema/JsonSchema.cs#L521-L525

JsonPointer of "/additionalProperties" consists of only a single PointerSegment.
The extracted keyword here is a `AdditionalPropertiesKeyword` implementing `ISchemaContainer`
On pointers with more segments this will go through the switch, get unwrapped, and as the comment intended reprocessed.
With only one segment the container will go the final return and therefore be null when tried to cast to `JsonSchema`

My suggested fix, if you want I can create a PR for it:

```diff
diff --git a/JsonSchema/JsonSchema.cs b/JsonSchema/JsonSchema.cs
index ba330279..ab8d73e2 100644
--- a/JsonSchema/JsonSchema.cs
+++ b/JsonSchema/JsonSchema.cs
@@ -489,22 +489,6 @@ public class JsonSchema : IBaseDocument
 			int index;
 			switch (resolvable)
 			{
-				case ISchemaContainer container and ISchemaCollector collector:
-					if (container.Schema != null)
-					{
-						newResolvable = container.Schema;
-						i--;
-					}
-					else if (int.TryParse(segment.Value, out index) &&
-							 index >= 0 && index < collector.Schemas.Count)
-						newResolvable = collector.Schemas[index];
-
-					break;
-				case ISchemaContainer container:
-					newResolvable = container.Schema;
-					// need to reprocess the segment
-					i--;
-					break;
 				case ISchemaCollector collector:
 					if (int.TryParse(segment.Value, out index) &&
 						index >= 0 && index < collector.Schemas.Count)
@@ -519,8 +503,10 @@ public class JsonSchema : IBaseDocument
 					i += segmentsConsumed;
 					break;
 				case JsonSchema { _keywords: not null } schema:
-					schema._keywords.TryGetValue(segment.Value, out var k);
-					newResolvable = k;
+					schema._keywords.TryGetValue(segment.Value, out var keyword);
+					newResolvable = keyword is ISchemaContainer { Schema: not null } kcontainer
+						? kcontainer.Schema
+						: keyword;
 					break;
 			}
 
```

Alternative:

```diff
diff --git a/JsonSchema/JsonSchema.cs b/JsonSchema/JsonSchema.cs
index ba330279..9513b5d3 100644
--- a/JsonSchema/JsonSchema.cs
+++ b/JsonSchema/JsonSchema.cs
@@ -538,7 +538,12 @@ public class JsonSchema : IBaseDocument
 			resolvable = newResolvable!;
 		}
 
-		return resolvable as JsonSchema;
+		return resolvable switch
+		{
+			JsonSchema schema => schema,
+			ISchemaContainer container => container.Schema,
+			_ => null
+		};
 	}
 
 	/// <summary>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the report.

While I agree that this should return the desired subschema, I'm curious why you're using a pointer to get to this subschema.  Getting a subschema under a keyword like `additionalProperties` (or anythings other than `$defs` is generally an anti-pattern.

`$defs` was created with the specific purpose of [schema reuse](https://json-schema.org/draft/2020-12/json-schema-core.html#name-schema-re-use-with-defs).  The specification _expects_ that subschemas you intend to reuse are moved to `$defs` and referenced (e.g. using `$ref`).

---

I'll set this up in a test and work on it.  I'm not sure about your changes.  I assume you've tested them, but it breaks the flow of that method.

**Comment by gregsdennis** [comment]
The `JsonNodeBaseDocument` approach works, but it does have the downside that it:

- serializes the schema to a string
- parses that string into `JsonNode`
- evaluates the pointer to obtain the target
- serializes the target back to a string
- deserializes that string into `JsonSchema`

That's a lot of processing that can be avoided by simply navigating the `JsonSchema` model, especially when most of the time, the target isn't going to be in an unrecognized keyword, so it'll already be deserialized as a `JsonSchema`.

---

I'm including this in the PR linked above, which is going to release a first draft at code generation in order to support my new OpenAPI implementation [Graeae](https://github.com/gregsdennis/Graeae).  That PR also has some changes I'll need to make to the base _JsonSchema.Net_ library, so it makes sense to just release it all at once.

**Comment by Splamy** [comment]
Much appreciated, thanks.
