### ISSUE TITLE
"[]".AsJsonElement() will not return as array. It will return as a string

### ISSUE THREAD

**Issue by NanFengCheong** [gregsdennis/json-everything#51]
**Describe the bug**
"[]".AsJsonElement() will not return as array. It will return as a string;

**To Reproduce**
"[]".AsJsonElement()  !=   JsonDocument.Parse("[]").RootElement

**Expected behavior**
It should be a json array

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
- .Net Target (Fwk 4.8, Core 3.x, etc.) 5.x

**Comment by gregsdennis** [comment]
That's because you're giving the method a string.  This method and it's overrides take objects and give the `JsonElement` equivalent.

To get an empty array, use `new JsonElement[].ToJsonElement()`.  This will give a single element containing an empty JSON array.

**Comment by NanFengCheong** [comment]
Got it. Thanks.
