### ISSUE TITLE
Undefined != Undefined in JSON equality comparisons

### ISSUE THREAD

**Issue by scharnyw** [gregsdennis/json-everything#510]
### Nuget Package

Json.More.Net

### Package Version

1.8.0

### What's your question?

I'm quite surprised to find the following:

    var undefined = default(JsonElement);
    var equals = undefined.IsEquivalentTo(undefined); // false

i.e. equality for `JsonElement` is not reflexive for `JsonValueKind.Undefined`;

Apparently this is done on purpose [here](https://github.com/gregsdennis/json-everything/blob/master/Json.More/JsonElementExtensions.cs#L46).

This does not agree with behavior in JavaScript where undefined is equal to itself (with both loose (==) and strict (===) equality), and in general non-reflexive equality is not expected except for a few well-established cases such as NaN and SQL NULL. May I know what's the rationale for implementing this behavior for undefined JSON?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
`JsonValueKind.Undefined` is not the same concept as JavaScript's `undefined` constant.  Rather it's just a placeholder for the default value of the enum, which is a common practice.  Just Google "use undefined for enum default," and you'll get a bunch of articles explaining why the default value for enums shouldn't be a valid value.

`JsonElement` is a strict, so the default value needs something for it's kind.  That is `Undefined`.  It's just a placeholder that says there isn't a value.  `default(JsonElement)` is an invalid state for that type.

**Comment by scharnyw** [comment]
Thanks for the quick reply.

Yes I'm aware that the JavaScript undefined is not part of JSON. My point is that the JavaScript undefined and a `JsonElement` with `JsonValueKind.Undefined` are similar in meaning (i.e. the value does not exist). Put it another way, had `JsonElement` been defined as a reference type, then I would fully expect `(JsonElement)null` to compare equal to itself. I see little reason why things should be different just because `JsonElement` is a value type (in any case it's a value type primarily because of performance concerns, not that people really want it to have value type semantics. It's more like an unwanted side effect IMO).

Just my two cents, although I do see your point that `JsonValueKind.Undefined` does not represent valid JSON so you would like to exclude it from equality comparisons. Feel free to close this issue and thanks for taking time to reply :)

**Comment by gregsdennis** [comment]
> My point is that the JavaScript undefined and a JsonElement with JsonValueKind.Undefined are similar in meaning (i.e. the value does not exist).

I'm not sure I agree with this assessment.  `JsonValueKind.Undefined` is a placeholder that's included because having a default that is an actual value kind is incorrect design for enums in general (not just for JSON).

Even so, I checked quickly on dotnetfiddle, and it seems that `.Equals()` does indeed return true for the default value compared against itself.

I'll need to think on this some more, and maybe poke the .Net team.

You're right in that I currently return false because it's an invalid state.

**Comment by gregsdennis** [comment]
Here's an older but still relevant discussion on `JsonElement` and equality.

https://github.com/dotnet/runtime/issues/62585

**Comment by gregsdennis** [comment]
The purpose of `.IsEquivalentTo()` is to assess JSON deep-equality.  Given then nature of the default value of `JsonElement` having a type of `Undefined` and it being inherently a different concept from the JavaScript `undefined` literal, I think the current implementation is most correct.
