### ISSUE TITLE
Property with type IList<JsonNode> causing exception

### ISSUE THREAD

**Issue by ashek-simeon** [gregsdennis/json-everything#512]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.3.1

### Operating System

Mac

### .Net Target (if relevant, please specify the version in the description)

.Net Framework

### A clear and concise description of the bug

I think I am experiencing a variant of [this issue](https://github.com/gregsdennis/json-everything/issues/274), which was fixed by [this PR](https://github.com/gregsdennis/json-everything/pull/275), except with JsonNode.

Locally, I've applied a fix similar to the fix in the above PR for JsonObject, except for JsonNode, and it seems to solve the issue.

### Please add test code or steps to reproduce the behavior

Run JsonSchemaBuilderExtensions.FromType on a type with a property that has a type of `IList<JsonNode>`.

See the following exception:

"System.ArgumentException: An item with the same key has already been added. Key: Item"

### What did you expect?

No exception is thrown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the report.  I'll work up a test to see if I can replicate this behavior.

**Comment by gregsdennis** [comment]
Yeah, it looks like the fix is just creating another generator for `JsonNode` that just generates the `true` schema (which validates all values).

Unfortunately, I don't have a mechanism for returning a boolean schema.  I'll need to see if I can work that in.  Until then, this will return the equivalen "empty" schema `{}`.

**Comment by gregsdennis** [comment]
Scratch that... it just works!  I must have accounted for zero intents means `true` schema.

```json
{
  "type": "object",
  "properties": {
    "Foo": {
      "type": "array",
      "items": true
    }
  }
}
```

I should have this out shortly.

**Comment by ashek-simeon** [comment]
Thank you so much for implementing the fix, and for this very useful package!
