### ISSUE TITLE
Unable to create JsonSchema with multiple UnrecognizedKeywords via JsonSchemaBuilder

### ISSUE THREAD

**Issue by mdekrey** [gregsdennis/json-everything#516]
### Nuget Package

JsonSchema.Net

### Package Version

5.2.0

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug

When using JsonSchemaBuilder, multiple UnrecognizedKeywords may be added. However, upon attempting to `Build()`, the keyword `Type`s are checked instead of using `KeywordExtensions.Keyword`

### Please add test code or steps to reproduce the behavior

```
var builder = new JsonSchemaBuilder();
builder.Add(new UnrecognizedKeyword("foo", null));
builder.Add(new UnrecognizedKeyword("bar", null));
builder.Build();
```

### What did you expect?

I expected the `JsonSchemaBuilder` to support the same structures as could be created via Deserialization, or that the constructors of `JsonSchema` used by the `JsonSchemaBuilder` would be available publicly from the library..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.  This is a pretty simple fix.

**Comment by mdekrey** [comment]
Thanks for implementing it so quickly - I expected a chance to write a PR for this this morning, too! 😁
