### ISSUE TITLE
JsonException line numbers do not indicate where issue occurred when deserializing JsonSchema

### ISSUE THREAD

**Issue by mdekrey** [gregsdennis/json-everything#517]
### Nuget Package

Json.More.Net

### Package Version

5.2.0

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug

When deserializing Jsonschema, line numbers always indicate the start of the JsonSchema.

### Please add test code or steps to reproduce the behavior

See https://github.com/mdekrey/json-everything/blob/test/json-line-numbers/JsonSchema.Tests/GithubTests.cs#L880-L894
```
	[Test]
	public void IssueTBD_IncorrectJsonExceptionpointer()
	{

		var schemaStr = @"{
  ""$schema"": ""https://json-schema.org/draft/2020-12/schema"",
  ""required"": [ { ""abc"": null } ]
  ""properties"": {
      ""abc"": { ""$ref"": ""mySchema.json"" }
  },
  ""additionalProperties"": false
}";
		var exception = Assert.Throws<JsonException>(() => JsonSerializer.Deserialize<JsonSchema>(schemaStr));
		Assert.IsNotNull(exception);
		Assert.AreEqual(2L, exception?.LineNumber);
	}
```

### What did you expect?

`LineNumber` and `BytePositionInLine` should correspond to the position of the error.

### Is there any other information you'd like to share regarding this bug?

According to https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-7-0, the correct way to write a `JsonConverter` uses `JsonSerializerOptions.GetConverter` to get appropriate converter types. By using `JsonSerializer.Deserialize`, the line numbers are stripped.

Converting to `JsonSerializerOptions.GetConverter` solves this issue.

I'm able to provide a PR to resolve this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
TIL.  Thanks.

**Comment by mdekrey** [comment]
I'll keep this one as tight as I can. A couple notes as I work on it:
- There is no non-generic version of `JsonConverter` that can access the `Read` function. The only mechanism I found to invoke this was through an additional generic class that has an interface on it. I feel like there's a more efficient way, but I do not know it.
- I'll add an internal JsonSerializerOptionsExtensions to make this change as surgical as possible.

Let me know if you have any other suggestions!

**Comment by gregsdennis** [comment]
> There is no non-generic version of JsonConverter that can access the Read function.

This is what I ran into immediately, and I figured I'd let you try.

If you can, please run the benchmark before and after.  (It just runs the test suite.)  I'd like to get a sense of the performance difference here.

**Comment by mdekrey** [comment]
I'm not familiar enough with BenchmarkDotNet to know what I'm looking for, but I don't see significant changes; the new method drops by about 2% for its mean run time, but itermittently shows Gen2 GC.

Old method:
```
|          Method |  n |       Mean |    Error |   StdDev |        Gen0 |       Gen1 | Allocated |
|---------------- |--- |-----------:|---------:|---------:|------------:|-----------:|----------:|
| RunSuite_Legacy |  1 |   930.0 ms | 11.49 ms | 10.75 ms |  33000.0000 | 16000.0000 | 145.05 MB |
| RunSuite_Legacy | 10 | 2,967.0 ms | 11.81 ms | 10.47 ms | 244000.0000 | 49000.0000 | 976.59 MB |
```

New method (when Gen2 is picked up):
````
|          Method |  n |       Mean |    Error |   StdDev |        Gen0 |       Gen1 |      Gen2 | Allocated |
|---------------- |--- |-----------:|---------:|---------:|------------:|-----------:|----------:|----------:|
| RunSuite_Legacy |  1 |   915.2 ms |  6.09 ms |  5.69 ms |  34000.0000 | 17000.0000 |         - | 143.83 MB |
| RunSuite_Legacy | 10 | 2,946.6 ms | 14.43 ms | 13.50 ms | 244000.0000 | 48000.0000 | 1000.0000 | 974.11 MB |
```

I can think of another solution that would avoid reflection/allocation during deserialization: use a registration entry object in the `SchemaKeywordRegistry` when a keyword is registered. 

It may also be nice to override the keywords in a particular `SchemaJsonConverter` to reflect the dialect for a particular schema, which may be necessary if two different vocabularies use the same "keyword" but different parsing rules. Some things I'm not able to test via JsonSchema deserialization because they aren't in the global keyword registry by default.

**Comment by gregsdennis** [comment]
Just looking for that report, perfect.  Looks like a minor perf improvement as well.

> I can think of another solution that would avoid reflection/allocation during deserialization: use a registration entry object in the SchemaKeywordRegistry when a keyword is registered.

I'm happy to look at this separately if you like.
