### ISSUE TITLE
Evaluation errors from if statements

### ISSUE THREAD

**Issue by m-adamkiewicz** [gregsdennis/json-everything#520]
### Nuget Package

JsonSchema.Net

### Package Version

5.2.2

### What's your question?

I'm wondering if it was intended to consider `if` condition that are not met as errors but instance is still considered as valid. 

As we retrieve all errors from `EvaluationResults` it leads to misleading messages as instead of one error from property we are getting errors from property and all preceding statements.

Is there any way to exclude these errors from `EvaluationResults`?

Example:

Schema:
```
{
  "type": "object",
  "properties": {
    "Foo": {
      "type": "string"
    }
  },
  "if": {"properties": {"Foo": {"const": "0"}}},
  "else": {
      "type": "object",
      "properties": {
        "Bar": {
          "type": "string",
          "maxLength": 1
        }
      },
      "required": ["Bar"]
  },
  "required": ["Foo"]
}
```

Instance:
```
{
  "Foo": "1",
  "Bar": "1"
}
```

Evaluation result:
```
{
  "valid": true,
  "details": [
   ...
    {
      "valid": false,
      "evaluationPath": "/if/properties/Foo",
      "schemaLocation": "https://json-everything.net/b58a2924bb#/if/properties/Foo",
      "instanceLocation": "/Foo",
      "errors": {
        "const": "Expected \"\\\"0\\\"\""
      }
    },
    ...
  ]
}
``` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
This is indeed intended behavior. Including these results is important for identifying why evaluation went into the `else`.

If you want to exclude them, filtering out errors which have `if` in the `evaluationPath` property would be a pretty basic approach.
