### ISSUE TITLE
Error in JsonPath.TryParse

### ISSUE THREAD

**Issue by Andrej-Peplinski** [gregsdennis/json-everything#525]
### Nuget Package

JsonPath.Net

### Package Version

0.6.6

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug

JsonPath.TryParse("$['a', 'b']", out _); //Returns false
JsonPath.Parse("$['a', 'b']"); //Returns a valid path

### Please add test code or steps to reproduce the behavior

var willBeFalse = JsonPath.TryParse("$['a', 'b']", out var willBeNull);
var validPath = JsonPath.Parse("$['a', 'b']");

### What did you expect?

TryParse should return TRUE and a valid path object as out-parameter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'm not sure how this got past my testing.  All of the tests run both `.Parse()` and `.TryParse()` and if either fail, the test fails.

I'll have a look.

**Comment by gregsdennis** [comment]
Hm... looks like my testing only checks both if it's an invalid selector. 🤦  I'll update the test runner and push a new package.

**Comment by Andrej-Peplinski** [comment]
Thanks a lot for the very fast response time 🌞
