### ISSUE TITLE
Q. Is there a way of schema validating during using Utf8JsonReader?

### ISSUE THREAD

**Issue by AntoineLarine** [gregsdennis/json-everything#533]
Does your excellent library provide a way for validating JSON schema during reading with Utf8JsonReader? Is it possible to evaluate a schema accordance during forward-only reading of a source document?

**Comment by gregsdennis** [comment]
I have a converter factory that you can use to [validate during serialization](https://docs.json-everything.net/schema/serialization).  However, streaming validation isn't supported.  The converters still need to read the entire JSON content in order to validate it.

**Comment by gregsdennis** [comment]
@AntoineLarine does this answer your question?

**Comment by AntoineLarine** [comment]
Yes, surely.
