### ISSUE TITLE
OpenAPI Evaluation lib

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#538]
I've created a library for evaluating HTTP request and response messages according to an OpenAPI 3.1 spec. It uses JsonSchema.NET for JSON instance evaluation. Have a look, I'd love some feedback!
https://github.com/Fresa/OpenAPI.Evaluation
https://github.com/Fresa/OpenAPI.Evaluation.AspNet

**Comment by gregsdennis** [comment]
@Fresa have you seen [Graeae](https://github.com/gregsdennis/Graeae)?

I'll have a look at yours.  Thanks for mentioning it!

**Comment by Fresa** [comment]
I have glanced at it, but I haven't tried it. I should :)

I've extended the Json Schema output format to include request and response evaluation path and introduced parameter value parsers to support parameter evaluation, those might be the most interesting parts, I've written an article about it here https://blog.fkan.se/net/openapi-evaluation/
