### ISSUE TITLE
Issue with online validator

### ISSUE THREAD

**Issue by alpharder** [gregsdennis/json-everything#541]
### Nuget Package

JsonSchema.Net

### Package Version

5.2.6

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

https://json-everything.net/json-schema/ marks valid document as invalid

### What did you expect?

https://json-everything.net/json-schema/ to function properly

### Please add test code or steps to reproduce the behavior.

Given the following schema:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$id": "https://example.com/websolver-object-definition/v1/object-definition-schema.json",

  "title": "Meta-schema for validating user-defined object schemas",

  "$dynamicAnchor": "object-definition-schema",

  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },

  "type": "object",

  "properties": {
    "$schema": {
      "const": "https://example.com/websolver-object-definition/v1/object-definition-schema.json"
    },
    "type": {
      "const": "object"
    },
    "properties": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/safeObjectProperty" },
      "default": {}
    },
    "additionalProperties": {
      "const": false
    },
    "unevaluatedProperties": {
      "const": false
    }
  },

  "required": ["type", "properties", "additionalProperties", "unevaluatedProperties"],

  "$defs": {
    "safeObjectProperty": {
      "allOf": [
        {"$ref": "https://json-schema.org/draft/2020-12/meta/applicator"},
        {"$ref": "https://json-schema.org/draft/2020-12/meta/unevaluated"},
        {"$ref": "https://json-schema.org/draft/2020-12/meta/validation"},
        {"$ref": "https://json-schema.org/draft/2020-12/meta/meta-data"},
        {"$ref": "https://json-schema.org/draft/2020-12/meta/format-annotation"},
        {"$ref": "https://json-schema.org/draft/2020-12/meta/content"},
        {
          "required": ["type"],
          "if": {
            "properties": {
              "type": {
                "const": "object"
              }
            }
          },
          "then": {
            "$dynamicRef": "#object-definition-schema"
          }
        }
      ]
    }
  },

  "additionalProperties": false,
  "unevaluatedProperties": false
}
```

This document is marked as invalid:
```json
{
  "$schema": "https://example.com/websolver-object-definition/v1/object-definition-schema.json",
  "type": "object",
  "additionalProperties": false,
  "unevaluatedProperties": false,
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "object",
      "additionalProperties": false,
      "unevaluatedProperties": false,
      "properties": {
        
      }
    }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the report @alpharder.  You mention that is not working in the online validator. Does it work in code?

**Comment by alpharder** [comment]
> Thanks for the report @alpharder. You mention that is not working in the online validator. Does it work in code?

My pleasure!
Unfortunately I had no opportunity in verifying this behavior in code since I'm not a .NET developer and was just using online validator as one of reference implementations.

The only piece of extra information I have is that https://json-schema.hyperjump.io/ seem to correctly handle the same combination of schema and validated JSON document.

**Comment by gregsdennis** [comment]
I've just now pasted that schema and instance into the site, and it comes back as valid.

{
  "valid": true,
  "evaluationPath": "",
  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#",
  "instanceLocation": "",
  "annotations": {
    "title": "Meta-schema for validating user-defined object schemas",
    "properties": [
      "$schema",
      "type",
      "properties",
      "additionalProperties",
      "unevaluatedProperties"
    ],
    "additionalProperties": []
  },
  "details": [
    {
      "valid": true,
      "evaluationPath": "/properties/$schema",
      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/$schema",
      "instanceLocation": "/$schema"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/type",
      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/type",
      "instanceLocation": "/type"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/properties",
      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/properties",
      "instanceLocation": "/properties",
      "annotations": {
        "default": {},
        "additionalProperties": [
          "foo",
          "bar"
        ]
      },
      "details": [
        {
          "valid": true,
          "evaluationPath": "/properties/properties/additionalProperties",
          "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/properties/additionalProperties",
          "instanceLocation": "/properties/foo",
          "details": [
            {
              "valid": true,
              "evaluationPath": "/properties/properties/additionalProperties/$ref",
              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/$defs/safeObjectProperty",
              "instanceLocation": "/properties/foo",
              "details": [
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/0",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/applicator#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Applicator vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/1",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/unevaluated#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Unevaluated applicator vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/2",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Validation vocabulary meta-schema",
                        "properties": [
                          "type"
                        ]
                      },
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type",
                          "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type",
                          "instanceLocation": "/properties/foo/type",
                          "details": [
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/0",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type/anyOf/0",
                              "instanceLocation": "/properties/foo/type",
                              "details": [
                                {
                                  "valid": true,
                                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/0/$ref",
                                  "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/$defs/simpleTypes",
                                  "instanceLocation": "/properties/foo/type"
                                }
                              ]
                            },
                            {
                              "valid": false,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/1",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type/anyOf/1",
                              "instanceLocation": "/properties/foo/type",
                              "errors": {
                                "type": "Value is \"string\" but should be \"array\""
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/3",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/3",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/3/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/meta-data#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Meta-data vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/4",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/4",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/4/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/format-annotation#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Format vocabulary meta-schema for annotation results",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/5",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/5",
                  "instanceLocation": "/properties/foo",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/5/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/content#",
                      "instanceLocation": "/properties/foo",
                      "annotations": {
                        "title": "Content vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6",
                  "instanceLocation": "/properties/foo",
                  "annotations": {
                    "if": false
                  },
                  "details": [
                    {
                      "valid": false,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/if",
                      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6/if",
                      "instanceLocation": "/properties/foo",
                      "details": [
                        {
                          "valid": false,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/if/properties/type",
                          "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6/if/properties/type",
                          "instanceLocation": "/properties/foo/type",
                          "errors": {
                            "const": "Expected \"\\\"object\\\"\""
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "valid": true,
          "evaluationPath": "/properties/properties/additionalProperties",
          "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/properties/additionalProperties",
          "instanceLocation": "/properties/bar",
          "details": [
            {
              "valid": true,
              "evaluationPath": "/properties/properties/additionalProperties/$ref",
              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/$defs/safeObjectProperty",
              "instanceLocation": "/properties/bar",
              "details": [
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/0",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/applicator#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Applicator vocabulary meta-schema",
                        "properties": [
                          "additionalProperties",
                          "properties"
                        ]
                      },
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0/$ref/properties/additionalProperties",
                          "schemaLocation": "https://json-schema.org/draft/2020-12/meta/applicator#/properties/additionalProperties",
                          "instanceLocation": "/properties/bar/additionalProperties",
                          "details": [
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0/$ref/properties/additionalProperties/$dynamicRef/$dynamicRef",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/applicator#",
                              "instanceLocation": "/properties/bar/additionalProperties",
                              "annotations": {
                                "title": "Applicator vocabulary meta-schema",
                                "properties": []
                              }
                            }
                          ]
                        },
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/0/$ref/properties/properties",
                          "schemaLocation": "https://json-schema.org/draft/2020-12/meta/applicator#/properties/properties",
                          "instanceLocation": "/properties/bar/properties",
                          "annotations": {
                            "default": {},
                            "additionalProperties": []
                          }
                        }
                      ]
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/1",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/unevaluated#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Unevaluated applicator vocabulary meta-schema",
                        "properties": [
                          "unevaluatedProperties"
                        ]
                      },
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1/$ref/properties/unevaluatedProperties",
                          "schemaLocation": "https://json-schema.org/draft/2020-12/meta/unevaluated#/properties/unevaluatedProperties",
                          "instanceLocation": "/properties/bar/unevaluatedProperties",
                          "details": [
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/1/$ref/properties/unevaluatedProperties/$dynamicRef/$dynamicRef",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/unevaluated#",
                              "instanceLocation": "/properties/bar/unevaluatedProperties",
                              "annotations": {
                                "title": "Unevaluated applicator vocabulary meta-schema",
                                "properties": []
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/2",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Validation vocabulary meta-schema",
                        "properties": [
                          "type"
                        ]
                      },
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type",
                          "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type",
                          "instanceLocation": "/properties/bar/type",
                          "details": [
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/0",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type/anyOf/0",
                              "instanceLocation": "/properties/bar/type",
                              "details": [
                                {
                                  "valid": true,
                                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/0/$ref",
                                  "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/$defs/simpleTypes",
                                  "instanceLocation": "/properties/bar/type"
                                }
                              ]
                            },
                            {
                              "valid": false,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/2/$ref/properties/type/anyOf/1",
                              "schemaLocation": "https://json-schema.org/draft/2020-12/meta/validation#/properties/type/anyOf/1",
                              "instanceLocation": "/properties/bar/type",
                              "errors": {
                                "type": "Value is \"string\" but should be \"array\""
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/3",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/3",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/3/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/meta-data#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Meta-data vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/4",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/4",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/4/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/format-annotation#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Format vocabulary meta-schema for annotation results",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/5",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/5",
                  "instanceLocation": "/properties/bar",
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/5/$ref",
                      "schemaLocation": "https://json-schema.org/draft/2020-12/meta/content#",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "title": "Content vocabulary meta-schema",
                        "properties": []
                      }
                    }
                  ]
                },
                {
                  "valid": true,
                  "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6",
                  "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6",
                  "instanceLocation": "/properties/bar",
                  "annotations": {
                    "if": true
                  },
                  "details": [
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/if",
                      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6/if",
                      "instanceLocation": "/properties/bar",
                      "annotations": {
                        "properties": [
                          "type"
                        ]
                      },
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/if/properties/type",
                          "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6/if/properties/type",
                          "instanceLocation": "/properties/bar/type"
                        }
                      ]
                    },
                    {
                      "valid": true,
                      "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then",
                      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/allOf/6/then",
                      "instanceLocation": "/properties/bar",
                      "details": [
                        {
                          "valid": true,
                          "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then/$dynamicRef/$dynamicRef",
                          "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#",
                          "instanceLocation": "/properties/bar",
                          "annotations": {
                            "title": "Meta-schema for validating user-defined object schemas",
                            "properties": [
                              "type",
                              "properties",
                              "additionalProperties",
                              "unevaluatedProperties"
                            ],
                            "additionalProperties": []
                          },
                          "details": [
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then/$dynamicRef/$dynamicRef/properties/type",
                              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/type",
                              "instanceLocation": "/properties/bar/type"
                            },
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then/$dynamicRef/$dynamicRef/properties/properties",
                              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/properties",
                              "instanceLocation": "/properties/bar/properties",
                              "annotations": {
                                "default": {},
                                "additionalProperties": []
                              }
                            },
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then/$dynamicRef/$dynamicRef/properties/additionalProperties",
                              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/additionalProperties",
                              "instanceLocation": "/properties/bar/additionalProperties"
                            },
                            {
                              "valid": true,
                              "evaluationPath": "/properties/properties/additionalProperties/$ref/allOf/6/then/$dynamicRef/$dynamicRef/properties/unevaluatedProperties",
                              "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/unevaluatedProperties",
                              "instanceLocation": "/properties/bar/unevaluatedProperties"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "valid": true,
      "evaluationPath": "/properties/additionalProperties",
      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/additionalProperties",
      "instanceLocation": "/additionalProperties"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/unevaluatedProperties",
      "schemaLocation": "https://example.com/websolver-object-definition/v1/object-definition-schema.json#/properties/unevaluatedProperties",
      "instanceLocation": "/unevaluatedProperties"
    }
  ]
}

**Comment by gregsdennis** [comment]
I note that you have v4.1.8 listed.  Is that what's showing as the _JsonSchema.Net_ version in your browser?  It should be v5.2.6.

To make sure you're not getting a cached version (e.g. if you've used the site before), do a hard refresh (CTRL+SHIFT+R for chrome in windows, CMD+SHIFT+R on mac).

**Comment by alpharder** [comment]
> I've just now pasted that schema and instance into the site, and it comes back as valid.
> 
> Expand to see results

I've re-checked and can confirm it works as expected (`valid: true`, versus `valid: false` I was getting previously). 

Sorry for bothering and thanks for your quick response!

This was probably some problem with the website itself (maybe a mismatch between what's shown in editor and what's actually evaluated when "Run" is clicked), since I always have this at the page footer:

<img width="551" alt="Screenshot 2023-10-26 at 11 16 26 AM" src="https://github.com/gregsdennis/json-everything/assets/1678161/e9c27bd5-1246-407c-8467-e75937b846d1">

> I note that you have v4.1.8 listed. Is that what's showing as the JsonSchema.Net version in your browser? It should be v5.2.6.

It's 5.2.6, I've originally specified 5.26 in the issue description

**Comment by gregsdennis** [comment]
Hm... Not sure what the error is for you.  What browser are you running?

Glad the validation is working, though.

**Comment by alpharder** [comment]
> Hm... Not sure what the error is for you. What browser are you running?

Google Chrome, Version 117.0.5938.149 (Official Build) (arm64)

<img width="1072" alt="Screenshot 2023-10-26 at 11 26 45 AM" src="https://github.com/gregsdennis/json-everything/assets/1678161/7ee50c62-fb87-48e1-93dc-b831fed51e99">
 
> Glad the validation is working, though.

Yep, that's awesome. Feel free to close this issue at your discretion

**Comment by gregsdennis** [comment]
Hm, that's really weird.  That lib is needed for the schema generation functionality.  It's not going to affect validation at all, but generation will likely fail.

**Comment by alpharder** [comment]
Thank you for the awesome toolkit!
