### ISSUE TITLE
ObsoleteAttribute affects all properties of a given type, even if other properties aren't obsolete

### ISSUE THREAD

**Issue by filzrev** [gregsdennis/json-everything#544]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.4.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

I'm trying to generating JSON schema from C# models.
When C# model's contains proprties that are marked `[Obsolete]` and handled first.
Generated schema's `$def` definitions are mixed with non `[Obsolete]` properties.

### What did you expect?

Unique definitions are generated when C# models property contains `[Obsolete]` attribute.

### Please add test code or steps to reproduce the behavior.

**C# Code**
```csharp
void Main()
{
	var builder = new JsonSchemaBuilder();
	builder.FromType<SampleClass>();

	var schema = builder.Build();
	var schemaJson = JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true });
	Console.WriteLine(schemaJson);
}

public class SampleClass
{
	[Obsolete]
	public int AAA { get; set; }

	public int BBB { get; set; }
	
	[Obsolete("CCC is deprecated.")]
	public int CCC{get;set;}
}
```
**Results**
```json
{
  "type": "object",
  "properties": {
    "AAA": {
      "$ref": "#/$defs/integer"
    },
    "BBB": {
      "$ref": "#/$defs/integer" // **It should be non deprecated.**
    },
    "CCC": {
      "$ref": "#/$defs/integer"
    }
  },
  "$defs": {
    "integer": {
      "type": "integer",
      "deprecated": true
    }
  }
}
```

### Is there any other information you'd like to share regarding this bug?

This problem is not occurred when running above code with version `2.1.0`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting. I'll look into this.
