### ISSUE TITLE
Stackoverflow when deserializing more than one time with ValidatingJsonConverter

### ISSUE THREAD

**Issue by EmmyDream** [gregsdennis/json-everything#550]
### Nuget Package

JsonSchema.Net

### Package Version

5.3.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Usage of `ValidatingJsonConverter` throws stackoverflow after second usage. From my understanding `_optionsFactory` is not working correctly (`ValidatingJsonConverter` is not removed from options), when there is a usage of cache - converter has been already defined in cache.
![image](https://github.com/gregsdennis/json-everything/assets/149778746/f1a3cf6c-6ed6-46cb-829b-99f0e68648d9)

### What did you expect?

Not having stackoverflow.

### Please add test code or steps to reproduce the behavior.

I have followed instruction here https://docs.json-everything.net/schema/serialization/, how to use `ValidatingJsonConverter` with attribute on deserializing type.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting.  I'll have a look.

**Comment by gregsdennis** [comment]
I've added this test which runs deserialization 10 times repeatedly.  It passes.

```c#
[Test]
public void WithSchema_MultipleDeserializations()
{
    try
    {
        var jsonText = @"{
  ""Bar"": ""bartholomew"",
  ""Value"": 42
}";

        for (int i = 0; i < 10; i++)
        {
            var model = JsonSerializer.Deserialize<FooWithSchema>(jsonText, _options);

            Console.WriteLine(JsonSerializer.Serialize(model, _options));
        }
    }
    catch (Exception e)
    {
        HandleException(e);
        throw;
    }
}
```

Can you provide a replicating test, please?

**Comment by EmmyDream** [comment]
Hello, thank you for your test. Please update is as follow:
```
    [Test]
    public void WithSchema_MultipleDeserializations()
    {
        try
        {
            var jsonText = @"{
  ""Bar"": ""bartholomew"",
  ""Value"": 42
}";
            
            for (int i = 0; i < 10; i++)
            {
                var options = new JsonSerializerOptions
                {
                    WriteIndented = true,
                    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                    Converters = { new ValidatingJsonConverter { OutputFormat = OutputFormat.List } }
                };
                
                var model = JsonSerializer.Deserialize<FooWithSchema>(jsonText, options);

                Console.WriteLine(JsonSerializer.Serialize(model, options));
            }
        }
        catch (Exception e)
        {
            HandleException(e);
            throw;
        }
    }
```

**Comment by gregsdennis** [comment]
Interesting.  You're generating new options objects for each iteration?  Why not create a static one and re-use that?

(I'll fix this, obviously, but it's still worth asking the question.)

**Comment by EmmyDream** [comment]
> Interesting. You're generating new options objects for each iteration? Why not create a static one and re-use that?
> 
> (I'll fix this, obviously, but it's still worth asking the question.)

For example, lets consider some scope service like this:

   ```
 private class FooService
    {
        private readonly JsonSerializerOptions _fooOptions = new JsonSerializerOptions
        {
            WriteIndented = true,
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            Converters = { new ValidatingJsonConverter { OutputFormat = OutputFormat.List } }
        };
        
        public FooWithSchema DeserializeFoo(string jsonText)
        {
            return JsonSerializer.Deserialize<FooWithSchema>(jsonText, _fooOptions);

        }
    }
```

And test method:

```
    [Test]
    public void WithSchema_MultipleDeserializations()
    {
        try
        {
            var jsonText = @"{
  ""Bar"": ""bartholomew"",
  ""Value"": 42
}";
            
            for (int i = 0; i < 10; i++)
            {
                var model = new FooService().DeserializeFoo(jsonText);
                Console.WriteLine(JsonSerializer.Serialize(model, _options));
            }
        }
        catch (Exception e)
        {
            HandleException(e);
            throw;
        }
    }
```

In my case I have common implementation of deserialization service, which allows to provide different `JsonSerializerOptions`, so that is why these `options` are coming from outside implementation and can be created each time when I call common service.

Anyway thank you for a quick fix! I will test it
