### ISSUE TITLE
MinItems and MaxItems attributes generates invalid schema inside array type items of strings

### ISSUE THREAD

**Issue by domchlouba** [gregsdennis/json-everything#551]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.4.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

According to the specification and the description on the package page, the MaxItems and MinItems attributes are valid for an array (or collection of items). However, when generating a schema for a class containing a list of strings with MinItems and MaxItems attributes, these keywords are also part of the items object in the schema.

### What did you expect?

I would expect the following result, i.e. that minItems and maxItems are listed only in the object describing the array type and the object in the items property no longer contains these keywords.

## Expected result of generator

```json
{
  "type": "object",
  "properties": {
    "Items": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "maxItems": 2
    }
  }
}
```

## Model

```csharp
public class Item
{
    [MinItems(0)]
    [MaxItems(2)]
    public List<string> Items { get; set; }
}
```
## Execution
```csharp
var schema = new JsonSchemaBuilder().FromType<Item>().Build();

Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(schema, new JsonSerializerOptions() { WriteIndented = true }));
```

## Result of generator

```json
{
  "type": "object",
  "properties": {
    "Items": {
      "type": "array",
      "items": {
        "type": "string",
        "minItems": 0,
        "maxItems": 2
      },
      "minItems": 0,
      "maxItems": 2
    }
  }
}
```

### Is there any other information you'd like to share regarding this bug?

During my debugging I came across the following condition inside MaxItemsAttribute (and MinItemsAttribute) in AddConstraints method:

```csharp
if (!context.Type.IsArray()) return;
```

The extension method itself has the following implementation:

```csharp
public static bool IsArray(this Type type)
{
	return type.IsArray ||
		   type == typeof(Array) ||
		   typeof(IEnumerable).IsAssignableFrom(type);
}
```

However, the string type also satisfies the condition **typeof(IEnumerable).IsAssignableFrom(type)**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Strictly speaking, what's returned is a valid schema; those extra keywords just aren't doing anything.

I'll have a look.
