### ISSUE TITLE
JsonPointer does not support index from a variable

### ISSUE THREAD

**Issue by OmiCron07** [gregsdennis/json-everything#555]
### Nuget Package

JsonPointer.Net

### Package Version

3.1.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

JsonPointer does in fact accept to convert a lamba expression when using a fixed index, but fails when using a variable.

Works:
`x => x.ApplicationList.Applications[42]`

Does not works:
`x => x.ApplicationList.Applications[applicationIndex]`

### What did you expect?

The value of the variable should be used instead of the namespace.

### Please add test code or steps to reproduce the behavior.

```csharp
int index = 42;
var pointer = JsonPointer.Create(x => x.ApplicationList.Applications[index]);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
This isn't a bug. It's simply not coded for.  Relabeling as an enhancement.

**Comment by OmiCron07** [comment]
How many times are you using hardcoded indexes ? Probably never and that makes the lambda expression overload totally useless, is it ?

**Comment by gregsdennis** [comment]
I'm not arguing the feature's usefulness. I'm just saying it's not a feature currently.

A bug is feature that isn't working.  This just isn't a feature.
