### ISSUE TITLE
Valid `ValidationResults` has detail with error [when usage of `const` in `if` statement]

### ISSUE THREAD

**Issue by EmmyDream** [gregsdennis/json-everything#556]
### Nuget Package

JsonSchema.Net

### Package Version

5.3.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Background: I wanted to provide to a user full description of what is invalid/what is inconsitent in file provided to JSON schema validation. I had to extract all errors from validation results, when validation has failed. During testing I discovered issue with usage of `const` in `if` statements. Usage of it produced an error, but it should not.

### What did you expect?

If validation is successful (flag `IsValid` is true) then all `ValidationResults` should have empty error's list.
If validation failed then list of extracted error's from all details should contain only errors which caused a failure.

### Please add test code or steps to reproduce the behavior.

I extended an objects and schema in `DeserializationTests` like this:
```
private class Foo
{
        [MinLength(5)]
        public string? Bar { get; set; }
        [Range(40, int.MaxValue)]
        [Required]
        public int Value { get; set; }
        [Required]
        public bool IsMultipleNewValue { get; set; }
        public string? NewValue { get; set; }
        public List<string>? NewValues { get; set; }
}

[JsonSchema(typeof(DeserializationTests), nameof(FooSchema))]
private class FooWithSchema
{
        public string? Bar { get; set; }
        public int Value { get; set; }
        public bool IsMultipleNewValue { get; set; }
        public string? NewValue { get; set; }
        public List<string>? NewValues { get; set; }
}

public static readonly JsonSchema FooSchema =
        new JsonSchemaBuilder()
	        .Type(SchemaValueType.Object)
	        .Properties(
		        (nameof(Foo.Bar), new JsonSchemaBuilder()
			        .Type(SchemaValueType.String | SchemaValueType.Null)
			        .MinLength(5)
		        ),
		        (nameof(Foo.Value), new JsonSchemaBuilder()
			        .Type(SchemaValueType.Integer)
			        .Minimum(40)
		        ),
		        (nameof(Foo.IsMultipleNewValue), new JsonSchemaBuilder()
			        .Type(SchemaValueType.Boolean)
		        ),
		        (nameof(Foo.NewValue), new JsonSchemaBuilder()
			        .Type(SchemaValueType.String, SchemaValueType.Null)
		        ),
		        (nameof(Foo.NewValues), new JsonSchemaBuilder()
			        .Type(SchemaValueType.Array, SchemaValueType.Null)
		        )
	        )
	        .Required(nameof(Foo.Value), nameof(Foo.IsMultipleNewValue))
	        .If(new JsonSchemaBuilder()
		        .Properties((nameof(Foo.IsMultipleNewValue), new JsonSchemaBuilder().Const(true))))
	        .Then(new JsonSchemaBuilder()
		        .Properties(
			        (nameof(Foo.NewValues), new JsonSchemaBuilder()
				        .Type(SchemaValueType.Array)),
			        (nameof(Foo.NewValue), new JsonSchemaBuilder()
				        .Type(SchemaValueType.Null))))
	        .Else(new JsonSchemaBuilder()
		        .Properties(
			        (nameof(Foo.NewValues), new JsonSchemaBuilder()
				        .Type(SchemaValueType.Null)),
			        (nameof(Foo.NewValue), new JsonSchemaBuilder()
				        .Type(SchemaValueType.String, SchemaValueType.Null))));
```
And added two test cases:

```
	/// <summary>
	/// validation result should not contain any detail with error when validation succeed
	/// </summary>
	[Test]
	public void WithSchema_AndIfCondition_Pass()
	{
		var jsonText = @"{
  ""Bar"": ""bartholomew"",
  ""Value"": 42,
""IsMultipleNewValue"": false,
""NewValues"": null,
""NewValue"": null
}";

		var validationResult = FooSchema.Evaluate(JsonNode.Parse(jsonText), new EvaluationOptions() { OutputFormat = OutputFormat.List, RequireFormatValidation = true });

		var errors = validationResult.Details.Where(detail => detail.HasErrors);
		Assert.IsEmpty(errors);
	}
	
	/// <summary>
	/// validation result should contain only one error - missing required field "Value"
	/// </summary>
	[Test]
	public void WithSchema_AndIfCondition_FailWithOneError()
	{
		var jsonText = @"{
  ""Bar"": ""bartholomew"",
""IsMultipleNewValue"": false,
""NewValues"": null,
""NewValue"": null
}";

		var validationResult = FooSchema.Evaluate(JsonNode.Parse(jsonText), new EvaluationOptions() { OutputFormat = OutputFormat.List, RequireFormatValidation = true });

		var errors = validationResult.Details.Where(detail => detail.HasErrors);
		Assert.That(errors, Has.Count.EqualTo(1));
	}
```
	
Both tests are failing because there is an error: 
	
![image](https://github.com/gregsdennis/json-everything/assets/149778746/8122cdfc-bb38-4327-9ff2-05b686834762)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EmmyDream** [comment]
Sure, here is minimum I believe.
```
	public void Evaluate_WithIfConditionAndConstInside_WhenJsonIsValid_ErrorsListShouldBeEmpty()
	{
		var schema = new JsonSchemaBuilder()
			.Properties(("boolProperty", new JsonSchemaBuilder()
				.Type(SchemaValueType.Boolean)))
			.If(new JsonSchemaBuilder()
				.Properties(("boolProperty", new JsonSchemaBuilder().Const(true))));
		
		const string jsonText = @"{""boolProperty"": false}";

		var validationResult = schema.Evaluate(JsonNode.Parse(jsonText), new EvaluationOptions { OutputFormat = OutputFormat.List});
		var errors = validationResult.Details.Where(detail => detail.HasErrors);
		
		Assert.IsEmpty(errors);
	}
```
If this behavior is the expected one then I have no idea how can I provide to user information what have failed during schema validation. This message about `const` will be confusing and not true.

**Comment by gregsdennis** [comment]
I thought this was what you were looking for (and I suppose I'll need to write a blog post so I don't have to keep answering this question).

Relevant to this is [this spec issue](https://github.com/json-schema-org/json-schema-spec/issues/1319) which discusses filtering output units to only those which impact the validation outcome.  It's... complicated.

For this example, I'm going to use the `Hierarchical` output format because its nested structure makes things a bit easier to visualize.

The schema you gave is effectively

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "root",
  "type": "object",
  "properties": {
    "foo": { "type": "boolean" }
  },
  "if": {
    "properties": {
      "foo": { "const": "true" }
    }
  }
}
```

Now if we throw a `then` and `else` in there,

```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "root",
  "type": "object",
  "properties": {
    "foo": { "type": "boolean" }
  },
  "if": {
    "properties": {
      "foo": { "const": "true" }
    }
  },
  "then": { "required": ["bar"] },
  "else": { "required": ["baz"] }
}
```

we get varying behavior.  If `foo` is true, then we require `bar`; otherwise we require `baz`.  So both of these validate:

```jsonc
{ "foo": true, "bar": 1 }   // 1
{ "foo": false, "baz": 1 }  // 2
```

and these don't

```jsonc
{ "foo": false, "bar": 1 }  // 3
{ "foo": true, "baz": 1 }   // 4
```

Looking at (2), we may ask why this is valid.  Looking through the output,

```jsonc
{
  "valid": true,
  "evaluationPath": "",
  "schemaLocation": "https://json-everything.net/root#",
  "instanceLocation": "",
  "annotations": {
    "properties": [
      "foo"
    ],
    "if": false
  },
  "details": [
    {
      "valid": true,
      "evaluationPath": "/properties/foo",
      "schemaLocation": "https://json-everything.net/root#/properties/foo",
      "instanceLocation": "/foo"
    },
    {
      "valid": false,
      "evaluationPath": "/if",                                                      // 5
      "schemaLocation": "https://json-everything.net/root#/if",
      "instanceLocation": "",
      "details": [
        {
          "valid": false,
          "evaluationPath": "/if/properties/foo",                                   // 6
          "schemaLocation": "https://json-everything.net/root#/if/properties/foo",
          "instanceLocation": "/foo",
          "errors": {
            "const": "Expected \"\\\"true\\\"\""
          }
        }
      ]
    },
    {
      "valid": true,
      "evaluationPath": "/else",
      "schemaLocation": "https://json-everything.net/root#/else",
      "instanceLocation": ""
    }
  ]
}
```

we see an output unit (5) that indicates the subschema at `/if` failed validation (specifically the `valid` property is false).  This means that the `/else` subschema must pass and the `/then` subschema is ignored (which we can also see from other output units).  If we want to see _why_ the `/if` subschema failed, then either it will contain an error itself, or it will contain an output unit somewhere in `details` that contains an error.  In this case, it's the latter, and shown by (6).

This illustrates that it's quite important to keep the output unit for the `/if` subschema, even though it failed.

---

I used `Hierarchical` output before.  Here's the same validation in `List` format:

```json
{
  "valid": true,
  "details": [
    {
      "valid": true,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/root#",
      "instanceLocation": "",
      "annotations": {
        "properties": [
          "foo"
        ],
        "if": false
      }
    },
    {
      "valid": true,
      "evaluationPath": "/properties/foo",
      "schemaLocation": "https://json-everything.net/root#/properties/foo",
      "instanceLocation": "/foo"
    },
    {
      "valid": false,
      "evaluationPath": "/if",                                                   // 5
      "schemaLocation": "https://json-everything.net/root#/if",
      "instanceLocation": ""
    },
    {
      "valid": true,
      "evaluationPath": "/else",
      "schemaLocation": "https://json-everything.net/root#/else",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/if/properties/foo",                                    // 6
      "schemaLocation": "https://json-everything.net/root#/if/properties/foo",
      "instanceLocation": "/foo",
      "errors": {
        "const": "Expected \"\\\"true\\\"\""
      }
    }
  ]
}
```

You can see the (5) and (6) output units are still there, it's just reorganized.  I think this arrangement makes it a bit more difficult to analyze the output to, e.g., debug a validation.  However it's still evident in the `evaluationPath` property that (6) is a subvalidation of (5).

---

Lastly, `if` [doesn't affect the validation result](https://json-schema.org/draft/2020-12/json-schema-core#name-if):

> This validation outcome of this keyword's subschema has no direct effect on the overall validation result.

Its presence in the output is informational.

**Comment by EmmyDream** [comment]
Thank you @gregsdennis for your detailed answer. I think the most important point for me was this one:

> This validation outcome of this keyword's subschema has no direct effect on the overall validation result.

I see it this way: if I want to extract list of errors from whole validation and provide this list to user, then I should ignore `ValidationResults` which `evaluationPath` contains `/if`. Because errors in ignored results did not affect on validation result. So my first question is:
**1. Are there any other keywords which also does not affect on overall validation result?**

Another point is that I have to provide my own messages about validation result (like required field, expected value and so on). One of the reason is that I have to localize them and you are not supporting such languages (which is ok for me). Right now I see two options:  

1. Take messages from library and use them as a key to get my own messages. I do not like this idea because it will fail once you update any message in a library. 
2. Do some extraction of data from messages to get error data (like what was expected, what was required) and  create own messages based on these data and keys from errors list. But then extracting data from messages looks like some nice hacks. I am missing here property in `ValidationResults.Errors` which contains error data. Right now there is a key - which validation failed and value - message of failure. I would prefer some structure like: Key, Data and Message. Example:

```
new Error
{
        Key = "Const",
        Data = new List<string> {"true"},
        Message = "Expected {0}"
}
```

**2. Is it possible to achieve something like this?**

**Comment by gregsdennis** [comment]
> Another point is that I have to provide my own messages about validation result

Have you looked at the [docs](https://docs.json-everything.net/schema/basics/#schema-errors)?  They explain how you can provide your own error messages.

Secondarily, a PR with additional translations would be most welcome!

**Comment by gregsdennis** [comment]
> Are there any other keywords which also does not affect on overall validation result?

The issue you're encountering isn't that `if` doesn't affect overall validation.  It's that it has a subschema that can fail without affecting overall validation.  Another example of this is `oneOf`.  By definition, it will contain subschemas that fail, but they're all still listed in the output so that you can know _why_ they failed.

**Comment by EmmyDream** [comment]
> > Another point is that I have to provide my own messages about validation result
> 
> Have you looked at the [docs](https://docs.json-everything.net/schema/basics/#schema-errors)? They explain how you can provide your own error messages.
> 
> Secondarily, a PR with additional translations would be most welcome!

Ok, my bad. I see it now. Thanks!
About PR, I will think about it.

**Comment by EmmyDream** [comment]
> > Are there any other keywords which also does not affect on overall validation result?
> 
> The issue you're encountering isn't that `if` doesn't affect overall validation. It's that it has a subschema that can fail without affecting overall validation. Another example of this is `oneOf`. By definition, it will contain subschemas that fail, but they're all still listed in the output so that you can know _why_ they failed.

Got it, thanks.
