### ISSUE TITLE
 Validating against a schema with an oneOf condition using the date and date-time format results in a invalid validation

### ISSUE THREAD

**Issue by FelixJungensbluth** [gregsdennis/json-everything#558]
### Nuget Package

JsonSchema.Net

### Package Version

5.3.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Validating against a schema with an oneOf condition using the date and date-time format with the value like 2019-07-03T13:13:13 results in a invalid validation with the error: 
```
"errors": {
        "oneOf": "Expected 1 matching subschema but found 2"
      },
```

Schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A schema to validate fields that can either be a date or a date-time",
  "properties": {
    "dateCreated": {
      "oneOf": [
        {
          "type": "string",
          "description": "A date string",
          "format": "date"
        },
        {
          "type": "string",
          "description": "A date-time string",
          "format": "date-time"
        }
      ]
    }
  },
  "required": ["dateCreated"]
}

```

### What did you expect?

valid = true

### Please add test code or steps to reproduce the behavior.

![oneOf-validation-error](https://github.com/gregsdennis/json-everything/assets/49518120/d80d79d0-9e34-4c4a-b3c4-6a89fb48b2de)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
As I mention in my [docs](https://docs.json-everything.net/schema/basics/#schema-format), I make an effort to validate `format`s closely, but I make no guarantee of them working 100%.

I recommend that you create and register your own implementation of these formats to suit your needs.  I'll have a look at improving them in the future.  Also a PR would be welcome.

**Comment by FelixJungensbluth** [comment]
Thanks for your quick response. I'll create my own implementations for these formats, as you recommended, and create a PR afterwards.
