### ISSUE TITLE
More valid characters for json property name 

### ISSUE THREAD

**Issue by masoud-c** [gregsdennis/json-everything#559]
### Nuget Package

JsonPath.Net

### Package Version

0.6.7

### Can this library make doing something simpler?

'%' and '-' also can be valid characters for json property name, right now  it throws an exception if there is a '%' or '-' in the path.

### Describe alternatives you've considered.

changing IsValidForPropertyName to:
`private static bool IsValidForPropertyName(this char ch)
{
	return ch.In('a'..('z' + 1)) ||
		   ch.In('A'..('Z' + 1)) ||
		   ch.In('0'..('9' + 1)) ||
		   ch.In('_') ||
		   ch.In('%') ||
		   ch.In('-') ||
		   ch.In(0x80..0x10FFFF);
}`

would do the job

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
These are not valid characters.  This library follows the upcoming IETF specification, which disallows those characters.  You can see the ABNF in [section 2.5.1.1](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-21.html#section-2.5.1.1).

There was considerable discussion about which characters to include, and ultimately we landed on (effectively) alphanumeric and underscore.

**Comment by masoud-c** [comment]
> These are not valid characters. 

Ok, maybe add an option to PathParsingOptions to use these characters in case it's required to do so.

**Comment by gregsdennis** [comment]
The correct way to reference a property containing these characters is with the bracket syntax.

As I mentioned we (I was a major contributor the spec) [discussed at length](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/16) the characters which should be supported.  You're welcome to read it.

This isn't something I'm going to support in this library, even under an option.
