### ISSUE TITLE
Typed JSonPointer

### ISSUE THREAD

**Issue by erwan-joly** [gregsdennis/json-everything#56]
**Can this library make doing something simpler?**
I'd like to be able to use typed objects to parse JSonPointer

**Additional context**
The JSonPatch lib i'm currently using is having typed object and that makes it a lot more easier to maintain than hardcoded string.
```
var patch = new JsonPatchDocument<Item>();
patch.Replace(link => link.Price, newPrice);
```

**Comment by gregsdennis** [comment]
This shouldn't be very difficult.  Nice suggestion.

**Comment by gregsdennis** [comment]
To what extent do you need support?  I have this working locally:

```c#
JsonPointer.Create<TestClass>(x => x.NestMore[5].Nest); // creates "/NestMore/5/Nest"
```

**Comment by erwan-joly** [comment]
seems like perfect in my case :)

**Comment by erwan-joly** [comment]
just tested: Works like a charm
