### ISSUE TITLE
Need help Extending JSON Schema Validation With Own Vocabularies/Keywords

### ISSUE THREAD

**Issue by StephanWVZ** [gregsdennis/json-everything#560]
### Nuget Package

JsonSchema.Net

### Package Version

5.3.1

### How can I help?  Please provide as much context as possible.

Hello!

I'm trying this library out and I'm having some trouble implementing and understanding how one adds his own keywords.
I'm trying to follow this [example](https://docs.json-everything.net/schema/examples/custom-vocabs/) from the docs. However, this seems to be outdated. One has to implement the `GetConstraint()` method now and not whatever is in the docs. 

So instead of the docs I cloned the source code and copied the `MaxDate` (including json serialization stuff) example from the test files + added the keyword to an example json-schema. 
Now I register that schema from a file into the `SchemaRegistry`, so far so good.
But I get stuck on how to use this `MaxDate` keyword/vocab so that the `JsonSChame.Evaluate()` can recognize and use it. 
I suspect I must do something with the `Vocab`/ `VocabularyRegistry` and tie it together with the SchemaRegistery somehow. 

Another (more up-to-date) example would be welcome! :) And let me know if more context is needed.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
> One has to implement the GetConstraint() method now and not whatever is in the docs.

I'm not sure I understand.  What's in the docs _is_ to [implement `IJsonSchemaKeyword`](https://docs.json-everything.net/schema/vocabs/#schema-vocabs-custom-keywords-1), which includes providing an implementation of `.GetConstraint()`.

![image](https://github.com/gregsdennis/json-everything/assets/2676804/f56d1458-8ebe-4500-ba4d-4184872e4465)

**Comment by StephanWVZ** [comment]
Oh my... How did I completely miss this page... Perhaps a bit tunnel visioned on the examples page -> [Custom Vocab](https://docs.json-everything.net/schema/examples/custom-vocabs/). There it does implement the IJsonSchemaKeyword interface. But the example there is from an old one I think.

Anyway, thanks for pointing me to this one. Gonna try and follow that one now :)

**Comment by gregsdennis** [comment]
> I suspect I must do something with the Vocab/ VocabularyRegistry and tie it together with the SchemaRegistery somehow.

I'm actually in process of updating my custom vocabs, and I'll need to update the docs accordingly.  For now, I suggest you follow the model of the OpenAPI extensions:

1. Create a vocab meta-schema for the keywords you're defining, e.g. [the OpenAPI vocab meta-schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/meta/base.schema.json)
2. Create a dialect meta-schema that combines the standard vocabs and your custom vocab, e.g. [the OpenAPI dialect meta-schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/dialect/base.schema.json).
3. Create a `Vocabulary` class following the examples I have in my [data vocabulary lib](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.Data/Vocabularies.cs) (the meta-schemas will be different, but it's the registration you want to follow; this is what I'll be updating soon).
4. In your startup code, register your vocabulary.

When you're creating your schemas, you'll want to use your dialect meta-schema's `$id` value for `$schema`.

**Comment by gregsdennis** [comment]
> But the example there is from an old one I think.

Ah, yes, I probably did forget to update the example.  I'll do that with the upcoming updates.

**Comment by gregsdennis** [comment]
Pushing an update now.  Let me know if that helps.

**Comment by StephanWVZ** [comment]
The new update definitely helped me getting further getting custom keywords to work and I succeededing creating meta schema when all is defined from code.
However, I'm trying to use a self-defined fetch method on the schema registry for retrieving all the schema's dynamically (including meta schema etc.) from a database. This is where everything fails apart.  Not sure what the issue is yet. 

Thanks for the updated docs though! Might comeback to you if I keep failing with the fetch method that I specifically want.

**Comment by gregsdennis** [comment]
No worries.  I'll close this for now.  Feel free to reopen.
