### ISSUE TITLE
`time-offset` should be required for `date-time`

### ISSUE THREAD

**Issue by danielstarck** [gregsdennis/json-everything#570]
### Nuget Package

JsonSchema.Net

### Package Version

5.4.0

### Operating System

Linux

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Instances like `"2023-01-01T12:34:56"` (essentially `date-time`s with the `time-offset` part omitted) are considered valid `date-time`s.

### What did you expect?

I expected `IsValid` to be `false`.

### Please add test code or steps to reproduce the behavior.

```
[Fact]
public void Evaluate_WhenGivenDateTimeWithMissingTimeOffset_ShouldReturnIsValidFalse()
{
    const string schemaString =
        """
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "missingTimeOffset": {
              "format": "date-time"
            }
          }
        }
        """;

    const string json =
        """
        {
          "missingTimeOffset": "2023-01-01T12:34:56"
        }
        """;

    var jsonDocument = JsonDocument.Parse(json);
    var evaluationOptions = new EvaluationOptions { RequireFormatValidation = true };
    var isValid = JsonSchema.FromText(schemaString).Evaluate(jsonDocument, evaluationOptions).IsValid;

    Assert.False(isValid);
}
```

### Is there any other information you'd like to share regarding this bug?

I can't find anything in [draft 2020-12](https://json-schema.org/draft/2020-12/json-schema-validation#name-dates-times-and-duration) (or the referenced [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339.txt)) that indicates that `time-offset` is optional. Of course, I may have overlooked something.

However, I found this quote (copied from https://json-schema.org/understanding-json-schema/reference/string#format):
> Implementations may provide validation for only a subset of the built-in formats or **do partial validation for a given format**.

It seems to offer the necessary wiggle room for this behavior to be considered "not a bug", i.e., while `"2023-01-01T12:34:56"` is not a valid `date-time` according to RFC 3339, implementations of json schema may still accept it as valid.

If the failing test is considered to be a bug I could look into creating a PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Also of note are:

- my [docs](https://docs.json-everything.net/schema/basics/#schema-format) on support for `format`:
  > _JsonSchema.Net_ makes a valiant attempt at validating a few of them... I’m not going to claim that the validation on any of these is perfect, but it will likely suffice for most applications. In the (rare) event that it doesn’t support your needs, they are completely overridable.
- the [2020-12 spec](https://json-schema.org/draft/2020-12/json-schema-validation#name-format-annotation-vocabular) on `format` in general:
  > When the implementation is configured for assertion behavior, it:
  >   - SHOULD provide an implementation-specific best effort validation for each format attribute defined below

That said, if you'd like to improve the validation that's supplied by the library, a PR would be most welcome.

**Comment by danielstarck** [comment]
Thanks for the reply. I'll look into creating a PR.

**Comment by gregsdennis** [comment]
Also worth linking to the [RFC3339/ISO8601 comparison](https://ijmacd.github.io/rfc3339-iso8601/).  Note that all RFC3339 versions have a TZ.
