### ISSUE TITLE
Add regex support to data generator using FARE

### ISSUE THREAD

**Issue by Crown0815** [gregsdennis/json-everything#580]
### Nuget Package

JsonSchema.Net.DataGeneration

### Package Version

Newest

### Can this library make doing something simpler?

according to the documentation, Regex Generation is not supported. Using the FARE library it should be easy to add proper support for it. 

https://github.com/moodmosaic/Fare/tree/master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the suggestion.  I think this is one of the many that [I looked at](https://github.com/gregsdennis/json-everything/issues/173#issuecomment-1038572466) when I was putting the library together.  Everything seemed to have some limitations.

I can take another look, though.  It looks like the only update it's received in the past 6 years has been to support `netstandard2.0` instead of 2.1.

**Comment by Crown0815** [comment]
@gregsdennis, hmm, those are cases I was not aware of.
My team and I recently invested some time in example generation from JSON schemas in .NET and came across the FARE project which served our purpose. 

While not supporting all cases, would using the FARE library not serve to solve a majority of cases? It would at lease allow to reduce the amount of unsupported cases.

From our side, supporting basic „pattern“ bases string properties would already be great.

mir would you say, that if regex is supported, it should either be supported 100% or not at all?

**Comment by gregsdennis** [comment]
I'll look into adding basic support in, but I don't think I want to account for the multiple-subschema cases I described above.  I think throwing an exception if a `pattern` is found inside a `*Of` might be acceptable.

**Comment by Crown0815** [comment]
> I think throwing an exception if a pattern is found inside a *Of might be acceptable.

I agree. Those are not „simple“ regex, but far more complicated to properly handle.
