### ISSUE TITLE
Add TypeConverter for JsonPointer, JsonPath, etc. to allow easy configuration binding

### ISSUE THREAD

**Issue by wazzamatazz** [gregsdennis/json-everything#585]
### Nuget Package

JsonPointer.Net

### Package Version

3.2.2

### Can this library make doing something simpler?

When using the .NET configuration system, it is not currently possible to bind an entry from an `IConfiguration` to a `JsonPointer` on an options class. For example, the following always results in a null value for the `MyPointer` member on the `MyOptions` class:

```json
// appsettings.json
{
  "MyOptions": {
    "MyPointer": "/some/pointer"
  }
}
```

```csharp
// Application code

public class MyOptions {
  public JsonPointer MyPointer { get; set; }
}

// ...

void AddMyOptions(IServiceCollection services, IConfiguration configuration) {
  services.AddOptions<MyOptions>().Bind(configuration.GetSection("MyOptions"));
}
```

The .NET configuration binder uses [TypeConverter](https://github.com/dotnet/runtime/blob/e9ddf98c8502cfa00823dc94d3fcbfe5aa03ece7/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L883)s to convert from strings to the target target type. By adding `TypeConverter` implementations for types such as `JsonPointer` and `JsonPath` it would allow options classes to easily make use of the types in this repository.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I'm actually quite saddened that this isn't covered with the JSON converter, but I suppose the config binding did come before STJ.

**Comment by wazzamatazz** [comment]
Yeah, I'd also imagine that native AOT support might also cause some complications if STJ was used to do the conversion instead.
