### ISSUE TITLE
No refresh of result in the web site https://json-everything.net/json-schema/ 

### ISSUE THREAD

**Issue by LasneF** [gregsdennis/json-everything#588]
### What's your idea or question?

Given the website https://json-everything.net/json-schema/ 

leveraging the generate data feature 

putting a wrong schema set in the results 
Schema is invalid 

and not able to generate instance fair 

but fixing the issue , i am able to generate instances 
still the results part is keeping that schema is invalid 

this section should be refresh when at least clicking on run , or during edit with a delay 

Still thanks for the job and having this validator / explainer online is really great 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I don't think I follow.  Are you saying that the output field isn't clearing?

**Comment by gregsdennis** [comment]
I've updated the site to clear the output before processing a new request.  Please try again.

**Comment by LasneF** [comment]
You fix it , thanks it improves user experience
