### ISSUE TITLE
Generate Data not compliant with Evaluation JSON 

### ISSUE THREAD

**Issue by LasneF** [gregsdennis/json-everything#589]
### Nuget Package

JsonSchema.Net.DataGeneration

### Package Version

online 

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

Data generation is not compliant with schema 

### What did you expect?

when i use data generation that the data generated is compliant with the schema

### Please add test code or steps to reproduce the behavior.

taking this schema 

```typescript
{
  "$id": "https://example.com/schemas/customer",
  "type": "object",
  "properties": {
    "first_name": { "$ref": "#/$defs/name" },
    "last_name": { "$ref": "#/$defs/name" }
  }
   , 
  "$defs": {
    "name": { "type": "string" }
  },
  "additionnalProperties" : false
}
``` 

it has  generated 
``` 
{
  "last_name": 348034114955755589,
  "first_name": true,
  "Ipsa": null,
  "vero": false,
  "non": "Libero ut reprehenderit aspernatur sit dolorum cumque alias modi saepe. Velit aut veniam voluptatem laboriosam laboriosam perferendis. Laudantium sint molestiae nihil omnis aperiam ab eos officiis.",
  "fugit": false
}
``` 
 
that looks wrong , especially then taking the instance and putting back to schema validation it says it is not valid (and he is right !) 

### Is there any other information you'd like to share regarding this bug?

leveraging the online UI only as a great tool 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Yeah, it looks like the additional properties shouldn't have been generated.  I'll have a look.

Can you tell if this is consistent behavior, or does it only happen occasionally?  Sometimes the system gets confused.

Also, be aware that the [docs](https://docs.json-everything.net/schema/datagen/schema-datagen/#schema-datagen-capabilities) clearly state that data generation doesn't support references, which your schema contains.

**Comment by gregsdennis** [comment]
Okay, so a few issues here.

First is that `$ref` isn't supported, as noted above.

The second is that `additionalProperties` is misspelled.  (You have two `n`s.)

This works:

```json
{
  "$id": "https://example.com/schemas/customer",
  "type": "object",
  "properties": {
    "first_name": { "type": "string" },
    "last_name": { "type": "string" }
  }, 
  "additionalProperties" : false
}
```

**Comment by LasneF** [comment]
so sorry , i ve not follow the RTFM rules :) 

in real world not having the $ref limits the usage. i could understand not resolving extenal reference for security reason but internal would be nice to have support ( i guess your lib should be capable to generate a extended schema from the one input) 

I will close the ticket , could be an enhancement for the future 

thx again for the analysis , and apologized about not having read the doc
