### ISSUE TITLE
Json Schema Transformers?

### ISSUE THREAD

**Issue by Lordfirespeed** [gregsdennis/json-everything#592]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

5.4.2

### How can I help?  Please provide as much context as possible.

Is there any 'transformer' type API?

For example, I want to have a `Dictionary<int, string>` serialized to JSON as an array 
```json
[
  {
    "key": 123,
    "value": "foo"
  },
  ...
]
```

and deserialized back to the `Dictionary`.

Is there some way of registering 'transformers' for a JsonSchema type?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. I'm not sure how this applies to JSON Schema.  Can you provide some more detail?

**Comment by Lordfirespeed** [comment]
Sure!!

I've previously seen the pattern I'm looking for in [Tomlet](https://github.com/SamboyCoding/Tomlet)

They provide an API for defining 'mappers' that further transform data when serialized/deserialized. 

Mappers are helpful when developers wish to utilise language- or library- specific data structures at runtime that can't be represented by their chosen serialized language.

In my particular use case, I am trying to work around JSON's limitation that keys (identifiers) must always be strings, when I wish to serialize a `Dictionary<int, string>`. 

Here's a usage example of Tomlet's API from their README: 
```cs
// Example: UnityEngine.Color stored as an integer in TOML. There is no differentiation between 32-bit and 64-bit integers, so we use TomlLong.
TomletMain.RegisterMapper<Color>(
    //Serializer (toml value from class). Return null if you don't want to serialize this value.
    color => new TomlLong(color.a << 24 | color.r << 16 | color.g << 8 | color.b),
    //Deserializler (class from toml value)
    tomlValue => {
        if(!(tomlValue is TomlLong tomlLong)) 
            throw new TomlTypeMismatchException(typeof(TomlLong), tomlValue.GetType(), typeof(Color))); //Expected type, actual type, context (type being deserialized)
            
        int a = tomlLong.Value >> 24 & 0xFF;
        int r = tomlLong.Value >> 16 & 0xFF;
        int g = tomlLong.Value >> 8 & 0xFF;
        int b = tomlLong.Value & 0xFF;
            
        return new Color(r, g, b, a); 
    }
);
```

**Comment by elgonzo** [comment]
Yeah, but _how_ does your question/problem relate to Json **Schema**? To me it feels like your problem can be solved by [JsonConverters](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to), which allow you to implement any custom transformation between .NET object/value instances and the desired json representation.

**Comment by gregsdennis** [comment]
> And when the deserializer finds a field of type Color in the schema

What schema?

**Comment by Lordfirespeed** [comment]
> Yeah, but _how_ does your question/problem relate to Json **Schema**? To me it feels like your problem can be solved by [JsonConverters](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to), which allow you to implement any custom transformation between .NET object/value instances and the desired json representation.
> 
> 
> 
> > And when the deserializer finds a field of type Color in the schema
> 
> 
> 
> But the schema for `Color` won't contain any values for a color -- it only describes the json _data structure_ used for representing Color data. How do you imagine deserializing a `Color` instance from a schema? A Json schema does not describe mappings between some .NET type and some json data structure either -- it _only_ describes json data structures.

Ah! You're quite possibly right - I'm sorry, I'm not as familiar with .NET's features and its ecosystem as I'd like to be.

My question is related to JSON schema because I am using JSON schema in my project. I suppose what would really help me is an example of applying a JSON converter when serializing/deserializing using JsonSchema.NET. I couldn't find such an example when I looked in the JsonSchema.NET documentation but perhaps that's because I didn't know that I was looking in the wrong place!

**Comment by gregsdennis** [comment]
Serialization of `JsonSchema` just goes through the `JsonSerializer` like anything else you want to serialize to JSON.

```c#
var serialized = JsonSerializer.Serialize(schema);
```

Is something about _how_ it's serialized not working for you?  Can you provide a short example, including code, the output you're getting, and the output you expect?

**Comment by Lordfirespeed** [comment]
> > And when the deserializer finds a field of type Color in the schema
> 
> 
> 
> What schema?  I don't see a schema anywhere in your response.

I took the example from Tomlet's README, and there isn't a schema associated with that example because Tomlet's 'mappers' apply globally. 

Here's an example schema in Tomlet (it doesn't look dissimilar to a schema in JsonSchema.NET) 

```cs
class MyClass {
    [TomlProperty("name")]
    public string Username { get; set; }
    [TomlProperty("password")] //
    public string Password { get; set; }
    [TomlProperty("favouriteColor")]
    public Color FavouriteColor { get; set; }
}
```

**Comment by elgonzo** [comment]
There is no point looking for something like that, because as said a Json schema describes only Json data structures. Json Schema does not describe anything about .NET types/objects, so it in itself cannot describe .NET object \<--\> json transformations and therefore cannot be used for such tasks.

> Here's an example schema in Tomlet

That's "just" a .NET class with attribute annotations, something also the System.Text.Json serializer supports and which is completely unrelated to Json Schema (Json.Schema is _not_ to be confused with an annotated .NET type definition):
```C#
class MyClass {
    [JsonProperty("name")]
    public string Username { get; set; }
    [JsonProperty("password")] 
    public string Password { get; set; }
    [JsonProperty("favouriteColor")]
    public Color FavouriteColor { get; set; }
}
```

**Comment by gregsdennis** [comment]
I think there's some confusion here as to what [JSON Schema](https://json-schema.org/) is.  JSON Schema is a system primarily for validating JSON data.  _JsonSchema.Net_ is an implementation of this system.

It doesn't have anything to do with (de)serialization of JSON data into object models or TOML.  Though I expect you might be able to write a JSON Schema using TOML, just like you can write one in YAML.)

**Comment by Lordfirespeed** [comment]
> I think there's some confusion here as to what [JSON Schema](https://json-schema.org/) is. JSON Schema is a system primarily for validating JSON data. _JsonSchema.Net_ is an implementation of this system.
> 
> It doesn't have anything to do with (de)serialization of JSON data into object models or TOML. Though I expect you might be able to write a JSON Schema using TOML, just like you can write one in YAML.)

Ah, I agree there's some confusion - However, I do know what JSON Schema is!

I've definitely been erroneously calling some other things 'JSON Schema' in this thread, though. 
In particular I didn't know the correct name for the annotated .NET classes. 

My apologies. Perhaps I should reiterate my question with the correct terminology?

**Comment by Lordfirespeed** [comment]
I have a JSON schema (a `.schema.json` file that adheres to the [JSON Schema Spec Draft 7](https://json-schema.org/specification-links#draft-7)):
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "My Data",
  "description": "Describes my data!",
  "type": "object",
  "properties": {
    "myKeyValueMapping": {
      "title": "My Key Value Mapping",
      "type": "array",
      "items": {
        "title": "My Key Value Mapping Entry",
        "type": "object",
        "properties": {
          "key": {
            "title": "Key",
            "type": "integer"
          },
          "value": {
            "title": "Value",
            "type": "string"
          }
        },
        "required": [ "key", "value" ]
      }
    }
  },
  "required": [ "myKeyValueMapping" ]
}
```
The schema describes my serialized data, an example of which follows:
```json
{
  "myKeyValueMapping": [
      {
        "key": 100,
        "value": "incredible!"
      },
      {
        "key": 451,
        "value": "something very interesting"
      },
      {
        "key": 907,
        "value": "hello, world!"
      }
    ]
  }
```

I also have a .NET class annotated for JsonSchema.NET, and I've additionally annotated to facilitate schema validation:

```cs
[JsonSchema(typeof(MyData), nameof(MyDataSchema))]
public class MyData
{
	public static JsonSchema MyData= JsonSchema.FromFile("my-data.schema.json");
	
	[JsonPropertyName("myKeyValueMapping")]
	public List<MyMappingEntry> myKeyValueMapping { get; set; }
}

public class MyMappingEntry 
{
    [JsonPropertyName("key")]
    public int Key { get; set; }
    
    [JsonPropertyName("value")]
    public string Value { get; set; }
}
```

Serializing/deserializing with validation via `JsonSerializer` works great with this setup. 

However, I don't actually want to deserialize to a `List<MyMappingEntry>`. I really want a `Dictionary<int, string>`, like this:

```cs
[JsonSchema(typeof(MyData), nameof(MyDataSchema))]
public class MyData
{
	public static JsonSchema MyData= JsonSchema.FromFile("my-data.schema.json");
	
	[JsonPropertyName("myKeyValueMapping")]
	public Dictionary<int, string> myKeyValueMapping { get; set; }
}
```

How can I achieve this?

**Comment by gregsdennis** [comment]
I expect that should just work. What are you experiencing?

I can play with it a bit locally as well.

**Comment by Lordfirespeed** [comment]
> I expect that should just work. What are you experiencing?
> 
> I can play with it a bit locally as well.

It should *just work*??? 

That seems so far-fetched to me I haven't even tried!

How does JsonSchema figure out which is the key and which is the value?

What about a slightly more complex case, where each entry has 3 properties, e.g.
```json
{
  "key": 123,
  "something": "oof",
  "woah": 456
}
```

and I want to deserialize a `Dictionary<int, Entry>` where the `key` properties are used as the dictionary keys and the `Entry` is an annotated class:
```cs
public class Entry 
{
  [JsonPropertyName("key")]
  public int Key { get; set; }

  [JsonPropertyName("something")]
  public string Something{ get; set; }

  [JsonPropertyName("woah")]
  public int Woah { get; set; }
  
}

I'll give it a go when I can and get back to you :)

**Comment by gregsdennis** [comment]
> How does JsonSchema figure out which is the key and which is the value?

It doesn't need to.  You've used the schema to specify that the `Key` property needs to be an integer, and the `Value` property needs to be a string.  As long as the JSON data matches that, the schema validation is done.

The rest is up to the STJ serializer, and this library doesn't have any influence there.

I suggest getting it to work without the schema validation first, and then add it later.

---

From some quick trying, it looks like `Dictionary<int, string>` serializes like this:

```json
{
  "1": "foo",
  "2": "bar",
  "10": "baz",
  "11": "quux"
}
```

However, if I make the key a non-stringable type, I get 

```
System.NotSupportedException : The type 'Json.Schema.Tests.NonStringable' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[Json.Schema.Tests.NonStringable]'. The unsupported member type is located on type 'System.String'. Path: $.
```

So it seems if your key type is convertible to a string, it'll do that conversion and use that as the key in an object.  But if not, it'll throw this exception.  But yours is convertible, so...

Trying to deserialize the array form you have, I get:

```
System.Text.Json.JsonException : The JSON value could not be converted to System.Collections.Generic.Dictionary`2[Json.Schema.Tests.NonStringable,System.String]. Path: $ | LineNumber: 1 | BytePositionInLine: 3.
```

So you're going to need to make a [custom converter](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-6-0) for `Dictionary<int, string>`.

**Comment by Lordfirespeed** [comment]
Okay - awesome - How do I *use* the custom converter once I've written it? 

That's the question I've been trying to ask all along :joy:

**Comment by gregsdennis** [comment]
The instructions should all be on that page that I linked. This isn't anything to do with this package, it's just how to use the serializer.

If you need an example of a custom converter, have a look throughout the code in this project.

**Comment by Lordfirespeed** [comment]
Okay, cool. I think I've just terribly misunderstood which namespace some of the classes I've been accessing were imported from.

**Comment by Lordfirespeed** [comment]
Thankyou very much for all your help! I think I'll be OK from here. ❤️
