### ISSUE TITLE
Json Schema generation for polymorphic classes

### ISSUE THREAD

**Issue by nautnatic** [gregsdennis/json-everything#594]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.5.1

### How can I help?  Please provide as much context as possible.

Hi,
I'm working on generating a json schema for a polymorphic class. I have to mirror the class relationships in json schema somehow (probably using the oneOf/allOf properties). More specficially, I want to create the json schema for the allowed json deserialized using the JsonDerivedType attribute from System.Text.Json (https://learn.microsoft.com/de-de/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-8-0).

I can't really find a straightforward solution, but I assume that there is one, because I expect this not to be an uncommon use case.
Can someone give me a hint or small example on how to achieve the behavior described above?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
So the primary issue is that we don't know of a good way to model polymorphism using JSON Schema.  @handrews (one of the spec authors) has a really good [article](https://modern-json-schema.com/json-schema-is-a-constraint-system) on the topic, and although I recently wrote an [article](https://json-schema.org/blog/posts/modelling-inheritance) on how it _could_ be done, I don't think that the solution I came up with is very nice.

JSON Schema just wasn't built for type definition, and certainly not OO concepts like polymorphism.

Over the past couple years, we've tried to get an [effort](https://github.com/json-schema-org/vocab-idl/issues/47) going to define the translation between JSON Schema and type definition, but sadly we're not getting the help that we need.

Until there's a good way to do it, I can't see supporting it in this library or in _JsonSchema.Net.CodeGeneration_.  Ideally, I'd like to be able to take the output from one library and generate the original input using the other.

**Comment by nautnatic** [comment]
Thanks for the response.

In my case I don't need actual type definitions and polymorphism in the JSON Schema itself, as I only have to generate schema from code and not code from schema. I only need a schema for the allowed JSON input of the deserializerl.

For me a solution like [this](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof) sounds sensible. It makes use of _allOf_ to include properties from the parent class and _oneOf_ to allow multiple implementations of a polymorphic class.

For schema generation specifically, I think the actually derived types that should be allowed in the Json should be the types used by the deserializer, e.g. from JsonDerivedType.

Here a quick example:

### Input code

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DerivedClass1), "type1")]
[JsonDerivedType(typeof(DerivedClass1), "type2")]
public abstract class BaseClass
{
    public required string BaseProperty { get; set; }
}

public class DerivedClass1
{
    [JsonPropertyName("type")]
    [Description("The type identifying the object (always type1)")]
    public required string Type { get; set; }

    public required string DerivedProperty1 { get; set; }
}

public class DerivedClass2
{
    [JsonPropertyName("type")]
    [Description("The type identifying the object (always type2)")]
    public required string Type { get; set; }

    public required string DerivedProperty1 { get; set; }
}
```

### Expected JSON schema

```json
{
  "definitions": {
    "BaseClass": {
      "type": "object",
      "properties": {
        "BaseProperty": {
          "type": "string"
        }
      },
      "required": [
        "BaseProperty"
      ]
    },
    "DerivedClass1": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseClass"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "description": "The type identifying the object (always type1)"
            },
            "DerivedProperty1": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "DerivedProperty1"
          ]
        }
      ]
    }
  },
  "DerivedClass2": {
    "allOf": [
      {
        "$ref": "#/definitions/BaseClass"
      },
      {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "The type identifying the object (always type2)"
          },
          "DerivedProperty2": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "DerivedProperty2"
        ]
      }
    ]
  },
  "anyOf": [
    {
      "$ref": "#/definitions/DerivedClass1"
    },
    {
      "$ref": "#/definitions/DerivedClass2"
    }
  ]
}
```

### Implementation
Basically, during schema generation I would check if the schema should be generated for an object.
If yes, generate the schema for the abstract object first. Then, check if the class has JsonDerivedType attributes. 
If yes, generate the schemas for all declared properties (not the inherited properties) of all derived types (according to the type defined in JsonDerivedType) and include the parent class properties by using allOf(<parentPropertiesModel>, <derivedPropertiesModel>) as described in the example above.
Finally, allow all implementations by using anyOf with the references to all the derived types.

### Final notes
However, there definitely could be a information loss during the recreation of the initial code in the code generation process.

Do you have some recommendations or workarounds to generate the schema as described in the example above? Are there other libraries, which support this?

**Comment by gregsdennis** [comment]
The `discriminator` approach is definitely the first thing that people use, likely because they're familiar with it from OpenAPI/Swagger.

A shortcoming to that approach is that this library generates for a single type, meaning that you can't generate the `anyOf` branches.

If you want to try to tackle that, I recommend you look at the docs for [extending schema generation](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-extension)
 and the existing generators.  I'm not saying it can't be done.  It likely can, but until we (JSON Schema) have something official (or are working toward that), I really don't want to include it here.

There are other [libraries](https://json-schema.org/implementations#from-code) which support generation from and to other languages.  They all do it a bit differently, and that's kind of the problem that we want to fix.

**Comment by nautnatic** [comment]
Thanks for the notes/references. For everyone trying to do the same: I ended up using the NJsonSchema package, which supports an approach similar the descriptions above (using definitions, discriminators and oneOf/allOf) out of the box: https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance#declare-inheritance.

**Comment by gregsdennis** [comment]
Note that NJsonSchema is based on Newtonsoft.Json, not System.Text.Json.

**Comment by armanossiloko** [comment]
> The `discriminator` approach is definitely the first thing that people use, likely because they're familiar with it from OpenAPI/Swagger.
> 
> A shortcoming to that approach is that this library generates for a single type, meaning that you can't generate the `anyOf` branches.
> 
> If you want to try to tackle that, I recommend you look at the docs for [extending schema generation](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-extension) and the existing generators. I'm not saying it can't be done. It likely can, but until we (JSON Schema) have something official (or are working toward that), I really don't want to include it here.
> 
> There are other [libraries](https://json-schema.org/implementations#from-code) which support generation from and to other languages. They all do it a bit differently, and that's kind of the problem that we want to fix.

I take it things have not changed since this was posted and there's still no plans for this to be officially supported / implemented in the package, correct?

**Comment by gregsdennis** [comment]
Yes, that's correct. Spec changes are slow, and this suite follows the spec.
