### ISSUE TITLE
Add strong name signing for  JsonSchema.Net

### ISSUE THREAD

**Issue by whatevergeek** [gregsdennis/json-everything#60]
**Feature Request**
Add strong-name signing to the JsonSchema.Net project so that strong-name signed projects can also use JsonSchema.Net.
We're keen to use this in an enterprise setting which requires strong-name signing from dependent nuget packages.

**Issue faced when strong-name is not present**
  Message: 
    System.IO.FileLoadException : Could not load file or assembly 'JsonSchema.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Describe alternatives you've considered**
Other open source libraries have similar issue on strong-names:    
e.g. https://github.com/auth0/auth0.net/issues/207

I've tried the suggested strong namer nuget packages:

- https://www.nuget.org/packages/strongnamer     

-  https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner

However, the above strong namers were not able to resolve the dependent Json.More package.

auth0 open source library ended up adding strong name to resolve the issue also.

**Reference Demo**
I've created the following VS solution to replicate the issue:
https://github.com/whatevergeek/JsonSchemaDemo

Currently, it fails when running the tests in JsonSchemaDemoTest because of the mentioned strong name issue.

**Comment by gregsdennis** [comment]
Microsoft does not advocate for the signing of DLLs in Nuget packages.  They list [four reasons](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies) why a DLL should be signed, and libraries like this one do not fall into these categories.  Specifically

> For .NET Core, strong-named assemblies do not provide material benefits.

**Comment by whatevergeek** [comment]
hi @gregsdennis  ,

Thanks for the quick response. I was hoping this could be addressed as part of the [first reason](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies): You want to enable your assemblies to be referenced by strong-named assemblies.   

We're using strong-named assemblies in an enterprise setting. Hence,  we'd need our dependent packages to be signed in order to use them. I was looking into this package as it's supporting .netstandard 2.0 (i.e. not only .net core) from nuget perspective. 

If it's meant to be used  on only on .net core client libraries, I understand. I appreciate your efforts on open source. Though, that would also mean that we need to look elsewhere to resolve our enterprise library issue (i.e. json schema validator based on System.Text.Json that is strongly named). :-(

I understand that to strong-name this package, **ALL** dependent packages (all the way down the dependency chain) will also need signing. This is the current issue we're facing in our enterprise library that was hoping to use JsonSchema.Net.

**Comment by gregsdennis** [comment]
There is [this guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming) as well.

May I ask, what is the reason your enterprise software is signed? The link above advises against this for general purposes.

**Comment by whatevergeek** [comment]
It's probably due to some legacy reasons.
We're contemplating on removing strong naming.
If we get to remove, we can try using your library again. :-)

**Comment by gregsdennis** [comment]
I'm going to do this.  Ultimately it doesn't hurt anything to do it.  But I look forward to the day where we don't have to sign packages anymore.

**Comment by whatevergeek** [comment]
thank you very much @gregsdennis !
this is highly appreciated!
we're back on using your library
i encountered another issue but i may be using it wrongly or maybe i lack some additonal settings... 
anyway, will raise as a separate github issue for clarification
