### ISSUE TITLE
Schema location in evaluation result is incorrect for $ref pointing to an embedded schema

### ISSUE THREAD

**Issue by Fresa** [gregsdennis/json-everything#600]
### Nuget Package

JsonSchema.Net

### Package Version

5.4.2

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Using a document with embedded schema the `schemaLocation` point incorrectly to any referenced schemas traversed in the evaluation output.

Document example:
```
openapi: "3.1.0"
info:
  version: 1.0.0
  title: Test API
servers:
  - url: http://localhost/v1
    description: "v1"
paths:
  /user/{user-id}:
    get:
      summary: Get a user
      operationId: getUserById
      parameters:
        - $ref: "#/components/parameters/user"
      responses:
        "200":
          description: Ok
components:
  schemas:
    user:
      title: User
      type: object
      properties:
        first-name:
          type: string
        last-name:
          type: string
        age:
          type: integer        
      required:
        - first-name
        - last-name        
  parameters:
    user:
      name: user
      in: query
      required: true
      description: The user
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/user"
```

Instance:
```
{
  "foo-name": "foo",
  "last-name": "bar"
}
```

When validating the instance against the `components/parameters/user/content/application~1json/schema` schema, the output becomes:
```
{
  "valid": false,
  "evaluationPath": "",
  "schemaLocation": "http://localhost#",
  "instanceLocation": "",
  "details": [
    {
      "valid": false,
      "evaluationPath": "/$ref",
      "schemaLocation": "http://localhost/#/components/schemas/user",
      "instanceLocation": "",
      "errors": {
        "required": "Required properties [\"first-name\"] are not present"
      },
      "details": [
        {
          "valid": true,
          "evaluationPath": "/$ref/properties/last-name",
          "schemaLocation": "http://localhost/#/properties/last-name",
          "instanceLocation": "/last-name"
        }
      ]
    }
  ]
}
```

Look at the `schemaLocation` for `last-name`; `http://localhost/#/properties/last-name`. Shouldn't it be `http://localhost/#/components/schemas/user/properties/last-name`?

I would also expect that the `evaluationPath` included the `user` schema as it was evaluated in order to visit `last-name`.

### What did you expect?

Se above

### Please add test code or steps to reproduce the behavior.

Se above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting.

Yeah, it looks like it's not considering an existing pointer on the base URI.  This likely affects [Graeae](https://github.com/gregsdennis/Graeae/tree/main) as well.

**Comment by gregsdennis** [comment]
Creating a test, and... this could be easier:

```c#
var file = GetFile(600, "schema");
var text = File.ReadAllText(file);

var baseDocumentJson = JsonNode.Parse(text)!;
var baseDocument = new JsonNodeBaseDocument(baseDocumentJson, new Uri("http://localhost/v1"));

var options = new EvaluationOptions { OutputFormat = OutputFormat.Hierarchical };
options.SchemaRegistry.Register(baseDocument);

var schemaLocation = JsonPointer.Parse("/components/parameters/user/content/application~1json/schema");
var schema = baseDocument.FindSubschema(schemaLocation, options)!;
```
