### ISSUE TITLE
Assignment/creation of fields in JSON

### ISSUE THREAD

**Issue by slyredbeard** [gregsdennis/json-everything#602]
### Nuget Package

JsonPath.Net

### Package Version

0.7.0

### Can this library make doing something simpler?

As you suggested in [this](https://stackoverflow.com/questions/77683897/) stackoverflow answer, I bring the idea here. 

The point is to allow assignment syntax, that will create fields or assign values to them. 

Source JSON:
```
{
  "options": [
    {
      "price": 217,
      "quantity": 2
    },
    {
      "price": 63,
      "quantity": 5
    }
  ]
}
```
Query: `options[?(@.result = @.price * @.quantity)]`
Result:
```
[
  {
    "price": 217,
    "quantity": 2,
    "result": 434  // yay!
  },
  {
    "price": 63,
    "quantity": 5,
    "result": 315  // yay!
  }
]
```

### Describe alternatives you've considered.

Or maybe allow some other way of performing aggretations on the source data. Like I said in the stackoverflow question, I didn't need to create those extra fields or modify the source in any way. I just wanted to perform arithmetic action on two fields before returning the result. Like that:
```
[
  434,
  315
]
```
So this is the use case I suggest supporting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks, but this needs to be a feature in JSON Path first. A syntax needs to be agreed upon, etc.

I might toy with it here, but I'm not going to publish support for anything that the spec group hadn't at least discussed.

**Comment by slyredbeard** [comment]
No worries. I just added it to return kindness for answering my question. Still would be great if it will be implemented some day.

**Comment by gregsdennis** [comment]
The conversation is started, so we'll see where that goes.

**Comment by gregsdennis** [comment]
Closing this since I've relayed the conversation to the above issue in the JSON Path spec repo.
