### ISSUE TITLE
Does JsonSchema.NET support validating while deserializing to external types?

### ISSUE THREAD

**Issue by guythetechie** [gregsdennis/json-everything#603]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

5.4.3

### How can I help?  Please provide as much context as possible.

Thanks for the great library.

If I understand [the documentation](https://docs.json-everything.net/schema/serialization/) correctly, deserialization with schema validation requires a ``[JsonSchema()]`` annotation on the destination type. What if we don't own the destination type though (e.g from an external class library)? Is there a way to validate and deserialize without the annotation?

My use case might actually be simpler than this. I'm trying to take a JsonObject, validate it with a predefined schema, then return a validated JsonObject. If the source JSON has extraneous properties but still passes validation, the destination JSON should only have properties from the schema. I was hoping for something like the code below, but I may be using the wrong tool for the job.

```csharp
public static class ValidationHelpers
{
    private static readonly JsonSchema schema = JsonSchema.FromText("my schema text");

    public static void Validate(JsonNode? source)
    {
        var result = schema.Evaluate(source, new EvaluationOptions { OutputFormat = OutputFormat.Hierarchical});
        if (result.IsValid)
        {
            var validatedNode = result.xxx;
            Console.Write("""
                          Validation successful. Source might have extra properties, but no big deal.
                          validatedNode only has properties defined in the schema.
                          """);
        }
        else
        {
            var errorMessage = GetEvaluationErrorMessage(result);
            throw new JsonException(errorMessage);
        }
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I don't have a way to do that, currently, no.  However, off the top of my head, maybe a static type/schema registry would do.  Something like:

```c#
ValidatingJsonConverter.Register<Point>(pointSchema);
```

**Comment by gregsdennis** [comment]
Here's what I've come up with:

```c#
JsonSchema PointSchema =
    new JsonSchemaBuilder()
        .Type(SchemaValueType.Object)
        .Properties(
            ("X", new JsonSchemaBuilder().Type(SchemaValueType.Integer)),
            ("Y", new JsonSchemaBuilder().Type(SchemaValueType.Integer))
        )
        .AdditionalProperties(false);

ValidatingJsonConverter.MapType<Point>(PointSchema);
```

Would this work for you?

**Comment by guythetechie** [comment]
I'm sorry, but I don't see ``MapType`` or ``Register`` as static methods on ``ValidatingJsonConverter``.

![image](https://github.com/gregsdennis/json-everything/assets/31325620/bb007fdc-abd5-46fb-9ad6-ff9ad3c5f9aa)

If I create an instance of ValidatingJsonConverter, those aren't available either.
![image](https://github.com/gregsdennis/json-everything/assets/31325620/f3dce8fc-0068-42b0-b536-28960506b44e)

Am I missing a package? Here's what I have installed.
``
    <PackageReference Include="JsonSchema.Net" Version="5.4.3" />
``

**Comment by gregsdennis** [comment]
Yeah, I haven't published anything. I'm getting your thoughts on whether a particular UX would work for you.

**Comment by guythetechie** [comment]
Understood. Yes, that should work. Thanks!
