### ISSUE TITLE
How to generate multiple types at the same time with common subschemas?

### ISSUE THREAD

**Issue by christophdebaene** [gregsdennis/json-everything#610]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

3.5.1

### How can I help?  Please provide as much context as possible.

I would like to generate multiple types at the same time with reuse of common types.
I have a scenario where I have request/response messages that at the end will be used in OpenApi specification.

```csharp
public record CreateContact
{
    public Contact Contact { get; set; }
}

public record EditContact
{
    public Contact Contact { get; set; }
}

public record Contact
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

Using the `FromType` on each type will not result in a reusable definition named `Contact`.
I tried by introducing a global class that encompass the `CreateContact` and `EditContact`.

```csharp
public class GenerationTarget
{
    public CreateContact CreateContact { get; set; }
    public EditContact EditContact { get; set; }
}

var options = new SchemaGeneratorConfiguration
{
    Optimize = true
};

var schemaBuilder = new JsonSchemaBuilder();
var schema = schemaBuilder
    .FromType<GenerationTarget>(options)
    .Build();
```

It resulted in a common subschema `Contact`.
This 'hack' would mean that I need to create dynamically a `GenerationTarget` class and also the resulting json schema will need some transformation.

My question is, is there another/better way to generate multiple types at the same time?
Maybe having a `schemaBuilder.FromTypes(IEnumerable<Type> types)`?

```json
{
  "type": "object",
  "properties": {
    "CreateContact": {
      "type": "object",
      "properties": {
        "Contact": {
          "$ref": "#/$defs/contact"
        }
      }
    },
    "EditContact": {
      "type": "object",
      "properties": {
        "Contact": {
          "$ref": "#/$defs/contact"
        }
      }
    },
  },
  "$defs": {
    "contact": {
      "type": "object",
      "properties": {
        "FirstName": {
          "type": "string"
        },
        "LastName": {
          "type": "string"
        }
      }
    }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there.  I don't have a way to do this right now aside from building a "container" type, as it seems you've tried.

That said, please be aware that this generation is meant to be used as a dev-time tool to get you started.  The intent is for you to take the generated schema and continue to refine it manually.  With that in mind, duplication should really be an issue, and you can piece-wise construct your final schema.

**Comment by christophdebaene** [comment]
Ok, thank you very much for your feedback.
