### ISSUE TITLE
Simple Path extension methods on JsonElement

### ISSUE THREAD

**Issue by shravan2x** [gregsdennis/json-everything#614]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonPath.Net

### Package Version

0.7.1

### How can I help?  Please provide as much context as possible.

Does the API offer simple extension methods on JsonElement to return a specific path? Something like

```
JsonElement result = JsonSerializer.Deserialize<JsonElement>(...);
... = result.SelectNode("@.child.x.y.z");
```

Parsing and then using a path feels quite awkward for simple paths like `@.child.x.y.z`, especially when they're used within a LINQ query. Eg. `someList.Select(x => x.SelectNode("@.child.x.y.z"))` instead of `someList.Select(x => JsonPath.Parse("@.child.x.y.z").Evaluate(x))`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the question.

Overall, I think it's much simpler to just use the correct path.  If you're deserializing into the JSON model anyway (use `JsonNode` for this library, not `JsonElement`), then that just becomes the root node, and the path is `$.*.child.x.y.z` or `$[*].child.x.y.z`.

```c#
var root = JsonSerializer.Deserialize<JsonNode>(...);
var path = JsonPath.Parse("$.*.child.x.y.z");
var result = path.Evaluate(root);
```

---

If you're starting with a _collection_ of JSON values (e.g. `IEnumerable<JsonNode>`), then wrap it in a `JsonArray` first by using the `.ToJsonArray()` extension method from _Json.More.Net_ (which is already referenced).

```c#
var root = someList.ToJsonArray();
// ...
```

---

Regarding an extension method, I'm not sure I want multiple conflicting ways to invoke evaluation.

Additionally, doing something like `someList.Select(x => x.SelectNode("@.child.x.y.z"))` would require that the path `@.child.x.y.z` be parsed for every element in `someList`, which is really inefficient.  You're better off parsing the path once and evaluating it multiple times.

Something like

```c#
var path = JsonPath.Parse("@.child.x.y.z");
var allResults = someList.Select(path.Evaluate);
```

is really simple and can be done easily with the current API.

If you just want all of the resulting values:

```c#
var path = JsonPath.Parse("@.child.x.y.z");
var allResults = someList.SelectMany(x => path.Evaluate(x).Matches.Select(n => n));
```

Remember that JSON Path doesn't eliminate duplicates, so maybe call `.Distinct()` if you want that.

**Comment by gregsdennis** [comment]
Unless there's anything further, I'm going to close this in favor of the alternative I described above.
