### ISSUE TITLE
Generate data from Json Schema provides incorrect results

### ISSUE THREAD

**Issue by LasneF** [gregsdennis/json-everything#617]
### Nuget Package

JsonSchema.Net.DataGeneration

### Package Version

online 

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

given the Schema provided  here 
https://json-schema.org/draft/2020-12/json-schema-core#name-schema-re-use-with-defs 

meaning : 
```
{
    "type": "array",
    "items": { "$ref": "#/$defs/positiveInteger" },
    "$defs": {
        "positiveInteger": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    },
    "additionnalProperties" : false
}
```

the sample generator generate invalid sample 
it should generate only an array of positive integer 

### What did you expect?

either valid sample 

either an error message , saying that the feature is not supported 

### Please add test code or steps to reproduce the behavior.

```
{
    "type": "array",
    "items": { "$ref": "#/$defs/positiveInteger" },
    "$defs": {
        "positiveInteger": {
            "type": "integer",
            "exclusiveMinimum": 0
        }
    },
    "additionnalProperties" : false
}
```

### Is there any other information you'd like to share regarding this bug?

Version used : online version   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the report.  A few clarifying questions:

1. What are you trying to generate?  Data, perhaps?
2. What is it actually generating, and why is that unexpected.

> saying that the feature is not supported

If you are trying to generate data, the [docs](https://docs.json-everything.net/schema/datagen/schema-datagen/#schema-datagen-capabilities) do clearly state that reference keywords like `$ref` are not supported.

Outside of what's not supported, the library will make a best effort to generate something.

**Comment by LasneF** [comment]
i am leveraging the online version  like this 
![image](https://github.com/gregsdennis/json-everything/assets/12461661/9987412b-9028-4de4-9824-31ee9819e9d0)


here are some sample value generated 
[
  "Fugit et nam ipsa corrupti quo exercitationem consequatur.",
  false
]

or 
[
  154316848882584128,
  -519446754129084882,
  [
    -1990970148624882852993655567.1
  ],
  {
    "Velit": 5560734661509559144706499309.5,
    "voluptas": null,
    "deserunt": -887861120249802902
  },
  -3765700173106497534064606983.1
]


what i would expect is that if the feature in the schema is not supported , that the generate data just fail rather that generating a wrong data , 

you could leverage the results part to mentionned that the feature $ref is not supported , and not generating a data.

**Comment by gregsdennis** [comment]
Note on your schema: `additionalProperties` doesn't do anything here because the instance must be an array.  `additionalProperties` only works on objects.

**Comment by gregsdennis** [comment]
Also appears that `exclusiveMin` and `exclusiveMax` are not currently supported.

I think you just found an example that showcases all of the unsupported features.

**Comment by Grgpuran07** [comment]
Hello @gregsdennis,

Is there any other way to support to generate data for this schema. It is returning error due to infinite recursive checking. 

{
  "type": "object",
  "properties": {
    "Name": {
      "type": "string"
    },
    "Children": {
      "type": "array",
      "items": {
        "$ref": "#"
      }
    }
  }
}

**Comment by gregsdennis** [comment]
@Grgpuran07 your question is unrelated to this issue.  Please don't reuse issues.  Please open a new issue.

**Comment by Grgpuran07** [comment]
@gregsdennis thank you for your response. In old version it was working fine but it is showing error for latest version. For this, is there no any fix or I shouldn't update to latest version. In docs there is only written not supported.
thank you!

**Comment by gregsdennis** [comment]
`$ref` has never been supported.  I'm unsure what's causing the error now, but it's not a change in that.
