### ISSUE TITLE
Generate sample does not handle well not keyword 

### ISSUE THREAD

**Issue by LasneF** [gregsdennis/json-everything#646]
### Nuget Package

JsonSchema.Net.DataGeneration

### Package Version

online 

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

give the schema below the data genereation generate data that are not valid if i pass them to the validator  

here i want to express that you must provide either A , or B but never both , and still be extensible ... 
so leveraging not keyword 

looks not working as generating data with A , and B ... 
then if i take back the value generated to the Validate data it mentionned that data are not valid 

according to the documentation 
https://docs.json-everything.net/schema/datagen/schema-datagen/#schema-datagen-capabilities 
it should be supported

generation
![image](https://github.com/gregsdennis/json-everything/assets/12461661/28bbbc01-6fb1-4a0f-b751-aceca15859c5)

validation 
![image](https://github.com/gregsdennis/json-everything/assets/12461661/a9347c76-813e-4c44-b594-05ed23d2a778)

### What did you expect?

to not generate unvalid data 
ie never have A and B 

### Please add test code or steps to reproduce the behavior.

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": true,
  "oneOf": [
    {
      "required": ["A"],
      "properties": {
        "A": {
          "type": "string"
        },
        "B": {
          "not": {}
        }
      }
    },
    {
      "required": ["B"],
      "properties": {
        "A": {
          "not": {}
        },
        "B": {
          "type": "string"
        }
      }
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.

What the generator does in the case of `not` is it inverts any requirements that are on the subschema.  In your case, you have an empty schema `{}` which means there are no requirements to invert.

Realistically, `{"not": {}}` is just `false`, and I recommend using that instead.

**Comment by LasneF** [comment]
the idea behind the scene was to say strictly A or B exclusive , without sacrifying extensibility of the object 
ans so leveraging not was a way to forbid usage of the other field .

**Comment by gregsdennis** [comment]
Yes, but by titling the issue "Generate sample does not handle well not keyword", you're saying that you think your usage of `not` is what's causing the problem, and it is part of it.

Please try with a `false` schema instead of the `not: {}`.

**Comment by LasneF** [comment]
not 100% confortable with the syntax 
tested with 
![image](https://github.com/gregsdennis/json-everything/assets/12461661/8c4c0e64-8a37-4b54-9fb2-d5d8660fdff3)

or  "B" :  {false}  gives invalid schema

**Comment by gregsdennis** [comment]
Okay, yeah. That demonstrate an issue with `oneOf`.
