### ISSUE TITLE
Can we get JsonPath.Net Support for .NET Standard 2.0?

### ISSUE THREAD

**Issue by Emcrank** [gregsdennis/json-everything#652]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonPath.Net

### Package Version

0.8.0

### How can I help?  Please provide as much context as possible.

Can we possibly get a package version of `JsonPath.Net` for `.NET Standard 2.0`? 

We are looking to get away from `Newtonsoft.Json` towards `System.Text.Json` however the latter does not have support for traversing the DOM using JsonPath's so I stumbled upon your library from the following [issue raised here](https://github.com/dotnet/runtime/issues/31068). Reason we cannot use it at .NET Standard 2.1 is we have some legacy application's which only accept imports for the latest .NET Framework. I've looked at the changes required and I don't think there is many, just mainly the fact there is no implicit operator to convert from string to `ReadOnlySpan<char>`. I suggest potentially calling `string.AsSpan()` in its place so it is compatible with .NET Standard 2.0?

Let me know your thoughts, cheers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I tried to do that with the recent update but couldn't get it building.

I can try again next week.  Also happy to accept a PR.

**Comment by Emcrank** [comment]
I've made the changes & all tests passing. Will submit a PR.

**Comment by Emcrank** [comment]
https://github.com/gregsdennis/json-everything/pull/653

**Comment by gregsdennis** [comment]
Merging the PR should close the issue. It should stay open until the problem is actually fixed.

**Comment by gregsdennis** [comment]
Odd.  The PR merge should have closed this.
