### ISSUE TITLE
JsonSchema Evaluate is not handling the 'allOf' with conditionally applied schemas using 'if then'

### ISSUE THREAD

**Issue by elitemike** [gregsdennis/json-everything#654]
### Nuget Package

JsonSchema.Net

### Package Version

6.0.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net Framework

### A clear and concise description of the bug.

The library does not appear to be handling the conditional applying of subschemas correctly.  The scenario that is failing is using the If-Then-Else that was added in draft 7 where sub schemas are applied based on a constant

### What did you expect?

The library should evaluate the included sample correctly which will be with no errors as the test file is written.  Python check-jsonschame handles this correctly as well as VS Code and liquid studio.

### Please add test code or steps to reproduce the behavior.

A full sample project can be found here https://github.com/elitemike/json_schema  but the schemas and the test file are included below.

[root.schema.json](https://github.com/gregsdennis/json-everything/files/14229378/root.schema.json)
[controlBase.schema.json](https://github.com/gregsdennis/json-everything/files/14229379/controlBase.schema.json)
[eventSubscriptionAction.schema.json](https://github.com/gregsdennis/json-everything/files/14229380/eventSubscriptionAction.schema.json)
[eventSubscriptions.schema.json](https://github.com/gregsdennis/json-everything/files/14229381/eventSubscriptions.schema.json)
[date.schema.json](https://github.com/gregsdennis/json-everything/files/14229382/date.schema.json)
[numeric.schema.json](https://github.com/gregsdennis/json-everything/files/14229383/numeric.schema.json)
[string.schema.json](https://github.com/gregsdennis/json-everything/files/14229384/string.schema.json)
[time.schema.json](https://github.com/gregsdennis/json-everything/files/14229385/time.schema.json)

[test1.json](https://github.com/gregsdennis/json-everything/files/14229386/test1.json)

### Is there any other information you'd like to share regarding this bug?

json-schema.org has an example of this case working https://json-schema.org/understanding-json-schema/reference/conditionals#ifthenelse 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey, @elitemike. Thanks for the issue, but I'm going to need you to reduce this to a minimal reproduction to help isolate the problem.  Like a test method or something.

**Comment by gregsdennis** [comment]
FWIW, it handles the json-schema.org example just fine.

**Comment by gregsdennis** [comment]
Confirmed not a bug in Slack.
