### ISSUE TITLE
Add Keyword documentation is slightly seems slightly outdated after an AOT change

### ISSUE THREAD

**Issue by mrBoie** [gregsdennis/json-everything#659]
### What's your idea or question?

Hi!

Been using the library for some light schema generation and it's great!
Wanted to augment the schema with some custom keywords and had some issues.

Tried following along the examples on the website in order to add a customkeyword that should be appended to properties upon having an attribute.

So pretty much:
This -> https://docs.json-everything.net/schema/examples/custom-vocabs/#example-schema-vocabs-keyword
And then This -> 
https://docs.json-everything.net/schema/examples/intent/
and This ->
https://docs.json-everything.net/schema/examples/attribute/

using system.text.json

Everything seemed to work until i wanted to serialize the schema i had generated from a model.
I found that GetTypeInfo was used and this is using a dictionary that is not populated using the Register<T>() method 
referenced in the documentation:
https://docs.json-everything.net/schema/examples/custom-vocabs/#example-schema-vocabs-register-keyword

This led to my custom keyword being misslabled as unrecognizable keyword and crasching due to a unable to cast exception

After some trial and error i ended up using Register<T>(JsonSerializerContext typeContext) instead and that seems to work sufficiently. 

Anyhow, since i managed to work around it and I could not find where to update the documentation I thought I would add an issue at least :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for pointing this out.  I haven't made it through all of the docs updates yet.  It's still something I'm working on.

> Wanted to augment the schema with some custom keywords and had some issues.

I haven't tried generation alongside custom keywords yet.  That's interesting!

**Comment by mrBoie** [comment]
Have a usecase where i want to use the generated jsonschema in order to dynamically generate and inject formcontorls in the frontend

So one endpoint for schema used in setting up the formcontrols and then some other endpoints for getting and updating the data.

Needed to augment the schema with some custom stuff for the dynamic frontend scaffolding and that led me down this path 😄

**Comment by gregsdennis** [comment]
> Everything seemed to work until i wanted to serialize the schema i had generated from a model. - @mrBoie 

Are you building a Native AOT app?  If you're not, I would expect the regular `.Register()` method to still work.

**Comment by gregsdennis** [comment]
I've added a note here: https://docs.json-everything.net/schema/examples/custom-vocabs/#example-schema-vocabs-register-keyword
