### ISSUE TITLE
Add Schema Validation Error Message

### ISSUE THREAD

**Issue by whatevergeek** [gregsdennis/json-everything#66]
**Environment**
- Nuget Package:  1.7.0
- OS: Windows 10
- .Net Target: 4.7.2

I'm using the validation like the code below:
```cs
        public bool IsValid(string data, out string result)
        {
            if (!string.IsNullOrWhiteSpace(Schema))
            {
                var doc = JsonDocument.Parse(data);
                JsonSchema schema = JsonSchema.FromText(Schema);

                var validationResult = schema.Validate(doc.RootElement);

                result = validationResult.IsValid ? "Validation Succeeded." : validationResult.Message;
                return validationResult.IsValid;
            }
            else
            {
                throw new Exception("Schema not set");
            }
        }
```

However, `validationResult.Message` doesn't contain anything (null) even if the json input is invalid.
Whereas, Json.NET's Schema validator contains at least some message     
e.g.    
`Integer -1 is less than minimum value of 0. Line 4, position 12.`

Is it possible to get the reason of the schema validation error like the one above? 

To replicate, I've created a dummy solution here:    
https://github.com/whatevergeek/JsonSchemaDemo    
You may run the unit tests to replicate the issue.

**Comment by gregsdennis** [comment]
How coincidental!  I was looking at your repo yesterday.

It looks like you're getting just the basic validation result, which is just a pass/fail.  To get more information, including an error message, you need to set up for one of the other [output formats](https://gregsdennis.github.io/json-everything/api/Json.Schema.OutputFormat.html).

```c#
var options = new ValidationOptions { OutputFormat = OutputFormat.Detailed };
var results = schema.Validate(instance, options);
```

See the [docs](https://gregsdennis.github.io/json-everything/usage/schema-validation.html#validation-results) for more information.

**Comment by whatevergeek** [comment]
thanks a lot for the clarification @gregsdennis 

I've set the OutputFormat as advised and it works now.
Here's how I've implemented: 
```cs
    public class Validator
    {
        public string Schema { get; set; }
        public bool IsValid(string data, out string result)
        {
            if (!string.IsNullOrWhiteSpace(Schema))
            {
                var doc = JsonDocument.Parse(data);
                JsonSchema schema = JsonSchema.FromText(Schema);

                var options = new ValidationOptions { OutputFormat = OutputFormat.Detailed };
                var validationResult = schema.Validate(doc.RootElement, options);

                result = GetValidationResultMessage(validationResult);
                return validationResult.IsValid;
            }
            else
            {
                throw new Exception("Schema not set");
            }
        }

        private string GetValidationResultMessage(ValidationResults validationResult)
        {
            var resultMessage = string.Empty;
            if (validationResult.IsValid)
            {
                resultMessage = "Validation Succeeded.";
            }
            else if (validationResult.NestedResults.Count > 0)
            {
                resultMessage = "Validation Errors: ";
                foreach (var result in validationResult.NestedResults)
                {
                    resultMessage += $"{result.Message} found at {result.SchemaLocation.Source}| ";
                }
            }
            else
            {
                resultMessage = $"Validation Errors: {validationResult.Message} found at {validationResult.SchemaLocation.Source}| ";
            }

            return resultMessage;
        }

    }
```

I've added some test cases in [the sample demo project](https://github.com/whatevergeek/JsonSchemaDemo) to confirm the behaviour.     
Just an observation, if `validationResult.NestedResults.Count` is more than 1,  the main `validationResult.Message` returns null.    
Hence, I had to check for it in my implementation above. Is this behavior intended?    
Anyway, I'm ok to proceed with this. Feel free to let me know if there's a better usage.

**Comment by gregsdennis** [comment]
This behavior is intended. Keywords that hold schemas are called "applicators."  These keywords have no message because it's the message from the contained keywords that hold the interesting data.

**Comment by whatevergeek** [comment]
thanks a lot @gregsdennis 
i'm so glad to be able to finally use your library
i'm closing this question now
all the best and thanks for your open source effort/contributions
highly appreciated! :-)
