### ISSUE TITLE
Support xml comments on generated schema

### ISSUE THREAD

**Issue by zlepper** [gregsdennis/json-everything#667]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.0.0

### Can this library make doing something simpler?

I would be really nice if the doc comments on member/types could automatically be included when generating a json schema from a type.

I know i can use the `[description]` attribute, however as i already have xml comments it would be nice to not have to duplicate those :)

### Describe alternatives you've considered.

Using the `[description]` attribute. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. Thanks for the idea, but I've decided to deprecate this library.

Please see the [blog post](https://blog.json-everything.net/posts/dropping-codegen/) for more info.

**Comment by zlepper** [comment]
Sorry if i'm being stupid here, but i just want to confirm that both `JsonSchema.Net.CodeGeneration` and `JsonSchema.Net.Generation` are being deprecated in favor of `Corvus.JsonSchema`, even though it only supports Json => C#?

I'm entirely understanding of that decision, i just want to make sure i haven't misunderstood something about `Corvus.JsonSchema` :)

**Comment by gregsdennis** [comment]
Oh!  My bad.  No, schema generation is still a thing.  The codegen one is deprecated.  I'm sorry.  I misread that.

**Comment by gregsdennis** [comment]
So... on to the request.

The XML comment data isn't provided via reflection, which is how the schema generation works.  In order to get that, you'd have to also provide the XML documentation file (e.g. _JsonSchema.Net.xml_).  For simple assembly references, that file is not typicall included.

For an example of this working, you can see my [API documentation generation](https://github.com/gregsdennis/json-everything/tree/schema/experiment-modelless-schema/tools/ApiDocsGenerator).  There's a lot of code there to read the file and match up the comments to the code.  It's not impossible...

**Comment by zlepper** [comment]
Yup, i know it's a PITA to grap even when the xml documentation file is generated. I have previously used https://github.com/RicoSuter/Namotion.Reflection to grap the documentation, however it's quite a big library if the only thing you are interested in is getting xml docs. Alternatively swashbuckle has some code also that might be easier to borrow/adapt: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments

It is honestly impressive that MS still doesn't provide any build in way of getting this information directly in dotnet...

> It's not impossible...

Just annoyingly difficult :D Which is exactly why i would love to push it to an external (To me) library :D

**Comment by gregsdennis** [comment]
Let me have a poke around and see what I can do.

**Comment by gregsdennis** [comment]
I've been able to add some support, but you'll have to provide the XML file.  Something like this:

```c#
var config = new SchemaGeneratorConfiguration();
config.RegisterXmlCommentFile<TypeCommentedModel>("JsonSchema.Net.Generation.Tests.xml");
```

I have some more work to do, but it's functioning.

**Comment by zlepper** [comment]
Holy shit, that was fast :D

**Comment by gregsdennis** [comment]
For your reading pleasure: https://docs.json-everything.net/schema/schemagen/schema-generation/#xml-comment-support

**Comment by zlepper** [comment]
There is a couple of small errors in the docs i noticed when trying it:
* The `SchemaGenerationConfiguration` is actually called `SchemaGeneratorConfiguration`
* The method is called `RegisterXmlCommentFile` not `RegisterXmlCommentsFile` (Notice comment vs comment*s*)

When doing local development, the working directory of the application tends to be slightly different from the actual application the ddls are at. Maybe consider adding an overload that basically looks like this:
```c#
public void RegisterXmlCommentFile<T>()
{
      RegisterXmlCommentFile<T>(typeof(T).Assembly.Location.Replace(".dll", ".xml"))
}
```
That should work for most common cases where the
```xml
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
```
csproj setting is set, but still allow people to control it using the current method :)

**Comment by gregsdennis** [comment]
For your purposes, you can probably make the parameterless an extension method.

I'll have a look at the docs tomorrow.

**Comment by gregsdennis** [comment]
I've updated the docs and included your extension method until I publish another version.  Thanks for the pointers.
