### ISSUE TITLE
Evaluate JsonRequired Attribute

### ISSUE THREAD

**Issue by kostyrin** [gregsdennis/json-everything#682]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

5.4.3

### How can I help?  Please provide as much context as possible.

How to evaluate json schema with object which has properties with JsonRequiredAttribute?
I have written an example, but there are no errors in the result.
```
class MyClass
{
    [JsonRequired]
    public string RequiredString { get; set; }
}

[Test]
public void JsonSchema_Test()
{

    var schema = new JsonSchemaBuilder().FromType<MyClass>().Build();
    var jsonString = "{\"NotRequiredString\":\"not_required\"}";

    using var jDoc = JsonDocument.Parse(jsonString);
    var result = schema.Evaluate(jDoc);
    result.HasErrors.ShouldBeTrue();
}
```
Thanks for any advice

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Have you read the documentation?

https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-nullability

The attribute you're looking for is `[Required]`.  I can support more with this attribute than what `[JsonRequired]` offers.

**Comment by kostyrin** [comment]
Due to Required Attribure is more specific for `Json.Schema.Generation`. I would prefer to use moustly using System.Text.Json.Serialization.JsonRequiredAttribute like System.Text.Json.Serialization.JsonPropertyNameAttribute. It's more make sense.

**Comment by gregsdennis** [comment]
I don't think you understand.  `System.Text.Json.Serialization.JsonRequiredAttribute` can't support the functionality I need for schema generation.  That's why I created a new attribute.

**Comment by kostyrin** [comment]
just after evaluation should be has errors due to RequiredString is marked as required with JsonRequired attribute. is it possible?

**Comment by gregsdennis** [comment]
Your issue is in the schema generation, which doesn't recognize `[JsonRequired]` (and I'm not inclined to add support for it).  You need to use the `[Required]` that's supplied with the generation library.

```c#
class MyClass
{
    [Required]
    [JsonRequired]
    public string RequiredString { get; set; }
}
```

This will add the `required` keyword to the schema, which will create an error.
