### ISSUE TITLE
Model with Nullable value type is invalid

### ISSUE THREAD

**Issue by kostyrin** [gregsdennis/json-everything#684]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

5.4.3

### How can I help?  Please provide as much context as possible.

Why is model with Nullable value type not valid? Like `bool?`. Evaliation result contains errors.
this is an example
```
class MyClass
{
    public bool? RequiredBoolean { get; set; }
}

[Test]
public void JsonSchema_Test()
{

    var schema = new JsonSchemaBuilder().FromType<MyClass>().Build();
    var jsonString = "{\"RequiredBoolean\":null}";

    using var jDoc = JsonDocument.Parse(jsonString);
    var result = schema.Evaluate(jDoc);
    result.IsValid.ShouldBeTrue();
}
```
The test doesn't pass due to message error: Value is "null" but should be "boolean".
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Again, please read the [documentation](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-nullability).

You need to set `SchemaGeneratorConfiguration.Nullability` to `AllowForNullableValueTypes`.
