### ISSUE TITLE
Model is not valid when has integer value as string

### ISSUE THREAD

**Issue by kostyrin** [gregsdennis/json-everything#685]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

5.4.3

### How can I help?  Please provide as much context as possible.

How to achive model is valid when
```
public class NumberSchemaGenerator : ISchemaGenerator
{
    public bool Handles(Type type) => type.IsNumber();
    public void AddConstraints(SchemaGenerationContextBase context)
    {
        context.Intents.Add(new TypeIntent(SchemaValueType.String));
        context.Intents.Add(new TypeIntent(SchemaValueType.Number));
        context.Intents.Add(new TypeIntent(SchemaValueType.Integer));
    }
}

class MyClass
{
    public int id{ get; set; }
}

[Test]
public void JsonSchema_Test()
{
    var config = new SchemaGeneratorConfiguration();
    config.Generators.Add(new NumberSchemaGenerator());
    var schema = new JsonSchemaBuilder().FromType<MyClass>(config).Build();
    var jsonString = "{\"id\":\"123\"}";

    using var jDoc = JsonDocument.Parse(jsonString);
    var result = schema.Evaluate(jDoc);
    result.HasErrors.ShouldBeTrue();
}
```
We have specific case: all integer and long values are retrieved as string.
We get model is not valid when try to evaluate this model.
Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
`SchemaValueType` is a flags enum.  You need to combine them in a single intent rather than adding the intent multiple times.

```c#
context.Intents.Add(new TypeIntent(SchemaValueType.String | SchemaValueType.Number));
```

Think of intents as keywords: they can only be added once.
