### ISSUE TITLE
that the custom metastructure could not be parsed

### ISSUE THREAD

**Issue by wszwc** [gregsdennis/json-everything#686]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

6.0.4

### How can I help?  Please provide as much context as possible.

Hello, thank you for your help. I used your package and it solved my problem very well, but I have a few doubts:
1. Have you considered adding support for the JToken type?
2. When I tried to use schema.GenerateData() to generate a data template, an error occurred that the custom metastructure could not be parsed. Can I ignore the parts that cannot be parsed through configuration?
3. How do I convert a JsonSchema into a JsonNode object

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
> Have you considered adding support for the JToken type?

Like, from _Newtonsoft.Json_?  No.  These libraries are built on _System.Text.Json_ which is built into .Net.

> When I tried to use schema.GenerateData() to generate a data template, an error occurred that the custom metastructure could not be parsed. Can I ignore the parts that cannot be parsed through configuration?

I'll need you to open a new bug issue for this.  Please select "JsonSchema.Net.DataGeneration" as the library and provide reproduction steps.

> How do I convert a JsonSchema into a JsonNode object

Serialize it.  Please see the documentation.

**Comment by wszwc** [comment]
>> 我需要您打开一个新的错误问题。请选择“JsonSchema.Net.DataGeneration”作为库并提供替换步骤。
> 
>This is my JsonSchema file
>
[brant.json](https://github.com/gregsdennis/json-everything/files/14582664/brant.json)
> 
> > 将其序列化。请参见文档。（[暗示](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializetonode?view=net-8.0)）
> Sorry I didn't express myself clearly, I want to convert the JsonSchema type object from the Json.Schema namespace into a JsonNode

**Comment by wszwc** [comment]
> > 您是否考虑添加对 JToken 类型的支持？
> 
> 也就是说，来自_Newtonsoft.Json_？不会。这些库基于_System.Text.Json_构建，而System.Text.Json内置于.Net中。
> 
> > 当我尝试使用 schema.GenerateData() 生成数据模板时，出现无法解析自定义元结构的错误。无法通过配置解析的部分可以忽略吗？
> 
> 我需要您打开一个新的错误问题。请选择“JsonSchema.Net.DataGeneration”作为库并提供替换步骤。
> 
> > 如何将 JsonSchema 转换为 JsonNode 对象
> 
> 将其序列化。请参见文档。（[暗示](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializetonode?view=net-8.0)）
About schema.GenerateData()
This is my JsonSchema file
[brant.json](https://github.com/gregsdennis/json-everything/files/14582664/brant.json)

Sorry I didn't express myself clearly, I want to convert the JsonSchema type object from the Json.Schema namespace into a JsonNode

**Comment by wszwc** [comment]
[Uploading brant.json…]()

**Comment by gregsdennis** [comment]
> About schema.GenerateData()
> This is my JsonSchema file
> https://github.com/wszwc/ProductContentJson/blob/main/test.json

That schema file has over 6700 lines!  I'm not going to debug that.  I need you to find a smaller example that replicates the issue.

> I want to convert the JsonSchema type object from the Json.Schema namespace into a JsonNode

You expressed yourself clearly.  You need to serialize it to do that.  The link I posted is the method you need to use.

```c#
var node = JsonSerializer.SerializeToNode(schema);
```
