### ISSUE TITLE
How to extend SchemaGenerator for DateTime

### ISSUE THREAD

**Issue by kostyrin** [gregsdennis/json-everything#687]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

5.4.3

### How can I help?  Please provide as much context as possible.

How to extend DateTime Schema Generator
in case DateTime could be "2023-06-15T13:45:30" or "2023-06-15" and etc.
I have found a way only
```
internal class DateTimeSchemaGenerator : ISchemaGenerator
{
    public bool Handles(Type type) => type == typeof(DateTime) 
                                   || type == typeof(DateTimeOffset)
                                   || type == typeof(DateOnly)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateTime)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateTimeOffset)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateOnly);

    public void AddConstraints(SchemaGenerationContextBase context)
    {
        context.Intents.Add(new TypeIntent(SchemaValueType.String | SchemaValueType.Object));
        context.Intents.Add(new FormatIntent(new PredicateFormat(Formats.DateTime.Key, (node) => Predicate(node,"yyyy-MM-dd", "yyyy-MM-ddTHH:mm:ss"))));
        context.Intents.Add(new FormatIntent(new PredicateFormat(Formats.Date.Key, (node) => Predicate(node, "yyyy-MM-dd", "yyyy-MM-ddTHH:mm:ss"))));
    }

    private bool Predicate(JsonNode node, params string[] formats)
    {
        if (node.GetSchemaValueType() != SchemaValueType.String) return true;

        var dateString = node!.GetValue<string>().ToUpperInvariant();
        if (formats.Length != 0)
        {
            var canParseExact = System.DateTime.TryParseExact(dateString, formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out _);
            if (canParseExact) return true;
        }

        var regex = new Regex(@"^((?:(\d{4}-\d{2}-\d{2})([Tt_]| )(\d{2}:\d{2}:\d{2}(?:\.\d+)?))([Zz]|[\+-]\d{2}:\d{2}))$");
        var match = regex.Match(dateString);
        return match.Success;
    }
}
```
But I am not sure this is a right way.
Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
There's an example in the documentation.

https://docs.json-everything.net/schema/examples/generator/

**Comment by kostyrin** [comment]
btw formats.date and formats.datetime don't work for these formats

**Comment by gregsdennis** [comment]
Please see 
https://github.com/dotnet/runtime/issues/85545

You may need to use `pattern` instead.

`format` is an annotation anyway. It doesn't validate.

**Comment by kostyrin** [comment]
I got this: The string value is not a match for the indicated regular expression
when I have date like `2023-06-15T13:45:30`
```
internal class DateTimeSchemaGenerator : ISchemaGenerator
{
    public bool Handles(Type type) => type == typeof(DateTime) 
                                   || type == typeof(DateTimeOffset)
                                   || type == typeof(DateOnly)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateTime)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateTimeOffset)
                                   || Nullable.GetUnderlyingType(type) == typeof(DateOnly);

    public void AddConstraints(SchemaGenerationContextBase context)
    {
        context.Intents.Add(new TypeIntent(SchemaValueType.String | SchemaValueType.Object));
        context.Intents.Add(new PatternIntent(@"^(?:(\d{4}-\d{2}-\d{2})([Tt]|)(\d{2}:\d{2}:\d{2}))$"));
        context.Intents.Add(new PatternIntent(@"^(?:(\d{4}-\d{2}-\d{2}))$"));
    }
}
```

I think nice to have possibility extend Formats in case 
https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/Formats.cs#L265
like Register a new format for DateTime.

**Comment by gregsdennis** [comment]
> like Register a new format for DateTime

Please, read the documentation.

https://docs.json-everything.net/schema/basics/#schema-format

"New formats must be registered via the Formats.Register() static method. This method will overwrite any existing registration for that format, so this can be used to override the default behavior for known formats."

**Comment by kostyrin** [comment]
I mean to have any needed format like `CheckDateFormat(node, "yyyy-MM-ddTHH:mm:ss");` or extend it in SchemaGenerator

**Comment by gregsdennis** [comment]
I'm not going to do your work for you.  You have all of the pieces you need:

- How to add custom formats (including overwriting existing formats).  This applies to validation.
- How to add custom generators.  This applies to creating schemas.

Moreover, all of this information is included in the documentation and has been for a long time.
