### ISSUE TITLE
Custom `IAttributeHandler` never called

### ISSUE THREAD

**Issue by craigktreasure** [gregsdennis/json-everything#689]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.1.1

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

I am trying to write an IAttributeHandler that will use the [System.ComponentModel.DataAnnotations.DisplayAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute) to set a title and description for a schema, but the handler's `AddConstraints` method never seems to get called, despite the handler being registered via the `AttributeHandler.AddHandler<T>` method.

Based on the instructions [here](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-attributes) for writing a handler for an attribute in an external assembly, I can't tell if there is something else that I am supposed to do.

### What did you expect?

Handlers registered via `AttributeHandler.AddHandler<T>` should be invoked when a schema is being built.

### Please add test code or steps to reproduce the behavior.

```csharp
void Main()
{
	AttributeHandler.AddHandler<DisplayAttributeHandler>();
	var schema = new JsonSchemaBuilder().FromType<MyType>().Build();
	Console.WriteLine(JsonSerializer.Serialize(schema, new JsonSerializerOptions
	{
		WriteIndented = true
	}));
}

// You can define other methods, fields, classes and namespaces here
public class DisplayAttributeHandler : IAttributeHandler
{
	public DisplayAttributeHandler()
	{
		Console.WriteLine("Constructor called");
	}

	public void AddConstraints(SchemaGenerationContextBase context, Attribute attribute)
	{
		Console.WriteLine("AddConstraints called");
		// TODO: update the context
	}
}

public class MyType
{
	[System.ComponentModel.DataAnnotations.Display(Name = "Test Name", Description = "Test description")]
	public string? SomeProperty { get; set; }
}
```

When I run the code above, I get the following output:
```
Constructor called
{
  "type": "object",
  "properties": {
    "SomeProperty": {
      "type": "string"
    }
  }
}
```

### Is there any other information you'd like to share regarding this bug?

I've attempted this code all the way back through version 2.2.1 with the same result.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll dig in and see what's going on.

**Comment by gregsdennis** [comment]
Ah, you need to use the `IAttributeHandler<T>` interface.

```c#
public class DisplayAttributeHandler : IAttributeHandler<DisplayAttribute>
```

**Comment by craigktreasure** [comment]
Ah. I see. Is the use of the non-generic `IAttributeHandler` no longer valid?

**Comment by gregsdennis** [comment]
It never really was.  The base non-generic version is just so I can hold them all in a list.

Looking at the registration methods, though, it seems they should probably use the generic.

```c#
void AddHandler<T>() where T : IAttributeHandler, new()
```

could be

```c#
void AddHandler<THandler, TAttribute>()
    where TAttribute: Attribute
    where THandler : IAttributeHandler<TAttribute>, new()
```

But that second type parameter feels clunky, which may be why I left it off.  You'd have to call this like

```c#
AttributeHandler.AddHandler<DisplayAttributeHandler, DisplayAttribute>();
```

**Comment by gregsdennis** [comment]
Related discussion: https://github.com/dotnet/csharplang/discussions/2845
