### ISSUE TITLE
Anchors naming of 2020 still following 2019 rules

### ISSUE THREAD

**Issue by Era-cell** [gregsdennis/json-everything#690]
### Nuget Package

JsonSchema.Net

### Package Version

6.0.4

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net Framework

### A clear and concise description of the bug.

The 2020 spec says anchor naming can start from "_" and not include ":", but _ isnt supported and : still works:

### What did you expect?

I expect ":" not to work and "_" to work

### Please add test code or steps to reproduce the behavior.

the website where I tested: https://json-everything.net/json-schema
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "if": {
        "properties": {
            "foo": {
              "$anchor":"it:em",
              "const": "then" }
        },
        "required": ["foo"]
    },
    "$ref":"#it:em"
  }

use 2020 schema evaluation

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Hey, thanks for reporting.

This is actually something that would be a great addition to the [Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite).

Would you mind opening an issue there, please?

**Comment by gregsdennis** [comment]
@Era-cell I had already gone that route, and it was decided that the Test Suite isn't set up for such tests, and they're just be meta-schema tests.

I've already added these locally.  There's nothing left to do here.

**Comment by gregsdennis** [comment]
That's a long-standing issue _in that repo_ and should be discussed there with the appropriate people, not in this repo.
