### ISSUE TITLE
Nullable decimal type removes multipleOf

### ISSUE THREAD

**Issue by rhwork** [gregsdennis/json-everything#696]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.0.0

### How can I help?  Please provide as much context as possible.

If I have the following code:

```
        [Nullable(true)]
        [MultipleOf(0.1)]
        public decimal? Apr { get; set; }
```

the generated schema looks like:

```
    "Apr": {
      "type": [
        "number",
        "null"
      ]
    },
```
If I change decimal? to decimal I get:

```
    "Apr": {
      "type": [
        "number",
        "null"
      ],
      "multipleOf": 0.1
    },
```

Is it possible to achieve the second result with a nullable decimal? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.  This is an interesting find!
