### ISSUE TITLE
Boolean applicator keywords must be non-empty

### ISSUE THREAD

**Issue by Era-cell** [gregsdennis/json-everything#697]
### Nuget Package

JsonSchema.Net

### Package Version

6.0.4

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

The meta-schema https://json-schema.org/draft/2020-12/meta/applicator has minItems in schemArray: i.e, for allOf, anyOf.. any array. But schema works for thsi:
```
{
  "$id":"http://example.com",
  "allOf":[]
}
```
And validates anything

### What did you expect?

Invalid schema

### Please add test code or steps to reproduce the behavior.

execute

```json
 {
  "$id":"http://example.com",
  "allOf":[]
}
```

in json-everything

### Is there any other information you'd like to share regarding this bug?

No

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll update this in the next version.
