### ISSUE TITLE
Verified error reporting type

### ISSUE THREAD

**Issue by wszwc** [gregsdennis/json-everything#701]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

6.0.4

### How can I help?  Please provide as much context as possible.

1. I want to know whether Evaluate contains error reports for prohibited types. I don’t seem to have received any error reports about this part.
2. I received the three report types of enum, contains, and required, but the error message about enum was 'Value should match one of the values specified by the enum'. But my json conforms to the enum given by JsonSchema. Below is an example

This is the JsonSchema of the error attribute
![fb3d7b4132a2e6ba2c32a73e74d239ae](https://github.com/gregsdennis/json-everything/assets/107897055/a714362f-73cb-458e-8e90-510b574b9594)

This is my json
![78eabae490d464134cee1a66a70b35c9](https://github.com/gregsdennis/json-everything/assets/107897055/3df7afda-908a-48c4-9460-2447d0b09ad0)

```json
{
  "allOf": [
    {
      "if": {
        "anyOf": [
          {
            "not": {
              "required": [
                "parentage_level"
              ],
              "properties": {
                "parentage_level": {
                  "items": {
                    "required": [
                      "value"
                    ]
                  }
                }
              }
            }
          },
          {
            "not": {
              "required": [
                "parentage_level"
              ],
              "properties": {
                "parentage_level": {
                  "contains": {
                    "required": [
                      "value"
                    ],
                    "properties": {
                      "value": {
                        "enum": [
                          "parent"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "then": {
        "required": [
          "model_name"
        ]
      }
    },
    {
      "if": {
        "allOf": [
          {
            "required": [
              "child_parent_sku_relationship"
            ],
            "properties": {
              "child_parent_sku_relationship": {
                "items": {
                  "required": [
                    "parent_sku"
                  ]
                }
              }
            }
          },
          {
            "not": {
              "required": [
                "parentage_level"
              ],
              "properties": {
                "parentage_level": {
                  "contains": {
                    "required": [
                      "value"
                    ],
                    "properties": {
                      "value": {
                        "enum": [
                          "parent"
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "required": [
              "variation_theme"
            ],
            "properties": {
              "variation_theme": {
                "contains": {
                  "required": [
                    "name"
                  ],
                  "properties": {
                    "name": {
                      "enum": [
                        "MODEL_NAME/COLOR_NAME/CONFIGURATION",
                        "MODEL_NAME/TEAM_NAME/SIZE_NAME"
                      ]
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "then": {
        "required": [
          "model_name"
        ]
      }
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for the question.  It seems you've posted partial information.  In order to provide better assistance, would you please post complete data and schemas in a _minimal_ reproduction that shows what you're trying to ask?

**Comment by gregsdennis** [comment]
You may also find [this blog post](https://json-schema.org/blog/posts/interpreting-output) helpful.  It explains why you might get errors from schemas in conditional constructs.

**Comment by wszwc** [comment]
I read your blog and I'm currently getting the unfilled required fields just fine via Evaluate, but I still don't understand if it's possible to get the following information via the Evaluate method:
Because the A attribute exists, the B attribute cannot exist, like this
That is, return attribute values that cannot be filled in because a certain condition is met.

**Comment by gregsdennis** [comment]
> return attribute values that cannot be filled in because a certain condition is met.

The only way to get this is through interpretation of the output.  For example, you'll need to browse the results to find the output node for the `if` keyword, which will tell you whether the condition was met.  Once you have that, you can go to the node for the assocated `then` keyword.

This is easier to see in the `Heirarchical` output format.

Again, if you can come up with a minimal example, I can walk you through it.

**Comment by wszwc** [comment]
Sorry for the long wait. My data is too large and it is difficult for me to find similar examples. I wrote one manually, as follows

```{
  "type" : "object",

    "properties" :{
	"shirt_size":{
		"type" : "array",
		"items":{
			  "type" : "object",
			  "properties": {
				"A":{
					"type" : "string",
					"enum":["a1","a2","a3"]
					},
				"B":{
					"type" : "string"
					},	

						},
		"required":["A"]
                              }
   				}
			},

  "allOf": [
    {
      "if": {
        "properties": {
          "A": { "enum": ["a1"] }
        }
      },
      "then": {
        "not": {
          "required": ["B"]
        }
      }
    }
  ]
}}

**Comment by wszwc** [comment]
I used the following data for verification,However, the result output by Evaluate does not return relevant information that cannot be filled in with the B attribute.

```json
{
  "shirt_size": [
    {
      "A": "a1",
      "B": "test"
    }
  ]
}
```

**Comment by wszwc** [comment]
> 再说一次，如果你能想出一个最小的例子，我可以引导你完成它。

This is the message returned

```json
{
  "valid": true,
  "details": [
    {
      "valid": true,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/94a566ed28#",
      "instanceLocation": "",
      "annotations": {
        "if": true
      }
    },
    {
      "valid": true,
      "evaluationPath": "/if",
      "schemaLocation": "https://json-everything.net/94a566ed28#/if",
      "instanceLocation": "",
      "annotations": {
        "properties": [
          "shirt_size"
        ]
      }
    },
    {
      "valid": true,
      "evaluationPath": "/then",
      "schemaLocation": "https://json-everything.net/94a566ed28#/then",
      "instanceLocation": ""
    },
    {
      "valid": true,
      "evaluationPath": "/if/properties/shirt_size",
      "schemaLocation": "https://json-everything.net/94a566ed28#/if/properties/shirt_size",
      "instanceLocation": "/shirt_size",
      "annotations": {
        "items": true
      }
    },
    {
      "valid": false,
      "evaluationPath": "/then/not",
      "schemaLocation": "https://json-everything.net/94a566ed28#/then/not",
      "instanceLocation": "",
      "errors": {
        "required": "Required properties [\u0022B\u0022] are not present"
      }
    },
    {
      "valid": true,
      "evaluationPath": "/if/properties/shirt_size/items",
      "schemaLocation": "https://json-everything.net/94a566ed28#/if/properties/shirt_size/items",
      "instanceLocation": "/shirt_size/0",
      "annotations": {
        "properties": [
          "A"
        ]
      }
    },
    {
      "valid": true,
      "evaluationPath": "/if/properties/shirt_size/items/properties/A",
      "schemaLocation": "https://json-everything.net/94a566ed28#/if/properties/shirt_size/items/properties/A",
      "instanceLocation": "/shirt_size/0/A"
    }
  ]
}
```

**Comment by gregsdennis** [comment]
> However, the result output by Evaluate does not return relevant information that cannot be filled in with the B attribute.

I don't understand this.  Can you elaborate?  What exactly are you looking for?  What are your requirements?

**Comment by wszwc** [comment]
> > 但评估输出的结果并无法返回无法使用B属性填写的相关信息。
> 
> 我不明白这一点。你能详细说明一下吗？你到底在寻找什么？你有什么要求？

In my example, my data should not meet the requirements, because the value of 'A' is obviously 'a1', but Evaluate verifies as true and outputs the message in my example, so I want to know, Evaluate cannot get it Information about certain fields being disabled

**Comment by elgonzo** [comment]
Your 
```
"then": {
        "not": {
          "required": ["B"]
        }
      }
```
schema appears to be testing the absence of the "B" property in the **root** object, not in the item objects of the "shirt_size" array, hence why validation passes.

**Comment by elgonzo** [comment]
I don't think your schema is correct. 
Note how you declare a "not" property name instead of using the "not" schema keyword due to it being placed inside the "properties" keyword. Try this instead:
```
      "then": {
        "properties": {
          "shirt_size": {
            "items": {
                "not": {
                  "required": [ "B" ]
              }
            }
... (sorry, can't be bothered to count the correct amount of closing braces ;-P)
```

**Comment by wszwc** [comment]
> 我建议不要使用`not: { required: [ B ] }`use `properties: { B: false }`。这通过禁止所有值来_禁止。_ `B`

Sorry, the example I gave is imitating Amazon's JsonSchema. They did not use the solution you provided, but the example I gave. This is not your problem.
In my case, I noticed that if the A attribute is 'a1', and the B attribute is present, it will report an error in another way.
It will tell me, "Value should match one of the values specified by the enum", whose example pointer points to the A property, not the B property.
Based on this information, I can only know that the enumeration of attribute A conflicts with other attributes, but I don’t know which attribute it is.

**Comment by gregsdennis** [comment]
I'm not sure what you're looking for here.

- Is the validation passing, but you're still receiving an error, and you don't understand why?
- Is the validation failing, but you're unable to determine what caused the failure?
- Something else?

I don't understand the problem.

**Comment by gregsdennis** [comment]
I'm sorry, but if the above doesn't get you to a solution, I don't know how to help here.

If you can devise a smaller example that demonstrates what you're looking for, I can probably help walk through that.  Feel free to re-open the issue if you want to continue.
