### ISSUE TITLE
Schema exception {"An item with the same key has already been added. Key: Child"}

### ISSUE THREAD

**Issue by ptr727** [gregsdennis/json-everything#703]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.3.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Generating a schema from a class that contains multiple definitions of the same attribute throws a duplicate key exception.

The code has several inherited record classes, with new versions marked as `[JsonRequired]`, and old versions marked as `[Obsolete]` but with the `[JsonRequired]` removed. This allows old json schema versions to be read using Text.Json, while only writing the current versions.

### What did you expect?

I expect the schema generation to succeed, and to use the "current" or `[JsonRequired]` version of the schema elements, not the `[Obsolete]` marked elements.

### Please add test code or steps to reproduce the behavior.

Example code (more elaborate tan required, but what I am using to help troubleshoot Json.Net to Text.Json conversion):

```csharp
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using Json.Schema;
using Json.Schema.Generation;

// Must contain something to keep the compiler happy
#pragma warning disable CS0219
int foo = 1;
#pragma warning restore CS0219

// Create test object and populate it with some data
/*
var parent1 = new Parent1()
{
    Child = new Child1()
    {
        List = [
            new() { Foo = "foo1", Bar = "bar1" },
            new() { Foo = "foo2", Bar = "bar2" }
            ]
    }
};
*/
const string parent1Json = "{\r\n  \"Child\": {\r\n    \"List\": [\r\n      {\r\n        \"Foo\": \"foo1\",\r\n        \"Bar\": \"bar1\"\r\n      },\r\n      {\r\n        \"Foo\": \"foo2\",\r\n        \"Bar\": \"bar2\"\r\n      }\r\n    ]\r\n  }\r\n}";

// Convert to and from JSON using Newtonsoft
var parentN1 = Newtonsoft.Json.JsonConvert.DeserializeObject<Parent1>(parent1Json, JsonHelper.JsonSerializerSettingsRead);
ArgumentNullException.ThrowIfNull(parentN1);
var parentN2 = new Parent2(parentN1);
var jsonN = Newtonsoft.Json.JsonConvert.SerializeObject(parentN2, JsonHelper.JsonSerializerSettingsWrite);
Console.WriteLine(jsonN);

// Convert to and from JSON using Text.Json
var parentT1 = JsonSerializer.Deserialize<Parent1>(parent1Json, JsonHelper.JsonSerializerOptionsRead);
ArgumentNullException.ThrowIfNull(parentT1);
var parentT2 = new Parent2(parentT1);
var jsonT = JsonSerializer.Serialize(parentT2, JsonHelper.JsonSerializerOptionsWrite);
Console.WriteLine(jsonT);

// Create JSON schema
const string SchemaUri = "https://raw.githubusercontent.com/ptr727/PlexCleaner/main/PlexCleaner.schema.json";
var schemaBuilder = new JsonSchemaBuilder();
var schema = schemaBuilder.FromType<Parent2>()
    .Title("PlexCleaner Configuration Schema")
    .Id(new Uri(SchemaUri))
    .Build();
Console.WriteLine(schema.ToString());


public static class JsonHelper
{
    public static readonly Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettingsRead = new Newtonsoft.Json.JsonSerializerSettings
    {
        ObjectCreationHandling = Newtonsoft.Json.ObjectCreationHandling.Reuse
    };

    public static readonly Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettingsWrite = new Newtonsoft.Json.JsonSerializerSettings
    {
        Formatting = Newtonsoft.Json.Formatting.Indented,
        StringEscapeHandling = Newtonsoft.Json.StringEscapeHandling.EscapeNonAscii,
        NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore,
        ContractResolver = new ExcludeObsoletePropertiesResolver()
    };

    public static readonly JsonSerializerOptions JsonSerializerOptionsRead = new JsonSerializerOptions
    {
        IncludeFields = true,
        PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    };

    public static readonly JsonSerializerOptions JsonSerializerOptionsWrite = new JsonSerializerOptions
    {
        IncludeFields = true,
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        TypeInfoResolver = new DefaultJsonTypeInfoResolver()
            .WithAddedModifier(ExcludeObsoleteProperties)
    };

    public static void ExcludeObsoleteProperties(JsonTypeInfo typeInfo)
    {
        if (typeInfo.Kind != JsonTypeInfoKind.Object)
            return;
        foreach (var property in typeInfo.Properties)
        {
            if (property.AttributeProvider?.IsDefined(typeof(ObsoleteAttribute), true) == true)
                property.ShouldSerialize = (_, _) => false;
        }
    }
}

public record Parent1
{
    [Obsolete]
    public Child1 Child { get; set; } = new();
}

public record Parent2 : Parent1
{
    public Parent2(Parent1 parent) : base(parent) 
    { 
        Upgrade(); 
    }

    [JsonRequired]
    public new Child2 Child { get; set; } = new();

#pragma warning disable CS0612 // Type or member is obsolete
    protected void Upgrade() 
    { 
        Parent1 parent1 = this;
        Child.NewList.AddRange(parent1.Child.List);
        parent1.Child.List.Clear();
    }
#pragma warning restore CS0612 // Type or member is obsolete
}

public record Sub
{
    public string Foo = "";
    public string Bar = "";
}

public record Child1
{
    public Child1() { }

    [Obsolete]
    public List<Sub> List { get; set; } = [];
}

public record Child2 : Child1
{
    public Child2() { }
    public Child2(Child1 child) : base(child) { }

    [JsonRequired]
    public List<Sub> NewList { get; set; } = [];
}

public class ExcludeObsoletePropertiesResolver : Newtonsoft.Json.Serialization.DefaultContractResolver
{
    protected override List<MemberInfo> GetSerializableMembers(Type objectType)
    {
        var memberList = base.GetSerializableMembers(objectType);
        memberList.RemoveAll(item => item.IsDefined(typeof(ObsoleteAttribute), true));
        return memberList;
    }
}
```

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by elgonzo** [comment]
Note that, as per [documentation](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-best-practices), JsonSchema.Net.Generation translates a member with an `[obsolete]` attribute into a schema that is deprecated (e.g., a schema that has its "deprecated" keyword being set to _true_). In other words, the `[obsolete]` does _not_ instruct the json schema generator to ignore the respective member, contrary to your assumption.

As the documentation i linked to explains, if you want to exclude/ignore the properties you marked as obsolete you should use either the `[JsonIgnore]` attribute from STJ or JsonSchema.Net.Generation's attribute `[JsonExclude]`. Note that the STJ attribute obviously has an effect on the STJ (de)serializer, whereas attributes from JsonSchema.Net.Generation won't affect the STJ (de)serializer.

**Comment by ptr727** [comment]
Thank you

Starting with `ToString()`, I almost line for line copied my Json.Net schema generation code, including `ToString()`, and never got that far to discover the issue ;)

I do want old config to be read but not written, so as you state `[JsonIgnore]` would not be the right choice.

If `[Obsolete]` is translated into `deprecated`, and the code seems valid for read and write, is the duplicate key exception really "not a bug", or is there no schema that can represent my code with all versions, including `deprecated`, accounted for?

Other than adding `JsonSchema.Net.Generation.JsonExclude]` to all the `[Obsolete]` items, is there no way to dynamically filter the schema generation, e.g. as I do for writing in `ExcludeObsoleteProperties()`?

**Comment by elgonzo** [comment]
> If `[Obsolete]` is translated into `deprecated`, and the code seems valid for read and write, is the duplicate key exception really "not a bug", or is there no schema that can represent my code with all versions, including `deprecated`, accounted for?

You should be able to represent this situation in a json schema using the `anyOf` composition keyword for the schema associated with the Child property. It seems the generator is not able to do this on its own. I'd suggest to manually improve the schema in this way after schema generation. Since it is strongly recommended to do a manual review of the generated schema(s) anyways, as stated by the [documentation](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-disclaimer):

> Ideally, this functionality should be used to create a starting point in authoring a schema. The schemas output by this library should be reviewed by actual people prior to being put into a production system.

I am not aware of other quick and easy ways to do this, unfortunately, and i'd like to defer to the author/maintainer of JsonSchema.Net.Generation with respect to advising what is the best way to address this scenario.

That said, i know of two ways to technically address your issue, but they don't seem appealing to me for different reasons.

There is the possibility of telling the schema generator your intents (https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-extension) regarding the usage of `anyOf`. But you would still need to implement some logic that detects hidden properties/fields in the types for which are schemas generates and composes an `AnyOfIntent` accordingly. The simplest place for doing that would theoretically be a refiner (see the aforementioned documentation link), but you would then still need to avoid/suppress the exception. Which would leave you with the unfortunate situation that you would still need to use for example the `[JsonExclude]` attribute, which kinda reads opposite to what the desired outcome will be.

The second way i know of that would also avoid needing `[JsonExclude]` annotations would be to implement your own schema generator. But that's costly, because you can't simply derive from and override the behavior of the default ObjectSchemaGenerator (because it is an internal type and neither has overridable methods) and thus would require you to basically reinvent the schema generation wheel here, so to speak. Which also to a large degree nullifies the convenience of using the JsonSchema.Net.Generation if you choose to do that. So, basically, i wouldn't recommend doing that either, because for this effort to be justified you would need to generate schemas for a metric ton of types with a butt load of hidden members you want to be accounted for in the schemas.

**Comment by gregsdennis** [comment]
I agree with the refiner approach.  In the refiner, you'd want to check for a `PropertiesIntent` that has any entries with a `DeprecatedIntent` keyword, and then remove those entries.

**Comment by gregsdennis** [comment]
Funnily, looking at it now, it seems I've left out support for `[Required]`.  I'll need to add that in, or a PR could be contributed....

**Comment by gregsdennis** [comment]
(Sorry about the previous comment.  Getting issues confused.)

Refiners and everything else is in the [docs](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-refiners), which has links in all the right places.

**Comment by ptr727** [comment]
Thank you, will investigate and report back.

**Comment by ptr727** [comment]
A custom refiner looked like it would take me more time than I was willing to spend on this, so I'm just using `[JsonSchema.Net.Generation.JsonExclude]` and `[obsolete]`.

As an enhancement a general option to exclude`[obsolete]` items could be added, or an easier way to customize behavior similar to e.g. `WithAddedModifier()`.
