### ISSUE TITLE
Possibly wrong return type

### ISSUE THREAD

**Issue by SGStino** [gregsdennis/json-everything#704]
### Nuget Package

JsonSchema.Net

### Package Version

6.0.7

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

```csharp
public static IReadOnlyCollection<JsonSchema>? GetPrefixItems(this JsonSchema schema)
```
 Should most likely return `IReadOnlyList<JsonSchema>`, as the keyword has 
```csharp
public IReadOnlyList<JsonSchema> ArraySchemas { get; }
```

Meaning you can't use the indexer, and have to resort to LINQ's `ElementAt(index)`, 
and since, if i interpret the spec right, it relies on the ordering of the items, it's not just collection, but an ordered collection: a list as  way to define typed tuples?

### What did you expect?

```csharp
public static IReadOnlyList<JsonSchema>? GetPrefixItems(this JsonSchema schema)
```

### Please add test code or steps to reproduce the behavior.

N/A

### Is there any other information you'd like to share regarding this bug?

Found a few others: 
```csharp
    public static IReadOnlyCollection<JsonSchema>? GetOneOf(this JsonSchema schema)	 
    public static IReadOnlyCollection<JsonSchema>? GetAllOf(this JsonSchema schema)	 
    public static IReadOnlyCollection<JsonSchema>? GetAnyOf(this JsonSchema schema)	 	 
    public static IReadOnlyCollection<JsonSchema>? GetItemsArrayForm(this JsonSchema schema)	 
    public static IReadOnlyCollection<JsonSchema>? GetPrefixItems(this JsonSchema schema)	 
```

 

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Yeah, I can update those, but it would be a breaking change, so it could be a bit.  For now, feel free to just cast them.  I'm not doing any transformations from the keywords, so a direct cast will work.

**Comment by SGStino** [comment]
No worries, if only dotnet's ElementAt would have checked for IReadOnlyList instead of IList 

But, is it breaking? IReadOnlyList implements IReadOnlyCollection, so all code that works now, should remain working?
It might need recompiling, not 100% sure how the CLI handles that at runtime, is the return type part of the signature?

**Comment by gregsdennis** [comment]
Return type _is_ part of the signature, but I think you're right.  This would be breaking if these methods were on an interface, but not as static methods.

**Comment by elgonzo** [comment]
No, return type is NOT part of the signature. That's why you can't have method overloads that only differ in return type.

**Comment by SGStino** [comment]
Doesn't matter, it still doesn't like it:
```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<Char> MethodSignatureTest.Lib.Extensions.GetContents(System.String)'.
   at Program.<Main>$(String[] args)
```
When i update only the called assembly from:
```csharp
namespace MethodSignatureTest.Lib
{
    public static class Extensions
    {

        public static IReadOnlyCollection<char> GetContents(this string data)
        {
            return data.ToCharArray();
        }
    }
}
```
to:
```csharp
namespace MethodSignatureTest.Lib
{
    public static class Extensions
    {

        public static IReadOnlyList<char> GetContents(this string data)
        {
            return data.ToCharArray();
        }
    }
}

```
while living the calling assembly intact:
```csharp 
using MethodSignatureTest.Lib;

var bytes = "hello world".GetContents();

Console.WriteLine("Hello, World:" + bytes.Count);
```

So yes, the return type is not part of the signature for compilation, but once compiled, it does matter.

**Comment by elgonzo** [comment]
> So yes, the return type is not part of the signature for compilation, but once compiled, it does matter.

Oh dang, you're right.

**Comment by gregsdennis** [comment]
@SGStino would you like to submit a PR for these changes?

**Comment by SGStino** [comment]
Sure, I'll have a look

**Comment by gregsdennis** [comment]
A collection is more general.  There's no reason you should need to access them with an index.

They should also all be read-only.

**Comment by SGStino** [comment]
Then it should be https://github.com/gregsdennis/json-everything/pull/707?
