### ISSUE TITLE
Customizing the `format` generated for a field (without attributes)

### ISSUE THREAD

**Issue by jonschoning** [gregsdennis/json-everything#705]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.3.0

### How can I help?  Please provide as much context as possible.

given a class
```cs
public class MyType
{
  public string Id { get; set; }
  public string Name { get; set; }
  public string RichText { get; set; }
}
```
- I want to generate a JSON Schema for the `MyType` class at run-time and do not want to specify the json schema independantly.
- I cannot add attributes to this class; it must be referenced as-is
- I want to add a custom [format ](https://json-schema.org/understanding-json-schema/reference/string#format) specifier, only to the `RichText` field of this class e.g. `"format": "richtext"`
- since each field's C# type is `string`, I cannot use this to target only the `RichText` field

With the provided documentation using `Generators`, `Intents`, `Attributes` (not applicable here), and `Refiners`, I cannot figure out how to customize generation to target only the `RichText` field to which to add "format": "richtext"`.

example desired generated json schema: 
```json
{
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "RichText": {
      "type": "string",
      "format": "richtext"
    }
  }
}
```
How would I achieve this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. What you want is a [refiner](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-refiners).

Inside the refiner, check for a `TypeIntent` with a value of `object` alongside a `PropertiesIntent` that defines your `RichText` property.  Then you can add a `Format Intent` directly to that property.

**Comment by jonschoning** [comment]
with the following refiner: 
```cs
 public class MyTypeRefiner : ISchemaRefiner
 {
     public void Run(SchemaGenerationContextBase context)
     {
         var propsIntent = (PropertiesIntent)context.Intents[1];
         var richTextField = propsIntent.Properties["RichText"];
         richTextField.Intents.Add(new FormatIntent(new Format("richtext")));
         return;
     }

     public bool ShouldRun(SchemaGenerationContextBase context)
     {
         return context.Type.Name == "MyType";
     }
 }
```
i get 
```json
{
    "type": "object",
    "properties": {
        "Id": {
            "$ref": "#/$defs/string"
        },
        "Name": {
            "$ref": "#/$defs/string"
        },
        "RichText": {
            "$ref": "#/$defs/string"
        }
    },
    "$defs": {
        "string": {
            "type": "string",
            "format": "richtext"
        }
    }
}
```

how do i modify the Run method to avoid creating $defs and also only select richtextfield and not the others?

**Comment by gregsdennis** [comment]
Hm... Yeah, it looks like the change is affecting the other properties.  The generator reuses the context for all of the properties because the type and attribute set (which is "no attributes") is the same.  So what you really need is to create a new context for that property...

But you can't because the context constructors are internal.

What you _could_ do (which isn't very obvious) is call `SchemaGenerationContextCache.Get()` with the type and a fabricated `format` attribute (which you'll need to [make](https://docs.json-everything.net/schema/schemagen/schema-generation/#schema-schemagen-attributes) because I don't have one 🤦).  There are a few house-keeping things you'll need to do as well.

```c#
var propsIntent = (PropertiesIntent)context.Intents[1];
var oldRichTextField = propsIntent.Properties["RichText"];
oldRichTextField.References--;

var newRichTextField = SchemaGeneratorContextCache.Get(oldRichTextField.Type, new[]{new FormatAttribute("richtext")}); // you'll need to create and implement FormatAttribute

propsIntent.Properties["RichText"] = newRichTextField;
```

**Comment by jonschoning** [comment]
the following code produces the correct output:
```cs
    [AttributeUsage(AttributeTargets.Property)]
    public class FormatAttribute : Attribute, IAttributeHandler<FormatAttribute>
    {
        public string Format { get; }

        public FormatAttribute(string format)
        {
            Format = format;
        }

        public void AddConstraints(SchemaGenerationContextBase context, Attribute attribute)
        {
            context.Intents.Add(new FormatIntent(new Format(Format)));
        }
    }

    public class MyTypeRefiner : ISchemaRefiner
    {

        // create a new context for the property
        public void ReplaceProperty(PropertiesIntent propsIntent, string propName, List<Attribute> attributes)
        {
            var property = propsIntent.Properties[propName];
            property.ReferenceCount--;
            propsIntent.Properties[propName] = SchemaGenerationContextCache.Get(property.Type, attributes);

        }
        public void Run(SchemaGenerationContextBase context)
        {
            var propsIntent = (PropertiesIntent)context.Intents[1];
            ReplaceProperty(propsIntent, nameof(MyType.RichText), [new FormatAttribute("richtext")]);
        }

        public bool ShouldRun(SchemaGenerationContextBase context)
        {
            return context.Type.Name == nameof(MyType);
        }
    }
```

**Comment by gregsdennis** [comment]
Glad you worked it out.  I think I might add this as an example in the docs!
