### ISSUE TITLE
Json.Schema.KeywordExtensions is not thread safe with custom keywords

### ISSUE THREAD

**Issue by jnystad** [gregsdennis/json-everything#710]
### Nuget Package

JsonSchema.Net

### Package Version

5.3.1

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

`_keywordNames` is updated on first occurrence of custom keywords. This operation uses a plain Dictionary instead of a ConcurrentDictionary and is therefore not thread safe.

### What did you expect?

Using Json.Schema should be thread safe.

### Please add test code or steps to reproduce the behavior.

This is a race condition. A reproduction case that is guaranteed to trigger this error is not trivial to create.

The fix is fairly straightforward, though. Use ConcurrentDictionary for caches that may be updated in code paths called during schema building (already done in SchemaKeywordRegistry, for example).

### Is there any other information you'd like to share regarding this bug?

This was mentioned in #503, but rejected due to not having a repro case. If desired, I can create a PR with suggested changes. Let me know.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
I think this is resolved with v7.  I've reworked the keyword registry, and it's now using a custom `MultiLookupConcurrentDictionary<T>` which is backed by `ConcurrentDictionary<TKey, TValue>`.
