### ISSUE TITLE
Update Nuget package meta-data

### ISSUE THREAD

**Issue by thompson-tomo** [gregsdennis/json-everything#711]
### Summary
I wish for the nuget packages to have the licence expression property set correctly

### Details

The licence expression property should be set to the correct licence type I.e. MIT as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by elgonzo** [comment]
Could you please clarify what exactly you are talking about?

I just checked JsonShema.NET 6.1.0 and 6.0.4 nuget package, and their nuspec files features a license expressions for the MIT license.

**Comment by elgonzo** [comment]
Okay, i can confirm. Every nuget package listed on https://github.com/gregsdennis/json-everything# except the JsonSchema.NET package doesn't have an MIT license expression in their respective nuspec files.

**Comment by gregsdennis** [comment]
Nuget has updated how they capture various information since I started publishing packages, and I just haven't kept up.  For instance, I need to create proper readmes as well.

**Comment by thompson-tomo** [comment]
Thanks @gregsdennis
