### ISSUE TITLE
Online schema validator: Is successful validation of illegal json just a quirk or intentional

### ISSUE THREAD

**Issue by elgonzo** [gregsdennis/json-everything#716]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

Whichever JsonSchema.Net version https://json-everything.net/json-schema is using, but in all likelihood the reported quirk is not in the JsonSchema.Net library but rather specific to the online schema validator.

### How can I help?  Please provide as much context as possible.

This is not really a question, but rather highlighting a quirk (perhaps a bug?) of the online schema validator at https://json-everything.net/json-schema just in case you are not already aware of it.

Given is the following json instance:
```
{
   "Number": .123,
   "String": foo
}
```
Note that this is not legal json, as (A) numbers in the json format are not allowed to have a decimal dot without a preceding numerical digit, and (B) string values need to be surrounded by double quotes.

Yet, validating this not exactly legal json with the online schema validator at https://json-everything.net/json-schema against the schema:
```
{
  "type": "object",
  "properties":
  {
    "Number": { "type": "number" },
    "String": { "type": "string" }
  }
}
```
will succeed with a validation result of true.

In a similar fashion, the schema json can also be "vandalized" and turned into illegal json by stripping the double quotes from it, yet the online schema validator still parses the schema json as if the double quotes were there and doesn't notice any issues.

Not sure if allowing such malformed/illegal json for the json instances and/or schema json is just a quirk of the online validator or an intentional design decision, but since i didn't manage to find any other report mentioning this i thought it's better to let you know...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
You may notice that the syntax highlighting changes when it's not valid JSON.  At that point it's interpreting as YAML and sending the text through Yaml2JsonNode's converter. 

In short, it's intentional, but what's happening could be made more obvious to the user.

**Comment by gregsdennis** [comment]
I've updated the site to have little language tags in the upper right of the editors.  It'll change as you edit, but I was having a hard time getting them to initialize right.  Not sure what the deal is, and I'm tired of fighting it.

I hate web dev.  Blazor makes it a little better, but it's really just different magic.

**Comment by gregsdennis** [comment]
> Whichever JsonSchema.Net version https://json-everything.net/json-schema is using

The site is always using the latest.  It'll also tell you.

![image](https://github.com/gregsdennis/json-everything/assets/2676804/d0c49c33-f940-4812-8cea-bd33d277d83c)

**Comment by elgonzo** [comment]
> The site is always using the latest. It'll also tell you.

Thanks for the clarification. I saw this, but it was unclear to me whether this is just meant to be a link to the latest nuget package on nuget.org or whether this is also signifying the JsonSchema.Net version the online validator is using.

**Comment by gregsdennis** [comment]
This is why I keep the site in the same solution.  It uses the projects directly, not the Nuget packages.
