### ISSUE TITLE
System.MissingMethodException for IReadOnlyCollection<JsonNode> after updating from JsonSchema.Net.Generation 4.3.0 to 4.3.0.2

### ISSUE THREAD

**Issue by KevinD-87** [gregsdennis/json-everything#718]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

4.3.0.2

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

When using AsyncAPI generation via the Neuroglia [asyncapi](https://github.com/neuroglia-io/asyncapi) package, which relies on JsonSchema.Net.Generation, in combination with the latest version of said package, the following exception occurs: 
`Unhandled exception. System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<System.Text.Json.Nodes.JsonNode> Json.Schema.JsonSchemaExtensions.GetExamples(Json.Schema.JsonSchema)'.`

This looks like a breaking change in the library?

### What did you expect?

For the above call to succeed.

### Please add test code or steps to reproduce the behavior.

-

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Crap, I thought so.  cc: @SGStino

I'm going to revert this and unlist these packages.

**Comment by gregsdennis** [comment]
Reversion pushed.  New package v6.1.2 should work for you.

**Comment by KevinD-87** [comment]
@gregsdennis I can confirm the latest version fixed the issue. Thanks for the quick fix!

**Comment by SGStino** [comment]
> Crap, I thought so. cc: @SGStino (#704)
> 
> I'm going to revert this and unlist these packages.

We did the test in that issue: https://github.com/gregsdennis/json-everything/issues/704#issuecomment-2048227375 

It requires a recompile, but in this case, of an intermediate package. So yes, queueing it for the next major might be a good thing.

**Comment by gregsdennis** [comment]
@SGStino I have included these changes in v7.
