### ISSUE TITLE
Can't get DiscriminatorKeyword working

### ISSUE THREAD

**Issue by darrelmiller** [gregsdennis/json-everything#720]
### Nuget Package

JsonSchema.Net.OpenApi

### Package Version

3.0.0.2

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

This test fails
```csharp
        [Fact]
        public void CreateDiscriminatorKeyword() {
            Json.Schema.OpenApi.Vocabularies.Register();
            var keyword = new DiscriminatorKeyword("petType",null,null);
            Assert.NotNull(keyword);
        }
```
with the error

```
System.InvalidCastException : Unable to cast object of type 'Json.Schema.OpenApi.DiscriminatorKeyword' to type 'System.Text.Json.Nodes.JsonNode'.
```

### What did you expect?

Expected it to pass.

### Please add test code or steps to reproduce the behavior.

See above.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
This might be the problem

https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.OpenApi%2FDiscriminatorKeyword.cs

Yeah I don't really expect people to manually create keywords.

**Comment by darrelmiller** [comment]
Thanks for this.  I only created the DiscriminatorKeyword directly to isolate the issue.  We were running into it in normal usage.
