### ISSUE TITLE
Schema Evaluation fails with "Cannot resolve schema at {uri}"

### ISSUE THREAD

**Issue by MaggieKimani1** [gregsdennis/json-everything#722]
### Nuget Package

JsonSchema.Net

### Package Version

4.1.5

### How can I help?  Please provide as much context as possible.

Given the following OpenApiDocument, 
``` YAML
openapi: 3.0.0
info:
  title: Sample API
  description: Lorem Ipsum
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Lorem Ipsum
paths:
  /issues:
    get:
      summary: Returns a list of issues.
      description: Lorem Ipsum
      responses:
        "200":
          description: Lorem Ipsum
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/issueData"
              example:
                data:
                  - issuedAt: "2023-10-12"
components:
  schemas:
    issueData:
      type: object
      title: Issue Data
      description: Information about the issue.
      properties:
        issuedAt:
          type: string
          format: date
          description: Lorem Ipsum
          example: "2023-10-12"
```

I'm trying to evaluate the `example` object here:
``` YAML
example:
  data:
    - issuedAt: "2023-10-12"
```
Against the schema within the `application/json` content-type by calling `schema.Evaluate(example)`.
However, evaluation fails with the following error:

```
Json.Schema.JsonSchemaException: 'Cannot resolve schema `https://json-everything.net/bd1ea2d485#/components/schemas/issueData`'
```
Examining the stack trace says the exception is originally thrown by the RefKeyword's `Evaluate()` method
```
at Json.Schema.RefKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.ItemsKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.PropertiesKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
```

When I inspect the codebase, I see the error is thrown on this line https://github.com/gregsdennis/json-everything/blob/7d516fb3307a4fc90179b7a8a2575797bb509f17/JsonSchema/RefKeyword.cs#L90-L91
which I assume is as a result of this https://github.com/gregsdennis/json-everything/blob/7d516fb3307a4fc90179b7a8a2575797bb509f17/JsonSchema/RefKeyword.cs#L76

I've tried registering the schema in the components section with the local schema registry and passing it through the Evaluation options object but it isn't working either. 
I've also made sure that the baseUri's for the `items` schema and that of the registered schema are the same.

Why isn't the embedded items $ref being resolved? What could I be doing wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elgonzo** [comment]
I can only speculate here as you didn't show how your code is using the schema to evaluate instances. I assume your code extracts/isolates the schema from the OpenApiDocument either without extracting the schema components like "issueData" or your extraction attempt of the "issueData" (sub-)schema somehow leaves it at a (relative) path different from the original
"#/components/schemas/issueData" path. Hard to tell without knowing how you precisely process the OpenApiDocument, though...

(As a side note, JsonSchema.NET is already at version 6.1.2)

**Comment by elgonzo** [comment]
For what it's worth, here is an illustrative example code, modifying the schema by adding the component schemas to it. This is done because the schema reference in your example schema has an `#`, which indicates an _embedded_ schema, so by making the "components" object a part of the schema object the path of the reference will resolve successfully.

```C#
var yaml = new YamlStream();
yaml.Load(... the OpenApiDocument as shown in your report ...);

var joSchema = (JsonObject) joOpenAPIDoc["paths"]["/issues"]["get"]["responses"]["200"]["content"]["application/json"]["schema"];
var joComponentSchemas = (JsonObject)joOpenAPIDoc["components"];
joOpenAPIDoc.Remove("components");
joSchema.Add("components", joComponentSchemas);

var schema = joSchema.Deserialize<JsonSchema>();
var result = schema.Evaluate(... the example instance ...);
```

(Note that the example instance you have given will not validate successfully, because it is a root object with only an "example" property. However, your schema attempts to validate a root object with a mandatory "data" property.)

**Comment by MaggieKimani1** [comment]
> How exactly is your code utilizing the schema(s) inside the OpenApiDocument?
> 
> (As a side note, JsonSchema.NET is already at version 6.1.2)

We're simply loading up the document in memory, then performing validation using a set of rules for every component within the document here https://github.com/microsoft/OpenAPI.NET/blob/f069dc154ab2c6c0c7e89cc6587f2f61b356d846/src/Microsoft.OpenApi/Reader/OpenApiJsonReader.cs#L108

When it gets to the media type object and finds an example node, it tries to validate it against the schema to see if the data type matches here: https://github.com/microsoft/OpenAPI.NET/blob/e76101a582b59d94a98f6103fe05c3d908ef79ef/src/Microsoft.OpenApi/Validations/Rules/OpenApiMediaTypeRules.cs#L35

https://github.com/microsoft/OpenAPI.NET/blob/e76101a582b59d94a98f6103fe05c3d908ef79ef/src/Microsoft.OpenApi/Validations/Rules/RuleHelpers.cs#L68

**Comment by MaggieKimani1** [comment]
> For what it's worth, here is an illustrative example code, modifying the schema by adding the component schemas to it. This is done because the schema reference in your example schema has an `#`, which indicates an _embedded_ schema, so by making the "components" object a part of the schema object the path of the reference will resolve successfully.
> 
> ```cs
> var yaml = new YamlStream();
> yaml.Load(... the OpenApiDocument as shown in your report ...);
> var joOpenAPIDoc = (JsonObject) yaml.ToJsonNode().First();
> 
> var joSchema = (JsonObject) joOpenAPIDoc["paths"]["/issues"]["get"]["responses"]["200"]["content"]["application/json"]["schema"];
> var joComponentSchemas = (JsonObject)joOpenAPIDoc["components"];
> 
> joSchema.Add("components", joComponentSchemas.DeepClone());
> 
> var schema = joSchema.Deserialize<JsonSchema>();
> var result = schema.Evaluate(... the example instance ...);
> ```
> 
> (Note that the example instance you have given will not validate successfully, because it is a root object with only an "example" property. However, your schema attempts to validate a root object with a mandatory "data" property.)

Does this mean I should try dereference the schema first before performing evaluation?
I see you're replacing the embedded $ref with the component schema here before calling `schema.Evaluate()`?

**Comment by gregsdennis** [comment]
@MaggieKimani1 you need to register the _entire_ OpenAPI document under a URI identifier.  Then, when you create a new schema, set its `.BaseUri` to the same identifier.

See this test:

https://github.com/gregsdennis/json-everything/blob/d30e70760fd5797e6d831a4b950bdadf6071904f/JsonSchema.Tests/BaseDocumentTests.cs#L163-L207

This is why I suggested to you that you need to make your `OpenAPIDocument` type implement `IBaseDocument`.  I created `IBaseDocument` explicitly to support this use case.  You can see it working in my [Graeae project](https://github.com/gregsdennis/Graeae).

What I recommend:

1. Make `OpenApiDocument` implement `IBaseDocument`.
2. When you initialize `OpenApiDocument` scan for schemas and set their `.BaseUri`s.
3. Register the `OpenApiDocument` with the schema registry.  (You can use either the global registry or the one in `EvaluationOptions`.  If you use the options one, you'll need to always use those options or remember to re-register the schema with the new options.)

Then you should be able to grab any nested schema and validate with it.
