### ISSUE TITLE
Could not load file or assembly 'JsonPointer.Net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=17ed63f672b0e278'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by na1307** [gregsdennis/json-everything#723]
### Nuget Package

JsonSchema.Net

### Package Version

7.0.0

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

When I use JsonSchema.Net 7.0.0 and try to evaluate the schema I get a FileNotFoundException.

### What did you expect?

The schema is evaluated normally.

### Please add test code or steps to reproduce the behavior.

Try schema evaluation using JsonSchema.Net 7.0.0.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Odd.  Thanks for the report. 

Checking the package, it looks like the dependency is listed as JsonPointer.Net v4.

I'll have a look. The build usually gets all the dependencies right.

**Comment by gregsdennis** [comment]
The package that built locally has a v5 dependency.  I'm not sure what's going on.  I'll try to push a repackage update.

**Comment by gregsdennis** [comment]
@na1307 please try manually referencing JsonPointer.Net v5.

**Comment by na1307** [comment]
![화면 캡처 2024-05-01 180358](https://github.com/gregsdennis/json-everything/assets/103810717/f754ddb1-888a-4bc2-a1d1-df345f6f1fbc)

I referred it manually, and there is no problem.

**Comment by gregsdennis** [comment]
Looks like I forgot that I use a nuspec file for JsonSchema.Net, and I needed to update the dependency there.

I'm pushing v7.0.0.2.   Please let me know if that works for you.  (Remove the explicit reference to JsonPointer.Net)

**Comment by na1307** [comment]
Now I get NU1605.

![화면 캡처 2024-05-01 181346](https://github.com/gregsdennis/json-everything/assets/103810717/143efc29-39e7-4276-be1c-cd97b50df33d)

**Comment by gregsdennis** [comment]
> ConsoleApp1 -> JsonSchema.Net 7.0.0.2 -> JsonPointer.Net 5.0.0 -> Json.More.Net (>= 2.0.1.2) 
> ConsoleApp1 -> JsonSchema.Net 7.0.0.2 -> Json.More.Net (>= 2.0.0)

... That's such a stupid error.  Nuget should be smart enough to take the later of the two.  That's what `>=` means.

v7.0.0.3 incoming...

**Comment by na1307** [comment]
I tried 7.0.0.3 and it seems to be fine now. I think the evaluation is good, too.
![화면 캡처 2024-05-01 182643](https://github.com/gregsdennis/json-everything/assets/103810717/3d0ad895-de73-4d24-add7-59c43e098aad)

**Comment by gregsdennis** [comment]
Thanks for verifying.  Let me know if you have further issues.
