### ISSUE TITLE
Escaping single quote in json path string

### ISSUE THREAD

**Issue by ashek-simeon** [gregsdennis/json-everything#728]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonPath.Net

### Package Version

0.6.7

### How can I help?  Please provide as much context as possible.

Is there a way to escape a single quote within a string like this one?

$[?(@.Name == 'how do I escape a single' quote here?')]

I've tried putting a backslash before the single quote, which I believe should be valid based on the JsonPath specifications, unless I'm misinterpreting them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. You can use double quotes for the string. 

```jsonpath
$[?(@.Name == "how do I escape a single' quote here?")]
```

Then you don't need to escape it. 

Otherwise, you'll use a backslash `\` to escape.

**Comment by ashek-simeon** [comment]
Thank you so much for responding, and for all the work you do on this amazing library!

I think the escaping may not be working for single quotes in strings surrounded by single quotes, since this fails to parse

$[?(@.Name == 'how do I escape a single\' quote here?')]

![image](https://github.com/gregsdennis/json-everything/assets/133139131/8a6ecbec-0a6f-4630-b4ae-96424911b0f0)

Also, the string I am working with may contains single quotes or double quotes (it is dynamic), so I may still have to use escaping if I used double quotes to surround the string. Good news is -- escaping seems to be working as expected for double quote strings.

Do you think I should open a new issue with a type of "bug" for parsing failing with the escaped single quotes?

**Comment by gregsdennis** [comment]
I'll use this issue, thanks.

**Comment by He-Pin** [comment]
This is a bug and the parser need to do an escaping.
I think this issue can be added to the test suite too.

![image](https://github.com/gregsdennis/json-everything/assets/501740/cf688792-5927-4d46-994c-a6b7b972c45c)

**Comment by gregsdennis** [comment]
> This is a bug

Yes, as labeled.

**Comment by gregsdennis** [comment]
It doesn't!

**Comment by ashek-simeon** [comment]
> It doesn't! I'm going to add this to the test suite and then fix it here.

Thank you so much!
