### ISSUE TITLE
How to export or save JsonSchema to plaintext?

### ISSUE THREAD

**Issue by garryxiao** [gregsdennis/json-everything#742]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

latest

### How can I help?  Please provide as much context as possible.

I have read the documentation but did not find any clue or example to do that. As with the "builder.Build()", I would like to check the plaintext to learn and double check the schema. Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
The [docs](https://docs.json-everything.net/schema/basics/#schema-deserialization) do mention that `JsonSchema` is fully serializable. If you need a textual representation, you just need to serialize it.

**Comment by garryxiao** [comment]
Hi @gregsdennis, I see, thanks. Maybe it's a dum question, but please add a line of words to mention it for a beginner. "How to check the plaintext of the schema? Call `JsonSerializer.Serialize(schema)` with your C# code to double check when you want." I believe it's a very common question when start using the amazing library.

**Comment by gregsdennis** [comment]
I'll see how I can work something in.  When originally writing them, I think I expected a user to have a certain level of experience working with JSON in .Net already.  That's a bad assumption.

Thanks for bringing it up.
