### ISSUE TITLE
How to write a JsonSchemaBuilder for a class that has a property of a class?

### ISSUE THREAD

**Issue by Welchen** [gregsdennis/json-everything#743]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net

### Package Version

7.0.2

### How can I help?  Please provide as much context as possible.

I have two classes and one is a property of another class that is being serialized. I want to validate the class during deserialization.  How do I write a JsonSchemaBuilder for the parent class that also validates the child class property? 

Here is the closest I got in code but can't figure out how to set the Type or Required for the Property in the ParentClass schema. 

I only see examples for primative types but not nested classes. 

```
using Json.Schema;
using Json.Schema.Serialization;
using System.ComponentModel.DataAnnotations;

namespace JsonInvestigation;

[JsonSchema(typeof(ParentClass), nameof(Schema))]   
public sealed class ParentClass
{
    [Required]
    [StringLength(5)]
    public string Name { get; set; } = string.Empty;

    [Required]
    public PropertyClass Property { get; set; } = new PropertyClass();  

    public readonly static JsonSchema Schema = new JsonSchemaBuilder()
        .Type(SchemaValueType.Object)
        .Properties((nameof(Name), new JsonSchemaBuilder()
            .Type(SchemaValueType.String)
            .MaxLength(5)
            .Required()),
            (nameof(Property), PropertyClass.Schema)
        );
}

[JsonSchema(typeof(PropertyClass), nameof(Schema))]
public sealed class PropertyClass
{
    [Required]
    [StringLength(5)]
    public string Name { get; set; } = string.Empty;

    public readonly static JsonSchema Schema = new JsonSchemaBuilder()
        .Type(SchemaValueType.Object)
        .Properties((nameof(Name), new JsonSchemaBuilder()
            .Type(SchemaValueType.String)
            .MaxLength(5)
            .Required())
        );
}

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I would expect what you have to work just fine.  Have you tried it?

The validating deserialization works (in this example) by creating a serializer when you deserialize `ParentClass`.  That serializer will decode the entire payload and validate it against `ParentClass.Schema` which has the reference to `PropertyClass.Schema` already.

So all validation really occurs at the parent level.

If validation is successful, the validating serializer will be removed from the options (so that the serializing one doesn't get called again), and then it will attempt to deserialize with the updated options.

**Comment by Welchen** [comment]
I haven't tried it because it is still missing a piece of validation. I want the property of PropertyClass to also be required and I see no way to do that.  I also have the string properties set as Required. Validation is missing in ParentClass.Schema.

**Comment by Welchen** [comment]
I think I figured it out.  I am passing the Properties from the PropertyClass.Schema into the JsonSchemaBuilder of ParentClass. That seems to be doing the validation for me.  I did realize that I was doing Required wrong.  Since it was an optional parameter for the name, I thought if you just put Required() on the JsonSchemaBuilder that it would assign required to property name. 

If there is a better way to do Required, much appreciated to know. 

Here is my new code:

```
using Json.Schema;
using Json.Schema.Serialization;
using System.ComponentModel.DataAnnotations;

namespace JsonInvestigation;

[JsonSchema(typeof(ParentClass), nameof(Schema))]   
public sealed class ParentClass
{
    [Required]
    [StringLength(5)]
    public string Name { get; set; } = string.Empty;

    [Required]
    public PropertyClass Property { get; set; } = new PropertyClass();

    public readonly static JsonSchema Schema = new JsonSchemaBuilder()
        .Type(SchemaValueType.Object)
        .Properties((nameof(Name), new JsonSchemaBuilder()
            .Type(SchemaValueType.String)
            .MaxLength(5)),
            (nameof(Property), new JsonSchemaBuilder()
                .Type(SchemaValueType.Object)
                .Properties(PropertyClass.Schema.GetProperties() ?? new Dictionary<string, JsonSchema>())))
        .Required(nameof(Name), nameof(Property));
}

[JsonSchema(typeof(PropertyClass), nameof(Schema))]
public sealed class PropertyClass
{
    [Required]
    [StringLength(5)]
    public string Name { get; set; } = string.Empty;

    public readonly static JsonSchema Schema = new JsonSchemaBuilder()
        .Type(SchemaValueType.Object)
        .Properties((nameof(Name), new JsonSchemaBuilder()
            .Type(SchemaValueType.String)
            .MaxLength(5)))
        .Required(nameof(Name));

}
```

**Comment by gregsdennis** [comment]
The builder extensions mimic the schema itself.  The `required` keyword is placed at the object level to require the properties which are required in that object.

```json
{
  "type": "object",
  "required": ["foo"]
}
```

The extension method acts the same.

```c#
JsonSchema schema = new JsonSchemaBuilder()
     .Type(SchemaValueType.Object)
     .Required("foo");
```
