### ISSUE TITLE
 `JsonSchema.GetHashCode` isn't consistent on field re-ordering

### ISSUE THREAD

**Issue by amosonn** [gregsdennis/json-everything#76]
**Environment**
- Nuget Package: JsonSchema.NET
- Nuget Version: 1.8.0
- OS: Linux
- .Net Target: net5.0

**Describe the bug**

`JsonSchema.GetHashCode` isn't consistent on field re-ordering. All the following schemas compare equal but have different hash-codes:

```
           var schema1Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""required"": [
    ""a"",
    ""b""
  ],
  ""properties"": {
    ""a"": { ""const"": ""a"" },
    ""b"": { ""const"": ""b"" }
  }
}";

            var schema2Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""required"": [
    ""b"",
    ""a""
  ],
  ""properties"": {
    ""a"": { ""const"": ""a"" },
    ""b"": { ""const"": ""b"" }
  }
}";

            var schema3Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""required"": [
    ""a"",
    ""b""
  ],
  ""properties"": {
    ""b"": { ""const"": ""b"" },
    ""a"": { ""const"": ""a"" }
  }
}";

            var schema4Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""properties"": {
    ""a"": { ""const"": ""a"" },
    ""b"": { ""const"": ""b"" }
  },
  ""required"": [
    ""a"",
    ""b""
  ]
}";
            var schema1 = JsonSerializer.Deserialize<JsonSchema>(schema1Str);
            var schema2 = JsonSerializer.Deserialize<JsonSchema>(schema2Str);
            var schema3 = JsonSerializer.Deserialize<JsonSchema>(schema3Str);
            var schema4 = JsonSerializer.Deserialize<JsonSchema>(schema4Str);
            Console.WriteLine("{0}, {1}, {2}", schema1.Equals(schema2), schema1.GetHashCode(), schema2.GetHashCode());
            Console.WriteLine("{0}, {1}, {2}", schema1.Equals(schema3), schema1.GetHashCode(), schema3.GetHashCode());
            Console.WriteLine("{0}, {1}, {2}", schema1.Equals(schema4), schema1.GetHashCode(), schema4.GetHashCode());
```

It seems that `Json.Pointer.EnumerableExtensions.GetCollectionHashCode` doesn't sort the enumerable, and neither do the callers.

**Comment by gregsdennis** [comment]
Thank for the report.

I may need to go through and verify where I need ordering.

The `.GetCollectionHashCode()` method expects ordering of the collection to be important, so it's working right.  But maybe I need a set-based one that's not ordered.

**Comment by gregsdennis** [comment]
So I made some changes, defining various collection hash code extensions.  But in the end, your specific case (and probably others) come down to they keyword `const` actually storing a `JsonElement` and trying to generate the hash code from that.  Other keywords like `examples` that store `JsonElement` will also likely have this problem.

Funny thing is that `JsonElement` doesn't override `.GetHashCode()`, which means it's just based on the `object` version.

I'm not sure what to do with that, but the methods I made look good.  I may have to define a custom method in _Json.More_.

You can see the updates in the commit 👇.

**Comment by amosonn** [comment]
Cool, thanks for the quick reply! I indeed forgot about the `JsonElement.GetHashCode()` issue. Here is an upstream issue relevant to this:
https://github.com/dotnet/runtime/issues/33388
This discusses comparison and not hashcodes, but these are of course strongly related. However it sadly seems that they're not going to implement this anytime soon, so a custom method seems like the way to go.

We have our own implementation in our codebase (both for equality and hashcodes), should I post it somehow? It doesn't take a very informed stance on the considerations described in the issue above, but I guess it's still better than nothing.

**Comment by gregsdennis** [comment]
Nice find!  I'm incorporating a modified version of that SO answer into Json.More.  I'll use that.
