### ISSUE TITLE
Fetch base directory URI from Registry

### ISSUE THREAD

**Issue by amosonn** [gregsdennis/json-everything#79]
**Environment**

- Nuget Package: JsonSchema.Net
- Nuget Version: 1.9.0 (regression from 1.8.0)
- OS: Linux
- .Net Target: .net 5.0

**Describe the bug**

In some cases, the schema validation erroneously attempts to fetch the directory containing a schema as a schema itself. It seems to happen when we have one schema referring to another with a relative URI, and the second schema has internal references (i.e. `"#/definitions/...`).

**To Reproduce**

```C#
            var schema1Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""$id"": ""schema1.json"",
  ""definitions"": {
    ""myDef"": {
      ""properties"": {
        ""abc"": { ""type"": ""string"" }
      }
    }
  },
  ""$ref"": ""#/definitions/myDef""
}";
            var schema2Str = @"
{
  ""$schema"": ""http://json-schema.org/draft-07/schema#"",
  ""$id"": ""schema2.json"",
  ""$ref"": ""schema1.json""
}";
            var jsonStr = @"{ ""abc"": ""s"" }";
            var schema1 = JsonSerializer.Deserialize<JsonSchema>(schema1Str);
            var schema2 = JsonSerializer.Deserialize<JsonSchema>(schema2Str);
            var json = JsonDocument.Parse(jsonStr).RootElement;
            var uri1 = new Uri("http://first.com/schema1.json");
            var uri2 = new Uri("http://first.com/schema2.json");
            var firstBaseUri = new Uri("http://first.com");
            var map = new Dictionary<Uri, JsonSchema>
            {
                { uri1, schema1 },
                { uri2, schema2 },
            };
            var options = new ValidationOptions
            {
                OutputFormat = OutputFormat.Verbose,
                DefaultBaseUri = firstBaseUri,
                SchemaRegistry =
                {
                    Fetch = uri =>
                    {
                        Console.WriteLine("Fetching {0}", uri);
                        // return map.TryGetValue(uri, out var ret) ? ret : null;
                        return map[uri];
                    }
                }
            };
            var validation = schema2.Validate(json, options);
            Console.WriteLine("Validation: {0}", JsonSerializer.Serialize(validation));
```

Prints
```
Fetching http://first.com/schema1.json
Fetching http://first.com/
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'http://first.com/' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at test3.Program.<>c__DisplayClass0_0.<Main>b__0(Uri uri) in /tmp/test_jsonschema/Program.cs:line 56
   at Json.Schema.SchemaRegistry.Get(Uri uri, String anchor) in /git/json-everything/JsonSchema/SchemaRegistry.cs:line 115
   at Json.Schema.RefKeyword.Validate(ValidationContext context) in /git/json-everything/JsonSchema/RefKeyword.cs:line 68
   at Json.Schema.JsonSchema.ValidateSubschema(ValidationContext context) in /git/json-everything/JsonSchema/JsonSchema.cs:line 213
   at Json.Schema.RefKeyword.Validate(ValidationContext context) in /git/json-everything/JsonSchema/RefKeyword.cs:line 110
   at Json.Schema.JsonSchema.ValidateSubschema(ValidationContext context) in /git/json-everything/JsonSchema/JsonSchema.cs:line 213
   at Json.Schema.JsonSchema.Validate(JsonElement root, ValidationOptions options) in /git/json-everything/JsonSchema/JsonSchema.cs:line 119
   at test3.Program.Main(String[] args) in /tmp/test_jsonschema/Program.cs:line 60
```

**Expected behavior**
The URL `http://first.com/` should never be fetched. This is a regression from version 1.8.0, which displays the correct behaviour.

**Comment by gregsdennis** [comment]
Thanks for the report. I'll have to check what changed.  Refs are hard.

**Comment by gregsdennis** [comment]
I think this is the cause

https://github.com/gregsdennis/json-everything/pull/75/files#diff-5a7712dfe232287659fbbe6cd3b9fcad14a4a20083d9cfa60f506c5f04f42ba8L67-R68

I remember I needed to make that change in the `$dynamicRef` and `$recursiveRef` keywords, but I may have been overzealous in changing `$ref` as well.

Also, your test case may be a good candidate for the [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite).

**Comment by amosonn** [comment]
Interesting. I'll take a look into adding it to that test suite!

Regarding the place that you mentioned, I remember already snagging once on the fact that `CurrentUri` sometimes actually contains the "parent directory" of the uri referring to the current schema. I think it was possible to get diagnostics where some uris were incorrect because of this. I'd wanted to write a minimal test-case but never got around to it.

My point is, it could be that the change you made there actually uncovered an underlaying problem. The last time I looked at it I tried to find a simple solution that will make sure that `CurrentUri` always contains the uri of the current schema, but didn't manage it. As you said, `$ref`-s are hard :)

**Comment by gregsdennis** [comment]
Yep, that's what did it.  The idea with the change was that I wanted to first check if the current URI was resolveable, and take the schema root if not.  It looks like you've found a case where that check throws an exception for some reason.  This is important if the URI completely changes while navigating the schema.

For example:

```c#
// schema
{
  "$id": "https://mydomain.com/outer",
  "properties": {
    "foo": {
      "$id": "https://mydomain.com/foo",
      "properties": {
        "inner1": {
          "$anchor": "bar",
          "type": "string"
        },
        "inner2": {
          "$ref": "#bar"
        }
      }
    },
    "bar": {
      "$anchor": "bar",
      "type": "integer"
    }
  }
}

// passes
{
  "foo": {
    "inner2": "value"
  }
}

// fails
{
  "foo": {
    "inner2": 42
  }
}
```

The first instance passes because the URI changes when navigating to the `$ref` from `outer` to `foo`, which means that we need to resolve `foo#bar`.  The subschema at `/properties/bar` has a URI of `outer#bar`.

I think I just need to figure out why the exception is thrown rather than changing the `$ref` resolution.

**Comment by gregsdennis** [comment]
The exception is thrown from your test code when trying to resolve the URI.  If you use the code _that you commented out_ (the `TryGetValue()` line), then it works just fine. 😑

**Comment by gregsdennis** [comment]
The reason for the call, however... I'm not sure.  My example still works without the change, as does the test suite.

I'll revert this change and republish.

**Comment by amosonn** [comment]
Sorry, I should have written this more clearly. Of course the exception is from my code, and one could argue that a good `Fetch` should return null and not throw exceptions when e.g. a file is missing. OTOH, if I know what schemas would need to be fetched, and that the files are all there, then I shouldn't expect it to be called with a "strange" uri.

I left the exception-throwing version to highlight this; i.e., the bug is IMO that this uri was ever fetched. If you use the version which silencesthis exception in the test, it will not catch this bug.

Put otherwise: in the test which you added, I would have used the following `Fetch`:

```C#
uri =>
{
    map.TryGetValue(uri, out var ret).AssertTrue();
    return ret;
}
```

since the only uris passed to this fetch should be in that dictionary. This would then indeed fail the test gracefully and not with an error (and also be more readable).
