### ISSUE TITLE
JsonSchema errors for additionalProperties not the same as 2019-09 draft specification

### ISSUE THREAD

**Issue by brigadier90** [gregsdennis/json-everything#89]
**.net core 3.1**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.9.3
- OS: Windows 10 version 20H2

I am trying to replicate the scenario specified in this official [draft](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4). Here is my code:

```


using Json.Pointer;
using Json.Schema;
using System;
using System.Text.Json;

namespace ConsoleApp1
{
    class Program
    {
        static void GetErrorString(
            ValidationResults results,
            ref string errorString)
        {
            if (results.Message != null)
            {
                errorString += results.InstanceLocation + ": ";
                errorString += results.Message + "\n";
            }

            foreach (var result in results.NestedResults)
                GetErrorString(result, ref errorString);
        }

        static void Main(string[] args)
        {
            var schema = JsonSchema.FromFile("./point.json");
            var jsnStr = @"[
                {""x"": 2.5, ""y"":1.3}, 
                {""x"": 1, ""z"":6.7}
            ]";

            var jsnObj = JsonDocument.Parse(jsnStr).RootElement;

            ValidationOptions options = new ValidationOptions();
            options.OutputFormat = OutputFormat.Detailed;
            options.ValidateAs = Draft.Draft201909;

            var result = schema.Validate(jsnObj, options);

            var errorString = "";
            if(!result.IsValid)
                GetErrorString(result, ref errorString);

            Console.WriteLine(errorString);
        }
    }
}
```
This is my output:
```
#: Value has less than 3 items
#/1: Required properties [y] were not present
#/1/z: All values fail against the false schema
```
I noticed the error for pointer "#/1/z" is different to the one specified in the draft [here](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4.3) which says: "Additional property 'z' found but was invalid". 

This becomes especially problematic when I have the following schema:
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "/CheckRequest",
  "type": "object",
  "properties": {
    "code": {
      "type": "string",
      "minLength": 4,
      "maxLength": 10
    },
    "phone": {
      "type": "string",
      "pattern": "^\\+[1-9]\\d{1,14}$"
    }
  },
  "required": [ "code", "phone"],
  "additionalProperties":  false 
}
```
with the following json instance:
```
var jsnStr = @"{
                ""code"": ""12555"", 
                ""phone"":""357998765436"", 
                ""extra"":""extra""
            }";
```
Note: the phone input is invalid since it doesn not match the regex ( does not begin with a +) and my output becomes:

```
#/phone: The string value was not a match for the indicated regular expression
#/code: All values fail against the false schema
#/phone: All values fail against the false schema
#/extra: All values fail against the false schema
```

Why does this message (All values fail against the false schema) print for all my properties instead of just the "extra" property?

Thanks in advance

**Comment by gregsdennis** [comment]
I think you're experiencing the same thing as was reported in [another issue](https://github.com/gregsdennis/json-everything/issues/39#issuecomment-730116851).

Basically, `additionalProperties` operates (per the spec) based on annotations from other keywords, including `properties`.  But since the keywords fail, `properties` doesn't generate any annotations, so `additionalProperties` applies to everything, generating the errors you see.

It's entirely possible that the sample output in the spec is wrong.  I hand-wrote it when we put it in 2019-09, and we didn't change that section for 2020-12.

**Comment by karenetheridge** [comment]
fwiw, this is what my implementation produces:

```
{
  "errors" : [
    {
      "instanceLocation" : "/phone",
      "keywordLocation" : "/properties/phone/pattern",
      "error" : "pattern does not match",
      "absoluteKeywordLocation" : "/CheckRequest#/properties/phone/pattern"
    },
    {
      "instanceLocation" : "",
      "keywordLocation" : "/properties",
      "error" : "not all properties are valid",
      "absoluteKeywordLocation" : "/CheckRequest#/properties"
    },
    {
      "keywordLocation" : "/additionalProperties",
      "instanceLocation" : "/extra",
      "error" : "additional property not permitted",
      "absoluteKeywordLocation" : "/CheckRequest#/additionalProperties"
    },
    {
      "absoluteKeywordLocation" : "/CheckRequest#/additionalProperties",
      "instanceLocation" : "",
      "keywordLocation" : "/additionalProperties",
      "error" : "not all additional properties are valid"
    }
  ],
  "valid" : false
}
```

**Comment by brigadier90** [comment]
> fwiw, this is what my implementation produces:
> 
> ```
> {
>   "errors" : [
>     {
>       "absoluteKeywordLocation" : "/CheckRequest#/properties/phone/pattern",
>       "error" : "pattern does not match",
>       "instanceLocation" : "/phone",
>       "keywordLocation" : "/properties/phone/pattern"
>     },
>     {
>       "absoluteKeywordLocation" : "/CheckRequest#/properties",
>       "error" : "not all properties are valid",
>       "instanceLocation" : "",
>       "keywordLocation" : "/properties"
>     },
>     {
>       "absoluteKeywordLocation" : "/CheckRequest#/additionalProperties",
>       "error" : "additional property not permitted",
>       "instanceLocation" : "/extra",
>       "keywordLocation" : "/additionalProperties"
>     },
>     {
>       "absoluteKeywordLocation" : "/CheckRequest#/additionalProperties",
>       "error" : "not all additional properties are valid",
>       "instanceLocation" : "",
>       "keywordLocation" : "/additionalProperties"
>     }
>   ],
>   "valid" : false
> }
> ```

Do you mind sharing your code for the above result?

**Comment by karenetheridge** [comment]
my implementation of `additionalProperties` is here: https://metacpan.org/release/JSON-Schema-Draft201909/source/lib/JSON/Schema/Draft201909/Vocabulary/Applicator.pm#L491-527

(repository: https://github.com/karenetheridge/JSON-Schema-Draft201909)

**Comment by gregsdennis** [comment]
There's a lot of consideration regarding the output here.  We have a discussion on his to improve it going over at the spec repo.

**Comment by gregsdennis** [comment]
I'm not sure that anything's actually wrong with the implementation, but rather you'd just like it to work differently.  As it meets the requirements of the specification, that's where the change should take place.

I'm going to close this issue for now.
