### ISSUE TITLE
How to incrementally add properties?

### ISSUE THREAD

**Issue by andreinitescu** [gregsdennis/json-everything#90]
I'm creating a JsonSchema dynamically by code. 
How can I add a property to the existing properties?

The following will produce a JsonSchema with only a "p2" property:
```
var b = new JsonSchemaBuilder();

b = b.Properties(("p1", new JsonSchemaBuilder().Type(SchemaValueType.Object)));
b = b.Properties(("p2", new JsonSchemaBuilder().Type(SchemaValueType.Object)));

```

**Comment by gregsdennis** [comment]
Interesting. This is a case I hadn't considered.

I can update those methods to add the new values to the current set in the builder.

**Comment by gregsdennis** [comment]
I'm still trying to figure out the best API for this.  Running through several options.

**Comment by gregsdennis** [comment]
I can't find a way to do this that I want to add to the library.

The idea is behind the current design is that a schema should be immutable once it's built.  That said, I understand the argument that the _builder_ shouldn't be immutable, but your use isn't quite what I had expected.

My suggestion would be to store your collection of properties in a dictionary separately and then pass that to the builder:

```c#
var builder = new JsonSchemaBuilder();
var propertySchemas = new Dictionary<string, JsonSchema>();
foreach(var prop in propertiesToGenerate)
{
    var propertySchema = BuildFromProperty(prop); // whatever you're doing to generate a schema
    propertySchemas[prop.Name] = propertySchema;
}
builder.Properties(propertySchemas);
```

Aside from that, I've create a [gist](https://gist.github.com/gregsdennis/6919d9d37ef90ef837d66550b131686b) for what I have currently.  It does require that I update the builder to include a new `Get<T>()` method (which I'll publish), but they're just extension methods, so you should be able to just use as is and/or create your own.

**Comment by andreinitescu** [comment]
> My suggestion would be to store your collection of properties in a dictionary separately and then pass that to the builder:

Yes, that's the path I took.

Thank you for your input.

> The idea is behind the current design is that a schema should be immutable once it's built.

Yes, I saw the pattern. 

> Aside from that, I've create a gist for what I have currently. 

Looks good. 
Not sure if you need it, but here's another idea: what if the Properties() method took a 'generator'? For example:
```
builder.Properties(() => // return properties by some custom way);
```
