### ISSUE TITLE
JsonLogic Custom Operators

### ISSUE THREAD

**Issue by rhullah** [gregsdennis/json-everything#91]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 1.2.1
- OS: Mac
- .Net Target: netcoreapp3.1

**How can I help you today?**
I see in your documentation for JsonLogic that [custom operators are coming](https://gregsdennis.github.io/json-everything/usage/json-logic.html#creating-new-rules).  I was hoping to add one to help with case-insensitive comparisons.  I was curious how close your library is to support adding a custom operator like this to handle some custom case-insensitive operations?

Thanks for all you've done!

**Comment by gregsdennis** [comment]
Custom rules are already supported.  Check out the `RuleRegistry.AddRule<T>()` method.

Looks like I just need to update the docs.

**Comment by rhullah** [comment]
Perfect! Thanks so much!

**Comment by rhullah** [comment]
I saw your PR and I had a question around the `RuleRegistry.AddRule<T>()`. I see it has a constraint that it needs to inherit from `Rule` and have a default constructor.  Is the default constructor constraint really needed?  I mean you don't really know which constructer will be called as it's dependent on the number or arguments the rule can accept and likely the default constructor won't ever be called since most (all?) rules require a parameter, right?  So, it ends up becoming a non-used constraint.

**Comment by gregsdennis** [comment]
Yeah I think your right.  I think that's a hold-over from a previous Implementation idea.  My rules don't have parameterless constructors.

The reason I had done that initially was because I'm using `Activator` to build the rules in the deserialization process.  But I'm also passing the arguments to it through that method.

I'll update the docs to indicate the importance of correct constructors.

**Comment by rhullah** [comment]
Thanks, I'm sure that'll help others implementing custom Rules. I know it tripped me up at first while going through it.

Ok, I'll comment on the PR next time I see something.

Thanks!

**Comment by gregsdennis** [comment]
@rhullah please see v1.3.0 and the updated docs.
