### ISSUE TITLE
Generating the same scheme FromType multimpe times

### ISSUE THREAD

**Issue by livwvil** [gregsdennis/json-everything#97]
**Environment**
- Nuget Package: [JsonSchema.Net, Json.Schema.Generation]
- Nuget Version: JsonSchema.Net -Version 1.10.0, JsonSchema.Net -Version 1.10.0
- OS: Windows 10
- .Net Target: Core 3.1

**Describe the bug**
Generating the same scheme FromType multimpe times and then veryfying some JsonElement with it causes StackOverflow. The place of schema definition doesn't matter: two times in main, one time in main and one time in the callable function, etc.

**To Reproduce**
```
using Json.Schema;
using Json.Schema.Generation;
using System.Text.Json;

public class SimpleValueWidgetSettings
{
    [Required]
    public string name { get; set; }

    [Required]
    public string valueLink { get; set; }

    [Required]
    public string qualityValueLink { get; set; }

    [Required]
    public string unitLink { get; set; }

    [Required]
    public string displayMultiplier { get; set; }

    [Required]
    public string displayUnits { get; set; }

    [Required]
    public string fontColor { get; set; }

    [Required]
    public string stringFormat { get; set; }

    static void Main(string[] args)
    {

        var simpleValueJson = "{\"name\":\"LD2/ATCC1.CtlV.db\"}";
        var simpleValueParsed = JsonDocument.Parse(simpleValueJson).RootElement;
        var simpleValueParsed2 = JsonDocument.Parse(simpleValueJson).RootElement;

        var simpleValueSettingsSchema2 = new JsonSchemaBuilder().FromType<SimpleValueWidgetSettings>().AdditionalProperties(false).Build();
        var simpleValueSettingsSchema = new JsonSchemaBuilder().FromType<SimpleValueWidgetSettings>().AdditionalProperties(false).Build();

        simpleValueSettingsSchema.Validate(simpleValueParsed);
        simpleValueSettingsSchema.Validate(simpleValueParsed2);
    }
}
```
**Expected behavior**
Validating without causing StackOverflow. Multiple definition of the same schema shouldn't cause StackOverflow when trying to validate some JsonElement with the last one.

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll look into it next.

**Comment by gregsdennis** [comment]
I've added this to the test suite and confirmed that this is an issue.  Commenting just the `simpleValueSettingsSchema2` line allows the test to pass.

**Comment by gregsdennis** [comment]
Looks like the problem is in the optimization logic.  The schema that's generated the first time is:

```json
{
  "type": "object",
  "properties": {
    "displayMultiplier": {
      "$ref": "#/$defs/string"
    },
    "displayUnits": {
      "$ref": "#/$defs/string"
    },
    "fontColor": {
      "$ref": "#/$defs/string"
    },
    "name": {
      "$ref": "#/$defs/string"
    },
    "qualityValueLink": {
      "$ref": "#/$defs/string"
    },
    "stringFormat": {
      "$ref": "#/$defs/string"
    },
    "unitLink": {
      "$ref": "#/$defs/string"
    },
    "valueLink": {
      "$ref": "#/$defs/string"
    }
  },
  "required": [
    "displayMultiplier",
    "displayUnits",
    "fontColor",
    "name",
    "qualityValueLink",
    "stringFormat",
    "unitLink",
    "valueLink"
  ],
  "$defs": {
    "string": {
      "type": "string"
    }
  },
  "additionalProperties": false
}
```

which I think is what you're looking for.

But on the second generation, it creates this:

```json
{
  ...,
  "$defs": {
    "string": {
      "$ref": "#/$defs/string"
    }
  },
  ...
}
```

_That_ is a circular definition.  So there are two bugs here:

1. The generation creates this madness.
2. The validator needs to detect circular references better.

**Comment by gregsdennis** [comment]
I've fixed the first issue.  I'm not sure why you're generating a schema for the same type repeatedly.  I'd advise to just generate once and hold onto it.

Also, please note the disclaimer on the [docs site](https://gregsdennis.github.io/json-everything/usage/schema-generation.html):

> Ideally, this functionality should be used to create a starting point in authoring a schema. The schemas output by this library should be reviewed by actual people prior to being put into a production system.

I'm still working on the second issue.

**Comment by livwvil** [comment]
> I've fixed the first issue. I'm not sure why you're generating a schema for the same type repeatedly. I'd advise to just generate once and hold onto it.
> 
> Also, please note the disclaimer on the [docs site](https://gregsdennis.github.io/json-everything/usage/schema-generation.html)

I have seen this disclaimer. The schema that's generated the first time is what i need. I expect library generate the same schema second time but it doesn't (expecting behavior like: Integer i = new Integer(0); i = new Integer(0), both times value of i was the same.). My example is simplyfied. I found this problem when I create method that generates schema and does some stuff with it. This method calls multiple times, but works fine just once. Now I define the schema once in singletone and use it everywhere, so it works fine.
Thank you for your answer and sorry for my english :)

**Comment by gregsdennis** [comment]
I've fixed the second issue now.  I just need to update version and docs, then I can create a PR and publish a new version for you.
